EARS-PIO-WSS3-LVGL-001: SDCard Class Reference
SDCard Class Reference
SD Card management class.
#include <SDCard.h>
Public Member Functions
SDCard ()
Construct a new SDCard object.
~SDCard ()
Destroy the SDCard object.
bool begin ()
Initialize the SD card.
bool isAvailable ()
Check if SD card is available.
String getCardType ()
Get SD card type.
uint64_t getCardSizeMB ()
Get SD card size in MB.
uint64_t getFreeSpaceMB ()
Get SD card free space in MB.
bool createDirectory (const char *path)
Create a directory on SD card.
bool fileExists (const char *path)
Check if file exists.
bool directoryExists (const char *path)
Check if directory exists.
bool removeFile (const char *path)
Remove a file.
bool removeDirectory (const char *path)
Remove a directory.
void listDirectory (const char *path, uint8_t indent=0)
List directory contents.
String readFile (const char *path)
Read entire file into String.
bool writeFile (const char *path, const String &content)
Write String to file (overwrites existing).
bool appendFile (const char *path, const String &content)
Append String to file.
Private Member Functions
void initSPI ()
Initialize SPI bus for SD card.
Private Attributes
bool _initialized
SPIClass * _spi
Detailed Description
SD Card management class.
Handles SD card initialization and provides basic file operations for the Waveshare ESP32-S3 3.5" LCD with dedicated SD card SPI bus
Definition at line 25 of file SDCard.h.
Constructor & Destructor Documentation
SDCard()
SDCard::SDCard ()
Construct a new SDCard object.
Parameters
spi SPI bus instance
Initialised flag
Returns
void
Definition at line 20 of file SDCard.cpp.
               : _initialized(false), _spi(nullptr) {
}
References _initialized, and _spi.
~SDCard()
SDCard::~SDCard ()
Destroy the SDCard object.
Definition at line 26 of file SDCard.cpp.
                {
    if (_spi) {
        _spi->end();
    }
}
References _spi.
Member Function Documentation
appendFile()
bool SDCard::appendFile (const char * path, const String & content)
Append String to file.
Parameters
path File path
content Content to append
Returns
true if append successful
false if append failed
Definition at line 349 of file SDCard.cpp.
{
    if (!_initialized) return false;
    File file = SD.open(path, FILE_APPEND);
    if (!file) {
        Serial.print("[SDCard] Failed to open file for appending: ");
        Serial.println(path);
        return false;
    }
    size_t written = file.print(content);
    file.close();
    if (written == content.length()) {
        return true;
    }
    Serial.print("[SDCard] Append failed: ");
    Serial.println(path);
    return false;
}
References _initialized.
begin()
bool SDCard::begin ()
Initialize the SD card.
Returns
true if SD card initialized successfully
false if SD card initialization failed
Definition at line 49 of file SDCard.cpp.
                   {
    if (_initialized) {
        return true;
    }
    // Initialize SPI bus
    initSPI();
    // Try to initialize SD card
    if (!SD.begin(SD_CS, *_spi)) {
        Serial.println("[SDCard] Initialization failed!");
        _initialized = false;
        return false;
    }
    // Check card type
    uint8_t cardType = SD.cardType();
    if (cardType == CARD_NONE) {
        Serial.println("[SDCard] No SD card attached");
        _initialized = false;
        return false;
    }
    _initialized = true;
    // Print card info
    Serial.println("[SDCard] Initialization successful");
    Serial.print("[SDCard] Type: ");
    Serial.println(getCardType());
    Serial.print("[SDCard] Size: ");
    Serial.print(getCardSizeMB());
    Serial.println(" MB");
    Serial.print("[SDCard] Free: ");
    Serial.print(getFreeSpaceMB());
    Serial.println(" MB");
    return true;
}
References _initialized, _spi, getCardSizeMB(), getCardType(), getFreeSpaceMB(), initSPI(), and SD_CS.
createDirectory()
bool SDCard::createDirectory (const char * path)
Create a directory on SD card.
Parameters
path Directory path
Returns
true if directory created or already exists
false if creation failed
Definition at line 149 of file SDCard.cpp.
{
    if (!_initialized) return false;
    if (SD.mkdir(path)) {
        Serial.print("[SDCard] Directory created: ");
        Serial.println(path);
        return true;
    } else {
        // Check if it already exists
        if (directoryExists(path)) {
            return true;
        }
        Serial.print("[SDCard] Failed to create directory: ");
        Serial.println(path);
        return false;
    }
}
References _initialized, and directoryExists().
directoryExists()
bool SDCard::directoryExists (const char * path)
Check if directory exists.
Parameters
path Directory path
Returns
true if directory exists
false if directory does not exist
Definition at line 191 of file SDCard.cpp.
{
    if (!_initialized) return false;
    File dir = SD.open(path);
    if (dir) {
        bool isDir = dir.isDirectory();
        dir.close();
        return isDir;
    }
    return false;
}
References _initialized.
Referenced by createDirectory().
fileExists()
bool SDCard::fileExists (const char * path)
Check if file exists.
Parameters
path File path
Returns
true if file exists
false if file does not exist
Definition at line 173 of file SDCard.cpp.
{
    if (!_initialized) return false;
    File file = SD.open(path);
    if (file) {
        bool isFile = !file.isDirectory();
        file.close();
        return isFile;
    }
    return false;
}
References _initialized.
getCardSizeMB()
uint64_t SDCard::getCardSizeMB ()
Get SD card size in MB.
Returns
uint64_t card size in megabytes
Definition at line 122 of file SDCard.cpp.
{
    if (!_initialized) return 0;
    uint64_t cardSize = SD.cardSize() / (1024 * 1024);
    return cardSize;
}
References _initialized.
Referenced by begin().
getCardType()
String SDCard::getCardType ()
Get SD card type.
Returns
String describing card type (SD, SDHC, etc.)
String describing card type (SD, SDHC, MMC, Unknown, NONE)
Definition at line 101 of file SDCard.cpp.
{
    if (!_initialized) return "NONE";
    uint8_t cardType = SD.cardType();
    switch (cardType) {
        case CARD_MMC:
            return "MMC";
        case CARD_SD:
            return "SD";
        case CARD_SDHC:
            return "SDHC";
        default:
            return "UNKNOWN";
    }
}
References _initialized.
Referenced by begin().
getFreeSpaceMB()
uint64_t SDCard::getFreeSpaceMB ()
Get SD card free space in MB.
Returns
uint64_t free space in megabytes
Definition at line 133 of file SDCard.cpp.
{
    if (!_initialized) return 0;
    uint64_t totalBytes = SD.totalBytes();
    uint64_t usedBytes = SD.usedBytes();
    uint64_t freeBytes = totalBytes - usedBytes;
    return freeBytes / (1024 * 1024);
}
References _initialized.
Referenced by begin().
initSPI()
void SDCard::initSPI () private
Initialize SPI bus for SD card.
Returns
void
Definition at line 36 of file SDCard.cpp.
                     {
    // Create new SPI instance for SD card
    _spi = new SPIClass(HSPI);
    // Initialize SPI with SD card pins
    _spi->begin(SD_SCK, SD_MISO, SD_MOSI, SD_CS);
}
References _spi, SD_CS, SD_MISO, SD_MOSI, and SD_SCK.
Referenced by begin().
isAvailable()
bool SDCard::isAvailable ()
Check if SD card is available.
Returns
true if SD card is available
false if SD card is not available
Definition at line 93 of file SDCard.cpp.
{
    return _initialized;
}
References _initialized.
listDirectory()
void SDCard::listDirectory (const char * path, uint8_t indent = 0)
List directory contents.
Parameters
path Directory path
indent Indentation level for display
path Directory path
indent Indentation level for display
Returns
void
Definition at line 247 of file SDCard.cpp.
{
    if (!_initialized) return;
    File dir = SD.open(path);
    if (!dir) {
        Serial.print("[SDCard] Failed to open directory: ");
        Serial.println(path);
        return;
    }
    if (!dir.isDirectory()) {
        Serial.println("[SDCard] Not a directory");
        dir.close();
        return;
    }
    File file = dir.openNextFile();
    while (file) {
        for (uint8_t i = 0; i < indent; i++) {
            Serial.print("  ");
        }
        Serial.print(file.name());
        if (file.isDirectory()) {
            Serial.println("/");
            // Recursively list subdirectories
            String subPath = String(path) + "/" + String(file.name());
            listDirectory(subPath.c_str(), indent + 1);
        } else {
            Serial.print(" - ");
            Serial.print(file.size());
            Serial.println(" bytes");
        }
        file.close();
        file = dir.openNextFile();
    }
    dir.close();
}
References _initialized, and listDirectory().
Referenced by listDirectory().
readFile()
String SDCard::readFile (const char * path)
Read entire file into String.
Parameters
path File path
Returns
String file contents (empty if failed)
Definition at line 294 of file SDCard.cpp.
{
    if (!_initialized) return "";
    File file = SD.open(path, FILE_READ);
    if (!file) {
        Serial.print("[SDCard] Failed to open file for reading: ");
        Serial.println(path);
        return "";
    }
    String content = "";
    while (file.available()) {
        content += char(file.read());
    }
    file.close();
    return content;
}
References _initialized.
removeDirectory()
bool SDCard::removeDirectory (const char * path)
Remove a directory.
Parameters
path Directory path
Returns
true if directory removed
false if removal failed
Definition at line 228 of file SDCard.cpp.
{
    if (!_initialized) return false;
    if (SD.rmdir(path)) {
        Serial.print("[SDCard] Directory removed: ");
        Serial.println(path);
        return true;
    }
    Serial.print("[SDCard] Failed to remove directory: ");
    Serial.println(path);
    return false;
}
References _initialized.
removeFile()
bool SDCard::removeFile (const char * path)
Remove a file.
Parameters
path File path
Returns
true if file removed
false if removal failed
Definition at line 209 of file SDCard.cpp.
{
    if (!_initialized) return false;
    if (SD.remove(path)) {
        Serial.print("[SDCard] File removed: ");
        Serial.println(path);
        return true;
    }
    Serial.print("[SDCard] Failed to remove file: ");
    Serial.println(path);
    return false;
}
References _initialized.
writeFile()
bool SDCard::writeFile (const char * path, const String & content)
Write String to file (overwrites existing).
Parameters
path File path
content Content to write
Returns
true if write successful
false if write failed
Definition at line 320 of file SDCard.cpp.
{
    if (!_initialized) return false;
    File file = SD.open(path, FILE_WRITE);
    if (!file) {
        Serial.print("[SDCard] Failed to open file for writing: ");
        Serial.println(path);
        return false;
    }
    size_t written = file.print(content);
    file.close();
    if (written == content.length()) {
        return true;
    }
    Serial.print("[SDCard] Write failed: ");
    Serial.println(path);
    return false;
}
References _initialized.
Field Documentation
_initialized
bool SDCard::_initialized private
Definition at line 156 of file SDCard.h.
Referenced by appendFile(), begin(), createDirectory(), directoryExists(), fileExists(), getCardSizeMB(), getCardType(), getFreeSpaceMB(), isAvailable(), listDirectory(), readFile(), removeDirectory(), removeFile(), SDCard(), and writeFile().
_spi
SPIClass* SDCard::_spi private
Definition at line 157 of file SDCard.h.
Referenced by begin(), initSPI(), SDCard(), and ~SDCard().
The documentation for this class was generated from the following files:
lib/SDCard/SDCard.h
lib/SDCard/SDCard.cpp