EARS-PIO-WSS3-LVGL-001: NVSEeprom Class Reference
NVSEeprom Class Reference
NVS EEPROM wrapper class @description This class provides a simple interface for storing and retrieving data.
#include <NVSEeprom.h>
Public Member Functions
NVSEeprom ()
~NVSEeprom ()
bool begin ()
Begin NVS.
String getHash (const char *key, const String &defaultValue="")
Get Hash from NVS.
bool putHash (const char *key, const String &value)
Put Hash into NVS.
String makeHash (const String &data)
Generate CRC32 hash from data.
bool compareHash (const String &data, const String &storedHash)
Compare data against stored hash.
uint16_t getVersion (const char *key, uint16_t defaultVersion=0)
Get version number from NVS.
bool putVersion (const char *key, uint16_t version)
Put version number into NVS.
NVSValidationResult validateNVS ()
Validate entire NVS storage.
bool updateNVSCRC ()
Update the stored NVS CRC32 value.
uint32_t calculateNVSCRC ()
Calculate CRC32 for entire NVS contents (excluding the CRC itself).
bool isValidZapNumber (const String &zapNumber)
Validate ZapNumber format (AANNNN).
String getZapNumber ()
Get ZapNumber from NVS.
bool setZapNumber (const String &zapNumber)
Set ZapNumber in NVS.
Static Public Attributes
static const uint16_t CURRENT_VERSION = 1
static const char * KEY_VERSION = "nvsVersion"
static const char * KEY_ZAPNUMBER = "zapNumber"
static const char * KEY_PASSWORD_HASH = "pwdHash"
static const char * KEY_NVS_CRC = "nvsCRC"
Private Member Functions
uint32_t calculateCRC32 (const uint8_t *data, size_t length)
Calculate CRC32 checksum.
bool upgradeNVS (uint16_t fromVersion, uint16_t toVersion)
Upgrade NVS from one version to another.
Static Private Attributes
static const char * NAMESPACE = "EARS"
Detailed Description
NVS EEPROM wrapper class @description This class provides a simple interface for storing and retrieving data.
Definition at line 70 of file NVSEeprom.h.
Constructor & Destructor Documentation
NVSEeprom()
NVSEeprom::NVSEeprom ()
Definition at line 27 of file NVSEeprom.cpp.
                     {
}
~NVSEeprom()
NVSEeprom::~NVSEeprom ()
Definition at line 31 of file NVSEeprom.cpp.
                      {
}
Member Function Documentation
begin()
bool NVSEeprom::begin ()
Begin NVS.
Returns
true
false
Definition at line 39 of file NVSEeprom.cpp.
                      {
    esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        nvs_flash_erase();
        err = nvs_flash_init();
    }
    return (err == ESP_OK);
}
calculateCRC32()
uint32_t NVSEeprom::calculateCRC32 (const uint8_t * data, size_t length) private
Calculate CRC32 checksum.
Parameters
data
length
Returns
uint32_t
Definition at line 94 of file NVSEeprom.cpp.
{
    uint32_t crc = 0xFFFFFFFF;
    for (size_t i = 0; i < length; i++) {
        crc ^= data[i];
        for (uint8_t j = 0; j < 8; j++) {
            crc = (crc >> 1) ^ (0xEDB88320 & -(crc & 1));
        }
    }
    return ~crc;
}
Referenced by calculateNVSCRC(), and makeHash().
calculateNVSCRC()
uint32_t NVSEeprom::calculateNVSCRC ()
Calculate CRC32 for entire NVS contents (excluding the CRC itself).
Returns
uint32_t CRC32 value
Definition at line 208 of file NVSEeprom.cpp.
{
    String dataToHash = "";
    // Open namespace in read-only mode
    if (!Preferences::begin(NAMESPACE, true)) {
        return 0;
    }
    // Concatenate all critical data in a specific order
    // Version
    uint16_t version = getUShort(KEY_VERSION, 0);
    dataToHash += String(version);
    dataToHash += "|";
    // ZapNumber
    String zapNum = getString(KEY_ZAPNUMBER, "");
    dataToHash += zapNum;
    dataToHash += "|";
    // Password Hash
    String pwdHash = getString(KEY_PASSWORD_HASH, "");
    dataToHash += pwdHash;
    end();
    // Calculate CRC32 of concatenated data
    return calculateCRC32((const uint8_t*)dataToHash.c_str(), dataToHash.length());
}
References calculateCRC32(), KEY_PASSWORD_HASH, KEY_VERSION, KEY_ZAPNUMBER, and NAMESPACE.
Referenced by updateNVSCRC(), and validateNVS().
compareHash()
bool NVSEeprom::compareHash (const String & data, const String & storedHash)
Compare data against stored hash.
Parameters
data
storedHash
Returns
true
false
Definition at line 131 of file NVSEeprom.cpp.
{
    String computedHash = makeHash(data);
    return (computedHash.equals(storedHash));
}
References makeHash().
getHash()
String NVSEeprom::getHash (const char * key, const String & defaultValue = "")
Get Hash from NVS.
Parameters
key
defaultValue
Returns
Hash String
Definition at line 55 of file NVSEeprom.cpp.
{
    // Open namespace in read-only mode
    if (!Preferences::begin(NAMESPACE, true)) {
        return defaultValue;
    }
    String hash = getString(key, defaultValue);
    end();
    return hash;
}
References NAMESPACE.
getVersion()
uint16_t NVSEeprom::getVersion (const char * key, uint16_t defaultVersion = 0)
Get version number from NVS.
Parameters
key
defaultVersion
Returns
uint16_t Version number (0-65535)
Definition at line 143 of file NVSEeprom.cpp.
{
    // Open namespace in read-only mode
    if (!Preferences::begin(NAMESPACE, true)) {
        return defaultVersion;
    }
    uint16_t version = getUShort(key, defaultVersion);
    end();
    return version;
}
References NAMESPACE.
getZapNumber()
String NVSEeprom::getZapNumber ()
Get ZapNumber from NVS.
Returns
String The stored ZapNumber or empty string if not found
Definition at line 402 of file NVSEeprom.cpp.
{
    // Open namespace in read-only mode
    if (!Preferences::begin(NAMESPACE, true)) {
        return "";
    }
    String zapNumber = getString(KEY_ZAPNUMBER, "");
    end();
    return zapNumber;
}
References KEY_ZAPNUMBER, and NAMESPACE.
isValidZapNumber()
bool NVSEeprom::isValidZapNumber (const String & zapNumber)
Validate ZapNumber format (AANNNN).
Parameters
zapNumber String to validate
Returns
true Valid format
false Invalid format
Definition at line 182 of file NVSEeprom.cpp.
{
    // Must be exactly 6 characters
    if (zapNumber.length() != 6) {
        return false;
    }
    // First two characters must be letters (A-Z)
    if (!isAlpha(zapNumber[0]) || !isAlpha(zapNumber[1])) {
        return false;
    }
    // Last four characters must be digits (0-9)
    for (int i = 2; i < 6; i++) {
        if (!isDigit(zapNumber[i])) {
            return false;
        }
    }
    return true;
}
Referenced by setZapNumber(), and validateNVS().
makeHash()
String NVSEeprom::makeHash (const String & data)
Generate CRC32 hash from data.
Parameters
data
Returns
String
Definition at line 113 of file NVSEeprom.cpp.
{
    uint32_t crc = calculateCRC32((const uint8_t*)data.c_str(), data.length());
    // Convert to 8-character hex string
    char hashStr[9];
    sprintf(hashStr, "%08X", crc);
    return String(hashStr);
}
References calculateCRC32().
Referenced by compareHash().
putHash()
bool NVSEeprom::putHash (const char * key, const String & value)
Put Hash into NVS.
Parameters
key
value
Returns
true
false
Definition at line 75 of file NVSEeprom.cpp.
{
    // Open namespace in read-write mode
    if (!Preferences::begin(NAMESPACE, false)) {
        return false;
    }
    size_t result = putString(key, value);
    end();
    return (result > 0);
}
References NAMESPACE.
putVersion()
bool NVSEeprom::putVersion (const char * key, uint16_t version)
Put version number into NVS.
Parameters
key
version Version number (0-65535)
Returns
true Success
false Failed
Definition at line 163 of file NVSEeprom.cpp.
{
    // Open namespace in read-write mode
    if (!Preferences::begin(NAMESPACE, false)) {
        return false;
    }
    size_t result = putUShort(key, version);
    end();
    return (result > 0);
}
References NAMESPACE.
setZapNumber()
bool NVSEeprom::setZapNumber (const String & zapNumber)
Set ZapNumber in NVS.
Parameters
zapNumber The ZapNumber to store (format: AANNNN)
Returns
true if successful
false if invalid format or write failed
Definition at line 421 of file NVSEeprom.cpp.
{
    // Validate format first
    if (!isValidZapNumber(zapNumber)) {
        return false;
    }
    // Open namespace in read-write mode
    if (!Preferences::begin(NAMESPACE, false)) {
        return false;
    }
    // Store in NVS
    size_t result = putString(KEY_ZAPNUMBER, zapNumber);
    end();
    if (result == 0) {
        return false;
    }
    // Update CRC after successful write
    return updateNVSCRC();
}
References isValidZapNumber(), KEY_ZAPNUMBER, NAMESPACE, and updateNVSCRC().
updateNVSCRC()
bool NVSEeprom::updateNVSCRC ()
Update the stored NVS CRC32 value.
Returns
true Success
false Failed
Definition at line 243 of file NVSEeprom.cpp.
{
    uint32_t crc = calculateNVSCRC();
    // Open namespace in read-write mode
    if (!Preferences::begin(NAMESPACE, false)) {
        return false;
    }
    size_t result = putUInt(KEY_NVS_CRC, crc);
    end();
    return (result > 0);
}
References calculateNVSCRC(), KEY_NVS_CRC, and NAMESPACE.
Referenced by setZapNumber(), and upgradeNVS().
upgradeNVS()
bool NVSEeprom::upgradeNVS (uint16_t fromVersion, uint16_t toVersion) private
Upgrade NVS from one version to another.
Parameters
fromVersion Current version
toVersion Target version
Returns
true Upgrade successful
false Upgrade failed
Definition at line 265 of file NVSEeprom.cpp.
{
    // Prevent downgrade
    if (toVersion <= fromVersion) {
        return false;
    }
    // Prevent upgrade beyond CURRENT_VERSION
    if (toVersion > CURRENT_VERSION) {
        return false;
    }
    // Open namespace in read-write mode
    if (!Preferences::begin(NAMESPACE, false)) {
        return false;
    }
    // Future: Add version-specific upgrade logic here
    // For now, just update the version number
    // Example upgrade paths:
    // if (fromVersion == 0 && toVersion >= 1) {
    //     // Upgrade from version 0 to 1
    //     // Add new keys, migrate data, etc.
    // }
    // Update version
    size_t result = putUShort(KEY_VERSION, toVersion);
    end();
    if (result == 0) {
        return false;
    }
    // Recalculate and update CRC after upgrade
    return updateNVSCRC();
}
References CURRENT_VERSION, KEY_VERSION, NAMESPACE, and updateNVSCRC().
Referenced by validateNVS().
validateNVS()
NVSValidationResult NVSEeprom::validateNVS ()
Validate entire NVS storage.
This function checks:
Version matches or can be upgraded
ZapNumber exists and is valid format
Password hash exists
Overall CRC32 is valid (no tampering)
Returns
NVSValidationResult Structure containing validation results
Definition at line 313 of file NVSEeprom.cpp.
{
    NVSValidationResult result;
    result.expectedVersion = CURRENT_VERSION;
    // Step 1: Check NVS initialization
    if (!Preferences::begin(NAMESPACE, true)) {
        result.status = NVSStatus::INITIALIZATION_FAILED;
        end();
        return result;
    }
    // Step 2: Get and check version
    result.currentVersion = getUShort(KEY_VERSION, 0);
    // Check if upgrade is needed
    if (result.currentVersion < CURRENT_VERSION) {
        end(); // Close read-only session
        // Attempt upgrade
        if (upgradeNVS(result.currentVersion, CURRENT_VERSION)) {
            result.wasUpgraded = true;
            result.currentVersion = CURRENT_VERSION;
        } else {
            result.status = NVSStatus::INVALID_VERSION;
            return result;
        }
        // Reopen for continued validation
        if (!Preferences::begin(NAMESPACE, true)) {
            result.status = NVSStatus::INITIALIZATION_FAILED;
            return result;
        }
    } else if (result.currentVersion > CURRENT_VERSION) {
        // Version from future - cannot handle
        result.status = NVSStatus::INVALID_VERSION;
        end();
        return result;
    }
    // Step 3: Check ZapNumber
    String zapNum = getString(KEY_ZAPNUMBER, "");
    if (zapNum.length() == 0 || !isValidZapNumber(zapNum)) {
        result.zapNumberValid = false;
        result.status = NVSStatus::MISSING_ZAPNUMBER;
        end();
        return result;
    }
    result.zapNumberValid = true;
    zapNum.toCharArray(result.zapNumber, 7);
    // Step 4: Check password hash
    String pwdHash = getString(KEY_PASSWORD_HASH, "");
    if (pwdHash.length() == 0) {
        result.passwordHashValid = false;
        result.status = NVSStatus::MISSING_PASSWORD;
        end();
        return result;
    }
    result.passwordHashValid = true;
    // Step 5: Check overall CRC32
    uint32_t storedCRC = getUInt(KEY_NVS_CRC, 0);
    end(); // Close before calculating new CRC
    uint32_t calculatedCRC = calculateNVSCRC();
    result.calculatedCRC = calculatedCRC;
    if (storedCRC != calculatedCRC) {
        result.crcValid = false;
        result.status = NVSStatus::CRC_FAILED;
        return result;
    }
    result.crcValid = true;
    // Step 6: All checks passed
    if (result.wasUpgraded) {
        result.status = NVSStatus::UPGRADED;
    } else {
        result.status = NVSStatus::VALID;
    }
    return result;
}
References NVSValidationResult::calculatedCRC, calculateNVSCRC(), CRC_FAILED, NVSValidationResult::crcValid, CURRENT_VERSION, NVSValidationResult::currentVersion, NVSValidationResult::expectedVersion, INITIALIZATION_FAILED, INVALID_VERSION, isValidZapNumber(), KEY_NVS_CRC, KEY_PASSWORD_HASH, KEY_VERSION, KEY_ZAPNUMBER, MISSING_PASSWORD, MISSING_ZAPNUMBER, NAMESPACE, NVSValidationResult::passwordHashValid, NVSValidationResult::status, UPGRADED, upgradeNVS(), VALID, NVSValidationResult::wasUpgraded, NVSValidationResult::zapNumber, and NVSValidationResult::zapNumberValid.
Field Documentation
CURRENT_VERSION
const uint16_t NVSEeprom::CURRENT_VERSION = 1 static
Definition at line 73 of file NVSEeprom.h.
Referenced by example_firstTimeSetup(), upgradeNVS(), and validateNVS().
KEY_NVS_CRC
const char * NVSEeprom::KEY_NVS_CRC = "nvsCRC" static
Definition at line 79 of file NVSEeprom.h.
Referenced by updateNVSCRC(), and validateNVS().
KEY_PASSWORD_HASH
const char * NVSEeprom::KEY_PASSWORD_HASH = "pwdHash" static
Definition at line 78 of file NVSEeprom.h.
Referenced by calculateNVSCRC(), example_firstTimeSetup(), example_validateLogin(), and validateNVS().
KEY_VERSION
const char * NVSEeprom::KEY_VERSION = "nvsVersion" static
Definition at line 76 of file NVSEeprom.h.
Referenced by calculateNVSCRC(), example_firstTimeSetup(), upgradeNVS(), and validateNVS().
KEY_ZAPNUMBER
const char * NVSEeprom::KEY_ZAPNUMBER = "zapNumber" static
Definition at line 77 of file NVSEeprom.h.
Referenced by calculateNVSCRC(), example_firstTimeSetup(), getZapNumber(), setZapNumber(), and validateNVS().
NAMESPACE
const char * NVSEeprom::NAMESPACE = "EARS" static private
Definition at line 114 of file NVSEeprom.h.
Referenced by calculateNVSCRC(), getHash(), getVersion(), getZapNumber(), putHash(), putVersion(), setZapNumber(), updateNVSCRC(), upgradeNVS(), and validateNVS().
The documentation for this class was generated from the following files:
lib/NVSEeprom/NVSEeprom.h
lib/NVSEeprom/NVSEeprom.cpp