EARS-PIO-WSS3-LVGL-001: Logger Class Reference
Logger Class Reference
Enhanced Logger class with hierarchical levels.
#include <Logger.h>
Public Member Functions
bool begin (const char *logFilePath, const char *configFilePath, SDCard *sdCard)
Initialize logger.
bool isInitialized () const
Check if logger is initialized.
void debug (const char *message)
Log a message at DEBUG level.
void debugf (const char *format,...)
Log a formatted message at DEBUG level.
void info (const char *message)
Log a message at INFO level.
void infof (const char *format,...)
Log a formatted message at INFO level.
void warn (const char *message)
Log a message at WARN level.
void warnf (const char *format,...)
Log a formatted message at WARN level.
void error (const char *message)
Log a message at ERROR level.
void errorf (const char *format,...)
Log a formatted message at ERROR level.
void setLogLevel (LogLevel level)
Set current log level.
LogLevel getLogLevel () const
Get current log level.
String getLogLevelString () const
Get log level as string.
bool setLogLevelFromString (const String &levelStr)
Set log level from string.
bool saveConfig ()
Save logger config to unified ears.config.
bool loadConfig ()
Load logger config from unified ears.config.
bool clearLog ()
Clear/delete current log file.
uint32_t getLogFileSize ()
Get current log file size in bytes.
float getLogFileSizeMB ()
Get current log file size in MB.
bool rotateLog ()
Force log rotation (for testing).
bool wouldLog (LogLevel level) const
Check if a message at given level would be logged.
Static Public Member Functions
static Logger & getInstance ()
Get singleton instance.
Private Member Functions
Logger ()
Private constructor.
~Logger ()
Destructor.
Logger (const Logger &)=delete
Logger & operator= (const Logger &)=delete
void log (LogLevel level, const char *message)
Core logging function.
void logf (LogLevel level, const char *format, va_list args)
Core formatted logging function.
bool shouldLog (LogLevel level) const
Check if level should be logged (hierarchical).
const char * getLevelString (LogLevel level) const
Get level string for log entry.
String getTimestamp () const
Get current timestamp string.
bool needsRotation ()
Check if log needs rotation.
bool performRotation ()
Perform log rotation.
bool loadUnifiedConfig (JsonDocument &doc)
Load entire unified config file.
bool saveUnifiedConfig (const JsonDocument &doc)
Save entire unified config file.
LogLevel parseLevelString (const String &levelStr) const
Parse log level from string.
String levelToString (LogLevel level) const
Convert log level to string.
Private Attributes
bool _initialized
String _logFilePath
String _configFilePath
SDCard * _sdCard
LoggerConfig _config
Detailed Description
Enhanced Logger class with hierarchical levels.
Definition at line 56 of file Logger.h.
Constructor & Destructor Documentation
Logger() [1/2]
Logger::Logger () private
Private constructor.
Definition at line 27 of file Logger.cpp.
               :
    _initialized(false),
    _logFilePath(""),
    _configFilePath(""),
    _sdCard(nullptr) {
}
References _configFilePath, _initialized, _logFilePath, and _sdCard.
Referenced by getInstance(), Logger(), and operator=().
~Logger()
Logger::~Logger () private
Destructor.
Definition at line 37 of file Logger.cpp.
                {
}
Logger() [2/2]
Logger::Logger (const Logger &) private delete
References Logger().
Member Function Documentation
begin()
bool Logger::begin (const char * logFilePath, const char * configFilePath, SDCard * sdCard)
Initialize logger.
Parameters
logFilePath Path to log file (e.g., "/logs/debug.log")
configFilePath Path to unified config file (e.g., "/config/ears.config")
sdCard Pointer to SDCard instance
Returns
true if initialization successful
false if initialization failed
true if initialization successful.
false if initialization failed.
Parameters
logFilePath Path to log file (e.g., "/logs/debug.log")
configFilePath Path to unified config file (e.g., "/config/ears.config")
sdCard Pointer to SDCard instance
Definition at line 49 of file Logger.cpp.
{
    if (_initialized) {
        return true;
    }
    if (!sdCard || !sdCard->isAvailable()) {
        return false;
    }
    _sdCard = sdCard;
    _logFilePath = String(logFilePath);
    _configFilePath = String(configFilePath);
    // Ensure log directory exists
    int lastSlash = _logFilePath.lastIndexOf('/');
    if (lastSlash > 0) {
        String logDir = _logFilePath.substring(0, lastSlash);
        if (!_sdCard->directoryExists(logDir.c_str())) {
            _sdCard->createDirectory(logDir.c_str());
        }
    }
    // Ensure config directory exists
    lastSlash = _configFilePath.lastIndexOf('/');
    if (lastSlash > 0) {
        String configDir = _configFilePath.substring(0, lastSlash);
        if (!_sdCard->directoryExists(configDir.c_str())) {
            _sdCard->createDirectory(configDir.c_str());
        }
    }
    // Load configuration (creates default if not exists)
    loadConfig();
    _initialized = true;
    // Log initialization
    info("=== Logger v2.1 Initialized ===");
    infof("Log file: %s", _logFilePath.c_str());
    infof("Config file: %s", _configFilePath.c_str());
    infof("Log level: %s", getLogLevelString().c_str());
    infof("Max file size: %d bytes (%.2f MB)", _config.maxFileSizeBytes, _config.maxFileSizeBytes / 1048576.0);
    infof("Max rotated files: %d", _config.maxRotatedFiles);
    return true;
}
References _config, _configFilePath, _initialized, _logFilePath, _sdCard, getLogLevelString(), info(), infof(), loadConfig(), and sdCard.
clearLog()
bool Logger::clearLog ()
Clear/delete current log file.
Returns
true if log cleared successfully
false if clearing log failed
true if clear successful
false if clear failed
Definition at line 464 of file Logger.cpp.
                      {
    if (!_initialized) {
        return false;
    }
    bool result = _sdCard->removeFile(_logFilePath.c_str());
    if (result) {
        info("Log file cleared");
    }
    return result;
}
References _initialized, _logFilePath, _sdCard, and info().
debug()
void Logger::debug (const char * message)
Log a message at DEBUG level.
Returns
void
Parameters
message Message to log
Returns
void
Definition at line 101 of file Logger.cpp.
{
    log(LogLevel::DEBUG, message);
}
References DEBUG, and log().
debugf()
void Logger::debugf (const char * format, ...)
Log a formatted message at DEBUG level.
Parameters
format printf-style format string
Returns
void
Parameters
format Format string
Returns
void
Definition at line 110 of file Logger.cpp.
{
    va_list args;
    va_start(args, format);
    logf(LogLevel::DEBUG, format, args);
    va_end(args);
}
References DEBUG, and logf().
error()
void Logger::error (const char * message)
Log a message at ERROR level.
Parameters
message Message to log
Returns
void
Definition at line 164 of file Logger.cpp.
{
    log(LogLevel::ERROR, message);
}
References ERROR, and log().
Referenced by loadUnifiedConfig().
errorf()
void Logger::errorf (const char * format, ...)
Log a formatted message at ERROR level.
Parameters
format printf-style format string
Returns
void
Parameters
format Format string
Returns
void
Definition at line 173 of file Logger.cpp.
{
    va_list args;
    va_start(args, format);
    logf(LogLevel::ERROR, format, args);
    va_end(args);
}
References ERROR, and logf().
getInstance()
Logger & Logger::getInstance () static
Get singleton instance.
Returns
Logger& Reference to Logger instance.
Definition at line 19 of file Logger.cpp.
{
    static Logger instance;
    return instance;
}
References Logger().
getLevelString()
const char * Logger::getLevelString (LogLevel level) const private
Get level string for log entry.
Parameters
level Log level
Returns
const char* Level string
Definition at line 252 of file Logger.cpp.
{
    switch (level) {
        case LogLevel::DEBUG:
            return "DEBUG";
        case LogLevel::INFO:
            return "INFO";
        case LogLevel::WARN:
            return "WARN";
        case LogLevel::ERROR:
            return "ERROR";
        case LogLevel::NONE:
        default:
            return "NONE";
    }
}
References DEBUG, ERROR, INFO, NONE, and WARN.
Referenced by log().
getLogFileSize()
uint32_t Logger::getLogFileSize ()
Get current log file size in bytes.
Returns
uint32_t log file size in bytes
uint32_t Log file size in bytes
Definition at line 482 of file Logger.cpp.
{
    if (!_initialized || !_sdCard->fileExists(_logFilePath.c_str())) {
        return 0;
    }
    File file = SD.open(_logFilePath.c_str(), FILE_READ);
    if (!file) {
        return 0;
    }
    uint32_t size = file.size();
    file.close();
    return size;
}
References _initialized, _logFilePath, and _sdCard.
Referenced by getLogFileSizeMB(), and needsRotation().
getLogFileSizeMB()
float Logger::getLogFileSizeMB ()
Get current log file size in MB.
Returns
float log file size in megabytes
float Log file size in MB
Definition at line 502 of file Logger.cpp.
{
    return getLogFileSize() / 1048576.0;
}
References getLogFileSize().
getLogLevel()
LogLevel Logger::getLogLevel () const inline
Get current log level.
Parameters
level New log level (NONE, ERROR, WARN, INFO, DEBUG)
Returns
LogLevel current log level
Definition at line 148 of file Logger.h.
{ return _config.currentLevel; }
References _config.
getLogLevelString()
String Logger::getLogLevelString () const
Get log level as string.
Returns
String "NONE", "ERROR", "WARN", "INFO", or "DEBUG"
String Log level string
Definition at line 310 of file Logger.cpp.
{
    return levelToString(_config.currentLevel);
}
References _config, and levelToString().
Referenced by begin().
getTimestamp()
String Logger::getTimestamp () const private
Get current timestamp string.
Returns
String timestamp in "YYYY-MM-DD HH:MM:SS" format
String Timestamp in "YYYY-MM-DD HH:MM:SS" format
Definition at line 272 of file Logger.cpp.
{
    struct timeval tv;
    gettimeofday(&tv, NULL);
    struct tm timeinfo;
    localtime_r(&tv.tv_sec, &timeinfo);
    char buffer[32];
    snprintf(buffer, sizeof(buffer), "%04d-%02d-%02d %02d:%02d:%02d",
             timeinfo.tm_year + 1900,
             timeinfo.tm_mon + 1,
             timeinfo.tm_mday,
             timeinfo.tm_hour,
             timeinfo.tm_min,
             timeinfo.tm_sec);
    return String(buffer);
}
Referenced by log().
info()
void Logger::info (const char * message)
Log a message at INFO level.
Parameters
message Message to log
Returns
void
Definition at line 122 of file Logger.cpp.
{
    log(LogLevel::INFO, message);
}
References INFO, and log().
Referenced by begin(), clearLog(), and performRotation().
infof()
void Logger::infof (const char * format, ...)
Log a formatted message at INFO level.
Parameters
format printf-style format string
Returns
void
Parameters
format Format string
Returns
void
Definition at line 131 of file Logger.cpp.
{
    va_list args;
    va_start(args, format);
    logf(LogLevel::INFO, format, args);
    va_end(args);
}
References INFO, and logf().
Referenced by begin(), and setLogLevel().
isInitialized()
bool Logger::isInitialized () const inline
Check if logger is initialized.
Returns
true if initialized
false if not initialized
Definition at line 79 of file Logger.h.
{ return _initialized; }
References _initialized.
levelToString()
String Logger::levelToString (LogLevel level) const private
Convert log level to string.
Parameters
level LogLevel to convert
Returns
String log level as string
Parameters
level Log level
Returns
String Log level string
Definition at line 352 of file Logger.cpp.
{
    switch (level) {
        case LogLevel::NONE:
            return "NONE";
        case LogLevel::ERROR:
            return "ERROR";
        case LogLevel::WARN:
            return "WARN";
        case LogLevel::INFO:
            return "INFO";
        case LogLevel::DEBUG:
            return "DEBUG";
        default:
            return "UNKNOWN";
    }
}
References DEBUG, ERROR, INFO, NONE, and WARN.
Referenced by getLogLevelString(), saveConfig(), and setLogLevel().
loadConfig()
bool Logger::loadConfig ()
Load logger config from unified ears.config.
Returns
true if load successful
false if load failed
Definition at line 406 of file Logger.cpp.
{
    JsonDocument doc;
    if (!loadUnifiedConfig(doc)) {
        // Config doesn't exist, create default
        doc["system"]["version"] = "1.0.0";
        doc["system"]["zap_number"] = "";  // Will be populated from NVS
        doc["system"]["device_name"] = "EARS";
        doc["logger"]["log_level"] = "DEBUG";
        doc["logger"]["max_file_size_bytes"] = 1048576;
        doc["logger"]["max_rotated_files"] = 3;
        saveUnifiedConfig(doc);
    }
    // Extract logger section
    JsonObject loggerObj = doc["logger"];
    if (loggerObj.isNull()) {
        return false;
    }
    String levelStr = loggerObj["log_level"] | "DEBUG";
    _config.currentLevel = parseLevelString(levelStr);
    _config.maxFileSizeBytes = loggerObj["max_file_size_bytes"] | 1048576;
    _config.maxRotatedFiles = loggerObj["max_rotated_files"] | 3;
    return true;
}
References _config, loadUnifiedConfig(), parseLevelString(), and saveUnifiedConfig().
Referenced by begin().
loadUnifiedConfig()
bool Logger::loadUnifiedConfig (JsonDocument & doc) private
Load entire unified config file.
Parameters
doc JsonDocument to load config into
Returns
true if load successful
false if load failed
Parameters
doc JsonDocument to load into
Returns
true if load successful
false if load failed*
Definition at line 375 of file Logger.cpp.
{
    if (!_sdCard || !_sdCard->fileExists(_configFilePath.c_str())) {
        return false;
    }
    String jsonString = _sdCard->readFile(_configFilePath.c_str());
    if (jsonString.length() == 0) {
        return false;
    }
    DeserializationError error = deserializeJson(doc, jsonString);
    return !error;
}
References _configFilePath, _sdCard, and error().
Referenced by loadConfig(), and saveConfig().
log()
void Logger::log (LogLevel level, const char * message) private
Core logging function.
Parameters
level LogLevel of the message
message Message to log
Returns
void
Parameters
level Log level
message Message to log
Returns
void
Definition at line 186 of file Logger.cpp.
{
    if (!_initialized || !shouldLog(level)) {
        return;
    }
    // Check if rotation needed
    if (needsRotation()) {
        performRotation();
    }
    // Format log entry
    String logEntry = "[";
    logEntry += getTimestamp();
    logEntry += "] [";
    logEntry += getLevelString(level);
    logEntry += "] ";
    logEntry += message;
    logEntry += "\n";
    // Write to file
    _sdCard->appendFile(_logFilePath.c_str(), logEntry);
}
References _initialized, _logFilePath, _sdCard, getLevelString(), getTimestamp(), needsRotation(), performRotation(), and shouldLog().
Referenced by debug(), error(), info(), logf(), and warn().
logf()
void Logger::logf (LogLevel level, const char * format, va_list args) private
Core formatted logging function.
Parameters
level LogLevel of the message
format printf-style format string
args va_list of arguments
Returns
void
Parameters
level Log level
format Format string
args Variable argument list
Returns
void
Definition at line 216 of file Logger.cpp.
{
    if (!_initialized || !shouldLog(level)) {
        return;
    }
    char buffer[512];
    vsnprintf(buffer, sizeof(buffer), format, args);
    log(level, buffer);
}
References _initialized, log(), and shouldLog().
Referenced by debugf(), errorf(), infof(), and warnf().
needsRotation()
bool Logger::needsRotation () private
Check if log needs rotation.
Returns
true if rotation needed
false if rotation not needed
Definition at line 511 of file Logger.cpp.
{
    uint32_t currentSize = getLogFileSize();
    return (currentSize >= _config.maxFileSizeBytes);
}
References _config, and getLogFileSize().
Referenced by log().
operator=()
Logger & Logger::operator= (const Logger &) private delete
References Logger().
parseLevelString()
LogLevel Logger::parseLevelString (const String & levelStr) const private
Parse log level from string.
Parameters
levelStr "NONE", "ERROR", "WARN", "INFO", or "DEBUG"
Returns
LogLevel parsed log level
Parameters
levelStr Log level string
Returns
LogLevel Parsed log level
Definition at line 334 of file Logger.cpp.
{
    String upper = levelStr;
    upper.toUpperCase();
    if (upper == "NONE") return LogLevel::NONE;
    if (upper == "ERROR") return LogLevel::ERROR;
    if (upper == "WARN" || upper == "WARNING") return LogLevel::WARN;
    if (upper == "INFO") return LogLevel::INFO;
    if (upper == "DEBUG") return LogLevel::DEBUG;
    return LogLevel::NONE;  // Default to NONE if invalid
}
References DEBUG, ERROR, INFO, NONE, and WARN.
Referenced by loadConfig(), and setLogLevelFromString().
performRotation()
bool Logger::performRotation () private
Perform log rotation.
Returns
true if rotation successful
false if rotation failed
Definition at line 521 of file Logger.cpp.
{
    if (!_initialized) {
        return false;
    }
    info("Starting log rotation...");
    // Delete oldest rotated file if it exists
    String oldestFile = _logFilePath + "." + String(_config.maxRotatedFiles);
    if (_sdCard->fileExists(oldestFile.c_str())) {
        _sdCard->removeFile(oldestFile.c_str());
    }
    // Shift all rotated files up by one
    for (int i = _config.maxRotatedFiles - 1; i >= 1; i--) {
        String oldName = _logFilePath + "." + String(i);
        String newName = _logFilePath + "." + String(i + 1);
        if (_sdCard->fileExists(oldName.c_str())) {
            // Read old file
            String content = _sdCard->readFile(oldName.c_str());
            // Write to new file
            _sdCard->writeFile(newName.c_str(), content);
            // Delete old file
            _sdCard->removeFile(oldName.c_str());
        }
    }
    // Rename current log to .1
    String rotatedName = _logFilePath + ".1";
    if (_sdCard->fileExists(_logFilePath.c_str())) {
        String content = _sdCard->readFile(_logFilePath.c_str());
        _sdCard->writeFile(rotatedName.c_str(), content);
        _sdCard->removeFile(_logFilePath.c_str());
    }
    info("Log rotation completed");
    return true;
}
References _config, _initialized, _logFilePath, _sdCard, and info().
Referenced by log(), and rotateLog().
rotateLog()
bool Logger::rotateLog ()
Force log rotation (for testing).
Returns
true if rotation successful
false if rotation failed
Definition at line 567 of file Logger.cpp.
                       {
    return performRotation();
}
References performRotation().
saveConfig()
bool Logger::saveConfig ()
Save logger config to unified ears.config.
Returns
true if save successful
false if save failed
Only updates the logger section, preserves other sections
Returns
true if save successful
false if save failed
Definition at line 441 of file Logger.cpp.
{
    if (!_initialized) {
        return false;
    }
    JsonDocument doc;
    // Load existing config or create new
    loadUnifiedConfig(doc);
    // Update logger section
    doc["logger"]["log_level"] = levelToString(_config.currentLevel);
    doc["logger"]["max_file_size_bytes"] = _config.maxFileSizeBytes;
    doc["logger"]["max_rotated_files"] = _config.maxRotatedFiles;
    return saveUnifiedConfig(doc);
}
References _config, _initialized, levelToString(), loadUnifiedConfig(), and saveUnifiedConfig().
Referenced by setLogLevel().
saveUnifiedConfig()
bool Logger::saveUnifiedConfig (const JsonDocument & doc) private
Save entire unified config file.
Parameters
doc JsonDocument containing config to save
Returns
true if save successful
false if save failed
Parameters
doc JsonDocument to save
Returns
true if save successful
false if save failed
Definition at line 395 of file Logger.cpp.
{
    String jsonString;
    serializeJsonPretty(doc, jsonString);
    return _sdCard->writeFile(_configFilePath.c_str(), jsonString);
}
References _configFilePath, and _sdCard.
Referenced by loadConfig(), and saveConfig().
setLogLevel()
void Logger::setLogLevel (LogLevel level)
Set current log level.
Parameters
level New log level (NONE, ERROR, WARN, INFO, DEBUG)
Returns
void
Definition at line 296 of file Logger.cpp.
{
    _config.currentLevel = level;
    saveConfig();
    // Log the change at INFO level (if it will be visible)
    if (shouldLog(LogLevel::INFO)) {
        infof("Log level changed to: %s", levelToString(level).c_str());
    }
}
References _config, INFO, infof(), levelToString(), saveConfig(), and shouldLog().
Referenced by setLogLevelFromString().
setLogLevelFromString()
bool Logger::setLogLevelFromString (const String & levelStr)
Set log level from string.
Parameters
levelStr "NONE", "ERROR", "WARN", "INFO", or "DEBUG"
Returns
true if valid level string
false if invalid level string
Definition at line 320 of file Logger.cpp.
{
    LogLevel level = parseLevelString(levelStr);
    if (level == LogLevel::NONE && levelStr != "NONE") {
        return false;  // Invalid string
    }
    setLogLevel(level);
    return true;
}
References NONE, parseLevelString(), and setLogLevel().
shouldLog()
bool Logger::shouldLog (LogLevel level) const private
Check if level should be logged (hierarchical).
Parameters
level LogLevel to check
Returns
true if level should be logged
false if level should be ignored
Parameters
level Log level to check
Returns
true if should log
false if should not log
Definition at line 232 of file Logger.cpp.
{
    // Hierarchical: current level must be >= message level
    return (static_cast<int>(_config.currentLevel) >= static_cast<int>(level));
}
References _config.
Referenced by log(), logf(), setLogLevel(), and wouldLog().
warn()
void Logger::warn (const char * message)
Log a message at WARN level.
Parameters
message Message to log
Returns
void
Definition at line 143 of file Logger.cpp.
{
    log(LogLevel::WARN, message);
}
References log(), and WARN.
warnf()
void Logger::warnf (const char * format, ...)
Log a formatted message at WARN level.
Parameters
format printf-style format string
Returns
void
Parameters
format Format string
Returns
void
Definition at line 152 of file Logger.cpp.
{
    va_list args;
    va_start(args, format);
    logf(LogLevel::WARN, format, args);
    va_end(args);
}
References logf(), and WARN.
wouldLog()
bool Logger::wouldLog (LogLevel level) const
Check if a message at given level would be logged.
Parameters
level LogLevel to check
Returns
true if message at this level would be logged
false if message at this level would be ignored
Useful for avoiding expensive string operations
Parameters
level Log level to check
Returns
true if would log
false if would not log
Definition at line 243 of file Logger.cpp.
{
    return _initialized && shouldLog(level);
}
References _initialized, and shouldLog().
Field Documentation
_config
LoggerConfig Logger::_config private
Definition at line 230 of file Logger.h.
Referenced by begin(), getLogLevel(), getLogLevelString(), loadConfig(), needsRotation(), performRotation(), saveConfig(), setLogLevel(), and shouldLog().
_configFilePath
String Logger::_configFilePath private
Definition at line 228 of file Logger.h.
Referenced by begin(), loadUnifiedConfig(), Logger(), and saveUnifiedConfig().
_initialized
bool Logger::_initialized private
Definition at line 226 of file Logger.h.
Referenced by begin(), clearLog(), getLogFileSize(), isInitialized(), log(), logf(), Logger(), performRotation(), saveConfig(), and wouldLog().
_logFilePath
String Logger::_logFilePath private
Definition at line 227 of file Logger.h.
Referenced by begin(), clearLog(), getLogFileSize(), log(), Logger(), and performRotation().
_sdCard
SDCard* Logger::_sdCard private
Definition at line 229 of file Logger.h.
Referenced by begin(), clearLog(), getLogFileSize(), loadUnifiedConfig(), log(), Logger(), performRotation(), and saveUnifiedConfig().
The documentation for this class was generated from the following files:
lib/Logger/Logger.h
lib/Logger/Logger.cpp