EARS-PIO-WSS3-LVGL-001: ScreensaverLib Class Reference
ScreensaverLib Class Reference
Screensaver Library Class.
#include <ScreensaverLib.h>
Public Member Functions
ScreensaverLib ()
Construct a new Screensaver Lib:: Screensaver Lib object.
void begin (lv_display_t *display)
Initialization.
void setEnabled (bool enabled)
Set explicit state.
void toggleEnabled ()
Toggle current state.
void setTimeout (uint8_t seconds)
Set timeout in seconds.
void setMode (ScreensaverMode mode)
Set screensaver mode.
void setAnimationSpeed (uint8_t speed)
Set animation speed in seconds.
void setBounceMode (bool bounce)
Set bounce mode.
void reset ()
Reset inactivity timer.
void activate ()
Activate screensaver.
void deactivate ()
Deactivate screensaver.
void update ()
Update screensaver state, call regularly in loop.
bool isActive ()
Check if screensaver is active.
ScreensaverSettings getSettings ()
Get current settings.
Private Member Functions
void createScreensaverScreen ()
Private: Create the screensaver screen.
void destroyScreensaverScreen ()
Private: Destroy the screensaver screen.
void saveBacklight ()
Private: Save current backlight value.
void restoreBacklight ()
Private: Restore backlight to saved value.
void updateAnimation ()
Private: Update screensaver animation.
Private Attributes
lv_display_t * _display
ScreensaverSettings _settings
uint32_t _last_activity_ms
bool _is_active
lv_obj_t * _screensaver_screen
Detailed Description
Screensaver Library Class.
Definition at line 60 of file ScreensaverLib.h.
Constructor & Destructor Documentation
ScreensaverLib()
ScreensaverLib::ScreensaverLib ()
Construct a new Screensaver Lib:: Screensaver Lib object.
Returns
ScreensaverLib&*
Definition at line 18 of file ScreensaverLib.cpp.
{
    _display = nullptr;
    _is_active = false;
    _last_activity_ms = 0;
    _screensaver_screen = nullptr;
    // Default settings
    _settings.enabled = true;
    _settings.timeout_seconds = 30;
    _settings.mode = SS_MODE_EARS_TEXT;
    _settings.animation_speed = 5;
    _settings.bounce_mode = true;
    _settings.backlight_restore = 255;
}
References _display, _is_active, _last_activity_ms, _screensaver_screen, _settings, and SS_MODE_EARS_TEXT.
Member Function Documentation
activate()
void ScreensaverLib::activate ()
Activate screensaver.
Returns
void
Definition at line 147 of file ScreensaverLib.cpp.
{
    if (_is_active) return;
    saveBacklight();
    createScreensaverScreen();
    _is_active = true;
}
References _is_active, createScreensaverScreen(), and saveBacklight().
Referenced by update().
begin()
void ScreensaverLib::begin (lv_display_t * display)
Initialization.
Initialize the screensaver.
Parameters
display
Returns
void
Definition at line 38 of file ScreensaverLib.cpp.
{
    _display = display;
    _last_activity_ms = millis();
}
References _display, and _last_activity_ms.
createScreensaverScreen()
void ScreensaverLib::createScreensaverScreen () private
Private: Create the screensaver screen.
Returns
void
Definition at line 188 of file ScreensaverLib.cpp.
{
    // TODO: Implement screen creation
}
Referenced by activate().
deactivate()
void ScreensaverLib::deactivate ()
Deactivate screensaver.
Returns
void
Definition at line 159 of file ScreensaverLib.cpp.
{
    if (!_is_active) return;
    destroyScreensaverScreen();
    restoreBacklight();
    _is_active = false;
    reset();  // Reset timer
}
References _is_active, destroyScreensaverScreen(), reset(), and restoreBacklight().
destroyScreensaverScreen()
void ScreensaverLib::destroyScreensaverScreen () private
Private: Destroy the screensaver screen.
Returns
void
Definition at line 196 of file ScreensaverLib.cpp.
{
    // TODO: Implement screen destruction
}
Referenced by deactivate().
getSettings()
ScreensaverSettings ScreensaverLib::getSettings ()
Get current settings.
Returns
ScreensaverSettings
Definition at line 119 of file ScreensaverLib.cpp.
{
    return _settings;
}
References _settings.
isActive()
bool ScreensaverLib::isActive ()
Check if screensaver is active.
Returns
true
false
Definition at line 111 of file ScreensaverLib.cpp.
{
    return _is_active;
}
References _is_active.
reset()
void ScreensaverLib::reset ()
Reset inactivity timer.
Returns
void
Definition at line 47 of file ScreensaverLib.cpp.
{
    _last_activity_ms = millis();
}
References _last_activity_ms.
Referenced by deactivate().
restoreBacklight()
void ScreensaverLib::restoreBacklight () private
Private: Restore backlight to saved value.
Returns
void
Definition at line 180 of file ScreensaverLib.cpp.
{
    // TODO: Implement backlight restore
}
Referenced by deactivate().
saveBacklight()
void ScreensaverLib::saveBacklight () private
Private: Save current backlight value.
Returns
void
Definition at line 172 of file ScreensaverLib.cpp.
{
    // TODO: Implement backlight save
}
Referenced by activate().
setAnimationSpeed()
void ScreensaverLib::setAnimationSpeed (uint8_t speed)
Set animation speed in seconds.
Parameters
speed
Returns
void
Definition at line 91 of file ScreensaverLib.cpp.
{
    if (speed >= 1 && speed <= 10) {
        _settings.animation_speed = speed;
    }
}
References _settings.
setBounceMode()
void ScreensaverLib::setBounceMode (bool bounce)
Set bounce mode.
Parameters
bounce
Returns
void
Definition at line 102 of file ScreensaverLib.cpp.
{
    _settings.bounce_mode = bounce;
}
References _settings.
setEnabled()
void ScreensaverLib::setEnabled (bool enabled)
Set explicit state.
Parameters
enabled
Returns
void
Definition at line 56 of file ScreensaverLib.cpp.
{
    _settings.enabled = enabled;
}
References _settings.
setMode()
void ScreensaverLib::setMode (ScreensaverMode mode)
Set screensaver mode.
Parameters
mode
Returns
void
Definition at line 82 of file ScreensaverLib.cpp.
{
    _settings.mode = mode;
}
References _settings.
setTimeout()
void ScreensaverLib::setTimeout (uint8_t seconds)
Set timeout in seconds.
Parameters
seconds
Returns
void
Definition at line 73 of file ScreensaverLib.cpp.
{
    _settings.timeout_seconds = seconds;
}
References _settings.
toggleEnabled()
void ScreensaverLib::toggleEnabled ()
Toggle current state.
Returns
void
Definition at line 64 of file ScreensaverLib.cpp.
{
    _settings.enabled = !_settings.enabled;
}
References _settings.
update()
void ScreensaverLib::update ()
Update screensaver state, call regularly in loop.
Returns
void
Definition at line 127 of file ScreensaverLib.cpp.
{
    if (!_settings.enabled) return;
    if (_settings.timeout_seconds == 0) return;  // Disabled via timeout
    uint32_t elapsed = millis() - _last_activity_ms;
    uint32_t timeout_ms = _settings.timeout_seconds * 1000;
    if (!_is_active && elapsed >= timeout_ms) {
        activate();
    }
    if (_is_active) {
        updateAnimation();
    }
}
References _is_active, _last_activity_ms, _settings, activate(), and updateAnimation().
updateAnimation()
void ScreensaverLib::updateAnimation () private
Private: Update screensaver animation.
Returns
void
Definition at line 204 of file ScreensaverLib.cpp.
{
    // TODO: Implement animation
}
Referenced by update().
Field Documentation
_display
lv_display_t* ScreensaverLib::_display private
Definition at line 90 of file ScreensaverLib.h.
Referenced by begin(), and ScreensaverLib().
_is_active
bool ScreensaverLib::_is_active private
Definition at line 93 of file ScreensaverLib.h.
Referenced by activate(), deactivate(), isActive(), ScreensaverLib(), and update().
_last_activity_ms
uint32_t ScreensaverLib::_last_activity_ms private
Definition at line 92 of file ScreensaverLib.h.
Referenced by begin(), reset(), ScreensaverLib(), and update().
_screensaver_screen
lv_obj_t* ScreensaverLib::_screensaver_screen private
Definition at line 94 of file ScreensaverLib.h.
Referenced by ScreensaverLib().
_settings
ScreensaverSettings ScreensaverLib::_settings private
Definition at line 91 of file ScreensaverLib.h.
Referenced by getSettings(), ScreensaverLib(), setAnimationSpeed(), setBounceMode(), setEnabled(), setMode(), setTimeout(), toggleEnabled(), and update().
The documentation for this class was generated from the following files:
lib/ScreensaverLib/ScreensaverLib.h
lib/ScreensaverLib/ScreensaverLib.cpp