EARS-PIO-WSS3-LVGL-001: src/ui/eez-flow.cpp File Reference
eez-flow.cpp File Reference
#include "eez-flow.h"
#include <stdio.h>
#include <math.h>
#include <assert.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <inttypes.h>
#include <chrono>
#include <string>
Data Structures
struct eez::flow::AnimateComponenentExecutionState
struct eez::flow::CompareActionComponent
struct eez::flow::ConstantActionComponent
struct eez::flow::CounterComponenentExecutionState
struct eez::flow::DelayComponenentExecutionState
struct eez::flow::LabelOutActionComponent
struct eez::flow::LoopComponenentExecutionState
struct eez::flow::LVGLExecutionState
struct eez::flow::LVGLApiExecutionState
struct eez::flow::LVGLUserWidgetComponent
struct eez::flow::MQTTEventActionComponenent
struct eez::flow::MQTTEvent
struct eez::flow::MQTTEventActionComponenentExecutionState
struct eez::flow::MQTTConnectionEventHandler
struct eez::flow::MQTTConnection
struct eez::flow::OutputActionComponent
struct eez::flow::ShowPageActionComponent
struct eez::flow::WatchVariableComponenentExecutionState
struct eez::flow::date::TimeChangeRule
struct eez::flow::WatchListNode
struct eez::flow::WatchList
Namespaces
namespace eez
namespace eez::flow
namespace eez::flow::date
Macros
#define SCPI_ERROR_OUT_OF_DEVICE_MEMORY -321
#define SCPI_ERROR_INVALID_BLOCK_DATA -161
#define _USE_MATH_DEFINES
#define VALUE_TYPE(NAME)
#define VALUE_TYPE(NAME)
#define VALUE_TYPE(NAME)
#define VALUE_TYPE(NAME)
#define VALUE_TYPE(NAME)
#define VALUE_TYPE(NAME)
#define ACTION_START(NAME)
#define INT8_PROP(NAME)
#define UINT8_PROP(NAME)
#define INT16_PROP(NAME)
#define UINT16_PROP(NAME)
#define INT32_PROP(NAME)
#define UINT32_PROP(NAME)
#define BOOL_PROP(NAME)
#define STR_PROP(NAME)
#define SCREEN_PROP(NAME)
#define WIDGET_PROP(NAME)
#define GROUP_PROP(NAME)
#define STYLE_PROP(NAME)
#define RESULT(NAME, VALUE)
#define ACTION_END }
#define ANIM_PROPS
#define SECONDS_PER_MINUTE 60UL
#define SECONDS_PER_HOUR (SECONDS_PER_MINUTE * 60)
#define SECONDS_PER_DAY (SECONDS_PER_HOUR * 24)
#define LEAP_YEAR(Y)
#define MAX_ARRAY_SIZE_TRANSFERRED_IN_DEBUGGER 1000
#define WRITE_TO_OUTPUT_BUFFER(ch)
#define FLUSH_OUTPUT_BUFFER()
#define VALUE_TYPE (instructions[i] + (instructions[i + 1] << 8) + (instructions[i + 2] << 16) + (instructions[i + 3] << 24))
#define EEZ_FLOW_TICK_MAX_DURATION_MS 5
#define EEZ_LVGL_SCREEN_STACK_SIZE 10
#define EEZ_LVGL_TEMP_STRING_BUFFER_SIZE 1024
#define GET_MESSAGE(FMT, ...)
Typedefs
typedef void(* eez::flow::ExecuteComponentFunctionType) (FlowState *flowState, unsigned componentIndex)
typedef void(* eez::flow::ActionType) (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
Enumerations
enum eez::flow::PropertyCode {
eez::flow::NONE , eez::flow::ARC_VALUE , eez::flow::BAR_VALUE , eez::flow::BASIC_X ,
eez::flow::BASIC_Y , eez::flow::BASIC_WIDTH , eez::flow::BASIC_HEIGHT , eez::flow::BASIC_OPACITY ,
eez::flow::BASIC_HIDDEN , eez::flow::BASIC_CHECKED , eez::flow::BASIC_DISABLED , eez::flow::DROPDOWN_SELECTED ,
eez::flow::IMAGE_IMAGE , eez::flow::IMAGE_ANGLE , eez::flow::IMAGE_ZOOM , eez::flow::LABEL_TEXT ,
eez::flow::ROLLER_SELECTED , eez::flow::SLIDER_VALUE , eez::flow::KEYBOARD_TEXTAREA
}
enum eez::flow::GroupActions {
eez::flow::GROUP_ACTION_SET_WRAP = 0 , eez::flow::GROUP_ACTION_FOCUS_OBJ = 1 , eez::flow::GROUP_ACTION_FOCUS_NEXT = 2 , eez::flow::GROUP_ACTION_FOCUS_PREVIOUS = 3 ,
eez::flow::GROUP_ACTION_FOCUS_FREEZE = 4 , eez::flow::GROUP_ACTION_SET_EDITING = 5
}
enum eez::flow::date::Week {
eez::flow::date::Last , eez::flow::date::First , eez::flow::date::Second , eez::flow::date::Third ,
eez::flow::date::Fourth
}
enum eez::flow::date::DayOfWeek {
eez::flow::date::Sun = 1 , eez::flow::date::Mon , eez::flow::date::Tue , eez::flow::date::Wed ,
eez::flow::date::Thu , eez::flow::date::Fri , eez::flow::date::Sat
}
enum eez::flow::date::Month {
eez::flow::date::Jan = 1 , eez::flow::date::Feb , eez::flow::date::Mar , eez::flow::date::Apr ,
eez::flow::date::May , eez::flow::date::Jun , eez::flow::date::Jul , eez::flow::date::Aug ,
eez::flow::date::Sep , eez::flow::date::Oct , eez::flow::date::Nov , eez::flow::date::Dec
}
enum eez::flow::MessagesToDebugger {
eez::flow::MESSAGE_TO_DEBUGGER_STATE_CHANGED , eez::flow::MESSAGE_TO_DEBUGGER_ADD_TO_QUEUE , eez::flow::MESSAGE_TO_DEBUGGER_REMOVE_FROM_QUEUE , eez::flow::MESSAGE_TO_DEBUGGER_GLOBAL_VARIABLE_INIT ,
eez::flow::MESSAGE_TO_DEBUGGER_LOCAL_VARIABLE_INIT , eez::flow::MESSAGE_TO_DEBUGGER_COMPONENT_INPUT_INIT , eez::flow::MESSAGE_TO_DEBUGGER_VALUE_CHANGED , eez::flow::MESSAGE_TO_DEBUGGER_FLOW_STATE_CREATED ,
eez::flow::MESSAGE_TO_DEBUGGER_FLOW_STATE_TIMELINE_CHANGED , eez::flow::MESSAGE_TO_DEBUGGER_FLOW_STATE_DESTROYED , eez::flow::MESSAGE_TO_DEBUGGER_FLOW_STATE_ERROR , eez::flow::MESSAGE_TO_DEBUGGER_LOG ,
eez::flow::MESSAGE_TO_DEBUGGER_PAGE_CHANGED , eez::flow::MESSAGE_TO_DEBUGGER_COMPONENT_EXECUTION_STATE_CHANGED , eez::flow::MESSAGE_TO_DEBUGGER_COMPONENT_ASYNC_STATE_CHANGED
}
enum eez::flow::MessagesFromDebugger {
eez::flow::MESSAGE_FROM_DEBUGGER_RESUME , eez::flow::MESSAGE_FROM_DEBUGGER_PAUSE , eez::flow::MESSAGE_FROM_DEBUGGER_SINGLE_STEP , eez::flow::MESSAGE_FROM_DEBUGGER_ADD_BREAKPOINT ,
eez::flow::MESSAGE_FROM_DEBUGGER_REMOVE_BREAKPOINT , eez::flow::MESSAGE_FROM_DEBUGGER_ENABLE_BREAKPOINT , eez::flow::MESSAGE_FROM_DEBUGGER_DISABLE_BREAKPOINT , eez::flow::MESSAGE_FROM_DEBUGGER_MODE
}
enum eez::flow::LogItemType {
eez::flow::LOG_ITEM_TYPE_FATAL , eez::flow::LOG_ITEM_TYPE_ERROR , eez::flow::LOG_ITEM_TYPE_WARNING , eez::flow::LOG_ITEM_TYPE_SCPI ,
eez::flow::LOG_ITEM_TYPE_INFO , eez::flow::LOG_ITEM_TYPE_DEBUG
}
enum eez::flow::DebuggerState { eez::flow::DEBUGGER_STATE_RESUMED , eez::flow::DEBUGGER_STATE_PAUSED , eez::flow::DEBUGGER_STATE_SINGLE_STEP , eez::flow::DEBUGGER_STATE_STOPPED }
enum eez::flow::FormatType {
eez::flow::type_int , eez::flow::type_signed_char , eez::flow::type_short_int , eez::flow::type_long_int ,
eez::flow::type_long_long_int , eez::flow::type_intmax_t , eez::flow::type_size_t , eez::flow::type_unsigned_int ,
eez::flow::type_unsigned_char , eez::flow::type_unsigned_short_int , eez::flow::type_unsigned_long_int , eez::flow::type_unsigned_long_long_int ,
eez::flow::type_uintmax_t , eez::flow::type_double , eez::flow::type_string
}
enum eez::flow::FormatLength {
eez::flow::length_none , eez::flow::length_hh , eez::flow::length_h , eez::flow::length_l ,
eez::flow::length_ll , eez::flow::length_j , eez::flow::length_z , eez::flow::length_t ,
eez::flow::length_L
}
Functions
void eez::executeActionFunction (int actionId)
void eez::initAllocHeap (uint8_t *heap, size_t heapSize)
void * eez::alloc (size_t size, uint32_t id)
void eez::free (void *ptr)
template<typename T>
void eez::freeObject (T *ptr)
void eez::getAllocInfo (uint32_t &free, uint32_t &alloc)
void eez::fixOffsets (Assets *assets)
bool eez::decompressAssetsData (const uint8_t *assetsData, uint32_t assetsDataSize, Assets *decompressedAssets, uint32_t maxDecompressedAssetsSize, int *err)
static void eez::allocMemoryForDecompressedAssets (const uint8_t *assetsData, uint32_t assetsDataSize, uint8_t *&decompressedAssetsMemoryBuffer, uint32_t &decompressedAssetsMemoryBufferSize)
void eez::loadMainAssets (const uint8_t *assets, uint32_t assetsSize)
void eez::unloadExternalAssets ()
int eez::getThemesCount ()
static Theme * eez::getTheme (int i)
const char * eez::getThemeName (int i)
uint32_t eez::getThemeColorsCount (int themeIndex)
const uint16_t * eez::getThemeColors (int themeIndex)
const uint16_t * eez::getColors ()
int eez::getExternalAssetsMainPageId ()
void eez::initMemory ()
void eez::initAssetsMemory ()
void eez::initOtherMemory ()
uint8_t * eez::allocBuffer (uint32_t size)
uint32_t eez::millis ()
Unit eez::getUnitFromName (const char *unitName)
Unit eez::getBaseUnit (Unit unit)
float eez::getUnitFactor (Unit unit)
static Unit eez::getDerivedUnit (Unit unit, float factor)
Unit eez::findDerivedUnit (float value, Unit unit)
static float eez::getSmallerFactor (float factor)
Unit eez::getSmallerUnit (Unit unit, float min, float precision)
Unit eez::getBiggestUnit (Unit unit, float max)
Unit eez::getSmallestUnit (Unit unit, float min, float precision)
float eez::remap (float x, float x1, float y1, float x2, float y2)
float eez::remapQuad (float x, float x1, float y1, float x2, float y2)
float eez::remapOutQuad (float x, float x1, float y1, float x2, float y2)
float eez::remapInOutQuad (float x, float x1, float y1, float x2, float y2)
float eez::remapCubic (float x, float x1, float y1, float x2, float y2)
float eez::remapOutCubic (float x, float x1, float y1, float x2, float y2)
float eez::remapExp (float x, float x1, float y1, float x2, float y2)
float eez::remapOutExp (float x, float x1, float y1, float x2, float y2)
float eez::clamp (float x, float min, float max)
void eez::stringCopy (char *dst, size_t maxStrLength, const char *src)
void eez::stringCopyLength (char *dst, size_t maxStrLength, const char *src, size_t length)
void eez::stringAppendString (char *str, size_t maxStrLength, const char *value)
void eez::stringAppendStringLength (char *str, size_t maxStrLength, const char *value, size_t length)
void eez::stringAppendInt (char *str, size_t maxStrLength, int value)
void eez::stringAppendUInt32 (char *str, size_t maxStrLength, uint32_t value)
void eez::stringAppendInt64 (char *str, size_t maxStrLength, int64_t value)
void eez::stringAppendUInt64 (char *str, size_t maxStrLength, uint64_t value)
void eez::stringAppendFloat (char *str, size_t maxStrLength, float value)
void eez::stringAppendFloat (char *str, size_t maxStrLength, float value, int numDecimalPlaces)
void eez::stringAppendDouble (char *str, size_t maxStrLength, double value)
void eez::stringAppendDouble (char *str, size_t maxStrLength, double value, int numDecimalPlaces)
void eez::stringAppendVoltage (char *str, size_t maxStrLength, float value)
void eez::stringAppendCurrent (char *str, size_t maxStrLength, float value)
void eez::stringAppendPower (char *str, size_t maxStrLength, float value)
void eez::stringAppendDuration (char *str, size_t maxStrLength, float value)
void eez::stringAppendLoad (char *str, size_t maxStrLength, float value)
uint32_t eez::crc32 (const uint8_t *mem_block, size_t block_size)
uint8_t eez::toBCD (uint8_t bin)
uint8_t eez::fromBCD (uint8_t bcd)
float eez::roundPrec (float a, float prec)
float eez::floorPrec (float a, float prec)
float eez::ceilPrec (float a, float prec)
bool eez::isNaN (float x)
bool eez::isNaN (double x)
bool eez::isDigit (char ch)
bool eez::isHexDigit (char ch)
bool eez::isUperCaseLetter (char ch)
char eez::toHexDigit (int num)
int eez::fromHexDigit (char ch)
bool eez::pointInsideRect (int xPoint, int yPoint, int xRect, int yRect, int wRect, int hRect)
void eez::getParentDir (const char *path, char *parentDirPath)
bool eez::parseMacAddress (const char *macAddressStr, size_t macAddressStrLength, uint8_t *macAddress)
bool eez::parseIpAddress (const char *ipAddressStr, size_t ipAddressStrLength, uint32_t &ipAddress)
int eez::getIpAddressPartA (uint32_t ipAddress)
void eez::setIpAddressPartA (uint32_t *ipAddress, uint8_t value)
int eez::getIpAddressPartB (uint32_t ipAddress)
void eez::setIpAddressPartB (uint32_t *ipAddress, uint8_t value)
int eez::getIpAddressPartC (uint32_t ipAddress)
void eez::setIpAddressPartC (uint32_t *ipAddress, uint8_t value)
int eez::getIpAddressPartD (uint32_t ipAddress)
void eez::setIpAddressPartD (uint32_t *ipAddress, uint8_t value)
void eez::ipAddressToArray (uint32_t ipAddress, uint8_t *ipAddressArray)
uint32_t eez::arrayToIpAddress (uint8_t *ipAddressArray)
uint32_t eez::getIpAddress (uint8_t a, uint8_t b, uint8_t c, uint8_t d)
void eez::ipAddressToString (uint32_t ipAddress, char *ipAddressStr, size_t maxIpAddressStrLength)
void eez::macAddressToString (const uint8_t *macAddress, char *macAddressStr)
void eez::formatTimeZone (int16_t timeZone, char *text, int count)
bool eez::parseTimeZone (const char *timeZoneStr, size_t timeZoneLength, int16_t &timeZone)
void eez::replaceCharacter (char *str, char ch, char repl)
int eez::strcicmp (char const *a, char const *b)
int eez::strncicmp (char const *a, char const *b, int n)
bool eez::isStringEmpty (char const *s)
bool eez::startsWith (const char *str, const char *prefix)
bool eez::startsWithNoCase (const char *str, const char *prefix)
bool eez::endsWith (const char *str, const char *suffix)
bool eez::endsWithNoCase (const char *str, const char *suffix)
void eez::formatBytes (uint64_t bytes, char *text, int count)
void eez::getFileName (const char *path, char *fileName, unsigned fileNameSize)
void eez::getBaseFileName (const char *path, char *baseName, unsigned baseNameSize)
float eez_linear (float x)
float eez_easeInQuad (float x)
float eez_easeOutQuad (float x)
float eez_easeInOutQuad (float x)
float eez_easeInCubic (float x)
float eez_easeOutCubic (float x)
float eez_easeInOutCubic (float x)
float eez_easeInQuart (float x)
float eez_easeOutQuart (float x)
float eez_easeInOutQuart (float x)
float eez_easeInQuint (float x)
float eez_easeOutQuint (float x)
float eez_easeInOutQuint (float x)
float eez_easeInSine (float x)
float eez_easeOutSine (float x)
float eez_easeInOutSine (float x)
float eez_easeInExpo (float x)
float eez_easeOutExpo (float x)
float eez_easeInOutExpo (float x)
float eez_easeInCirc (float x)
float eez_easeOutCirc (float x)
float eez_easeInOutCirc (float x)
float eez_easeInBack (float x)
float eez_easeOutBack (float x)
float eez_easeInOutBack (float x)
float eez_easeInElastic (float x)
float eez_easeOutElastic (float x)
float eez_easeInOutElastic (float x)
float eez_easeOutBounce (float x)
float eez_easeInBounce (float x)
float eez_easeInOutBounce (float x)
static bool eez::compare_UNDEFINED_value (const Value &a, const Value &b)
static void eez::UNDEFINED_value_to_text (const Value &value, char *text, int count)
static const char * eez::UNDEFINED_value_type_name (const Value &value)
static bool eez::compare_NULL_value (const Value &a, const Value &b)
static void eez::NULL_value_to_text (const Value &value, char *text, int count)
static const char * eez::NULL_value_type_name (const Value &value)
static bool eez::compare_BOOLEAN_value (const Value &a, const Value &b)
static void eez::BOOLEAN_value_to_text (const Value &value, char *text, int count)
static const char * eez::BOOLEAN_value_type_name (const Value &value)
static bool eez::compare_INT8_value (const Value &a, const Value &b)
static void eez::INT8_value_to_text (const Value &value, char *text, int count)
static const char * eez::INT8_value_type_name (const Value &value)
static bool eez::compare_UINT8_value (const Value &a, const Value &b)
static void eez::UINT8_value_to_text (const Value &value, char *text, int count)
static const char * eez::UINT8_value_type_name (const Value &value)
static bool eez::compare_INT16_value (const Value &a, const Value &b)
static void eez::INT16_value_to_text (const Value &value, char *text, int count)
static const char * eez::INT16_value_type_name (const Value &value)
static bool eez::compare_UINT16_value (const Value &a, const Value &b)
static void eez::UINT16_value_to_text (const Value &value, char *text, int count)
static const char * eez::UINT16_value_type_name (const Value &value)
static bool eez::compare_INT32_value (const Value &a, const Value &b)
static void eez::INT32_value_to_text (const Value &value, char *text, int count)
static const char * eez::INT32_value_type_name (const Value &value)
static bool eez::compare_UINT32_value (const Value &a, const Value &b)
static void eez::UINT32_value_to_text (const Value &value, char *text, int count)
static const char * eez::UINT32_value_type_name (const Value &value)
static bool eez::compare_INT64_value (const Value &a, const Value &b)
static void eez::INT64_value_to_text (const Value &value, char *text, int count)
static const char * eez::INT64_value_type_name (const Value &value)
static bool eez::compare_UINT64_value (const Value &a, const Value &b)
static void eez::UINT64_value_to_text (const Value &value, char *text, int count)
static const char * eez::UINT64_value_type_name (const Value &value)
static bool eez::compare_FLOAT_value (const Value &a, const Value &b)
static void eez::FLOAT_value_to_text (const Value &value, char *text, int count)
static const char * eez::FLOAT_value_type_name (const Value &value)
static bool eez::compare_DOUBLE_value (const Value &a, const Value &b)
static void eez::DOUBLE_value_to_text (const Value &value, char *text, int count)
static const char * eez::DOUBLE_value_type_name (const Value &value)
static bool eez::compare_STRING_value (const Value &a, const Value &b)
static void eez::STRING_value_to_text (const Value &value, char *text, int count)
static const char * eez::STRING_value_type_name (const Value &value)
static bool eez::compare_STRING_ASSET_value (const Value &a, const Value &b)
static void eez::STRING_ASSET_value_to_text (const Value &value, char *text, int count)
static const char * eez::STRING_ASSET_value_type_name (const Value &value)
static bool eez::compare_ARRAY_value (const Value &a, const Value &b)
static void eez::ARRAY_value_to_text (const Value &value, char *text, int count)
static const char * eez::ARRAY_value_type_name (const Value &value)
static bool eez::compare_ARRAY_ASSET_value (const Value &a, const Value &b)
static void eez::ARRAY_ASSET_value_to_text (const Value &value, char *text, int count)
static const char * eez::ARRAY_ASSET_value_type_name (const Value &value)
static bool eez::compare_ARRAY_REF_value (const Value &a, const Value &b)
static void eez::ARRAY_REF_value_to_text (const Value &value, char *text, int count)
static const char * eez::ARRAY_REF_value_type_name (const Value &value)
static bool eez::compare_STRING_REF_value (const Value &a, const Value &b)
static void eez::STRING_REF_value_to_text (const Value &value, char *text, int count)
static const char * eez::STRING_REF_value_type_name (const Value &value)
static bool eez::compare_BLOB_REF_value (const Value &a, const Value &b)
static void eez::BLOB_REF_value_to_text (const Value &value, char *text, int count)
static const char * eez::BLOB_REF_value_type_name (const Value &value)
static bool eez::compare_STREAM_value (const Value &a, const Value &b)
static void eez::STREAM_value_to_text (const Value &value, char *text, int count)
static const char * eez::STREAM_value_type_name (const Value &value)
static bool eez::compare_WIDGET_value (const Value &a, const Value &b)
static void eez::WIDGET_value_to_text (const Value &value, char *text, int count)
static const char * eez::WIDGET_value_type_name (const Value &value)
static bool eez::compare_JSON_value (const Value &a, const Value &b)
static void eez::JSON_value_to_text (const Value &value, char *text, int count)
static const char * eez::JSON_value_type_name (const Value &value)
static bool eez::compare_JSON_MEMBER_VALUE_value (const Value &a, const Value &b)
static void eez::JSON_MEMBER_VALUE_value_to_text (const Value &value, char *text, int count)
static const char * eez::JSON_MEMBER_VALUE_value_type_name (const Value &value)
static bool eez::compare_EVENT_value (const Value &a, const Value &b)
static void eez::EVENT_value_to_text (const Value &value, char *text, int count)
static const char * eez::EVENT_value_type_name (const Value &value)
static const char * eez::PROPERTY_REF_value_type_name (const Value &value)
static bool eez::compare_PROPERTY_REF_value (const Value &a, const Value &b)
static void eez::PROPERTY_REF_value_to_text (const Value &value, char *text, int count)
static bool eez::compare_DATE_value (const Value &a, const Value &b)
static void eez::DATE_value_to_text (const Value &value, char *text, int count)
static const char * eez::DATE_value_type_name (const Value &value)
static bool eez::compare_VERSIONED_STRING_value (const Value &a, const Value &b)
static void eez::VERSIONED_STRING_value_to_text (const Value &value, char *text, int count)
static const char * eez::VERSIONED_STRING_value_type_name (const Value &value)
static bool eez::compare_VALUE_PTR_value (const Value &a, const Value &b)
static void eez::VALUE_PTR_value_to_text (const Value &value, char *text, int count)
static const char * eez::VALUE_PTR_value_type_name (const Value &value)
static bool eez::compare_ARRAY_ELEMENT_VALUE_value (const Value &a, const Value &b)
static void eez::ARRAY_ELEMENT_VALUE_value_to_text (const Value &value, char *text, int count)
static const char * eez::ARRAY_ELEMENT_VALUE_value_type_name (const Value &value)
static bool eez::compare_FLOW_OUTPUT_value (const Value &a, const Value &b)
static void eez::FLOW_OUTPUT_value_to_text (const Value &value, char *text, int count)
static const char * eez::FLOW_OUTPUT_value_type_name (const Value &value)
static bool eez::compare_NATIVE_VARIABLE_value (const Value &a, const Value &b)
static void eez::NATIVE_VARIABLE_value_to_text (const Value &value, char *text, int count)
static const char * eez::NATIVE_VARIABLE_value_type_name (const Value &value)
static bool eez::compare_ERROR_value (const Value &a, const Value &b)
static void eez::ERROR_value_to_text (const Value &value, char *text, int count)
static const char * eez::ERROR_value_type_name (const Value &value)
static bool eez::compare_RANGE_value (const Value &a, const Value &b)
static void eez::RANGE_value_to_text (const Value &value, char *text, int count)
static const char * eez::RANGE_value_type_name (const Value &value)
static bool eez::compare_POINTER_value (const Value &a, const Value &b)
static void eez::POINTER_value_to_text (const Value &value, char *text, int count)
static const char * eez::POINTER_value_type_name (const Value &value)
static bool eez::compare_ENUM_value (const Value &a, const Value &b)
static void eez::ENUM_value_to_text (const Value &value, char *text, int count)
static const char * eez::ENUM_value_type_name (const Value &value)
static bool eez::compare_YT_DATA_GET_VALUE_FUNCTION_POINTER_value (const Value &a, const Value &b)
static bool eez::compare_IP_ADDRESS_value (const Value &a, const Value &b)
static void eez::IP_ADDRESS_value_to_text (const Value &value, char *text, int count)
static const char * eez::IP_ADDRESS_value_type_name (const Value &value)
static bool eez::compare_TIME_ZONE_value (const Value &a, const Value &b)
static void eez::TIME_ZONE_value_to_text (const Value &value, char *text, int count)
static const char * eez::TIME_ZONE_value_type_name (const Value &value)
static void eez::YT_DATA_GET_VALUE_FUNCTION_POINTER_value_to_text (const Value &value, char *text, int count)
static const char * eez::YT_DATA_GET_VALUE_FUNCTION_POINTER_value_type_name (const Value &value)
bool eez::assignValue (Value &dstValue, const Value &srcValue, uint32_t dstValueType)
uint16_t eez::getPageIndexFromValue (const Value &value)
uint16_t eez::getNumPagesFromValue (const Value &value)
Value eez::MakeRangeValue (uint16_t from, uint16_t to)
Value eez::MakeEnumDefinitionValue (uint8_t enumValue, uint8_t enumDefinition)
Value eez::getVar (int16_t id)
void eez::setVar (int16_t id, const Value &value)
void eez::flow::executeStartComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeEndComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeInputComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeOutputComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeWatchVariableComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeEvalExprComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeSetVariableComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeSwitchComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeCompareComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeIsTrueComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeConstantComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeLogComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeCallActionComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeDelayComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeErrorComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeCatchErrorComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeCounterComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeLoopComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeShowPageComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeSelectLanguageComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeAnimateComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeSetColorThemeComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeNoopComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeOnEventComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeLVGLComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeLVGLUserWidgetComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeSortArrayComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeTestAndSetComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeMQTTInitComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeMQTTConnectComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeMQTTDisconnectComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeMQTTEventComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeMQTTSubscribeComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeMQTTUnsubscribeComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeMQTTPublishComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeLabelInComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeLabelOutComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeLVGLApiComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::registerComponent (ComponentTypes componentType, ExecuteComponentFunctionType executeComponentFunction)
void eez::flow::executeComponent (FlowState *flowState, unsigned componentIndex)
void eez::flow::executeCallAction (FlowState *flowState, unsigned componentIndex, int flowIndex, const Value &inputValue)
bool eez::flow::getCallActionValue (FlowState *flowState, unsigned componentIndex, Value &value)
static void eez::flow::anim_callback_set_x (void *obj, int32_t v)
static int32_t eez::flow::anim_callback_get_x (lv_anim_t *a)
static void eez::flow::anim_callback_set_y (void *obj, int32_t v)
static int32_t eez::flow::anim_callback_get_y (lv_anim_t *a)
static void eez::flow::anim_callback_set_width (void *obj, int32_t v)
static int32_t eez::flow::anim_callback_get_width (lv_anim_t *a)
static void eez::flow::anim_callback_set_height (void *obj, int32_t v)
static int32_t eez::flow::anim_callback_get_height (lv_anim_t *a)
static void eez::flow::anim_callback_set_opacity (void *obj, int32_t v)
static int32_t eez::flow::anim_callback_get_opacity (lv_anim_t *a)
static void eez::flow::anim_callback_set_image_zoom (void *obj, int32_t v)
static int32_t eez::flow::anim_callback_get_image_zoom (lv_anim_t *a)
static void eez::flow::anim_callback_set_image_angle (void *obj, int32_t v)
static int32_t eez::flow::anim_callback_get_image_angle (lv_anim_t *a)
static void eez::flow::changeScreen (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::changeToPreviousScreen (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objSetX (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objGetX (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objSetY (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objGetY (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objSetWidth (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objGetWidth (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objSetHeight (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objGetHeight (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objSetStyleOpa (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objGetStyleOpa (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objAddStyle (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objRemoveStyle (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objSetFlagHidden (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objAddFlag (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objClearFlag (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objHasFlag (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objSetStateChecked (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objSetStateDisabled (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objAddState (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objClearState (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::objHasState (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::arcSetValue (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::barSetValue (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::dropdownSetSelected (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::imageSetSrc (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::imageSetAngle (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::imageSetZoom (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::labelSetText (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::qrCodeUpdate (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::rollerSetSelected (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::sliderSetValue (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::sliderSetValueLeft (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::sliderSetRange (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::keyboardSetTextarea (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::groupFocusObj (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::groupFocusNext (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::groupFocusPrev (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::groupGetFocused (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::groupFocusFreeze (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::groupSetWrap (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::groupSetEditing (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::playAnimation (lv_obj_t *obj, int32_t start, int32_t end, int32_t delay, int32_t time, bool relative, bool instant, int32_t path, lv_anim_exec_xcb_t set_callback, lv_anim_get_value_cb_t get_callback)
static void eez::flow::animX (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::animY (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::animWidth (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::animHeight (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::animOpacity (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::animImageZoom (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::animImageAngle (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::createScreen (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::deleteScreen (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::isScreenCreated (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::calendarSetTodayDate (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::calendarSetShowedDate (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::calendarSetHighlightedDate (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::calendarGetPressedDate (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::buttonMatrixSetButtonCtrl (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void eez::flow::buttonMatrixClearButtonCtrl (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
LVGLUserWidgetExecutionState * eez::flow::createUserWidgetFlowState (FlowState *flowState, unsigned userWidgetWidgetComponentIndex)
static MQTTConnection * eez::flow::addConnection (void *handle)
static MQTTConnection * eez::flow::findConnection (void *handle)
static void eez::flow::deleteConnection (void *handle)
static MQTTConnectionEventHandler * eez::flow::addConnectionEventHandler (void *handle, MQTTEventActionComponenentExecutionState *componentExecutionState)
static void eez::flow::removeEventHandler (MQTTEventActionComponenentExecutionState *componentExecutionState)
void eez::flow::onFreeMQTTConnection (ArrayValue *mqttConnectionValue)
int eez_mqtt_init (const char *protocol, const char *host, int port, const char *username, const char *password, void **handle)
int eez_mqtt_deinit (void *handle)
int eez_mqtt_connect (void *handle)
int eez_mqtt_disconnect (void *handle)
int eez_mqtt_subscribe (void *handle, const char *topic)
int eez_mqtt_unsubscribe (void *handle, const char *topic)
int eez_mqtt_publish (void *handle, const char *topic, const char *payload)
static int eez::flow::elementCompare (const void *a, const void *b)
void eez::flow::sortArray (SortArrayActionComponent *component, ArrayValue *array)
static void eez::flow::date::convertTime24to12 (int &hours, bool &am)
static bool eez::flow::date::isDst (Date time, DstRule dstRule)
static uint8_t eez::flow::date::dayOfWeek (int y, int m, int d)
static Date eez::flow::date::timeChangeRuleToLocal (TimeChangeRule &r, int year)
Date eez::flow::date::now ()
void eez::flow::date::toString (Date time, char *str, uint32_t strLen)
void eez::flow::date::toLocaleString (Date time, char *str, uint32_t strLen)
Date eez::flow::date::fromString (const char *str)
Date eez::flow::date::makeDate (int year, int month, int day, int hours, int minutes, int seconds, int milliseconds)
void eez::flow::date::breakDate (Date time, int &result_year, int &result_month, int &result_day, int &result_hours, int &result_minutes, int &result_seconds, int &result_milliseconds)
int eez::flow::date::getYear (Date time)
int eez::flow::date::getMonth (Date time)
int eez::flow::date::getDay (Date time)
int eez::flow::date::getHours (Date time)
int eez::flow::date::getMinutes (Date time)
int eez::flow::date::getSeconds (Date time)
int eez::flow::date::getMilliseconds (Date time)
Date eez::flow::date::utcToLocal (Date utc)
Date eez::flow::date::localToUtc (Date local)
void eez::flow::setDebuggerMessageSubsciptionFilter (uint32_t filter)
static bool eez::flow::isSubscribedTo (MessagesToDebugger messageType)
static void eez::flow::setDebuggerState (DebuggerState newState)
void eez::flow::onDebuggerClientConnected ()
void eez::flow::onDebuggerClientDisconnected ()
void eez::flow::processDebuggerInput (char *buffer, uint32_t length)
bool eez::flow::canExecuteStep (FlowState *&flowState, unsigned &componentIndex)
static void eez::flow::writeValueAddr (const void *pValue)
static void eez::flow::writeString (const char *str)
static void eez::flow::writeArrayType (uint32_t arrayType)
static void eez::flow::writeArray (const ArrayValue *arrayValue)
static void eez::flow::writeHex (char *dst, uint8_t *src, size_t srcLength)
static void eez::flow::writeValue (const Value &value)
void eez::flow::onStarted (Assets *assets)
void eez::flow::onStopped ()
void eez::flow::onAddToQueue (FlowState *flowState, int sourceComponentIndex, int sourceOutputIndex, unsigned targetComponentIndex, int targetInputIndex)
void eez::flow::onRemoveFromQueue ()
void eez::flow::onValueChanged (const Value *pValue)
void eez::flow::onFlowStateCreated (FlowState *flowState)
void eez::flow::onFlowStateDestroyed (FlowState *flowState)
void eez::flow::onFlowStateTimelineChanged (FlowState *flowState)
void eez::flow::onFlowError (FlowState *flowState, int componentIndex, const char *errorMessage)
void eez::flow::onComponentExecutionStateChanged (FlowState *flowState, int componentIndex)
void eez::flow::onComponentAsyncStateChanged (FlowState *flowState, int componentIndex)
static void eez::flow::writeLogMessage (const char *str)
static void eez::flow::writeLogMessage (const char *str, size_t len)
void eez::flow::logInfo (FlowState *flowState, unsigned componentIndex, const char *message)
void eez::flow::logScpiCommand (FlowState *flowState, unsigned componentIndex, const char *cmd)
void eez::flow::logScpiQuery (FlowState *flowState, unsigned componentIndex, const char *query)
void eez::flow::logScpiQueryResult (FlowState *flowState, unsigned componentIndex, const char *resultText, size_t resultTextLen)
void eez::flow::onPageChanged (int previousPageId, int activePageId, bool activePageIsFromStack, bool previousPageIsStillOnStack)
static void eez::flow::evalExpression (FlowState *flowState, const uint8_t *instructions, int *numInstructionBytes)
bool eez::flow::evalExpression (FlowState *flowState, int componentIndex, const uint8_t *instructions, Value &result, const FlowError &errorMessage, int *numInstructionBytes, const int32_t *iterators)
bool eez::flow::evalAssignableExpression (FlowState *flowState, int componentIndex, const uint8_t *instructions, Value &result, const FlowError &errorMessage, int *numInstructionBytes, const int32_t *iterators)
bool eez::flow::evalProperty (FlowState *flowState, int componentIndex, int propertyIndex, Value &result, const FlowError &errorMessage, int *numInstructionBytes, const int32_t *iterators)
bool eez::flow::evalAssignableProperty (FlowState *flowState, int componentIndex, int propertyIndex, Value &result, const FlowError &errorMessage, int *numInstructionBytes, const int32_t *iterators)
static void eez::flow::doStop ()
unsigned eez::flow::start (Assets *assets)
void eez::flow::tick ()
void eez::flow::stop ()
bool eez::flow::isFlowStopped ()
unsigned eez::flow::getTickMaxDurationCounter ()
FlowState * eez::flow::getPageFlowState (Assets *assets, int16_t pageIndex)
int eez::flow::getPageIndex (FlowState *flowState)
void eez::flow::deletePageFlowState (Assets *assets, int16_t pageIndex)
Value eez::flow::getGlobalVariable (uint32_t globalVariableIndex)
Value eez::flow::getGlobalVariable (Assets *assets, uint32_t globalVariableIndex)
void eez::flow::setGlobalVariable (uint32_t globalVariableIndex, const Value &value)
void eez::flow::setGlobalVariable (Assets *assets, uint32_t globalVariableIndex, const Value &value)
Value eez::flow::getUserProperty (unsigned propertyIndex)
void eez::flow::setUserProperty (unsigned propertyIndex, const Value &value)
AsyncAction * eez::flow::beginAsyncExecution ()
void eez::flow::endAsyncExecution (AsyncAction *asyncAction)
Value eez::flow::getUserPropertyAsync (AsyncAction *asyncAction, unsigned propertyIndex)
void eez::flow::setUserPropertyAsync (AsyncAction *asyncAction, unsigned propertyIndex, const Value &value)
void eez::flow::onArrayValueFree (ArrayValue *arrayValue)
static void eez::flow::replacePage (int16_t pageId, uint32_t animType, uint32_t speed, uint32_t delay)
static void eez::flow::showKeyboard (Value label, Value initialText, Value minChars, Value maxChars, bool isPassword, void(*onOk)(char *), void(*onCancel)())
static void eez::flow::showKeypad (Value label, Value initialValue, Value min, Value max, Unit unit, void(*onOk)(float), void(*onCancel)())
static void eez::flow::stopScript ()
static void eez::flow::scpiComponentInit ()
static void eez::flow::startToDebuggerMessage ()
static void eez::flow::writeDebuggerBuffer (const char *buffer, uint32_t length)
static void eez::flow::finishToDebuggerMessage ()
static void eez::flow::onDebuggerInputAvailable ()
static lv_obj_t * eez::flow::getLvglObjectFromIndex (int32_t index)
static lv_group_t * eez::flow::getLvglGroupFromIndex (int32_t index)
static int32_t eez::flow::getLvglScreenByName (const char *name)
static int32_t eez::flow::getLvglObjectByName (const char *name)
static int32_t eez::flow::getLvglGroupByName (const char *name)
static int32_t eez::flow::getLvglStyleByName (const char *name)
static const void * eez::flow::getLvglImageByName (const char *name)
static void eez::flow::executeLvglAction (int actionIndex)
static void eez::flow::lvglObjAddStyle (lv_obj_t *object, int32_t styleIndex)
static void eez::flow::lvglObjRemoveStyle (lv_obj_t *object, int32_t styleIndex)
static void eez::flow::lvglSetColorTheme (const char *themeName)
static double eez::flow::getDateNowDefaultImplementation ()
static void replacePageHook (int16_t pageId, uint32_t animType, uint32_t speed, uint32_t delay)
void create_screens ()
void tick_screen (int screen_index)
static lv_obj_t * getLvglObjectFromIndex (int32_t index)
static lv_group_t * getLvglGroupFromIndex (int32_t index)
static int32_t getLvglScreenByName (const char *name)
static int32_t getLvglObjectByName (const char *name)
static int32_t getLvglGroupByName (const char *name)
static int32_t getLvglStyleByName (const char *name)
static const void * getLvglImageByName (const char *name)
static void executeLvglAction (int actionIndex)
void eez_flow_init_themes (const char **themeNames, size_t numThemes, void(*changeColorTheme)(uint32_t themeIndex))
void eez_flow_set_create_screen_func (void(*createScreenFunc)(int screenIndex))
void eez_flow_set_delete_screen_func (void(*deleteScreenFunc)(int screenIndex))
static void lvglSetColorTheme (const char *themeName)
int16_t eez_flow_get_current_screen ()
static bool isScreenCreated (int screenIndex)
static void createScreen (int screenIndex)
static void deleteScreen (int screenIndex)
void eez_flow_set_screen (int16_t screenId, lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
void eez_flow_push_screen (int16_t screenId, lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
void eez_flow_pop_screen (lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
void eez_flow_create_screen (int16_t screenId)
void eez_flow_delete_screen (int16_t screenId)
bool eez_flow_is_screen_created (int16_t screenId)
static void on_screen_unloaded (lv_event_t *e)
void eez_flow_delete_screen_on_unload (int screenIndex)
void eez_flow_init (const uint8_t *assets, uint32_t assetsSize, lv_obj_t **objects, size_t numObjects, const ext_img_desc_t *images, size_t numImages, ActionExecFunc *actions)
void eez_flow_init_styles (void(*add_style)(lv_obj_t *obj, int32_t styleIndex), void(*remove_style)(lv_obj_t *obj, int32_t styleIndex))
void eez_flow_init_groups (lv_group_t **groups, size_t numGroups)
void eez_flow_init_screen_names (const char **screenNames, size_t numScreens)
void eez_flow_init_object_names (const char **objectNames, size_t numObjects)
void eez_flow_init_group_names (const char **groupNames, size_t numGroups)
void eez_flow_init_style_names (const char **styleNames, size_t numStyles)
void eez_flow_tick ()
bool eez_flow_is_stopped ()
void flowOnPageLoaded (unsigned pageIndex)
void flowPropagateValue (void *flowState, unsigned componentIndex, unsigned outputIndex)
void flowPropagateValueInt32 (void *flowState, unsigned componentIndex, unsigned outputIndex, int32_t value)
void flowPropagateValueUint32 (void *flowState, unsigned componentIndex, unsigned outputIndex, uint32_t value)
void flowPropagateValueLVGLEvent (void *flowState, unsigned componentIndex, unsigned outputIndex, lv_event_t *event)
const char * _evalTextProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *errorMessage, const char *file, int line)
int32_t _evalIntegerProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *errorMessage, const char *file, int line)
uint32_t _evalUnsignedIntegerProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *errorMessage, const char *file, int line)
bool _evalBooleanProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *errorMessage, const char *file, int line)
const char * _evalStringArrayPropertyAndJoin (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *errorMessage, const char *separator, const char *file, int line)
void _assignStringProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *value, const char *errorMessage, const char *file, int line)
void _assignIntegerProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, int32_t value, const char *errorMessage, const char *file, int line)
void _assignBooleanProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, bool value, const char *errorMessage, const char *file, int line)
float getTimelinePosition (void *flowState)
void * getFlowState (void *flowState, unsigned userWidgetComponentIndexOrPageIndex)
void deletePageFlowState (unsigned pageIndex)
bool compareRollerOptions (lv_roller_t *roller, const char *new_val, const char *cur_val, lv_roller_mode_t mode)
uint32_t eez_flow_get_selected_theme_index ()
Value eez::flow::op_add (const Value &a1, const Value &b1)
Value eez::flow::op_sub (const Value &a1, const Value &b1)
Value eez::flow::op_mul (const Value &a1, const Value &b1)
Value eez::flow::op_div (const Value &a1, const Value &b1)
Value eez::flow::op_mod (const Value &a1, const Value &b1)
Value eez::flow::op_left_shift (const Value &a1, const Value &b1)
Value eez::flow::op_right_shift (const Value &a1, const Value &b1)
Value eez::flow::op_binary_and (const Value &a1, const Value &b1)
Value eez::flow::op_binary_or (const Value &a1, const Value &b1)
Value eez::flow::op_binary_xor (const Value &a1, const Value &b1)
static bool eez::flow::is_equal (const Value &a1, const Value &b1)
static bool eez::flow::is_less (const Value &a1, const Value &b1)
static bool eez::flow::is_great (const Value &a1, const Value &b1)
Value eez::flow::op_eq (const Value &a1, const Value &b1)
Value eez::flow::op_neq (const Value &a1, const Value &b1)
Value eez::flow::op_less (const Value &a1, const Value &b1)
Value eez::flow::op_great (const Value &a1, const Value &b1)
Value eez::flow::op_less_eq (const Value &a1, const Value &b1)
Value eez::flow::op_great_eq (const Value &a1, const Value &b1)
static void eez::flow::do_OPERATION_TYPE_ADD (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_SUB (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MUL (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DIV (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MOD (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_LEFT_SHIFT (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_RIGHT_SHIFT (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_BINARY_AND (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_BINARY_OR (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_BINARY_XOR (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_EQUAL (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_NOT_EQUAL (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_LESS (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_GREATER (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_LESS_OR_EQUAL (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_GREATER_OR_EQUAL (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_LOGICAL_AND (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_LOGICAL_OR (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_UNARY_PLUS (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_UNARY_MINUS (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_BINARY_ONE_COMPLEMENT (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_NOT (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_CONDITIONAL (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_SYSTEM_GET_TICK (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_INDEX (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_IS_PAGE_ACTIVE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_PAGE_TIMELINE_POSITION (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_MAKE_ARRAY_VALUE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_LANGUAGES (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_TRANSLATE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_THEMES (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_PARSE_INTEGER (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_PARSE_FLOAT (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_PARSE_DOUBLE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_TO_INTEGER (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_GET_BITMAP_INDEX (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_FLOW_GET_BITMAP_AS_DATA_URL (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_NOW (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_TO_STRING (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_TO_LOCALE_STRING (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_FROM_STRING (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_GET_YEAR (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_GET_MONTH (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_GET_DAY (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_GET_HOURS (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_GET_MINUTES (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_GET_SECONDS (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_GET_MILLISECONDS (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_DATE_MAKE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MATH_SIN (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MATH_COS (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MATH_POW (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MATH_LOG (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MATH_LOG10 (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MATH_ABS (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MATH_FLOOR (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MATH_CEIL (EvalStack &stack)
static float eez::flow::roundN (float value, unsigned int numDigits)
static double eez::flow::roundN (double value, unsigned int numDigits)
static void eez::flow::do_OPERATION_TYPE_MATH_ROUND (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MATH_MIN (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_MATH_MAX (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_STRING_LENGTH (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_STRING_SUBSTRING (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_STRING_FIND (EvalStack &stack)
static size_t eez::flow::do_string_format (FormatType type, const Value &b, char *result, size_t result_size, const char *format)
static void eez::flow::do_OPERATION_TYPE_STRING_FORMAT (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_STRING_FORMAT_PREFIX (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_STRING_PAD_START (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_STRING_SPLIT (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_STRING_FROM_CODE_POINT (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_STRING_CODE_POINT_AT (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_ARRAY_LENGTH (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_ARRAY_SLICE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_ARRAY_ALLOCATE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_ARRAY_APPEND (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_ARRAY_INSERT (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_ARRAY_REMOVE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_ARRAY_CLONE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_LVGL_METER_TICK_INDEX (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_CRYPTO_SHA256 (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_BLOB_ALLOCATE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_BLOB_TO_STRING (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_JSON_GET (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_JSON_CLONE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_EVENT_GET_CODE (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_EVENT_GET_CURRENT_TARGET (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_EVENT_GET_TARGET (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_EVENT_GET_USER_DATA (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_EVENT_GET_KEY (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_EVENT_GET_GESTURE_DIR (EvalStack &stack)
static void eez::flow::do_OPERATION_TYPE_EVENT_GET_ROTARY_DIFF (EvalStack &stack)
bool eez::flow::isInputEmpty (const Value &inputValue)
Value eez::flow::getEmptyInputValue ()
void eez::flow::initGlobalVariables (Assets *assets)
static bool eez::flow::isComponentReadyToRun (FlowState *flowState, unsigned componentIndex)
static bool eez::flow::pingComponent (FlowState *flowState, unsigned componentIndex, int sourceComponentIndex=-1, int sourceOutputIndex=-1, int targetInputIndex=-1)
static FlowState * eez::flow::initFlowState (Assets *assets, int flowIndex, FlowState *parentFlowState, int parentComponentIndex, const Value &inputValue)
FlowState * eez::flow::initActionFlowState (int flowIndex, FlowState *parentFlowState, int parentComponentIndex, const Value &inputValue)
FlowState * eez::flow::initPageFlowState (Assets *assets, int flowIndex, FlowState *parentFlowState, int parentComponentIndex)
void eez::flow::incRefCounterForFlowState (FlowState *flowState)
void eez::flow::decRefCounterForFlowState (FlowState *flowState)
bool eez::flow::canFreeFlowState (FlowState *flowState)
void eez::flow::freeFlowState (FlowState *flowState)
void eez::flow::freeAllChildrenFlowStates (FlowState *firstChildFlowState)
void eez::flow::deallocateComponentExecutionState (FlowState *flowState, unsigned componentIndex)
void eez::flow::resetSequenceInputs (FlowState *flowState)
void eez::flow::propagateValue (FlowState *flowState, unsigned componentIndex, unsigned outputIndex, const Value &value)
void eez::flow::propagateValue (FlowState *flowState, unsigned componentIndex, unsigned outputIndex)
void eez::flow::propagateValueThroughSeqout (FlowState *flowState, unsigned componentIndex)
void eez::flow::assignValue (FlowState *flowState, int componentIndex, Value &dstValue, const Value &srcValue)
void eez::flow::clearInputValue (FlowState *flowState, int inputIndex)
void eez::flow::startAsyncExecution (FlowState *flowState, int componentIndex)
void eez::flow::endAsyncExecution (FlowState *flowState, int componentIndex)
void eez::flow::onEvent (FlowState *flowState, FlowEvent flowEvent, Value eventValue)
static bool eez::flow::findCatchErrorComponent (FlowState *flowState, FlowState *&catchErrorFlowState, int &catchErrorComponentIndex)
void eez::flow::throwError (FlowState *flowState, int componentIndex, const char *errorMessage)
void eez::flow::throwError (FlowState *flowState, int componentIndex, const FlowError &error)
void eez::flow::enableThrowError (bool enable)
void eez::flow::queueReset ()
size_t eez::flow::getQueueSize ()
size_t eez::flow::getMaxQueueSize ()
bool eez::flow::addToQueue (FlowState *flowState, unsigned componentIndex, int sourceComponentIndex, int sourceOutputIndex, int targetInputIndex, bool continuousTask)
bool eez::flow::peekNextTaskFromQueue (FlowState *&flowState, unsigned &componentIndex, bool &continuousTask)
void eez::flow::removeNextTaskFromQueue ()
bool eez::flow::isInQueue (FlowState *flowState, unsigned componentIndex)
void eez::flow::removeTasksFromQueueForFlowState (FlowState *flowState)
WatchListNode * eez::flow::watchListAdd (FlowState *flowState, unsigned componentIndex)
void eez::flow::watchListRemove (WatchListNode *node)
void eez::flow::visitWatchList ()
void eez::flow::watchListReset ()
void eez::flow::removeWatchesForFlowState (FlowState *flowState)
unsigned eez::flow::getWatchListSize ()
Variables
bool eez::g_isMainAssetsLoaded
Assets * eez::g_mainAssets
bool eez::g_mainAssetsUncompressed
Assets * eez::g_externalAssets
uint8_t * eez::DECOMPRESSED_ASSETS_START_ADDRESS
uint8_t * eez::FLOW_TO_DEBUGGER_MESSAGE_BUFFER
uint8_t * eez::ALLOC_BUFFER = 0
uint32_t eez::ALLOC_BUFFER_SIZE = 0
const char * eez::g_unitNames []
const Unit eez::g_baseUnit []
const float eez::g_unitFactor []
static const float eez::FACTORS [] = { 1E-12F, 1E-9F, 1E-6F, 1E-3F, 1E0F, 1E3F, 1E6F, 1E9F, 1E12F }
static const float PI_FLOAT = (float)3.14159265358979323846
static const float c1 = 1.70158f
static const float c2 = c1 * 1.525f
static const float c3 = c1 + 1.0f
static const float c4 = (2 * PI_FLOAT) / 3
static const float c5 = (2 * PI_FLOAT) / 4.5f
EasingFuncType eez::g_easingFuncs []
CompareValueFunction eez::g_valueTypeCompareFunctions []
ValueToTextFunction eez::g_valueTypeToTextFunctions []
ValueTypeNameFunction eez::g_valueTypeNames []
static ExecuteComponentFunctionType eez::flow::g_executeComponentFunctions []
FlowState * eez::flow::g_executeActionFlowState
unsigned eez::flow::g_executeActionComponentIndex
lv_anim_exec_xcb_t eez::flow::anim_set_callbacks []
lv_anim_get_value_cb_t eez::flow::anim_get_callbacks []
int32_t(* eez::flow::anim_path_callbacks [])(const lv_anim_t *a)
static ActionType eez::flow::actions []
MQTTConnection * eez::flow::g_firstMQTTConnection = nullptr
MQTTConnection * eez::flow::g_lastMQTTConnection = nullptr
SortArrayActionComponent * eez::flow::g_sortArrayActionComponent
static const uint8_t eez::flow::date::monthDays [] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }
struct {
TimeChangeRule eez::flow::date::dstStart
TimeChangeRule eez::flow::date::dstEnd
} eez::flow::date::g_dstRules []
Format eez::flow::date::g_localeFormat = FORMAT_DMY_24
int eez::flow::date::g_timeZone = 0
DstRule eez::flow::date::g_dstRule = DST_RULE_OFF
bool eez::flow::g_debuggerIsConnected
static uint32_t eez::flow::g_messageSubsciptionFilter = 0xFFFFFFFF
static DebuggerState eez::flow::g_debuggerState
static bool eez::flow::g_skipNextBreakpoint
static char eez::flow::g_inputFromDebugger [64]
static unsigned eez::flow::g_inputFromDebuggerPosition
int eez::flow::g_debuggerMode = DEBUGGER_MODE_RUN
char eez::flow::outputBuffer [64]
int eez::flow::outputBufferPosition = 0
EvalStack eez::flow::g_stack
static const uint32_t eez::flow::FLOW_TICK_MAX_DURATION_MS = 5
static unsigned eez::flow::g_tick_max_duration_count = 0
int eez::flow::g_selectedLanguage = 0
FlowState * eez::flow::g_firstFlowState
FlowState * eez::flow::g_lastFlowState
static bool eez::flow::g_isStopping = false
static bool eez::flow::g_isStopped = true
void(* eez::flow::replacePageHook)(int16_t pageId, uint32_t animType, uint32_t speed, uint32_t delay) = replacePage
void(* eez::flow::showKeyboardHook)(Value label, Value initialText, Value minChars, Value maxChars, bool isPassword, void(*onOk)(char *), void(*onCancel)()) = showKeyboard
void(* eez::flow::showKeypadHook)(Value label, Value initialValue, Value min, Value max, Unit unit, void(*onOk)(float), void(*onCancel)()) = showKeypad
void(* eez::flow::stopScriptHook)() = stopScript
void(* eez::flow::scpiComponentInitHook)() = scpiComponentInit
void(* eez::flow::startToDebuggerMessageHook)() = startToDebuggerMessage
void(* eez::flow::writeDebuggerBufferHook)(const char *buffer, uint32_t length) = writeDebuggerBuffer
void(* eez::flow::finishToDebuggerMessageHook)() = finishToDebuggerMessage
void(* eez::flow::onDebuggerInputAvailableHook)() = onDebuggerInputAvailable
lv_obj_t *(* eez::flow::getLvglObjectFromIndexHook)(int32_t index) = getLvglObjectFromIndex
lv_group_t *(* eez::flow::getLvglGroupFromIndexHook)(int32_t index) = getLvglGroupFromIndex
int32_t(* eez::flow::getLvglScreenByNameHook)(const char *name) = getLvglScreenByName
int32_t(* eez::flow::getLvglObjectByNameHook)(const char *name) = getLvglObjectByName
int32_t(* eez::flow::getLvglGroupByNameHook)(const char *name) = getLvglGroupByName
int32_t(* eez::flow::getLvglStyleByNameHook)(const char *name) = getLvglStyleByName
const void *(* eez::flow::getLvglImageByNameHook)(const char *name) = getLvglImageByName
void(* eez::flow::executeLvglActionHook)(int actionIndex) = executeLvglAction
void(* eez::flow::lvglObjAddStyleHook)(lv_obj_t *object, int32_t styleIndex) = lvglObjAddStyle
void(* eez::flow::lvglObjRemoveStyleHook)(lv_obj_t *object, int32_t styleIndex) = lvglObjRemoveStyle
void(* eez::flow::lvglSetColorThemeHook)(const char *themeName) = lvglSetColorTheme
double(* eez::flow::getDateNowHook)() = getDateNowDefaultImplementation
void(* eez::flow::onFlowErrorHook)(FlowState *flowState, int componentIndex, const char *errorMessage) = nullptr
static const char ** g_screenNames
static size_t g_numScreens
static lv_obj_t ** g_objects
static const char ** g_objectNames
static size_t g_numObjects
static lv_group_t ** g_groups
static const char ** g_groupNames
static size_t g_numGroups
static const char ** g_styleNames
static size_t g_numStyles
static const ext_img_desc_t * g_images
static size_t g_numImages
static ActionExecFunc * g_actions
int16_t g_currentScreen = -1
static const char ** g_themeNames
static size_t g_numThemes
static void(* g_changeColorTheme)(uint32_t themeIndex)
static uint32_t g_selectedThemeIndex
static void(* g_createScreenFunc)(int screenIndex)
static void(* g_deleteScreenFunc)(int screenIndex)
uint8_t g_lastLVGLEventUserDataBuffer [64]
uint8_t g_lastLVGLEventParamBuffer [64]
static lv_event_t g_lastLVGLEvent
int16_t g_screenStack [10]
unsigned g_screenStackPosition = 0
ActionExecFunc eez::g_actionExecFunctions [] = { 0 }
static char textValue [1024]
int g_eezFlowLvlgMeterTickIndex = 0
EvalOperation eez::flow::g_evalOperations []
GlobalVariables * eez::flow::g_globalVariables = nullptr
static const unsigned eez::flow::NO_COMPONENT_INDEX = 0xFFFFFFFF
static bool eez::flow::g_enableThrowError = true
static const unsigned eez::flow::QUEUE_SIZE = 1000
struct {
FlowState * eez::flow::flowState
unsigned eez::flow::componentIndex
bool eez::flow::continuousTask
} eez::flow::g_queue [QUEUE_SIZE]
static unsigned eez::flow::g_queueHead
static unsigned eez::flow::g_queueTail
static unsigned eez::flow::g_queueMax
static bool eez::flow::g_queueIsFull = false
unsigned eez::flow::g_numNonContinuousTaskInQueue
static WatchList eez::flow::g_watchList
Macro Definition Documentation
_USE_MATH_DEFINES
#define _USE_MATH_DEFINES
Definition at line 916 of file eez-flow.cpp.
ACTION_END
#define ACTION_END }
Definition at line 4306 of file eez-flow.cpp.
Referenced by eez::flow::animHeight(), eez::flow::animImageAngle(), eez::flow::animImageZoom(), eez::flow::animOpacity(), eez::flow::animWidth(), eez::flow::animX(), eez::flow::animY(), eez::flow::arcSetValue(), eez::flow::barSetValue(), eez::flow::buttonMatrixClearButtonCtrl(), eez::flow::buttonMatrixSetButtonCtrl(), eez::flow::calendarGetPressedDate(), eez::flow::calendarSetHighlightedDate(), eez::flow::calendarSetShowedDate(), eez::flow::calendarSetTodayDate(), eez::flow::changeToPreviousScreen(), eez::flow::createScreen(), eez::flow::deleteScreen(), eez::flow::dropdownSetSelected(), eez::flow::groupFocusFreeze(), eez::flow::groupFocusNext(), eez::flow::groupFocusObj(), eez::flow::groupFocusPrev(), eez::flow::groupGetFocused(), eez::flow::groupSetEditing(), eez::flow::groupSetWrap(), eez::flow::imageSetAngle(), eez::flow::imageSetZoom(), eez::flow::isScreenCreated(), eez::flow::keyboardSetTextarea(), eez::flow::labelSetText(), eez::flow::objAddFlag(), eez::flow::objAddState(), eez::flow::objAddStyle(), eez::flow::objClearFlag(), eez::flow::objClearState(), eez::flow::objGetHeight(), eez::flow::objGetStyleOpa(), eez::flow::objGetWidth(), eez::flow::objGetX(), eez::flow::objGetY(), eez::flow::objHasFlag(), eez::flow::objHasState(), eez::flow::objRemoveStyle(), eez::flow::objSetFlagHidden(), eez::flow::objSetHeight(), eez::flow::objSetStateChecked(), eez::flow::objSetStateDisabled(), eez::flow::objSetStyleOpa(), eez::flow::objSetWidth(), eez::flow::objSetX(), eez::flow::objSetY(), eez::flow::qrCodeUpdate(), eez::flow::rollerSetSelected(), eez::flow::sliderSetRange(), eez::flow::sliderSetValue(), and eez::flow::sliderSetValueLeft().
ACTION_START
#define ACTION_START (NAME)
Value:
    static void NAME(FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr<Property> &properties, uint32_t actionIndex) { \
    const char *actionName = #NAME; \
    int propIndex = 0;
Definition at line 4157 of file eez-flow.cpp.
#define ACTION_START(NAME) static void NAME(FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr<Property> &properties, uint32_t actionIndex) { \
    const char *actionName = #NAME; \
    int propIndex = 0;
ANIM_PROPS
#define ANIM_PROPS
Value:
    WIDGET_PROP(obj); \
    INT32_PROP(start); \
    INT32_PROP(end); \
    INT32_PROP(delay); \
    INT32_PROP(time); \
    BOOL_PROP(relative); \
    BOOL_PROP(instant); \
    INT32_PROP(path);
Definition at line 4592 of file eez-flow.cpp.
#define ANIM_PROPS \
    WIDGET_PROP(obj); \
    INT32_PROP(start); \
    INT32_PROP(end); \
    INT32_PROP(delay); \
    INT32_PROP(time); \
    BOOL_PROP(relative); \
    BOOL_PROP(instant); \
    INT32_PROP(path);
Referenced by eez::flow::animHeight(), eez::flow::animImageAngle(), eez::flow::animImageZoom(), eez::flow::animOpacity(), eez::flow::animWidth(), eez::flow::animX(), and eez::flow::animY().
BOOL_PROP
#define BOOL_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int32_t NAME = NAME##Value.getBoolean();
Definition at line 4202 of file eez-flow.cpp.
#define BOOL_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int32_t NAME = NAME##Value.getBoolean();
EEZ_FLOW_TICK_MAX_DURATION_MS
#define EEZ_FLOW_TICK_MAX_DURATION_MS 5
Definition at line 7018 of file eez-flow.cpp.
EEZ_LVGL_SCREEN_STACK_SIZE
#define EEZ_LVGL_SCREEN_STACK_SIZE 10
Definition at line 7701 of file eez-flow.cpp.
Referenced by eez_flow_push_screen().
EEZ_LVGL_TEMP_STRING_BUFFER_SIZE
#define EEZ_LVGL_TEMP_STRING_BUFFER_SIZE 1024
Definition at line 7906 of file eez-flow.cpp.
FLUSH_OUTPUT_BUFFER
#define FLUSH_OUTPUT_BUFFER ()
Value:
    if (outputBufferPosition > 0) { \
        writeDebuggerBufferHook(outputBuffer, outputBufferPosition); \
        outputBufferPosition = 0; \
    }
Definition at line 6205 of file eez-flow.cpp.
#define FLUSH_OUTPUT_BUFFER() \
    if (outputBufferPosition > 0) { \
        writeDebuggerBufferHook(outputBuffer, outputBufferPosition); \
        outputBufferPosition = 0; \
    }
Referenced by eez::flow::writeArray(), eez::flow::writeLogMessage(), eez::flow::writeLogMessage(), and eez::flow::writeString().
GET_MESSAGE
#define GET_MESSAGE (FMT, ...)
Value:
        if (file) snprintf(messageStr, messageStrLength, FMT " | %d.%d | %s:%d", __VA_ARGS__, flowIndex, componentIndex, file, line); \
        else snprintf(messageStr, messageStrLength, FMT " | %d.%d", __VA_ARGS__, flowIndex, componentIndex);
GROUP_PROP
#define GROUP_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    lv_group_t *NAME; \
    if (NAME##Value.isString()) { \
        const char *groupName = NAME##Value.getString(); \
        int32_t NAME##_GroupIndex = getLvglGroupByNameHook(groupName); \
        if (NAME##_GroupIndex == -1) { \
            throwError(flowState, componentIndex, FlowError::NotFoundInAction("Group", groupName, actionName, actionIndex)); \
            return; \
        } \
        NAME = getLvglGroupFromIndexHook(NAME##_GroupIndex); \
    } else { \
        int32_t NAME##_GroupIndex = NAME##Value.getInt(); \
        NAME = getLvglGroupFromIndexHook(NAME##_GroupIndex); \
    } \
    if (!NAME) { \
        throwError(flowState, componentIndex, FlowError::NullInAction("Group", actionName, actionIndex)); \
        return; \
    }
Definition at line 4259 of file eez-flow.cpp.
#define GROUP_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    lv_group_t *NAME; \
    if (NAME##Value.isString()) { \
        const char *groupName = NAME##Value.getString(); \
        int32_t NAME##_GroupIndex = getLvglGroupByNameHook(groupName); \
        if (NAME##_GroupIndex == -1) { \
            throwError(flowState, componentIndex, FlowError::NotFoundInAction("Group", groupName, actionName, actionIndex)); \
            return; \
        } \
        NAME = getLvglGroupFromIndexHook(NAME##_GroupIndex); \
    } else { \
        int32_t NAME##_GroupIndex = NAME##Value.getInt(); \
        NAME = getLvglGroupFromIndexHook(NAME##_GroupIndex); \
    } \
    if (!NAME) { \
        throwError(flowState, componentIndex, FlowError::NullInAction("Group", actionName, actionIndex)); \
        return; \
    }
INT16_PROP
#define INT16_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int16_t NAME = NAME##Value.getInt16();
Definition at line 4174 of file eez-flow.cpp.
#define INT16_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int16_t NAME = NAME##Value.getInt16();
INT32_PROP
#define INT32_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int32_t NAME = NAME##Value.getInt();
Definition at line 4188 of file eez-flow.cpp.
#define INT32_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int32_t NAME = NAME##Value.getInt();
INT8_PROP
#define INT8_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int8_t NAME = NAME##Value.getInt8();
Definition at line 4160 of file eez-flow.cpp.
#define INT8_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int8_t NAME = NAME##Value.getInt8();
LEAP_YEAR
#define LEAP_YEAR (Y)
Value:
    (((1970 + Y) > 0) && !((1970 + Y) % 4) && (((1970 + Y) % 100) || !((1970 + Y) % 400)))
Definition at line 5803 of file eez-flow.cpp.
#define LEAP_YEAR(Y)                                                                               \
    (((1970 + Y) > 0) && !((1970 + Y) % 4) && (((1970 + Y) % 100) || !((1970 + Y) % 400)))
Referenced by eez::flow::date::breakDate(), and eez::flow::date::makeDate().
MAX_ARRAY_SIZE_TRANSFERRED_IN_DEBUGGER
#define MAX_ARRAY_SIZE_TRANSFERRED_IN_DEBUGGER 1000
Definition at line 6035 of file eez-flow.cpp.
Referenced by eez::flow::writeArray().
RESULT
#define RESULT (NAME, VALUE)
Value:
    Value NAME##Value; \
    if (!evalAssignableExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyAssignInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    assignValue(flowState, componentIndex, NAME##Value, VALUE);
Definition at line 4299 of file eez-flow.cpp.
#define RESULT(NAME, VALUE) \
    Value NAME##Value; \
    if (!evalAssignableExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyAssignInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    assignValue(flowState, componentIndex, NAME##Value, VALUE);
SCPI_ERROR_INVALID_BLOCK_DATA
#define SCPI_ERROR_INVALID_BLOCK_DATA -161
Definition at line 252 of file eez-flow.cpp.
Referenced by eez::decompressAssetsData().
SCPI_ERROR_OUT_OF_DEVICE_MEMORY
#define SCPI_ERROR_OUT_OF_DEVICE_MEMORY -321
Definition at line 251 of file eez-flow.cpp.
Referenced by eez::decompressAssetsData().
SCREEN_PROP
#define SCREEN_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int32_t NAME; \
    if (NAME##Value.isString()) { \
        const char *screenName = NAME##Value.getString(); \
        NAME = getLvglScreenByNameHook(screenName); \
        if (NAME == 0) { \
            throwError(flowState, componentIndex, FlowError::NotFoundInAction("Screen", screenName, actionName, actionIndex)); \
            return; \
        } \
    } else { \
        NAME = NAME##Value.getInt(); \
    }
Definition at line 4216 of file eez-flow.cpp.
#define SCREEN_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int32_t NAME; \
    if (NAME##Value.isString()) { \
        const char *screenName = NAME##Value.getString(); \
        NAME = getLvglScreenByNameHook(screenName); \
        if (NAME == 0) { \
            throwError(flowState, componentIndex, FlowError::NotFoundInAction("Screen", screenName, actionName, actionIndex)); \
            return; \
        } \
    } else { \
        NAME = NAME##Value.getInt(); \
    }
SECONDS_PER_DAY
#define SECONDS_PER_DAY (SECONDS_PER_HOUR * 24)
Definition at line 5802 of file eez-flow.cpp.
Referenced by eez::flow::date::makeDate(), and eez::flow::date::timeChangeRuleToLocal().
SECONDS_PER_HOUR
#define SECONDS_PER_HOUR (SECONDS_PER_MINUTE * 60)
Definition at line 5801 of file eez-flow.cpp.
Referenced by eez::flow::date::localToUtc(), eez::flow::date::makeDate(), and eez::flow::date::utcToLocal().
SECONDS_PER_MINUTE
#define SECONDS_PER_MINUTE 60UL
Definition at line 5800 of file eez-flow.cpp.
Referenced by eez::flow::date::makeDate().
STR_PROP
#define STR_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    const char *NAME = NAME##Value.toString(0xe42b3ca2).getString();
Definition at line 4209 of file eez-flow.cpp.
#define STR_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    const char *NAME = NAME##Value.toString(0xe42b3ca2).getString();
STYLE_PROP
#define STYLE_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int32_t NAME; \
    if (NAME##Value.isString()) { \
        const char *styleName = NAME##Value.getString(); \
        NAME = getLvglStyleByNameHook(styleName); \
        if (NAME == -1) { \
            throwError(flowState, componentIndex, FlowError::NotFoundInAction("Style", styleName, actionName, actionIndex)); \
            return; \
        } \
    } else { \
        NAME = NAME##Value.getInt(); \
    }
Definition at line 4282 of file eez-flow.cpp.
#define STYLE_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    int32_t NAME; \
    if (NAME##Value.isString()) { \
        const char *styleName = NAME##Value.getString(); \
        NAME = getLvglStyleByNameHook(styleName); \
        if (NAME == -1) { \
            throwError(flowState, componentIndex, FlowError::NotFoundInAction("Style", styleName, actionName, actionIndex)); \
            return; \
        } \
    } else { \
        NAME = NAME##Value.getInt(); \
    }
UINT16_PROP
#define UINT16_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    uint16_t NAME = NAME##Value.getUInt16();
Definition at line 4181 of file eez-flow.cpp.
#define UINT16_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    uint16_t NAME = NAME##Value.getUInt16();
UINT32_PROP
#define UINT32_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    uint32_t NAME = NAME##Value.getUInt32();
Definition at line 4195 of file eez-flow.cpp.
#define UINT32_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    uint32_t NAME = NAME##Value.getUInt32();
UINT8_PROP
#define UINT8_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    uint8_t NAME = NAME##Value.getUInt8();
Definition at line 4167 of file eez-flow.cpp.
#define UINT8_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    uint8_t NAME = NAME##Value.getUInt8();
VALUE_TYPE [1/7]
#define VALUE_TYPE (instructions[i] + (instructions[i + 1] << 8) + (instructions[i + 2] << 16) + (instructions[i + 3] << 24))
Definition at line 2318 of file eez-flow.cpp.
VALUE_TYPE [2/7]
#define VALUE_TYPE (NAME)
Value:
NAME##_value_type_name,
Definition at line 2318 of file eez-flow.cpp.
VALUE_TYPE [3/7]
#define VALUE_TYPE (NAME)
Value:
const char * NAME##_value_type_name(const Value &value);
Definition at line 2318 of file eez-flow.cpp.
VALUE_TYPE [4/7]
#define VALUE_TYPE (NAME)
Value:
NAME##_value_to_text,
Definition at line 2318 of file eez-flow.cpp.
VALUE_TYPE [5/7]
#define VALUE_TYPE (NAME)
Value:
void NAME##_value_to_text(const Value &value, char *text, int count);
Definition at line 2318 of file eez-flow.cpp.
VALUE_TYPE [6/7]
#define VALUE_TYPE (NAME)
Value:
compare_##NAME##_value,
Definition at line 2318 of file eez-flow.cpp.
VALUE_TYPE [7/7]
#define VALUE_TYPE (NAME)
Value:
bool compare_##NAME##_value(const Value &a, const Value &b);
Definition at line 2318 of file eez-flow.cpp.
Referenced by eez::flow::evalExpression().
WIDGET_PROP
#define WIDGET_PROP (NAME)
Value:
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    lv_obj_t *NAME; \
    if (NAME##Value.isWidget()) { \
        NAME = (lv_obj_t *)NAME##Value.getWidget(); \
    } else if (NAME##Value.isString()) { \
        const char *objectName = NAME##Value.getString(); \
        int32_t widgetIndex = getLvglObjectByNameHook(objectName); \
        if (widgetIndex == -1) { \
            throwError(flowState, componentIndex, FlowError::NotFoundInAction("Widget", objectName, actionName, actionIndex)); \
            return; \
        } \
        NAME = getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + widgetIndex); \
    } else { \
        int32_t widgetIndex = NAME##Value.getInt(); \
        for (FlowState *fs = flowState; fs; fs = fs->parentFlowState) widgetIndex += fs->lvglWidgetStartIndex; \
        NAME = getLvglObjectFromIndexHook(widgetIndex); \
    } \
    if (!NAME) { \
        throwError(flowState, componentIndex, FlowError::NullInAction("Widget", actionName, actionIndex)); \
        return; \
    }
Definition at line 4233 of file eez-flow.cpp.
#define WIDGET_PROP(NAME) \
    Value NAME##Value; \
    if (!evalExpression(flowState, componentIndex, properties[propIndex]->evalInstructions, NAME##Value, FlowError::PropertyInAction(#NAME, actionName, actionIndex))) { \
        return; \
    }\
    propIndex++; \
    lv_obj_t *NAME; \
    if (NAME##Value.isWidget()) { \
        NAME = (lv_obj_t *)NAME##Value.getWidget(); \
    } else if (NAME##Value.isString()) { \
        const char *objectName = NAME##Value.getString(); \
        int32_t widgetIndex = getLvglObjectByNameHook(objectName); \
        if (widgetIndex == -1) { \
            throwError(flowState, componentIndex, FlowError::NotFoundInAction("Widget", objectName, actionName, actionIndex)); \
            return; \
        } \
        NAME = getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + widgetIndex); \
    } else { \
        int32_t widgetIndex = NAME##Value.getInt(); \
        for (FlowState *fs = flowState; fs; fs = fs->parentFlowState) widgetIndex += fs->lvglWidgetStartIndex; \
        NAME = getLvglObjectFromIndexHook(widgetIndex); \
    } \
    if (!NAME) { \
        throwError(flowState, componentIndex, FlowError::NullInAction("Widget", actionName, actionIndex)); \
        return; \
    }
WRITE_TO_OUTPUT_BUFFER
#define WRITE_TO_OUTPUT_BUFFER (ch)
Value:
    outputBuffer[outputBufferPosition++] = ch; \
    if (outputBufferPosition == sizeof(outputBuffer)) { \
        writeDebuggerBufferHook(outputBuffer, outputBufferPosition); \
        outputBufferPosition = 0; \
    }
Definition at line 6199 of file eez-flow.cpp.
#define WRITE_TO_OUTPUT_BUFFER(ch) \
    outputBuffer[outputBufferPosition++] = ch; \
    if (outputBufferPosition == sizeof(outputBuffer)) { \
        writeDebuggerBufferHook(outputBuffer, outputBufferPosition); \
        outputBufferPosition = 0; \
    }
Referenced by eez::flow::writeArray(), eez::flow::writeArrayType(), eez::flow::writeLogMessage(), eez::flow::writeLogMessage(), eez::flow::writeString(), and eez::flow::writeValueAddr().
Function Documentation
_assignBooleanProperty()
void _assignBooleanProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, bool value, const char * errorMessage, const char * file, int line)
Definition at line 7999 of file eez-flow.cpp.
{
    auto component = ((eez::flow::FlowState *)flowState)->flow->components[componentIndex];
    eez::Value dstValue;
    if (!eez::flow::evalAssignableExpression((eez::flow::FlowState *)flowState, componentIndex, component->properties[propertyIndex]->evalInstructions, dstValue, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return;
    }
    eez::Value srcValue(value, eez::VALUE_TYPE_BOOLEAN);
    eez::flow::assignValue((eez::flow::FlowState *)flowState, componentIndex, dstValue, srcValue);
}
References eez::flow::assignValue(), eez::flow::componentIndex, eez::flow::evalAssignableExpression(), and eez::flow::flowState.
_assignIntegerProperty()
void _assignIntegerProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, int32_t value, const char * errorMessage, const char * file, int line)
Definition at line 7990 of file eez-flow.cpp.
{
    auto component = ((eez::flow::FlowState *)flowState)->flow->components[componentIndex];
    eez::Value dstValue;
    if (!eez::flow::evalAssignableExpression((eez::flow::FlowState *)flowState, componentIndex, component->properties[propertyIndex]->evalInstructions, dstValue, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return;
    }
    eez::Value srcValue((int)value, eez::VALUE_TYPE_INT32);
    eez::flow::assignValue((eez::flow::FlowState *)flowState, componentIndex, dstValue, srcValue);
}
References eez::flow::assignValue(), eez::flow::componentIndex, eez::flow::evalAssignableExpression(), and eez::flow::flowState.
_assignStringProperty()
void _assignStringProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * value, const char * errorMessage, const char * file, int line)
Definition at line 7981 of file eez-flow.cpp.
{
    auto component = ((eez::flow::FlowState *)flowState)->flow->components[componentIndex];
    eez::Value dstValue;
    if (!eez::flow::evalAssignableExpression((eez::flow::FlowState *)flowState, componentIndex, component->properties[propertyIndex]->evalInstructions, dstValue, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return;
    }
    eez::Value srcValue = eez::Value::makeStringRef(value, -1, 0x3eefcf0d);
    eez::flow::assignValue((eez::flow::FlowState *)flowState, componentIndex, dstValue, srcValue);
}
References eez::flow::assignValue(), eez::flow::componentIndex, eez::flow::evalAssignableExpression(), and eez::flow::flowState.
_evalBooleanProperty()
bool _evalBooleanProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * errorMessage, const char * file, int line)
Definition at line 7943 of file eez-flow.cpp.
{
    eez::Value value;
    if (!eez::flow::evalProperty((eez::flow::FlowState *)flowState, componentIndex, propertyIndex, value, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return 0;
    }
    int err;
    bool booleanValue = value.toBool(&err);
    if (err) {
        eez::flow::throwError((eez::flow::FlowState *)flowState, componentIndex, errorMessage);
        return 0;
    }
    return booleanValue;
}
References eez::flow::componentIndex, eez::flow::evalProperty(), eez::flow::flowState, and eez::flow::throwError().
_evalIntegerProperty()
int32_t _evalIntegerProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * errorMessage, const char * file, int line)
Definition at line 7917 of file eez-flow.cpp.
{
    eez::Value value;
    if (!eez::flow::evalProperty((eez::flow::FlowState *)flowState, componentIndex, propertyIndex, value, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return 0;
    }
    int err;
    int32_t intValue = value.toInt32(&err);
    if (err) {
        eez::flow::throwError((eez::flow::FlowState *)flowState, componentIndex, errorMessage);
        return 0;
    }
    return intValue;
}
References eez::flow::componentIndex, eez::flow::evalProperty(), eez::flow::flowState, and eez::flow::throwError().
_evalStringArrayPropertyAndJoin()
const char * _evalStringArrayPropertyAndJoin (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * errorMessage, const char * separator, const char * file, int line)
Definition at line 7956 of file eez-flow.cpp.
{
    eez::Value value;
    if (!eez::flow::evalProperty((eez::flow::FlowState *)flowState, componentIndex, propertyIndex, value, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return "";
    }
    if (value.isArray()) {
        auto array = value.getArray();
        textValue[0] = 0;
        size_t textPosition = 0;
        size_t separatorLength = strlen(separator);
        for (uint32_t elementIndex = 0; elementIndex < array->arraySize; elementIndex++) {
            if (elementIndex > 0) {
                eez::stringAppendString(textValue + textPosition, sizeof(textValue) - textPosition, separator);
                textPosition += separatorLength;
            }
            array->values[elementIndex].toText(textValue + textPosition, sizeof(textValue) - textPosition);
            textPosition = strlen(textValue);
        }
        return textValue;
    } else if (value.isString()) {
        value.toText(textValue, sizeof(textValue));
        return textValue;
    }
    return "";
}
References eez::flow::componentIndex, eez::flow::evalProperty(), eez::flow::flowState, eez::stringAppendString(), and textValue.
_evalTextProperty()
const char * _evalTextProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * errorMessage, const char * file, int line)
Definition at line 7909 of file eez-flow.cpp.
{
    eez::Value value;
    if (!eez::flow::evalProperty((eez::flow::FlowState *)flowState, componentIndex, propertyIndex, value, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return "";
    }
    value.toText(textValue, sizeof(textValue));
    return textValue;
}
References eez::flow::componentIndex, eez::flow::evalProperty(), eez::flow::flowState, and textValue.
_evalUnsignedIntegerProperty()
uint32_t _evalUnsignedIntegerProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * errorMessage, const char * file, int line)
Definition at line 7930 of file eez-flow.cpp.
{
    eez::Value value;
    if (!eez::flow::evalProperty((eez::flow::FlowState *)flowState, componentIndex, propertyIndex, value, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return 0;
    }
    int err;
    uint32_t intValue = (uint32_t)value.toInt32(&err);
    if (err) {
        eez::flow::throwError((eez::flow::FlowState *)flowState, componentIndex, errorMessage);
        return 0;
    }
    return intValue;
}
References eez::flow::componentIndex, eez::flow::evalProperty(), eez::flow::flowState, and eez::flow::throwError().
compareRollerOptions()
bool compareRollerOptions (lv_roller_t * roller, const char * new_val, const char * cur_val, lv_roller_mode_t mode)
Definition at line 8024 of file eez-flow.cpp.
{
    if (mode == LV_ROLLER_MODE_NORMAL) {
        return strcmp(new_val, cur_val) != 0;
    }
    auto n = strlen(new_val);
#if LVGL_VERSION_MAJOR >= 9
    size_t numPages = roller->inf_page_cnt;
#else
    size_t numPages = LV_ROLLER_INF_PAGES;
#endif
    for (size_t i = 0; i < numPages * (n + 1); i += n + 1) {
        if (strncmp(new_val, cur_val + i, n) != 0) {
            return true;
        }
    }
    return false;
}
create_screens()
void create_screens ()
Definition at line 57 of file screens.c.
                      {
    eez_flow_init_screen_names(screen_names, sizeof(screen_names) / sizeof(const char *));
    eez_flow_init_object_names(object_names, sizeof(object_names) / sizeof(const char *));
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    create_screen_initial_screen();
}
References create_screen_initial_screen(), eez_flow_init_object_names(), eez_flow_init_screen_names(), object_names, and screen_names.
Referenced by eez_flow_init().
createScreen()
void createScreen (int screenIndex) static
Definition at line 7711 of file eez-flow.cpp.
{
    if (g_createScreenFunc && !isScreenCreated(screenIndex)) {
        g_createScreenFunc(screenIndex);
    }
}
References g_createScreenFunc, and isScreenCreated().
Referenced by eez_flow_create_screen(), and replacePageHook().
deletePageFlowState()
void deletePageFlowState (unsigned pageIndex)
Definition at line 8021 of file eez-flow.cpp.
{
    eez::flow::deletePageFlowState(eez::g_mainAssets, (int16_t)pageIndex);
}
References eez::flow::deletePageFlowState(), and eez::g_mainAssets.
deleteScreen()
void deleteScreen (int screenIndex) static
Definition at line 7716 of file eez-flow.cpp.
{
    if (g_deleteScreenFunc && isScreenCreated(screenIndex)) {
        g_deleteScreenFunc(screenIndex);
    }
}
References g_deleteScreenFunc, and isScreenCreated().
Referenced by eez_flow_delete_screen(), and on_screen_unloaded().
eez_easeInBack()
float eez_easeInBack (float x)
Definition at line 1552 of file eez-flow.cpp.
{
    return c3 * x * x * x - c1 * x * x;
}
References c1, and c3.
eez_easeInBounce()
float eez_easeInBounce (float x)
Definition at line 1587 of file eez-flow.cpp.
{
    return 1 - eez_easeOutBounce(1 - x);
}
References eez_easeOutBounce().
eez_easeInCirc()
float eez_easeInCirc (float x)
Definition at line 1541 of file eez-flow.cpp.
{
    return 1 - sqrtf(1 - powf(x, 2));
}
eez_easeInCubic()
float eez_easeInCubic (float x)
Definition at line 1490 of file eez-flow.cpp.
{
    return x * x * x;
}
eez_easeInElastic()
float eez_easeInElastic (float x)
Definition at line 1563 of file eez-flow.cpp.
{
    return x == 0
        ? 0
        : x == 1
        ? 1
        : -powf(2, 10 * x - 10) * sinf((x * 10 - 10.75f) * c4);
}
References c4.
eez_easeInExpo()
float eez_easeInExpo (float x)
Definition at line 1526 of file eez-flow.cpp.
{
    return x == 0 ? 0 : powf(2, 10 * x - 10);
}
eez_easeInOutBack()
float eez_easeInOutBack (float x)
Definition at line 1558 of file eez-flow.cpp.
{
    return x < 0.5
        ? (powf(2 * x, 2) * ((c2 + 1) * 2 * x - c2)) / 2
        : (powf(2 * x - 2, 2) * ((c2 + 1) * (x * 2 - 2) + c2) + 2) / 2;
}
References c2.
eez_easeInOutBounce()
float eez_easeInOutBounce (float x)
Definition at line 1606 of file eez-flow.cpp.
{
    return x < 0.5
        ? (1 - eez_easeOutBounce(1 - 2 * x)) / 2
        : (1 + eez_easeOutBounce(2 * x - 1)) / 2;
}
References eez_easeOutBounce().
eez_easeInOutCirc()
float eez_easeInOutCirc (float x)
Definition at line 1547 of file eez-flow.cpp.
{
    return x < 0.5
        ? (1 - sqrtf(1 - pow(2 * x, 2))) / 2
        : (sqrtf(1 - powf(-2 * x + 2, 2)) + 1) / 2;
}
eez_easeInOutCubic()
float eez_easeInOutCubic (float x)
Definition at line 1496 of file eez-flow.cpp.
{
    return x < 0.5f ? 4 * x * x * x : 1 - powf(-2 * x + 2, 3) / 2;
}
eez_easeInOutElastic()
float eez_easeInOutElastic (float x)
Definition at line 1577 of file eez-flow.cpp.
{
    return x == 0
        ? 0
        : x == 1
        ? 1
        : x < 0.5
        ? -(powf(2, 20 * x - 10) * sinf((20 * x - 11.125f) * c5)) / 2
        : (powf(2, -20 * x + 10) * sinf((20 * x - 11.125f) * c5)) / 2 + 1;
}
References c5.
eez_easeInOutExpo()
float eez_easeInOutExpo (float x)
Definition at line 1532 of file eez-flow.cpp.
{
    return x == 0
        ? 0
        : x == 1
        ? 1
        : x < 0.5
        ? powf(2, 20 * x - 10) / 2
        : (2 - powf(2, -20 * x + 10)) / 2;
}
eez_easeInOutQuad()
float eez_easeInOutQuad (float x)
Definition at line 1487 of file eez-flow.cpp.
{
    return x < 0.5f ? 2 * x * x : 1 - powf(-2 * x + 2, 2) / 2;
}
eez_easeInOutQuart()
float eez_easeInOutQuart (float x)
Definition at line 1505 of file eez-flow.cpp.
{
    return x < 0.5 ? 8 * x * x * x * x : 1 - powf(-2 * x + 2, 4) / 2;
}
eez_easeInOutQuint()
float eez_easeInOutQuint (float x)
Definition at line 1514 of file eez-flow.cpp.
{
    return x < 0.5f ? 16 * x * x * x * x * x : 1 - powf(-2 * x + 2, 5) / 2;
}
eez_easeInOutSine()
float eez_easeInOutSine (float x)
Definition at line 1523 of file eez-flow.cpp.
{
    return -(cosf(PI_FLOAT * x) - 1) / 2;
}
References PI_FLOAT.
eez_easeInQuad()
float eez_easeInQuad (float x)
Definition at line 1481 of file eez-flow.cpp.
{
    return x * x;
}
eez_easeInQuart()
float eez_easeInQuart (float x)
Definition at line 1499 of file eez-flow.cpp.
{
    return x * x * x * x;
}
eez_easeInQuint()
float eez_easeInQuint (float x)
Definition at line 1508 of file eez-flow.cpp.
{
    return x * x * x * x * x;
}
eez_easeInSine()
float eez_easeInSine (float x)
Definition at line 1517 of file eez-flow.cpp.
{
    return 1 - cosf((x * PI_FLOAT) / 2);
}
References PI_FLOAT.
eez_easeOutBack()
float eez_easeOutBack (float x)
Definition at line 1555 of file eez-flow.cpp.
{
    return 1 + c3 * powf(x - 1, 3) + c1 * powf(x - 1, 2);
}
References c1, and c3.
eez_easeOutBounce()
float eez_easeOutBounce (float x)
Definition at line 1590 of file eez-flow.cpp.
{
    static const float n1 = 7.5625f;
    static const float d1 = 2.75f;
    if (x < 1 / d1) {
        return n1 * x * x;
    } else if (x < 2 / d1) {
        x -= 1.5f / d1;
        return n1 * x * x + 0.75f;
    } else if (x < 2.5f / d1) {
        x -= 2.25f / d1;
        return n1 * x * x + 0.9375f;
    } else {
        x -= 2.625f / d1;
        return n1 * x * x + 0.984375f;
    }
};
Referenced by eez_easeInBounce(), and eez_easeInOutBounce().
eez_easeOutCirc()
float eez_easeOutCirc (float x)
Definition at line 1544 of file eez-flow.cpp.
{
    return sqrtf(1 - powf(x - 1, 2));
}
eez_easeOutCubic()
float eez_easeOutCubic (float x)
Definition at line 1493 of file eez-flow.cpp.
{
    return 1 - pow(1 - x, 3);
}
eez_easeOutElastic()
float eez_easeOutElastic (float x)
Definition at line 1570 of file eez-flow.cpp.
{
    return x == 0
        ? 0
        : x == 1
        ? 1
        : powf(2, -10 * x) * sinf((x * 10 - 0.75f) * c4) + 1;
}
References c4.
eez_easeOutExpo()
float eez_easeOutExpo (float x)
Definition at line 1529 of file eez-flow.cpp.
{
    return x == 1 ? 1 : 1 - powf(2, -10 * x);
}
eez_easeOutQuad()
float eez_easeOutQuad (float x)
Definition at line 1484 of file eez-flow.cpp.
{
    return 1 - (1 - x) * (1 - x);
}
eez_easeOutQuart()
float eez_easeOutQuart (float x)
Definition at line 1502 of file eez-flow.cpp.
{
    return 1 - powf(1 - x, 4);
}
eez_easeOutQuint()
float eez_easeOutQuint (float x)
Definition at line 1511 of file eez-flow.cpp.
{
    return 1 - powf(1 - x, 5);
}
eez_easeOutSine()
float eez_easeOutSine (float x)
Definition at line 1520 of file eez-flow.cpp.
{
    return sinf((x * PI_FLOAT) / 2);
}
References PI_FLOAT.
eez_flow_create_screen()
void eez_flow_create_screen (int16_t screenId)
Definition at line 7741 of file eez-flow.cpp.
{
    int16_t screenIndex = screenId - 1;
    createScreen(screenIndex);
}
References createScreen().
eez_flow_delete_screen()
void eez_flow_delete_screen (int16_t screenId)
Definition at line 7745 of file eez-flow.cpp.
{
    int16_t screenIndex = screenId - 1;
    deleteScreen(screenIndex);
}
References deleteScreen().
eez_flow_delete_screen_on_unload()
void eez_flow_delete_screen_on_unload (int screenIndex)
Definition at line 7759 of file eez-flow.cpp.
{
    lv_obj_add_event_cb(
        eez::flow::getLvglObjectFromIndexHook(screenIndex),
        on_screen_unloaded,
        LV_EVENT_SCREEN_UNLOADED,
        (void*)(lv_uintptr_t)(screenIndex)
    );
}
References eez::flow::getLvglObjectFromIndexHook, and on_screen_unloaded().
eez_flow_get_current_screen()
int16_t eez_flow_get_current_screen ()
Definition at line 7705 of file eez-flow.cpp.
{
    return g_currentScreen + 1;
}
References g_currentScreen.
eez_flow_get_selected_theme_index()
uint32_t eez_flow_get_selected_theme_index ()
Definition at line 8041 of file eez-flow.cpp.
{
    return g_selectedThemeIndex;
}
References g_selectedThemeIndex.
eez_flow_init()
void eez_flow_init (const uint8_t * assets, uint32_t assetsSize, lv_obj_t ** objects, size_t numObjects, const ext_img_desc_t * images, size_t numImages, ActionExecFunc * actions)
Definition at line 7767 of file eez-flow.cpp.
{
    g_objects = objects;
    g_numObjects = numObjects;
    g_images = images;
    g_numImages = numImages;
    g_actions = actions;
    eez::initAssetsMemory();
    eez::loadMainAssets(assets, assetsSize);
    eez::initOtherMemory();
    eez::initAllocHeap(eez::ALLOC_BUFFER, eez::ALLOC_BUFFER_SIZE);
    eez::flow::replacePageHook = replacePageHook;
    eez::flow::getLvglObjectFromIndexHook = getLvglObjectFromIndex;
    eez::flow::getLvglScreenByNameHook = getLvglScreenByName;
    eez::flow::getLvglObjectByNameHook = getLvglObjectByName;
    eez::flow::getLvglGroupByNameHook = getLvglGroupByName;
    eez::flow::getLvglStyleByNameHook = getLvglStyleByName;
    eez::flow::getLvglImageByNameHook = getLvglImageByName;
    eez::flow::executeLvglActionHook = executeLvglAction;
    eez::flow::getLvglGroupFromIndexHook = getLvglGroupFromIndex;
    eez::flow::lvglSetColorThemeHook = lvglSetColorTheme;
    eez::flow::start(eez::g_mainAssets);
    create_screens();
    replacePageHook(1, 0, 0, 0);
}
References actions, eez::ALLOC_BUFFER, eez::ALLOC_BUFFER_SIZE, assets, create_screens(), executeLvglAction(), eez::flow::executeLvglActionHook, g_actions, g_images, eez::g_mainAssets, g_numImages, g_numObjects, g_objects, getLvglGroupByName(), eez::flow::getLvglGroupByNameHook, getLvglGroupFromIndex(), eez::flow::getLvglGroupFromIndexHook, getLvglImageByName(), eez::flow::getLvglImageByNameHook, getLvglObjectByName(), eez::flow::getLvglObjectByNameHook, getLvglObjectFromIndex(), eez::flow::getLvglObjectFromIndexHook, getLvglScreenByName(), eez::flow::getLvglScreenByNameHook, getLvglStyleByName(), eez::flow::getLvglStyleByNameHook, images, eez::initAllocHeap(), eez::initAssetsMemory(), eez::initOtherMemory(), eez::loadMainAssets(), lvglSetColorTheme(), eez::flow::lvglSetColorThemeHook, objects, eez::flow::replacePageHook, replacePageHook(), and eez::flow::start().
Referenced by ui_init().
eez_flow_init_group_names()
void eez_flow_init_group_names (const char ** groupNames, size_t numGroups)
Definition at line 7810 of file eez-flow.cpp.
{
    g_groupNames = groupNames;
    EEZ_UNUSED(numGroups);
}
References EEZ_UNUSED, and g_groupNames.
eez_flow_init_groups()
void eez_flow_init_groups (lv_group_t ** groups, size_t numGroups)
Definition at line 7798 of file eez-flow.cpp.
{
    g_groups = groups;
    g_numGroups = numGroups;
}
References g_groups, and g_numGroups.
eez_flow_init_object_names()
void eez_flow_init_object_names (const char ** objectNames, size_t numObjects)
Definition at line 7806 of file eez-flow.cpp.
{
    g_objectNames = objectNames;
    EEZ_UNUSED(numObjects);
}
References EEZ_UNUSED, and g_objectNames.
Referenced by create_screens().
eez_flow_init_screen_names()
void eez_flow_init_screen_names (const char ** screenNames, size_t numScreens)
Definition at line 7802 of file eez-flow.cpp.
{
    g_screenNames = screenNames;
    g_numScreens = numScreens;
}
References g_numScreens, and g_screenNames.
Referenced by create_screens().
eez_flow_init_style_names()
void eez_flow_init_style_names (const char ** styleNames, size_t numStyles)
Definition at line 7814 of file eez-flow.cpp.
{
    g_styleNames = styleNames;
    g_numStyles = numStyles;
}
References g_numStyles, and g_styleNames.
eez_flow_init_styles()
void eez_flow_init_styles (void(* add_style)(lv_obj_t *obj, int32_t styleIndex), void(* remove_style)(lv_obj_t *obj, int32_t styleIndex))
Definition at line 7791 of file eez-flow.cpp.
  {
    eez::flow::lvglObjAddStyleHook = add_style;
    eez::flow::lvglObjRemoveStyleHook = remove_style;
}
References eez::flow::lvglObjAddStyleHook, and eez::flow::lvglObjRemoveStyleHook.
eez_flow_init_themes()
void eez_flow_init_themes (const char ** themeNames, size_t numThemes, void(* changeColorTheme)(uint32_t themeIndex))
Definition at line 7678 of file eez-flow.cpp.
{
    g_themeNames = themeNames;
    g_numThemes = numThemes;
    g_changeColorTheme = changeColorTheme;
}
References g_changeColorTheme, g_numThemes, and g_themeNames.
eez_flow_is_screen_created()
bool eez_flow_is_screen_created (int16_t screenId)
Definition at line 7749 of file eez-flow.cpp.
{
    int16_t screenIndex = screenId - 1;
    return isScreenCreated(screenIndex);
}
References isScreenCreated().
eez_flow_is_stopped()
bool eez_flow_is_stopped ()
Definition at line 7821 of file eez-flow.cpp.
{
    return eez::flow::isFlowStopped();
}
References eez::flow::isFlowStopped().
eez_flow_pop_screen()
void eez_flow_pop_screen (lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
Definition at line 7735 of file eez-flow.cpp.
{
    if (g_screenStackPosition > 0) {
        g_screenStackPosition--;
        eez::flow::replacePageHook(g_screenStack[g_screenStackPosition], animType, speed, delay);
    }
}
References g_screenStack, g_screenStackPosition, and eez::flow::replacePageHook.
Referenced by eez::flow::executeLVGLComponent().
eez_flow_push_screen()
void eez_flow_push_screen (int16_t screenId, lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
Definition at line 7725 of file eez-flow.cpp.
{
    if (g_screenStackPosition == EEZ_LVGL_SCREEN_STACK_SIZE) {
        for (unsigned i = 1; i < EEZ_LVGL_SCREEN_STACK_SIZE; i++) {
            g_screenStack[i - 1] = g_screenStack[i];
        }
        g_screenStackPosition--;
    }
    g_screenStack[g_screenStackPosition++] = g_currentScreen + 1;
    eez::flow::replacePageHook(screenId, animType, speed, delay);
}
References EEZ_LVGL_SCREEN_STACK_SIZE, g_currentScreen, g_screenStack, g_screenStackPosition, and eez::flow::replacePageHook.
Referenced by eez::flow::executeLVGLComponent().
eez_flow_set_create_screen_func()
void eez_flow_set_create_screen_func (void(* createScreenFunc)(int screenIndex))
Definition at line 7683 of file eez-flow.cpp.
{
    g_createScreenFunc = createScreenFunc;
}
References g_createScreenFunc.
eez_flow_set_delete_screen_func()
void eez_flow_set_delete_screen_func (void(* deleteScreenFunc)(int screenIndex))
Definition at line 7686 of file eez-flow.cpp.
{
    g_deleteScreenFunc = deleteScreenFunc;
}
References g_deleteScreenFunc.
eez_flow_set_screen()
void eez_flow_set_screen (int16_t screenId, lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
Definition at line 7721 of file eez-flow.cpp.
{
    g_screenStackPosition = 0;
    eez::flow::replacePageHook(screenId, animType, speed, delay);
}
References g_screenStackPosition, and eez::flow::replacePageHook.
eez_flow_tick()
void eez_flow_tick ()
Definition at line 7818 of file eez-flow.cpp.
{
    eez::flow::tick();
}
References eez::flow::tick().
Referenced by ui_tick().
eez_linear()
float eez_linear (float x)
Definition at line 1478 of file eez-flow.cpp.
{
    return x;
}
eez_mqtt_connect()
int eez_mqtt_connect (void * handle)
Definition at line 5416 of file eez-flow.cpp.
{
    EEZ_UNUSED(handle);
    return MQTT_ERROR_NOT_IMPLEMENTED;
}
References EEZ_UNUSED.
Referenced by eez::flow::executeMQTTConnectComponent().
eez_mqtt_deinit()
int eez_mqtt_deinit (void * handle)
Definition at line 5412 of file eez-flow.cpp.
{
    EEZ_UNUSED(handle);
    return MQTT_ERROR_NOT_IMPLEMENTED;
}
References EEZ_UNUSED.
Referenced by eez::flow::deleteConnection().
eez_mqtt_disconnect()
int eez_mqtt_disconnect (void * handle)
Definition at line 5420 of file eez-flow.cpp.
{
    EEZ_UNUSED(handle);
    return MQTT_ERROR_NOT_IMPLEMENTED;
}
References EEZ_UNUSED.
Referenced by eez::flow::executeMQTTDisconnectComponent().
eez_mqtt_init()
int eez_mqtt_init (const char * protocol, const char * host, int port, const char * username, const char * password, void ** handle)
Definition at line 5403 of file eez-flow.cpp.
{
    EEZ_UNUSED(protocol);
    EEZ_UNUSED(host);
    EEZ_UNUSED(port);
    EEZ_UNUSED(username);
    EEZ_UNUSED(password);
    EEZ_UNUSED(handle);
    return MQTT_ERROR_NOT_IMPLEMENTED;
}
References EEZ_UNUSED.
Referenced by eez::flow::executeMQTTInitComponent().
eez_mqtt_publish()
int eez_mqtt_publish (void * handle, const char * topic, const char * payload)
Definition at line 5434 of file eez-flow.cpp.
{
    EEZ_UNUSED(handle);
    EEZ_UNUSED(topic);
    EEZ_UNUSED(payload);
    return MQTT_ERROR_NOT_IMPLEMENTED;
}
References EEZ_UNUSED.
Referenced by eez::flow::executeMQTTPublishComponent().
eez_mqtt_subscribe()
int eez_mqtt_subscribe (void * handle, const char * topic)
Definition at line 5424 of file eez-flow.cpp.
{
    EEZ_UNUSED(handle);
    EEZ_UNUSED(topic);
    return MQTT_ERROR_NOT_IMPLEMENTED;
}
References EEZ_UNUSED.
Referenced by eez::flow::executeMQTTSubscribeComponent().
eez_mqtt_unsubscribe()
int eez_mqtt_unsubscribe (void * handle, const char * topic)
Definition at line 5429 of file eez-flow.cpp.
{
    EEZ_UNUSED(handle);
    EEZ_UNUSED(topic);
    return MQTT_ERROR_NOT_IMPLEMENTED;
}
References EEZ_UNUSED.
Referenced by eez::flow::executeMQTTUnsubscribeComponent().
executeLvglAction()
void executeLvglAction (int actionIndex) static
Definition at line 7675 of file eez-flow.cpp.
{
    g_actions[actionIndex](&g_lastLVGLEvent);
}
References g_actions, and g_lastLVGLEvent.
Referenced by eez_flow_init().
flowOnPageLoaded()
void flowOnPageLoaded (unsigned pageIndex)
Definition at line 7838 of file eez-flow.cpp.
{
    eez::flow::getPageFlowState(eez::g_mainAssets, pageIndex);
}
References eez::g_mainAssets, and eez::flow::getPageFlowState().
flowPropagateValue()
void flowPropagateValue (void * flowState, unsigned componentIndex, unsigned outputIndex)
Definition at line 7841 of file eez-flow.cpp.
{
    eez::flow::propagateValue((eez::flow::FlowState *)flowState, componentIndex, outputIndex);
}
References eez::flow::componentIndex, eez::flow::flowState, and eez::flow::propagateValue().
flowPropagateValueInt32()
void flowPropagateValueInt32 (void * flowState, unsigned componentIndex, unsigned outputIndex, int32_t value)
Definition at line 7844 of file eez-flow.cpp.
{
    eez::flow::propagateValue((eez::flow::FlowState *)flowState, componentIndex, outputIndex, eez::Value((int)value, eez::VALUE_TYPE_INT32));
}
References eez::flow::componentIndex, eez::flow::flowState, and eez::flow::propagateValue().
flowPropagateValueLVGLEvent()
void flowPropagateValueLVGLEvent (void * flowState, unsigned componentIndex, unsigned outputIndex, lv_event_t * event)
Definition at line 7850 of file eez-flow.cpp.
{
    lv_event_code_t event_code = lv_event_get_code(event);
    uint32_t code = (uint32_t)event_code;
    void *currentTarget = (void *)lv_event_get_current_target(event);
    void *target = (void *)lv_event_get_target(event);
    void *userDataPointer = lv_event_get_user_data(event);
    int32_t userData = (intptr_t)userDataPointer;
    uint32_t key = 0;
    if (event_code == LV_EVENT_KEY || (event_code == LV_EVENT_VALUE_CHANGED &&
#if LVGL_VERSION_MAJOR >= 9
        lv_obj_check_type((lv_obj_t*)target, &lv_buttonmatrix_class)
#else
        lv_obj_check_type((lv_obj_t*)target, &lv_btnmatrix_class)
#endif
    )) {
        uint32_t *param = (uint32_t *)lv_event_get_param(event);
        key = param ? *param : 0;
    }
    int32_t gestureDir = (int32_t)LV_DIR_NONE;
    if (event_code == LV_EVENT_GESTURE) {
#if LVGL_VERSION_MAJOR >= 9
        lv_indev_wait_release(lv_indev_active());
#else
        lv_indev_wait_release(lv_indev_get_act());
#endif
        gestureDir = (int32_t)lv_indev_get_gesture_dir(
#if LVGL_VERSION_MAJOR >= 9
            lv_indev_active()
#else
            lv_indev_get_act()
#endif
        );
    }
    int32_t rotaryDiff = 0;
#if LVGL_VERSION_MAJOR >= 9
    if (event_code == LV_EVENT_ROTARY) {
        rotaryDiff = lv_event_get_rotary_diff(event);
    }
#endif
    eez::flow::propagateValue(
        (eez::flow::FlowState *)flowState, componentIndex, outputIndex,
        eez::Value::makeLVGLEventRef(
            code, currentTarget, target, userData, key, gestureDir, rotaryDiff, 0xe7f23624
        )
    );
    g_lastLVGLEvent = *event;
    if (event->user_data) {
        g_lastLVGLEvent.user_data = &g_lastLVGLEventUserDataBuffer;
        memcpy(&g_lastLVGLEventUserDataBuffer, event->user_data, sizeof(g_lastLVGLEventUserDataBuffer));
    }
    if (event->param) {
        g_lastLVGLEvent.param = &g_lastLVGLEventParamBuffer;
        memcpy(&g_lastLVGLEventParamBuffer, event->param, sizeof(g_lastLVGLEventParamBuffer));
    }
}
References eez::flow::componentIndex, eez::flow::flowState, g_lastLVGLEvent, g_lastLVGLEventParamBuffer, g_lastLVGLEventUserDataBuffer, and eez::flow::propagateValue().
flowPropagateValueUint32()
void flowPropagateValueUint32 (void * flowState, unsigned componentIndex, unsigned outputIndex, uint32_t value)
Definition at line 7847 of file eez-flow.cpp.
{
    eez::flow::propagateValue((eez::flow::FlowState *)flowState, componentIndex, outputIndex, eez::Value(value, eez::VALUE_TYPE_UINT32));
}
References eez::flow::componentIndex, eez::flow::flowState, and eez::flow::propagateValue().
getFlowState()
void * getFlowState (void * flowState, unsigned userWidgetComponentIndexOrPageIndex)
Definition at line 8011 of file eez-flow.cpp.
{
    if (!flowState) {
        return eez::flow::getPageFlowState(eez::g_mainAssets, userWidgetComponentIndexOrPageIndex);
    }
    auto executionState = (eez::flow::LVGLUserWidgetExecutionState *)((eez::flow::FlowState *)flowState)->componenentExecutionStates[userWidgetComponentIndexOrPageIndex];
    if (!executionState) {
        executionState = eez::flow::createUserWidgetFlowState((eez::flow::FlowState *)flowState, userWidgetComponentIndexOrPageIndex);
    }
    return executionState->flowState;
}
References eez::flow::createUserWidgetFlowState(), eez::flow::flowState, eez::g_mainAssets, and eez::flow::getPageFlowState().
Referenced by create_screen_initial_screen(), and tick_screen_initial_screen().
getLvglGroupByName()
int32_t getLvglGroupByName (const char * name) static
Definition at line 7648 of file eez-flow.cpp.
{
    for (size_t i = 0; i < g_numGroups; i++) {
        if (strcmp(g_groupNames[i], name) == 0) {
            return i;
        }
    }
    return -1;
}
References g_groupNames, and g_numGroups.
Referenced by eez_flow_init().
getLvglGroupFromIndex()
lv_group_t * getLvglGroupFromIndex (int32_t index) static
Definition at line 7626 of file eez-flow.cpp.
{
    if (index >= 0 && (uint32_t)index < g_numGroups) {
        return g_groups[index];
    }
    return 0;
}
References g_groups, and g_numGroups.
Referenced by eez_flow_init().
getLvglImageByName()
const void * getLvglImageByName (const char * name) static
Definition at line 7664 of file eez-flow.cpp.
{
    for (size_t i = 0; i < g_numImages; i++) {
        if (strcmp(g_images[i].name, name) == 0) {
            return g_images[i].img_dsc;
        }
    }
    return 0;
}
References g_images, and g_numImages.
Referenced by eez_flow_init().
getLvglObjectByName()
int32_t getLvglObjectByName (const char * name) static
Definition at line 7640 of file eez-flow.cpp.
{
    for (size_t i = 0; i < g_numObjects; i++) {
        if (strcmp(g_objectNames[i], name) == 0) {
            return i;
        }
    }
    return -1;
}
References g_numObjects, and g_objectNames.
Referenced by eez_flow_init().
getLvglObjectFromIndex()
lv_obj_t * getLvglObjectFromIndex (int32_t index) static
Definition at line 7620 of file eez-flow.cpp.
{
    if (index >= 0 && (uint32_t)index < g_numObjects) {
        return g_objects[index];
    }
    return 0;
}
References g_numObjects, and g_objects.
Referenced by eez_flow_init().
getLvglScreenByName()
int32_t getLvglScreenByName (const char * name) static
Definition at line 7632 of file eez-flow.cpp.
{
    for (size_t i = 0; i < g_numScreens; i++) {
        if (strcmp(g_screenNames[i], name) == 0) {
            return i + 1;
        }
    }
    return -1;
}
References g_numScreens, and g_screenNames.
Referenced by eez_flow_init().
getLvglStyleByName()
int32_t getLvglStyleByName (const char * name) static
Definition at line 7656 of file eez-flow.cpp.
{
    for (size_t i = 0; i < g_numStyles; i++) {
        if (strcmp(g_styleNames[i], name) == 0) {
            return i;
        }
    }
    return -1;
}
References g_numStyles, and g_styleNames.
Referenced by eez_flow_init().
getTimelinePosition()
float getTimelinePosition (void * flowState)
Definition at line 8008 of file eez-flow.cpp.
{
    return ((eez::flow::FlowState *)flowState)->timelinePosition;
}
References eez::flow::flowState.
isScreenCreated()
bool isScreenCreated (int screenIndex) static
Definition at line 7708 of file eez-flow.cpp.
{
    return eez::flow::getLvglObjectFromIndexHook(screenIndex) != 0;
}
References eez::flow::getLvglObjectFromIndexHook.
Referenced by createScreen(), deleteScreen(), and eez_flow_is_screen_created().
lvglSetColorTheme()
void lvglSetColorTheme (const char * themeName) static
Definition at line 7689 of file eez-flow.cpp.
{
    for (uint32_t i = 0; i < g_numThemes; i++) {
        if (strcmp(themeName, g_themeNames[i]) == 0) {
            g_selectedThemeIndex = i;
            if (g_changeColorTheme) {
                g_changeColorTheme(g_selectedThemeIndex);
            }
            return;
        }
    }
}
References g_changeColorTheme, g_numThemes, g_selectedThemeIndex, and g_themeNames.
Referenced by eez_flow_init().
on_screen_unloaded()
void on_screen_unloaded (lv_event_t * e) static
Definition at line 7753 of file eez-flow.cpp.
{
    if (lv_event_get_code(e) == LV_EVENT_SCREEN_UNLOADED) {
        int16_t screenIndex = (int16_t)(lv_uintptr_t)lv_event_get_user_data(e);
        deleteScreen(screenIndex);
    }
}
References deleteScreen().
Referenced by eez_flow_delete_screen_on_unload().
replacePageHook()
void replacePageHook (int16_t pageId, uint32_t animType, uint32_t speed, uint32_t delay) static
Definition at line 7827 of file eez-flow.cpp.
{
    int16_t screenIndex = pageId - 1;
    createScreen(screenIndex);
    lv_obj_t *screen = eez::flow::getLvglObjectFromIndexHook(screenIndex);
    if (!screen) {
        return;
    }
    eez::flow::onPageChanged(g_currentScreen + 1, pageId);
    g_currentScreen = screenIndex;
    lv_scr_load_anim(screen, (lv_scr_load_anim_t)animType, speed, delay, false);
}
References createScreen(), g_currentScreen, eez::flow::getLvglObjectFromIndexHook, and eez::flow::onPageChanged().
Referenced by eez_flow_init().
tick_screen()
void tick_screen (int screen_index)
Definition at line 50 of file screens.c.
{
    tick_screen_funcs[screen_index]();
}
References tick_screen_funcs.
Referenced by ui_tick().
Variable Documentation
c1
const float c1 = 1.70158f static
Definition at line 1473 of file eez-flow.cpp.
Referenced by eez_easeInBack(), eez_easeOutBack(), and utf8ncasecmp().
c2
const float c2 = c1 * 1.525f static
Definition at line 1474 of file eez-flow.cpp.
Referenced by eez_easeInOutBack(), and utf8ncasecmp().
c3
const float c3 = c1 + 1.0f static
Definition at line 1475 of file eez-flow.cpp.
Referenced by eez_easeInBack(), and eez_easeOutBack().
c4
const float c4 = (2 * PI_FLOAT) / 3 static
Definition at line 1476 of file eez-flow.cpp.
Referenced by eez_easeInElastic(), and eez_easeOutElastic().
c5
const float c5 = (2 * PI_FLOAT) / 4.5f static
Definition at line 1477 of file eez-flow.cpp.
Referenced by eez_easeInOutElastic().
g_actions
ActionExecFunc* g_actions static
Definition at line 7612 of file eez-flow.cpp.
Referenced by eez_flow_init(), and executeLvglAction().
g_changeColorTheme
void(* g_changeColorTheme) (uint32_t themeIndex) (uint32_t themeIndex) static
Definition at line 7616 of file eez-flow.cpp.
Referenced by eez_flow_init_themes(), and lvglSetColorTheme().
g_createScreenFunc
void(* g_createScreenFunc) (int screenIndex) (int screenIndex) static
Definition at line 7618 of file eez-flow.cpp.
Referenced by createScreen(), and eez_flow_set_create_screen_func().
g_currentScreen
int16_t g_currentScreen = -1
Definition at line 7613 of file eez-flow.cpp.
Referenced by eez::flow::do_OPERATION_TYPE_FLOW_IS_PAGE_ACTIVE(), eez_flow_get_current_screen(), eez_flow_push_screen(), replacePageHook(), and ui_tick().
g_deleteScreenFunc
void(* g_deleteScreenFunc) (int screenIndex) (int screenIndex) static
Definition at line 7619 of file eez-flow.cpp.
Referenced by deleteScreen(), and eez_flow_set_delete_screen_func().
g_eezFlowLvlgMeterTickIndex
int g_eezFlowLvlgMeterTickIndex = 0
Definition at line 8064 of file eez-flow.cpp.
Referenced by eez::flow::do_OPERATION_TYPE_LVGL_METER_TICK_INDEX().
g_groupNames
const char** g_groupNames static
Definition at line 7606 of file eez-flow.cpp.
Referenced by eez_flow_init_group_names(), and getLvglGroupByName().
g_groups
lv_group_t** g_groups static
Definition at line 7605 of file eez-flow.cpp.
Referenced by eez_flow_init_groups(), and getLvglGroupFromIndex().
g_images
const ext_img_desc_t* g_images static
Definition at line 7610 of file eez-flow.cpp.
Referenced by eez_flow_init(), and getLvglImageByName().
g_lastLVGLEvent
lv_event_t g_lastLVGLEvent static
Definition at line 7674 of file eez-flow.cpp.
Referenced by executeLvglAction(), and flowPropagateValueLVGLEvent().
g_lastLVGLEventParamBuffer
uint8_t g_lastLVGLEventParamBuffer[64]
Definition at line 7673 of file eez-flow.cpp.
Referenced by flowPropagateValueLVGLEvent().
g_lastLVGLEventUserDataBuffer
uint8_t g_lastLVGLEventUserDataBuffer[64]
Definition at line 7672 of file eez-flow.cpp.
Referenced by flowPropagateValueLVGLEvent().
g_numGroups
size_t g_numGroups static
Definition at line 7607 of file eez-flow.cpp.
Referenced by eez_flow_init_groups(), getLvglGroupByName(), and getLvglGroupFromIndex().
g_numImages
size_t g_numImages static
Definition at line 7611 of file eez-flow.cpp.
Referenced by eez_flow_init(), and getLvglImageByName().
g_numObjects
size_t g_numObjects static
Definition at line 7604 of file eez-flow.cpp.
Referenced by eez_flow_init(), getLvglObjectByName(), and getLvglObjectFromIndex().
g_numScreens
size_t g_numScreens static
Definition at line 7601 of file eez-flow.cpp.
Referenced by eez_flow_init_screen_names(), and getLvglScreenByName().
g_numStyles
size_t g_numStyles static
Definition at line 7609 of file eez-flow.cpp.
Referenced by eez_flow_init_style_names(), and getLvglStyleByName().
g_numThemes
size_t g_numThemes static
Definition at line 7615 of file eez-flow.cpp.
Referenced by eez_flow_init_themes(), and lvglSetColorTheme().
g_objectNames
const char** g_objectNames static
Definition at line 7603 of file eez-flow.cpp.
Referenced by eez_flow_init_object_names(), and getLvglObjectByName().
g_objects
lv_obj_t** g_objects static
Definition at line 7602 of file eez-flow.cpp.
Referenced by eez_flow_init(), and getLvglObjectFromIndex().
g_screenNames
const char** g_screenNames static
Definition at line 7600 of file eez-flow.cpp.
Referenced by eez_flow_init_screen_names(), and getLvglScreenByName().
g_screenStack
int16_t g_screenStack[10]
Definition at line 7703 of file eez-flow.cpp.
Referenced by eez_flow_pop_screen(), and eez_flow_push_screen().
g_screenStackPosition
unsigned g_screenStackPosition = 0
Definition at line 7704 of file eez-flow.cpp.
Referenced by eez_flow_pop_screen(), eez_flow_push_screen(), and eez_flow_set_screen().
g_selectedThemeIndex
uint32_t g_selectedThemeIndex static
Definition at line 7617 of file eez-flow.cpp.
Referenced by eez_flow_get_selected_theme_index(), and lvglSetColorTheme().
g_styleNames
const char** g_styleNames static
Definition at line 7608 of file eez-flow.cpp.
Referenced by eez_flow_init_style_names(), and getLvglStyleByName().
g_themeNames
const char** g_themeNames static
Definition at line 7614 of file eez-flow.cpp.
Referenced by eez_flow_init_themes(), and lvglSetColorTheme().
PI_FLOAT
const float PI_FLOAT = (float)3.14159265358979323846 static
Definition at line 1471 of file eez-flow.cpp.
Referenced by eez_easeInOutSine(), eez_easeInSine(), and eez_easeOutSine().
textValue
char textValue[1024] static
Definition at line 7908 of file eez-flow.cpp.
Referenced by _evalStringArrayPropertyAndJoin(), and _evalTextProperty().