EARS-PIO-WSS3-LVGL-001: src/ui/eez-flow.h File Reference
eez-flow.h File Reference
#include <lvgl.h>
#include <Arduino.h>
#include <math.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
Data Structures
struct _native_var_t
struct _ext_img_desc_t
Macros
#define EEZ_FOR_LVGL 1
#define EEZ_FOR_LVGL_LZ4_OPTION 0
#define EEZ_FOR_LVGL_SHA256_OPTION 0
#define EEZ_FLOW_QUEUE_SIZE 1000
#define EEZ_FLOW_EVAL_STACK_SIZE 20
#define EEZ_FOR_LVGL 1
#define LV_LVGL_H_INCLUDE_SIMPLE
#define EEZ_OPTION_GUI 0
#define OPTION_KEYBOARD 0
#define OPTION_MOUSE 0
#define OPTION_KEYPAD 0
#define CUSTOM_VALUE_TYPES
#define EEZ_UNUSED(x)
#define EEZ_FRAMEWORK_CORE_VARS_H
#define EXT_IMG_DESC_T
#define evalTextProperty(flowState, componentIndex, propertyIndex, errorMessage)
#define evalIntegerProperty(flowState, componentIndex, propertyIndex, errorMessage)
#define evalUnsignedIntegerProperty(flowState, componentIndex, propertyIndex, errorMessage)
#define evalBooleanProperty(flowState, componentIndex, propertyIndex, errorMessage)
#define evalStringArrayPropertyAndJoin(flowState, componentIndex, propertyIndex, errorMessage, separator)
#define assignStringProperty(flowState, componentIndex, propertyIndex, value, errorMessage)
#define assignIntegerProperty(flowState, componentIndex, propertyIndex, value, errorMessage)
#define assignBooleanProperty(flowState, componentIndex, propertyIndex, value, errorMessage)
#define SHEREDOM_UTF8_H_INCLUDED
#define utf8_null 0
#define utf8_constexpr14 utf8_weak
#define utf8_constexpr14_impl
Typedefs
typedef struct _native_var_t native_var_t
typedef struct _ext_img_desc_t ext_img_desc_t
typedef void(* ActionExecFunc) (lv_event_t *e)
typedef int32_t utf8_int32_t
typedef char utf8_int8_t
Enumerations
enum NativeVarType {
NATIVE_VAR_TYPE_NONE , NATIVE_VAR_TYPE_INTEGER , NATIVE_VAR_TYPE_BOOLEAN , NATIVE_VAR_TYPE_FLOAT ,
NATIVE_VAR_TYPE_DOUBLE , NATIVE_VAR_TYPE_STRING
}
Functions
void eez_flow_init (const uint8_t *assets, uint32_t assetsSize, lv_obj_t **objects, size_t numObjects, const ext_img_desc_t *images, size_t numImages, ActionExecFunc *actions)
void eez_flow_init_styles (void(*add_style)(lv_obj_t *obj, int32_t styleIndex), void(*remove_style)(lv_obj_t *obj, int32_t styleIndex))
void eez_flow_init_groups (lv_group_t **groups, size_t numGroups)
void eez_flow_init_screen_names (const char **screenNames, size_t numScreens)
void eez_flow_init_object_names (const char **objectNames, size_t numObjects)
void eez_flow_init_group_names (const char **groupNames, size_t numGroups)
void eez_flow_init_style_names (const char **styleNames, size_t numStyles)
void eez_flow_init_themes (const char **themeNames, size_t numThemes, void(*changeColorTheme)(uint32_t themeIndex))
void eez_flow_set_create_screen_func (void(*createScreenFunc)(int screenIndex))
void eez_flow_set_delete_screen_func (void(*deleteScreenFunc)(int screenIndex))
void eez_flow_tick ()
bool eez_flow_is_stopped ()
int16_t eez_flow_get_current_screen ()
void eez_flow_set_screen (int16_t screenId, lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
void eez_flow_push_screen (int16_t screenId, lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
void eez_flow_pop_screen (lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
void eez_flow_create_screen (int16_t screenId)
void eez_flow_delete_screen (int16_t screenId)
bool eez_flow_is_screen_created (int16_t screenId)
void eez_flow_delete_screen_on_unload (int screenIndex)
void flowOnPageLoaded (unsigned pageIndex)
void * getFlowState (void *flowState, unsigned userWidgetComponentIndexOrPageIndex)
void deletePageFlowState (unsigned pageIndex)
void flowPropagateValue (void *flowState, unsigned componentIndex, unsigned outputIndex)
void flowPropagateValueInt32 (void *flowState, unsigned componentIndex, unsigned outputIndex, int32_t value)
void flowPropagateValueUint32 (void *flowState, unsigned componentIndex, unsigned outputIndex, uint32_t value)
void flowPropagateValueLVGLEvent (void *flowState, unsigned componentIndex, unsigned outputIndex, lv_event_t *event)
const char * _evalTextProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *errorMessage, const char *file, int line)
int32_t _evalIntegerProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *errorMessage, const char *file, int line)
uint32_t _evalUnsignedIntegerProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *errorMessage, const char *file, int line)
bool _evalBooleanProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *errorMessage, const char *file, int line)
const char * _evalStringArrayPropertyAndJoin (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *errorMessage, const char *separator, const char *file, int line)
void _assignStringProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, const char *value, const char *errorMessage, const char *file, int line)
void _assignIntegerProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, int32_t value, const char *errorMessage, const char *file, int line)
void _assignBooleanProperty (void *flowState, unsigned componentIndex, unsigned propertyIndex, bool value, const char *errorMessage, const char *file, int line)
float eez_linear (float x)
float eez_easeInQuad (float x)
float eez_easeOutQuad (float x)
float eez_easeInOutQuad (float x)
float eez_easeInCubic (float x)
float eez_easeOutCubic (float x)
float eez_easeInOutCubic (float x)
float eez_easeInQuart (float x)
float eez_easeOutQuart (float x)
float eez_easeInOutQuart (float x)
float eez_easeInQuint (float x)
float eez_easeOutQuint (float x)
float eez_easeInOutQuint (float x)
float eez_easeInSine (float x)
float eez_easeOutSine (float x)
float eez_easeInOutSine (float x)
float eez_easeInExpo (float x)
float eez_easeOutExpo (float x)
float eez_easeInOutExpo (float x)
float eez_easeInCirc (float x)
float eez_easeOutCirc (float x)
float eez_easeInOutCirc (float x)
float eez_easeInBack (float x)
float eez_easeOutBack (float x)
float eez_easeInOutBack (float x)
float eez_easeInElastic (float x)
float eez_easeOutElastic (float x)
float eez_easeInOutElastic (float x)
float eez_easeOutBounce (float x)
float eez_easeInBounce (float x)
float eez_easeInOutBounce (float x)
float getTimelinePosition (void *flowState)
bool compareRollerOptions (lv_roller_t *roller, const char *new_val, const char *cur_val, lv_roller_mode_t mode)
uint32_t eez_flow_get_selected_theme_index ()
utf8_weak utf8_nonnull utf8_pure int utf8casecmp (const utf8_int8_t *src1, const utf8_int8_t *src2)
utf8_nonnull utf8_weak utf8_int8_t * utf8cat (utf8_int8_t *utf8_restrict dst, const utf8_int8_t *utf8_restrict src)
utf8_weak utf8_nonnull utf8_pure utf8_int8_t * utf8chr (const utf8_int8_t *src, utf8_int32_t chr)
utf8_weak utf8_nonnull utf8_pure int utf8cmp (const utf8_int8_t *src1, const utf8_int8_t *src2)
utf8_nonnull utf8_weak utf8_int8_t * utf8cpy (utf8_int8_t *utf8_restrict dst, const utf8_int8_t *utf8_restrict src)
utf8_weak utf8_nonnull utf8_pure size_t utf8cspn (const utf8_int8_t *src, const utf8_int8_t *reject)
utf8_weak utf8_int8_t * utf8dup (const utf8_int8_t *src)
utf8_weak utf8_nonnull utf8_pure size_t utf8len (const utf8_int8_t *str)
utf8_weak utf8_nonnull utf8_pure size_t utf8nlen (const utf8_int8_t *str, size_t n)
utf8_weak utf8_nonnull utf8_pure int utf8ncasecmp (const utf8_int8_t *src1, const utf8_int8_t *src2, size_t n)
utf8_nonnull utf8_weak utf8_int8_t * utf8ncat (utf8_int8_t *utf8_restrict dst, const utf8_int8_t *utf8_restrict src, size_t n)
utf8_weak utf8_nonnull utf8_pure int utf8ncmp (const utf8_int8_t *src1, const utf8_int8_t *src2, size_t n)
utf8_nonnull utf8_weak utf8_int8_t * utf8ncpy (utf8_int8_t *utf8_restrict dst, const utf8_int8_t *utf8_restrict src, size_t n)
utf8_weak utf8_int8_t * utf8ndup (const utf8_int8_t *src, size_t n)
utf8_weak utf8_nonnull utf8_pure utf8_int8_t * utf8pbrk (const utf8_int8_t *str, const utf8_int8_t *accept)
utf8_weak utf8_nonnull utf8_pure utf8_int8_t * utf8rchr (const utf8_int8_t *src, int chr)
utf8_weak utf8_nonnull utf8_pure size_t utf8size (const utf8_int8_t *str)
utf8_weak utf8_nonnull utf8_pure size_t utf8size_lazy (const utf8_int8_t *str)
utf8_weak utf8_nonnull utf8_pure size_t utf8nsize_lazy (const utf8_int8_t *str, size_t n)
utf8_weak utf8_nonnull utf8_pure size_t utf8spn (const utf8_int8_t *src, const utf8_int8_t *accept)
utf8_weak utf8_nonnull utf8_pure utf8_int8_t * utf8str (const utf8_int8_t *haystack, const utf8_int8_t *needle)
utf8_weak utf8_nonnull utf8_pure utf8_int8_t * utf8casestr (const utf8_int8_t *haystack, const utf8_int8_t *needle)
utf8_weak utf8_nonnull utf8_pure utf8_int8_t * utf8valid (const utf8_int8_t *str)
utf8_weak utf8_nonnull utf8_pure utf8_int8_t * utf8nvalid (const utf8_int8_t *str, size_t n)
utf8_nonnull utf8_weak int utf8makevalid (utf8_int8_t *str, const utf8_int32_t replacement)
utf8_weak utf8_nonnull utf8_int8_t * utf8codepoint (const utf8_int8_t *utf8_restrict str, utf8_int32_t *utf8_restrict out_codepoint)
utf8_weak utf8_nonnull size_t utf8codepointcalcsize (const utf8_int8_t *str)
utf8_weak size_t utf8codepointsize (utf8_int32_t chr)
utf8_nonnull utf8_weak utf8_int8_t * utf8catcodepoint (utf8_int8_t *str, utf8_int32_t chr, size_t n)
utf8_weak int utf8islower (utf8_int32_t chr)
utf8_weak int utf8isupper (utf8_int32_t chr)
utf8_nonnull utf8_weak void utf8lwr (utf8_int8_t *utf8_restrict str)
utf8_nonnull utf8_weak void utf8upr (utf8_int8_t *utf8_restrict str)
utf8_weak utf8_int32_t utf8lwrcodepoint (utf8_int32_t cp)
utf8_weak utf8_int32_t utf8uprcodepoint (utf8_int32_t cp)
utf8_weak utf8_nonnull utf8_int8_t * utf8rcodepoint (const utf8_int8_t *utf8_restrict str, utf8_int32_t *utf8_restrict out_codepoint)
utf8_weak utf8_int8_t * utf8dup_ex (const utf8_int8_t *src, utf8_int8_t *(*alloc_func_ptr)(utf8_int8_t *, size_t), utf8_int8_t *user_data)
utf8_weak utf8_int8_t * utf8ndup_ex (const utf8_int8_t *src, size_t n, utf8_int8_t *(*alloc_func_ptr)(utf8_int8_t *, size_t), utf8_int8_t *user_data)
int utf8coll (const utf8_int8_t *src1, const utf8_int8_t *src2)
utf8_int8_t * utf8fry (const utf8_int8_t *str)
Variables
native_var_t native_vars []
int16_t g_currentScreen
int g_eezFlowLvlgMeterTickIndex
Macro Definition Documentation
assignBooleanProperty
#define assignBooleanProperty (flowState, componentIndex, propertyIndex, value, errorMessage)
Value:
_assignBooleanProperty(flowState, componentIndex, propertyIndex, value, errorMessage, __FILE__, __LINE__)
Definition at line 3068 of file eez-flow.h.
assignIntegerProperty
#define assignIntegerProperty (flowState, componentIndex, propertyIndex, value, errorMessage)
Value:
_assignIntegerProperty(flowState, componentIndex, propertyIndex, value, errorMessage, __FILE__, __LINE__)
Definition at line 3067 of file eez-flow.h.
assignStringProperty
#define assignStringProperty (flowState, componentIndex, propertyIndex, value, errorMessage)
Value:
_assignStringProperty(flowState, componentIndex, propertyIndex, value, errorMessage, __FILE__, __LINE__)
Definition at line 3066 of file eez-flow.h.
CUSTOM_VALUE_TYPES
#define CUSTOM_VALUE_TYPES
Definition at line 65 of file eez-flow.h.
EEZ_FLOW_EVAL_STACK_SIZE
#define EEZ_FLOW_EVAL_STACK_SIZE 20
Definition at line 17 of file eez-flow.h.
EEZ_FLOW_QUEUE_SIZE
#define EEZ_FLOW_QUEUE_SIZE 1000
Definition at line 16 of file eez-flow.h.
EEZ_FOR_LVGL [1/2]
#define EEZ_FOR_LVGL 1
Definition at line 13 of file eez-flow.h.
EEZ_FOR_LVGL [2/2]
#define EEZ_FOR_LVGL 1
Definition at line 13 of file eez-flow.h.
EEZ_FOR_LVGL_LZ4_OPTION
#define EEZ_FOR_LVGL_LZ4_OPTION 0
Definition at line 14 of file eez-flow.h.
EEZ_FOR_LVGL_SHA256_OPTION
#define EEZ_FOR_LVGL_SHA256_OPTION 0
Definition at line 15 of file eez-flow.h.
EEZ_FRAMEWORK_CORE_VARS_H
#define EEZ_FRAMEWORK_CORE_VARS_H
Definition at line 2987 of file eez-flow.h.
EEZ_OPTION_GUI
#define EEZ_OPTION_GUI 0
Definition at line 50 of file eez-flow.h.
EEZ_UNUSED
#define EEZ_UNUSED (x)
Value:
(void)(x)
Definition at line 85 of file eez-flow.h.
Referenced by eez::alloc(), eez::allocMemoryForDecompressedAssets(), eez::ARRAY_ASSET_value_to_text(), eez::ARRAY_ASSET_value_type_name(), eez::ARRAY_REF_value_to_text(), eez::ARRAY_REF_value_type_name(), eez::ARRAY_value_to_text(), eez::ARRAY_value_type_name(), eez::BLOB_REF_value_type_name(), eez::BOOLEAN_value_type_name(), eez::compare_ENUM_value(), eez::compare_ERROR_value(), eez::compare_NATIVE_VARIABLE_value(), eez::compare_NULL_value(), eez::DATE_value_type_name(), eez::decompressAssetsData(), eez::flow::deletePageFlowState(), eez::DOUBLE_value_type_name(), eez_flow_init_group_names(), eez_flow_init_object_names(), eez_mqtt_connect(), eez_mqtt_deinit(), eez_mqtt_disconnect(), eez_mqtt_init(), eez_mqtt_publish(), eez_mqtt_subscribe(), eez_mqtt_unsubscribe(), eez::ENUM_value_to_text(), eez::ENUM_value_type_name(), eez::ERROR_value_to_text(), eez::ERROR_value_type_name(), eez::EVENT_value_type_name(), eez::flow::executeEndComponent(), eez::flow::executeLabelInComponent(), eez::flow::executeLvglAction(), eez::FLOAT_value_type_name(), eez::FLOW_OUTPUT_value_to_text(), eez::FLOW_OUTPUT_value_type_name(), eez::flow::getLvglGroupByName(), eez::flow::getLvglGroupFromIndex(), eez::flow::getLvglImageByName(), eez::flow::getLvglObjectByName(), eez::flow::getLvglObjectFromIndex(), eez::flow::getLvglScreenByName(), eez::flow::getLvglStyleByName(), eez::initAllocHeap(), eez::INT16_value_type_name(), eez::INT32_value_type_name(), eez::INT64_value_type_name(), eez::INT8_value_type_name(), eez::IP_ADDRESS_value_type_name(), eez::JSON_value_type_name(), eez::flow::lvglObjAddStyle(), eez::flow::lvglObjRemoveStyle(), eez::flow::lvglSetColorTheme(), eez::NATIVE_VARIABLE_value_to_text(), eez::NATIVE_VARIABLE_value_type_name(), eez::NULL_value_to_text(), eez::NULL_value_type_name(), eez::POINTER_value_to_text(), eez::POINTER_value_type_name(), eez::PROPERTY_REF_value_type_name(), eez::RANGE_value_to_text(), eez::RANGE_value_type_name(), eez::flow::replacePage(), eez::flow::showKeyboard(), eez::flow::showKeypad(), eez::STREAM_value_type_name(), eez::STRING_ASSET_value_type_name(), eez::STRING_REF_value_type_name(), eez::STRING_value_type_name(), eez::TIME_ZONE_value_type_name(), eez::UINT16_value_type_name(), eez::UINT32_value_type_name(), eez::UINT64_value_type_name(), eez::UINT8_value_type_name(), eez::UNDEFINED_value_to_text(), eez::UNDEFINED_value_type_name(), eez::VERSIONED_STRING_value_type_name(), eez::WIDGET_value_type_name(), eez::flow::writeDebuggerBuffer(), eez::YT_DATA_GET_VALUE_FUNCTION_POINTER_value_to_text(), and eez::YT_DATA_GET_VALUE_FUNCTION_POINTER_value_type_name().
evalBooleanProperty
#define evalBooleanProperty (flowState, componentIndex, propertyIndex, errorMessage)
Value:
_evalBooleanProperty(flowState, componentIndex, propertyIndex, errorMessage, __FILE__, __LINE__)
Definition at line 3064 of file eez-flow.h.
evalIntegerProperty
#define evalIntegerProperty (flowState, componentIndex, propertyIndex, errorMessage)
Value:
_evalIntegerProperty(flowState, componentIndex, propertyIndex, errorMessage, __FILE__, __LINE__)
Definition at line 3062 of file eez-flow.h.
evalStringArrayPropertyAndJoin
#define evalStringArrayPropertyAndJoin (flowState, componentIndex, propertyIndex, errorMessage, separator)
Value:
_evalStringArrayPropertyAndJoin(flowState, componentIndex, propertyIndex, errorMessage, separator, __FILE__, __LINE__)
Definition at line 3065 of file eez-flow.h.
evalTextProperty
#define evalTextProperty (flowState, componentIndex, propertyIndex, errorMessage)
Value:
_evalTextProperty(flowState, componentIndex, propertyIndex, errorMessage, __FILE__, __LINE__)
Definition at line 3061 of file eez-flow.h.
evalUnsignedIntegerProperty
#define evalUnsignedIntegerProperty (flowState, componentIndex, propertyIndex, errorMessage)
Value:
_evalUnsignedIntegerProperty(flowState, componentIndex, propertyIndex, errorMessage, __FILE__, __LINE__)
Definition at line 3063 of file eez-flow.h.
EXT_IMG_DESC_T
#define EXT_IMG_DESC_T
Definition at line 3023 of file eez-flow.h.
LV_LVGL_H_INCLUDE_SIMPLE
#define LV_LVGL_H_INCLUDE_SIMPLE
Definition at line 45 of file eez-flow.h.
OPTION_KEYBOARD
#define OPTION_KEYBOARD 0
Definition at line 56 of file eez-flow.h.
OPTION_KEYPAD
#define OPTION_KEYPAD 0
Definition at line 62 of file eez-flow.h.
OPTION_MOUSE
#define OPTION_MOUSE 0
Definition at line 59 of file eez-flow.h.
SHEREDOM_UTF8_H_INCLUDED
#define SHEREDOM_UTF8_H_INCLUDED
Definition at line 3147 of file eez-flow.h.
utf8_constexpr14
#define utf8_constexpr14 utf8_weak
Definition at line 3212 of file eez-flow.h.
utf8_constexpr14_impl
#define utf8_constexpr14_impl
Definition at line 3213 of file eez-flow.h.
Referenced by utf8casecmp(), utf8casestr(), utf8chr(), utf8cmp(), utf8codepointcalcsize(), utf8codepointsize(), utf8coll(), utf8cspn(), utf8fry(), utf8islower(), utf8isupper(), utf8len(), utf8lwrcodepoint(), utf8ncasecmp(), utf8ncmp(), utf8nlen(), utf8nsize_lazy(), utf8nvalid(), utf8pbrk(), utf8rchr(), utf8size(), utf8size_lazy(), utf8spn(), utf8str(), utf8uprcodepoint(), and utf8valid().
utf8_null
#define utf8_null 0
Definition at line 3204 of file eez-flow.h.
Referenced by utf8casestr(), utf8catcodepoint(), utf8dup(), utf8dup_ex(), utf8ndup(), utf8ndup_ex(), utf8nvalid(), utf8pbrk(), utf8rchr(), and utf8str().
Typedef Documentation
ActionExecFunc
typedef void(* ActionExecFunc) (lv_event_t *e)
Definition at line 3029 of file eez-flow.h.
ext_img_desc_t
typedef struct _ext_img_desc_t ext_img_desc_t
native_var_t
typedef struct _native_var_t native_var_t
utf8_int32_t
typedef int32_t utf8_int32_t
Definition at line 3174 of file eez-flow.h.
utf8_int8_t
typedef char utf8_int8_t
Definition at line 3219 of file eez-flow.h.
Enumeration Type Documentation
NativeVarType
enum NativeVarType
Enumerator
NATIVE_VAR_TYPE_NONE
NATIVE_VAR_TYPE_INTEGER
NATIVE_VAR_TYPE_BOOLEAN
NATIVE_VAR_TYPE_FLOAT
NATIVE_VAR_TYPE_DOUBLE
NATIVE_VAR_TYPE_STRING
Definition at line 2988 of file eez-flow.h.
             {
    NATIVE_VAR_TYPE_NONE,
    NATIVE_VAR_TYPE_INTEGER,
    NATIVE_VAR_TYPE_BOOLEAN,
    NATIVE_VAR_TYPE_FLOAT,
    NATIVE_VAR_TYPE_DOUBLE,
    NATIVE_VAR_TYPE_STRING,
} NativeVarType;
Function Documentation
_assignBooleanProperty()
void _assignBooleanProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, bool value, const char * errorMessage, const char * file, int line)
Definition at line 7999 of file eez-flow.cpp.
{
    auto component = ((eez::flow::FlowState *)flowState)->flow->components[componentIndex];
    eez::Value dstValue;
    if (!eez::flow::evalAssignableExpression((eez::flow::FlowState *)flowState, componentIndex, component->properties[propertyIndex]->evalInstructions, dstValue, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return;
    }
    eez::Value srcValue(value, eez::VALUE_TYPE_BOOLEAN);
    eez::flow::assignValue((eez::flow::FlowState *)flowState, componentIndex, dstValue, srcValue);
}
References eez::flow::assignValue(), eez::flow::componentIndex, eez::flow::evalAssignableExpression(), and eez::flow::flowState.
_assignIntegerProperty()
void _assignIntegerProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, int32_t value, const char * errorMessage, const char * file, int line)
Definition at line 7990 of file eez-flow.cpp.
{
    auto component = ((eez::flow::FlowState *)flowState)->flow->components[componentIndex];
    eez::Value dstValue;
    if (!eez::flow::evalAssignableExpression((eez::flow::FlowState *)flowState, componentIndex, component->properties[propertyIndex]->evalInstructions, dstValue, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return;
    }
    eez::Value srcValue((int)value, eez::VALUE_TYPE_INT32);
    eez::flow::assignValue((eez::flow::FlowState *)flowState, componentIndex, dstValue, srcValue);
}
References eez::flow::assignValue(), eez::flow::componentIndex, eez::flow::evalAssignableExpression(), and eez::flow::flowState.
_assignStringProperty()
void _assignStringProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * value, const char * errorMessage, const char * file, int line)
Definition at line 7981 of file eez-flow.cpp.
{
    auto component = ((eez::flow::FlowState *)flowState)->flow->components[componentIndex];
    eez::Value dstValue;
    if (!eez::flow::evalAssignableExpression((eez::flow::FlowState *)flowState, componentIndex, component->properties[propertyIndex]->evalInstructions, dstValue, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return;
    }
    eez::Value srcValue = eez::Value::makeStringRef(value, -1, 0x3eefcf0d);
    eez::flow::assignValue((eez::flow::FlowState *)flowState, componentIndex, dstValue, srcValue);
}
References eez::flow::assignValue(), eez::flow::componentIndex, eez::flow::evalAssignableExpression(), and eez::flow::flowState.
_evalBooleanProperty()
bool _evalBooleanProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * errorMessage, const char * file, int line)
Definition at line 7943 of file eez-flow.cpp.
{
    eez::Value value;
    if (!eez::flow::evalProperty((eez::flow::FlowState *)flowState, componentIndex, propertyIndex, value, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return 0;
    }
    int err;
    bool booleanValue = value.toBool(&err);
    if (err) {
        eez::flow::throwError((eez::flow::FlowState *)flowState, componentIndex, errorMessage);
        return 0;
    }
    return booleanValue;
}
References eez::flow::componentIndex, eez::flow::evalProperty(), eez::flow::flowState, and eez::flow::throwError().
_evalIntegerProperty()
int32_t _evalIntegerProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * errorMessage, const char * file, int line)
Definition at line 7917 of file eez-flow.cpp.
{
    eez::Value value;
    if (!eez::flow::evalProperty((eez::flow::FlowState *)flowState, componentIndex, propertyIndex, value, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return 0;
    }
    int err;
    int32_t intValue = value.toInt32(&err);
    if (err) {
        eez::flow::throwError((eez::flow::FlowState *)flowState, componentIndex, errorMessage);
        return 0;
    }
    return intValue;
}
References eez::flow::componentIndex, eez::flow::evalProperty(), eez::flow::flowState, and eez::flow::throwError().
_evalStringArrayPropertyAndJoin()
const char * _evalStringArrayPropertyAndJoin (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * errorMessage, const char * separator, const char * file, int line)
Definition at line 7956 of file eez-flow.cpp.
{
    eez::Value value;
    if (!eez::flow::evalProperty((eez::flow::FlowState *)flowState, componentIndex, propertyIndex, value, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return "";
    }
    if (value.isArray()) {
        auto array = value.getArray();
        textValue[0] = 0;
        size_t textPosition = 0;
        size_t separatorLength = strlen(separator);
        for (uint32_t elementIndex = 0; elementIndex < array->arraySize; elementIndex++) {
            if (elementIndex > 0) {
                eez::stringAppendString(textValue + textPosition, sizeof(textValue) - textPosition, separator);
                textPosition += separatorLength;
            }
            array->values[elementIndex].toText(textValue + textPosition, sizeof(textValue) - textPosition);
            textPosition = strlen(textValue);
        }
        return textValue;
    } else if (value.isString()) {
        value.toText(textValue, sizeof(textValue));
        return textValue;
    }
    return "";
}
References eez::flow::componentIndex, eez::flow::evalProperty(), eez::flow::flowState, eez::stringAppendString(), and textValue.
_evalTextProperty()
const char * _evalTextProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * errorMessage, const char * file, int line)
Definition at line 7909 of file eez-flow.cpp.
{
    eez::Value value;
    if (!eez::flow::evalProperty((eez::flow::FlowState *)flowState, componentIndex, propertyIndex, value, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return "";
    }
    value.toText(textValue, sizeof(textValue));
    return textValue;
}
References eez::flow::componentIndex, eez::flow::evalProperty(), eez::flow::flowState, and textValue.
_evalUnsignedIntegerProperty()
uint32_t _evalUnsignedIntegerProperty (void * flowState, unsigned componentIndex, unsigned propertyIndex, const char * errorMessage, const char * file, int line)
Definition at line 7930 of file eez-flow.cpp.
{
    eez::Value value;
    if (!eez::flow::evalProperty((eez::flow::FlowState *)flowState, componentIndex, propertyIndex, value, eez::flow::FlowError::Plain(errorMessage, file, line))) {
        return 0;
    }
    int err;
    uint32_t intValue = (uint32_t)value.toInt32(&err);
    if (err) {
        eez::flow::throwError((eez::flow::FlowState *)flowState, componentIndex, errorMessage);
        return 0;
    }
    return intValue;
}
References eez::flow::componentIndex, eez::flow::evalProperty(), eez::flow::flowState, and eez::flow::throwError().
compareRollerOptions()
bool compareRollerOptions (lv_roller_t * roller, const char * new_val, const char * cur_val, lv_roller_mode_t mode)
Definition at line 8024 of file eez-flow.cpp.
{
    if (mode == LV_ROLLER_MODE_NORMAL) {
        return strcmp(new_val, cur_val) != 0;
    }
    auto n = strlen(new_val);
#if LVGL_VERSION_MAJOR >= 9
    size_t numPages = roller->inf_page_cnt;
#else
    size_t numPages = LV_ROLLER_INF_PAGES;
#endif
    for (size_t i = 0; i < numPages * (n + 1); i += n + 1) {
        if (strncmp(new_val, cur_val + i, n) != 0) {
            return true;
        }
    }
    return false;
}
deletePageFlowState()
void deletePageFlowState (unsigned pageIndex)
Definition at line 8021 of file eez-flow.cpp.
{
    eez::flow::deletePageFlowState(eez::g_mainAssets, (int16_t)pageIndex);
}
References eez::flow::deletePageFlowState(), and eez::g_mainAssets.
eez_easeInBack()
float eez_easeInBack (float x)
Definition at line 1552 of file eez-flow.cpp.
{
    return c3 * x * x * x - c1 * x * x;
}
References c1, and c3.
eez_easeInBounce()
float eez_easeInBounce (float x)
Definition at line 1587 of file eez-flow.cpp.
{
    return 1 - eez_easeOutBounce(1 - x);
}
References eez_easeOutBounce().
eez_easeInCirc()
float eez_easeInCirc (float x)
Definition at line 1541 of file eez-flow.cpp.
{
    return 1 - sqrtf(1 - powf(x, 2));
}
eez_easeInCubic()
float eez_easeInCubic (float x)
Definition at line 1490 of file eez-flow.cpp.
{
    return x * x * x;
}
eez_easeInElastic()
float eez_easeInElastic (float x)
Definition at line 1563 of file eez-flow.cpp.
{
    return x == 0
        ? 0
        : x == 1
        ? 1
        : -powf(2, 10 * x - 10) * sinf((x * 10 - 10.75f) * c4);
}
References c4.
eez_easeInExpo()
float eez_easeInExpo (float x)
Definition at line 1526 of file eez-flow.cpp.
{
    return x == 0 ? 0 : powf(2, 10 * x - 10);
}
eez_easeInOutBack()
float eez_easeInOutBack (float x)
Definition at line 1558 of file eez-flow.cpp.
{
    return x < 0.5
        ? (powf(2 * x, 2) * ((c2 + 1) * 2 * x - c2)) / 2
        : (powf(2 * x - 2, 2) * ((c2 + 1) * (x * 2 - 2) + c2) + 2) / 2;
}
References c2.
eez_easeInOutBounce()
float eez_easeInOutBounce (float x)
Definition at line 1606 of file eez-flow.cpp.
{
    return x < 0.5
        ? (1 - eez_easeOutBounce(1 - 2 * x)) / 2
        : (1 + eez_easeOutBounce(2 * x - 1)) / 2;
}
References eez_easeOutBounce().
eez_easeInOutCirc()
float eez_easeInOutCirc (float x)
Definition at line 1547 of file eez-flow.cpp.
{
    return x < 0.5
        ? (1 - sqrtf(1 - pow(2 * x, 2))) / 2
        : (sqrtf(1 - powf(-2 * x + 2, 2)) + 1) / 2;
}
eez_easeInOutCubic()
float eez_easeInOutCubic (float x)
Definition at line 1496 of file eez-flow.cpp.
{
    return x < 0.5f ? 4 * x * x * x : 1 - powf(-2 * x + 2, 3) / 2;
}
eez_easeInOutElastic()
float eez_easeInOutElastic (float x)
Definition at line 1577 of file eez-flow.cpp.
{
    return x == 0
        ? 0
        : x == 1
        ? 1
        : x < 0.5
        ? -(powf(2, 20 * x - 10) * sinf((20 * x - 11.125f) * c5)) / 2
        : (powf(2, -20 * x + 10) * sinf((20 * x - 11.125f) * c5)) / 2 + 1;
}
References c5.
eez_easeInOutExpo()
float eez_easeInOutExpo (float x)
Definition at line 1532 of file eez-flow.cpp.
{
    return x == 0
        ? 0
        : x == 1
        ? 1
        : x < 0.5
        ? powf(2, 20 * x - 10) / 2
        : (2 - powf(2, -20 * x + 10)) / 2;
}
eez_easeInOutQuad()
float eez_easeInOutQuad (float x)
Definition at line 1487 of file eez-flow.cpp.
{
    return x < 0.5f ? 2 * x * x : 1 - powf(-2 * x + 2, 2) / 2;
}
eez_easeInOutQuart()
float eez_easeInOutQuart (float x)
Definition at line 1505 of file eez-flow.cpp.
{
    return x < 0.5 ? 8 * x * x * x * x : 1 - powf(-2 * x + 2, 4) / 2;
}
eez_easeInOutQuint()
float eez_easeInOutQuint (float x)
Definition at line 1514 of file eez-flow.cpp.
{
    return x < 0.5f ? 16 * x * x * x * x * x : 1 - powf(-2 * x + 2, 5) / 2;
}
eez_easeInOutSine()
float eez_easeInOutSine (float x)
Definition at line 1523 of file eez-flow.cpp.
{
    return -(cosf(PI_FLOAT * x) - 1) / 2;
}
References PI_FLOAT.
eez_easeInQuad()
float eez_easeInQuad (float x)
Definition at line 1481 of file eez-flow.cpp.
{
    return x * x;
}
eez_easeInQuart()
float eez_easeInQuart (float x)
Definition at line 1499 of file eez-flow.cpp.
{
    return x * x * x * x;
}
eez_easeInQuint()
float eez_easeInQuint (float x)
Definition at line 1508 of file eez-flow.cpp.
{
    return x * x * x * x * x;
}
eez_easeInSine()
float eez_easeInSine (float x)
Definition at line 1517 of file eez-flow.cpp.
{
    return 1 - cosf((x * PI_FLOAT) / 2);
}
References PI_FLOAT.
eez_easeOutBack()
float eez_easeOutBack (float x)
Definition at line 1555 of file eez-flow.cpp.
{
    return 1 + c3 * powf(x - 1, 3) + c1 * powf(x - 1, 2);
}
References c1, and c3.
eez_easeOutBounce()
float eez_easeOutBounce (float x)
Definition at line 1590 of file eez-flow.cpp.
{
    static const float n1 = 7.5625f;
    static const float d1 = 2.75f;
    if (x < 1 / d1) {
        return n1 * x * x;
    } else if (x < 2 / d1) {
        x -= 1.5f / d1;
        return n1 * x * x + 0.75f;
    } else if (x < 2.5f / d1) {
        x -= 2.25f / d1;
        return n1 * x * x + 0.9375f;
    } else {
        x -= 2.625f / d1;
        return n1 * x * x + 0.984375f;
    }
};
Referenced by eez_easeInBounce(), and eez_easeInOutBounce().
eez_easeOutCirc()
float eez_easeOutCirc (float x)
Definition at line 1544 of file eez-flow.cpp.
{
    return sqrtf(1 - powf(x - 1, 2));
}
eez_easeOutCubic()
float eez_easeOutCubic (float x)
Definition at line 1493 of file eez-flow.cpp.
{
    return 1 - pow(1 - x, 3);
}
eez_easeOutElastic()
float eez_easeOutElastic (float x)
Definition at line 1570 of file eez-flow.cpp.
{
    return x == 0
        ? 0
        : x == 1
        ? 1
        : powf(2, -10 * x) * sinf((x * 10 - 0.75f) * c4) + 1;
}
References c4.
eez_easeOutExpo()
float eez_easeOutExpo (float x)
Definition at line 1529 of file eez-flow.cpp.
{
    return x == 1 ? 1 : 1 - powf(2, -10 * x);
}
eez_easeOutQuad()
float eez_easeOutQuad (float x)
Definition at line 1484 of file eez-flow.cpp.
{
    return 1 - (1 - x) * (1 - x);
}
eez_easeOutQuart()
float eez_easeOutQuart (float x)
Definition at line 1502 of file eez-flow.cpp.
{
    return 1 - powf(1 - x, 4);
}
eez_easeOutQuint()
float eez_easeOutQuint (float x)
Definition at line 1511 of file eez-flow.cpp.
{
    return 1 - powf(1 - x, 5);
}
eez_easeOutSine()
float eez_easeOutSine (float x)
Definition at line 1520 of file eez-flow.cpp.
{
    return sinf((x * PI_FLOAT) / 2);
}
References PI_FLOAT.
eez_flow_create_screen()
void eez_flow_create_screen (int16_t screenId)
Definition at line 7741 of file eez-flow.cpp.
{
    int16_t screenIndex = screenId - 1;
    createScreen(screenIndex);
}
References createScreen().
eez_flow_delete_screen()
void eez_flow_delete_screen (int16_t screenId)
Definition at line 7745 of file eez-flow.cpp.
{
    int16_t screenIndex = screenId - 1;
    deleteScreen(screenIndex);
}
References deleteScreen().
eez_flow_delete_screen_on_unload()
void eez_flow_delete_screen_on_unload (int screenIndex)
Definition at line 7759 of file eez-flow.cpp.
{
    lv_obj_add_event_cb(
        eez::flow::getLvglObjectFromIndexHook(screenIndex),
        on_screen_unloaded,
        LV_EVENT_SCREEN_UNLOADED,
        (void*)(lv_uintptr_t)(screenIndex)
    );
}
References eez::flow::getLvglObjectFromIndexHook, and on_screen_unloaded().
eez_flow_get_current_screen()
int16_t eez_flow_get_current_screen ()
Definition at line 7705 of file eez-flow.cpp.
{
    return g_currentScreen + 1;
}
References g_currentScreen.
eez_flow_get_selected_theme_index()
uint32_t eez_flow_get_selected_theme_index ()
Definition at line 8041 of file eez-flow.cpp.
{
    return g_selectedThemeIndex;
}
References g_selectedThemeIndex.
eez_flow_init()
void eez_flow_init (const uint8_t * assets, uint32_t assetsSize, lv_obj_t ** objects, size_t numObjects, const ext_img_desc_t * images, size_t numImages, ActionExecFunc * actions)
Definition at line 7767 of file eez-flow.cpp.
{
    g_objects = objects;
    g_numObjects = numObjects;
    g_images = images;
    g_numImages = numImages;
    g_actions = actions;
    eez::initAssetsMemory();
    eez::loadMainAssets(assets, assetsSize);
    eez::initOtherMemory();
    eez::initAllocHeap(eez::ALLOC_BUFFER, eez::ALLOC_BUFFER_SIZE);
    eez::flow::replacePageHook = replacePageHook;
    eez::flow::getLvglObjectFromIndexHook = getLvglObjectFromIndex;
    eez::flow::getLvglScreenByNameHook = getLvglScreenByName;
    eez::flow::getLvglObjectByNameHook = getLvglObjectByName;
    eez::flow::getLvglGroupByNameHook = getLvglGroupByName;
    eez::flow::getLvglStyleByNameHook = getLvglStyleByName;
    eez::flow::getLvglImageByNameHook = getLvglImageByName;
    eez::flow::executeLvglActionHook = executeLvglAction;
    eez::flow::getLvglGroupFromIndexHook = getLvglGroupFromIndex;
    eez::flow::lvglSetColorThemeHook = lvglSetColorTheme;
    eez::flow::start(eez::g_mainAssets);
    create_screens();
    replacePageHook(1, 0, 0, 0);
}
References actions, eez::ALLOC_BUFFER, eez::ALLOC_BUFFER_SIZE, assets, create_screens(), executeLvglAction(), eez::flow::executeLvglActionHook, g_actions, g_images, eez::g_mainAssets, g_numImages, g_numObjects, g_objects, getLvglGroupByName(), eez::flow::getLvglGroupByNameHook, getLvglGroupFromIndex(), eez::flow::getLvglGroupFromIndexHook, getLvglImageByName(), eez::flow::getLvglImageByNameHook, getLvglObjectByName(), eez::flow::getLvglObjectByNameHook, getLvglObjectFromIndex(), eez::flow::getLvglObjectFromIndexHook, getLvglScreenByName(), eez::flow::getLvglScreenByNameHook, getLvglStyleByName(), eez::flow::getLvglStyleByNameHook, images, eez::initAllocHeap(), eez::initAssetsMemory(), eez::initOtherMemory(), eez::loadMainAssets(), lvglSetColorTheme(), eez::flow::lvglSetColorThemeHook, objects, eez::flow::replacePageHook, replacePageHook(), and eez::flow::start().
Referenced by ui_init().
eez_flow_init_group_names()
void eez_flow_init_group_names (const char ** groupNames, size_t numGroups)
Definition at line 7810 of file eez-flow.cpp.
{
    g_groupNames = groupNames;
    EEZ_UNUSED(numGroups);
}
References EEZ_UNUSED, and g_groupNames.
eez_flow_init_groups()
void eez_flow_init_groups (lv_group_t ** groups, size_t numGroups)
Definition at line 7798 of file eez-flow.cpp.
{
    g_groups = groups;
    g_numGroups = numGroups;
}
References g_groups, and g_numGroups.
eez_flow_init_object_names()
void eez_flow_init_object_names (const char ** objectNames, size_t numObjects)
Definition at line 7806 of file eez-flow.cpp.
{
    g_objectNames = objectNames;
    EEZ_UNUSED(numObjects);
}
References EEZ_UNUSED, and g_objectNames.
Referenced by create_screens().
eez_flow_init_screen_names()
void eez_flow_init_screen_names (const char ** screenNames, size_t numScreens)
Definition at line 7802 of file eez-flow.cpp.
{
    g_screenNames = screenNames;
    g_numScreens = numScreens;
}
References g_numScreens, and g_screenNames.
Referenced by create_screens().
eez_flow_init_style_names()
void eez_flow_init_style_names (const char ** styleNames, size_t numStyles)
Definition at line 7814 of file eez-flow.cpp.
{
    g_styleNames = styleNames;
    g_numStyles = numStyles;
}
References g_numStyles, and g_styleNames.
eez_flow_init_styles()
void eez_flow_init_styles (void(* add_style)(lv_obj_t *obj, int32_t styleIndex), void(* remove_style)(lv_obj_t *obj, int32_t styleIndex))
Definition at line 7791 of file eez-flow.cpp.
  {
    eez::flow::lvglObjAddStyleHook = add_style;
    eez::flow::lvglObjRemoveStyleHook = remove_style;
}
References eez::flow::lvglObjAddStyleHook, and eez::flow::lvglObjRemoveStyleHook.
eez_flow_init_themes()
void eez_flow_init_themes (const char ** themeNames, size_t numThemes, void(* changeColorTheme)(uint32_t themeIndex))
Definition at line 7678 of file eez-flow.cpp.
{
    g_themeNames = themeNames;
    g_numThemes = numThemes;
    g_changeColorTheme = changeColorTheme;
}
References g_changeColorTheme, g_numThemes, and g_themeNames.
eez_flow_is_screen_created()
bool eez_flow_is_screen_created (int16_t screenId)
Definition at line 7749 of file eez-flow.cpp.
{
    int16_t screenIndex = screenId - 1;
    return isScreenCreated(screenIndex);
}
References isScreenCreated().
eez_flow_is_stopped()
bool eez_flow_is_stopped ()
Definition at line 7821 of file eez-flow.cpp.
{
    return eez::flow::isFlowStopped();
}
References eez::flow::isFlowStopped().
eez_flow_pop_screen()
void eez_flow_pop_screen (lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
Definition at line 7735 of file eez-flow.cpp.
{
    if (g_screenStackPosition > 0) {
        g_screenStackPosition--;
        eez::flow::replacePageHook(g_screenStack[g_screenStackPosition], animType, speed, delay);
    }
}
References g_screenStack, g_screenStackPosition, and eez::flow::replacePageHook.
Referenced by eez::flow::executeLVGLComponent().
eez_flow_push_screen()
void eez_flow_push_screen (int16_t screenId, lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
Definition at line 7725 of file eez-flow.cpp.
{
    if (g_screenStackPosition == EEZ_LVGL_SCREEN_STACK_SIZE) {
        for (unsigned i = 1; i < EEZ_LVGL_SCREEN_STACK_SIZE; i++) {
            g_screenStack[i - 1] = g_screenStack[i];
        }
        g_screenStackPosition--;
    }
    g_screenStack[g_screenStackPosition++] = g_currentScreen + 1;
    eez::flow::replacePageHook(screenId, animType, speed, delay);
}
References EEZ_LVGL_SCREEN_STACK_SIZE, g_currentScreen, g_screenStack, g_screenStackPosition, and eez::flow::replacePageHook.
Referenced by eez::flow::executeLVGLComponent().
eez_flow_set_create_screen_func()
void eez_flow_set_create_screen_func (void(* createScreenFunc)(int screenIndex))
Definition at line 7683 of file eez-flow.cpp.
{
    g_createScreenFunc = createScreenFunc;
}
References g_createScreenFunc.
eez_flow_set_delete_screen_func()
void eez_flow_set_delete_screen_func (void(* deleteScreenFunc)(int screenIndex))
Definition at line 7686 of file eez-flow.cpp.
{
    g_deleteScreenFunc = deleteScreenFunc;
}
References g_deleteScreenFunc.
eez_flow_set_screen()
void eez_flow_set_screen (int16_t screenId, lv_scr_load_anim_t animType, uint32_t speed, uint32_t delay)
Definition at line 7721 of file eez-flow.cpp.
{
    g_screenStackPosition = 0;
    eez::flow::replacePageHook(screenId, animType, speed, delay);
}
References g_screenStackPosition, and eez::flow::replacePageHook.
eez_flow_tick()
void eez_flow_tick ()
Definition at line 7818 of file eez-flow.cpp.
{
    eez::flow::tick();
}
References eez::flow::tick().
Referenced by ui_tick().
eez_linear()
float eez_linear (float x)
Definition at line 1478 of file eez-flow.cpp.
{
    return x;
}
flowOnPageLoaded()
void flowOnPageLoaded (unsigned pageIndex)
Definition at line 7838 of file eez-flow.cpp.
{
    eez::flow::getPageFlowState(eez::g_mainAssets, pageIndex);
}
References eez::g_mainAssets, and eez::flow::getPageFlowState().
flowPropagateValue()
void flowPropagateValue (void * flowState, unsigned componentIndex, unsigned outputIndex)
Definition at line 7841 of file eez-flow.cpp.
{
    eez::flow::propagateValue((eez::flow::FlowState *)flowState, componentIndex, outputIndex);
}
References eez::flow::componentIndex, eez::flow::flowState, and eez::flow::propagateValue().
flowPropagateValueInt32()
void flowPropagateValueInt32 (void * flowState, unsigned componentIndex, unsigned outputIndex, int32_t value)
Definition at line 7844 of file eez-flow.cpp.
{
    eez::flow::propagateValue((eez::flow::FlowState *)flowState, componentIndex, outputIndex, eez::Value((int)value, eez::VALUE_TYPE_INT32));
}
References eez::flow::componentIndex, eez::flow::flowState, and eez::flow::propagateValue().
flowPropagateValueLVGLEvent()
void flowPropagateValueLVGLEvent (void * flowState, unsigned componentIndex, unsigned outputIndex, lv_event_t * event)
Definition at line 7850 of file eez-flow.cpp.
{
    lv_event_code_t event_code = lv_event_get_code(event);
    uint32_t code = (uint32_t)event_code;
    void *currentTarget = (void *)lv_event_get_current_target(event);
    void *target = (void *)lv_event_get_target(event);
    void *userDataPointer = lv_event_get_user_data(event);
    int32_t userData = (intptr_t)userDataPointer;
    uint32_t key = 0;
    if (event_code == LV_EVENT_KEY || (event_code == LV_EVENT_VALUE_CHANGED &&
#if LVGL_VERSION_MAJOR >= 9
        lv_obj_check_type((lv_obj_t*)target, &lv_buttonmatrix_class)
#else
        lv_obj_check_type((lv_obj_t*)target, &lv_btnmatrix_class)
#endif
    )) {
        uint32_t *param = (uint32_t *)lv_event_get_param(event);
        key = param ? *param : 0;
    }
    int32_t gestureDir = (int32_t)LV_DIR_NONE;
    if (event_code == LV_EVENT_GESTURE) {
#if LVGL_VERSION_MAJOR >= 9
        lv_indev_wait_release(lv_indev_active());
#else
        lv_indev_wait_release(lv_indev_get_act());
#endif
        gestureDir = (int32_t)lv_indev_get_gesture_dir(
#if LVGL_VERSION_MAJOR >= 9
            lv_indev_active()
#else
            lv_indev_get_act()
#endif
        );
    }
    int32_t rotaryDiff = 0;
#if LVGL_VERSION_MAJOR >= 9
    if (event_code == LV_EVENT_ROTARY) {
        rotaryDiff = lv_event_get_rotary_diff(event);
    }
#endif
    eez::flow::propagateValue(
        (eez::flow::FlowState *)flowState, componentIndex, outputIndex,
        eez::Value::makeLVGLEventRef(
            code, currentTarget, target, userData, key, gestureDir, rotaryDiff, 0xe7f23624
        )
    );
    g_lastLVGLEvent = *event;
    if (event->user_data) {
        g_lastLVGLEvent.user_data = &g_lastLVGLEventUserDataBuffer;
        memcpy(&g_lastLVGLEventUserDataBuffer, event->user_data, sizeof(g_lastLVGLEventUserDataBuffer));
    }
    if (event->param) {
        g_lastLVGLEvent.param = &g_lastLVGLEventParamBuffer;
        memcpy(&g_lastLVGLEventParamBuffer, event->param, sizeof(g_lastLVGLEventParamBuffer));
    }
}
References eez::flow::componentIndex, eez::flow::flowState, g_lastLVGLEvent, g_lastLVGLEventParamBuffer, g_lastLVGLEventUserDataBuffer, and eez::flow::propagateValue().
flowPropagateValueUint32()
void flowPropagateValueUint32 (void * flowState, unsigned componentIndex, unsigned outputIndex, uint32_t value)
Definition at line 7847 of file eez-flow.cpp.
{
    eez::flow::propagateValue((eez::flow::FlowState *)flowState, componentIndex, outputIndex, eez::Value(value, eez::VALUE_TYPE_UINT32));
}
References eez::flow::componentIndex, eez::flow::flowState, and eez::flow::propagateValue().
getFlowState()
void * getFlowState (void * flowState, unsigned userWidgetComponentIndexOrPageIndex)
Definition at line 8011 of file eez-flow.cpp.
{
    if (!flowState) {
        return eez::flow::getPageFlowState(eez::g_mainAssets, userWidgetComponentIndexOrPageIndex);
    }
    auto executionState = (eez::flow::LVGLUserWidgetExecutionState *)((eez::flow::FlowState *)flowState)->componenentExecutionStates[userWidgetComponentIndexOrPageIndex];
    if (!executionState) {
        executionState = eez::flow::createUserWidgetFlowState((eez::flow::FlowState *)flowState, userWidgetComponentIndexOrPageIndex);
    }
    return executionState->flowState;
}
References eez::flow::createUserWidgetFlowState(), eez::flow::flowState, eez::g_mainAssets, and eez::flow::getPageFlowState().
Referenced by create_screen_initial_screen(), and tick_screen_initial_screen().
getTimelinePosition()
float getTimelinePosition (void * flowState)
Definition at line 8008 of file eez-flow.cpp.
{
    return ((eez::flow::FlowState *)flowState)->timelinePosition;
}
References eez::flow::flowState.
utf8casecmp()
int utf8casecmp (const utf8_int8_t * src1, const utf8_int8_t * src2)
Definition at line 3411 of file eez-flow.h.
{
  utf8_int32_t src1_lwr_cp = 0, src2_lwr_cp = 0, src1_upr_cp = 0,
               src2_upr_cp = 0, src1_orig_cp = 0, src2_orig_cp = 0;
  for (;;) {
    src1 = utf8codepoint(src1, &src1_orig_cp);
    src2 = utf8codepoint(src2, &src2_orig_cp);
    /* lower the srcs if required */
    src1_lwr_cp = utf8lwrcodepoint(src1_orig_cp);
    src2_lwr_cp = utf8lwrcodepoint(src2_orig_cp);
    /* lower the srcs if required */
    src1_upr_cp = utf8uprcodepoint(src1_orig_cp);
    src2_upr_cp = utf8uprcodepoint(src2_orig_cp);
    /* check if the lowered codepoints match */
    if ((0 == src1_orig_cp) && (0 == src2_orig_cp)) {
      return 0;
    } else if ((src1_lwr_cp == src2_lwr_cp) || (src1_upr_cp == src2_upr_cp)) {
      continue;
    }
    /* if they don't match, then we return the difference between the characters
     */
    return src1_lwr_cp - src2_lwr_cp;
  }
}
References utf8_constexpr14_impl, utf8codepoint(), utf8lwrcodepoint(), and utf8uprcodepoint().
Referenced by eez::flow::elementCompare().
utf8casestr()
utf8_int8_t * utf8casestr (const utf8_int8_t * haystack, const utf8_int8_t * needle)
Definition at line 4073 of file eez-flow.h.
{
  /* if needle has no utf8 codepoints before the null terminating
   * byte then return haystack */
  if ('\0' == *needle) {
    return (utf8_int8_t *)haystack;
  }
  for (;;) {
    const utf8_int8_t *maybeMatch = haystack;
    const utf8_int8_t *n = needle;
    utf8_int32_t h_cp = 0, n_cp = 0;
    /* Get the next code point and track it */
    const utf8_int8_t *nextH = haystack = utf8codepoint(haystack, &h_cp);
    n = utf8codepoint(n, &n_cp);
    while ((0 != h_cp) && (0 != n_cp)) {
      h_cp = utf8lwrcodepoint(h_cp);
      n_cp = utf8lwrcodepoint(n_cp);
      /* if we find a mismatch, bail out! */
      if (h_cp != n_cp) {
        break;
      }
      haystack = utf8codepoint(haystack, &h_cp);
      n = utf8codepoint(n, &n_cp);
    }
    if (0 == n_cp) {
      /* we found the whole utf8 string for needle in haystack at
       * maybeMatch, so return it */
      return (utf8_int8_t *)maybeMatch;
    }
    if (0 == h_cp) {
      /* no match */
      return utf8_null;
    }
    /* Roll back to the next code point in the haystack to test */
    haystack = nextH;
  }
}
References utf8_constexpr14_impl, utf8_null, utf8codepoint(), and utf8lwrcodepoint().
utf8cat()
utf8_int8_t * utf8cat (utf8_int8_t *utf8_restrict dst, const utf8_int8_t *utf8_restrict src)
Definition at line 3441 of file eez-flow.h.
{
  utf8_int8_t *d = dst;
  /* find the null terminating byte in dst */
  while ('\0' != *d) {
    d++;
  }
  /* overwriting the null terminating byte in dst, append src byte-by-byte */
  while ('\0' != *src) {
    *d++ = *src++;
  }
  /* write out a new null terminating byte into dst */
  *d = '\0';
  return dst;
}
utf8catcodepoint()
utf8_int8_t * utf8catcodepoint (utf8_int8_t * str, utf8_int32_t chr, size_t n)
Definition at line 4341 of file eez-flow.h.
{
  if (0 == ((utf8_int32_t)0xffffff80 & chr)) {
    /* 1-byte/7-bit ascii
     * (0b0xxxxxxx) */
    if (n < 1) {
      return utf8_null;
    }
    str[0] = (utf8_int8_t)chr;
    str += 1;
  } else if (0 == ((utf8_int32_t)0xfffff800 & chr)) {
    /* 2-byte/11-bit utf8 code point
     * (0b110xxxxx 0b10xxxxxx) */
    if (n < 2) {
      return utf8_null;
    }
    str[0] = (utf8_int8_t)(0xc0 | (utf8_int8_t)((chr >> 6) & 0x1f));
    str[1] = (utf8_int8_t)(0x80 | (utf8_int8_t)(chr & 0x3f));
    str += 2;
  } else if (0 == ((utf8_int32_t)0xffff0000 & chr)) {
    /* 3-byte/16-bit utf8 code point
     * (0b1110xxxx 0b10xxxxxx 0b10xxxxxx) */
    if (n < 3) {
      return utf8_null;
    }
    str[0] = (utf8_int8_t)(0xe0 | (utf8_int8_t)((chr >> 12) & 0x0f));
    str[1] = (utf8_int8_t)(0x80 | (utf8_int8_t)((chr >> 6) & 0x3f));
    str[2] = (utf8_int8_t)(0x80 | (utf8_int8_t)(chr & 0x3f));
    str += 3;
  } else { /* if (0 == ((int)0xffe00000 & chr)) { */
    /* 4-byte/21-bit utf8 code point
     * (0b11110xxx 0b10xxxxxx 0b10xxxxxx 0b10xxxxxx) */
    if (n < 4) {
      return utf8_null;
    }
    str[0] = (utf8_int8_t)(0xf0 | (utf8_int8_t)((chr >> 18) & 0x07));
    str[1] = (utf8_int8_t)(0x80 | (utf8_int8_t)((chr >> 12) & 0x3f));
    str[2] = (utf8_int8_t)(0x80 | (utf8_int8_t)((chr >> 6) & 0x3f));
    str[3] = (utf8_int8_t)(0x80 | (utf8_int8_t)(chr & 0x3f));
    str += 4;
  }
  return str;
}
References utf8_null.
Referenced by eez::flow::do_OPERATION_TYPE_STRING_FROM_CODE_POINT(), utf8lwr(), utf8makevalid(), and utf8upr().
utf8chr()
utf8_int8_t * utf8chr (const utf8_int8_t * src, utf8_int32_t chr)
Definition at line 3460 of file eez-flow.h.
{
  utf8_int8_t c[5] = {'\0', '\0', '\0', '\0', '\0'};
  if (0 == chr) {
    /* being asked to return position of null terminating byte, so
     * just run s to the end, and return! */
    while ('\0' != *src) {
      src++;
    }
    return (utf8_int8_t *)src;
  } else if (0 == ((utf8_int32_t)0xffffff80 & chr)) {
    /* 1-byte/7-bit ascii
     * (0b0xxxxxxx) */
    c[0] = (utf8_int8_t)chr;
  } else if (0 == ((utf8_int32_t)0xfffff800 & chr)) {
    /* 2-byte/11-bit utf8 code point
     * (0b110xxxxx 0b10xxxxxx) */
    c[0] = (utf8_int8_t)(0xc0 | (utf8_int8_t)(chr >> 6));
    c[1] = (utf8_int8_t)(0x80 | (utf8_int8_t)(chr & 0x3f));
  } else if (0 == ((utf8_int32_t)0xffff0000 & chr)) {
    /* 3-byte/16-bit utf8 code point
     * (0b1110xxxx 0b10xxxxxx 0b10xxxxxx) */
    c[0] = (utf8_int8_t)(0xe0 | (utf8_int8_t)(chr >> 12));
    c[1] = (utf8_int8_t)(0x80 | (utf8_int8_t)((chr >> 6) & 0x3f));
    c[2] = (utf8_int8_t)(0x80 | (utf8_int8_t)(chr & 0x3f));
  } else { /* if (0 == ((int)0xffe00000 & chr)) { */
    /* 4-byte/21-bit utf8 code point
     * (0b11110xxx 0b10xxxxxx 0b10xxxxxx 0b10xxxxxx) */
    c[0] = (utf8_int8_t)(0xf0 | (utf8_int8_t)(chr >> 18));
    c[1] = (utf8_int8_t)(0x80 | (utf8_int8_t)((chr >> 12) & 0x3f));
    c[2] = (utf8_int8_t)(0x80 | (utf8_int8_t)((chr >> 6) & 0x3f));
    c[3] = (utf8_int8_t)(0x80 | (utf8_int8_t)(chr & 0x3f));
  }
  /* we've made c into a 2 utf8 codepoint string, one for the chr we are
   * seeking, another for the null terminating byte. Now use utf8str to
   * search */
  return utf8str(src, c);
}
References utf8_constexpr14_impl, and utf8str().
utf8cmp()
int utf8cmp (const utf8_int8_t * src1, const utf8_int8_t * src2)
Definition at line 3501 of file eez-flow.h.
{
  while (('\0' != *src1) || ('\0' != *src2)) {
    if (*src1 < *src2) {
      return -1;
    } else if (*src1 > *src2) {
      return 1;
    }
    src1++;
    src2++;
  }
  /* both utf8 strings matched */
  return 0;
}
References utf8_constexpr14_impl.
Referenced by eez::flow::elementCompare().
utf8codepoint()
utf8_int8_t * utf8codepoint (const utf8_int8_t *utf8_restrict str, utf8_int32_t *utf8_restrict out_codepoint)
Definition at line 4288 of file eez-flow.h.
{
  if (0xf0 == (0xf8 & str[0])) {
    /* 4 byte utf8 codepoint */
    *out_codepoint = ((0x07 & str[0]) << 18) | ((0x3f & str[1]) << 12) |
                     ((0x3f & str[2]) << 6) | (0x3f & str[3]);
    str += 4;
  } else if (0xe0 == (0xf0 & str[0])) {
    /* 3 byte utf8 codepoint */
    *out_codepoint =
        ((0x0f & str[0]) << 12) | ((0x3f & str[1]) << 6) | (0x3f & str[2]);
    str += 3;
  } else if (0xc0 == (0xe0 & str[0])) {
    /* 2 byte utf8 codepoint */
    *out_codepoint = ((0x1f & str[0]) << 6) | (0x3f & str[1]);
    str += 2;
  } else {
    /* 1 byte utf8 codepoint otherwise */
    *out_codepoint = str[0];
    str += 1;
  }
  return (utf8_int8_t *)str;
}
Referenced by eez::flow::do_OPERATION_TYPE_STRING_CODE_POINT_AT(), utf8casecmp(), utf8casestr(), utf8lwr(), utf8makevalid(), utf8ncasecmp(), utf8str(), utf8upr(), and eez::flow::writeString().
utf8codepointcalcsize()
size_t utf8codepointcalcsize (const utf8_int8_t * str)
Definition at line 4313 of file eez-flow.h.
{
  if (0xf0 == (0xf8 & str[0])) {
    /* 4 byte utf8 codepoint */
    return 4;
  } else if (0xe0 == (0xf0 & str[0])) {
    /* 3 byte utf8 codepoint */
    return 3;
  } else if (0xc0 == (0xe0 & str[0])) {
    /* 2 byte utf8 codepoint */
    return 2;
  }
  /* 1 byte utf8 codepoint otherwise */
  return 1;
}
References utf8_constexpr14_impl.
utf8codepointsize()
size_t utf8codepointsize (utf8_int32_t chr)
Definition at line 4329 of file eez-flow.h.
{
  if (0 == ((utf8_int32_t)0xffffff80 & chr)) {
    return 1;
  } else if (0 == ((utf8_int32_t)0xfffff800 & chr)) {
    return 2;
  } else if (0 == ((utf8_int32_t)0xffff0000 & chr)) {
    return 3;
  } else { /* if (0 == ((int)0xffe00000 & chr)) { */
    return 4;
  }
}
References utf8_constexpr14_impl.
Referenced by utf8lwr(), utf8ncasecmp(), utf8ncpy(), and utf8upr().
utf8coll()
int utf8coll (const utf8_int8_t * src1, const utf8_int8_t * src2)
References utf8_constexpr14_impl.
utf8cpy()
utf8_int8_t * utf8cpy (utf8_int8_t *utf8_restrict dst, const utf8_int8_t *utf8_restrict src)
Definition at line 3521 of file eez-flow.h.
{
  utf8_int8_t *d = dst;
  /* overwriting anything previously in dst, write byte-by-byte
   * from src */
  while ('\0' != *src) {
    *d++ = *src++;
  }
  /* append null terminating byte */
  *d = '\0';
  return dst;
}
utf8cspn()
size_t utf8cspn (const utf8_int8_t * src, const utf8_int8_t * reject)
Definition at line 3537 of file eez-flow.h.
{
  size_t chars = 0;
  while ('\0' != *src) {
    const utf8_int8_t *r = reject;
    size_t offset = 0;
    while ('\0' != *r) {
      /* checking that if *r is the start of a utf8 codepoint
       * (it is not 0b10xxxxxx) and we have successfully matched
       * a previous character (0 < offset) - we found a match */
      if ((0x80 != (0xc0 & *r)) && (0 < offset)) {
        return chars;
      } else {
        if (*r == src[offset]) {
          /* part of a utf8 codepoint matched, so move our checking
           * onwards to the next byte */
          offset++;
          r++;
        } else {
          /* r could be in the middle of an unmatching utf8 code point,
           * so we need to march it on to the next character beginning, */
          do {
            r++;
          } while (0x80 == (0xc0 & *r));
          /* reset offset too as we found a mismatch */
          offset = 0;
        }
      }
    }
    /* found a match at the end of *r, so didn't get a chance to test it */
    if (0 < offset) {
      return chars;
    }
    /* the current utf8 codepoint in src did not match reject, but src
     * could have been partway through a utf8 codepoint, so we need to
     * march it onto the next utf8 codepoint starting byte */
    do {
      src++;
    } while ((0x80 == (0xc0 & *src)));
    chars++;
  }
  return chars;
}
References utf8_constexpr14_impl.
utf8dup()
utf8_int8_t * utf8dup (const utf8_int8_t * src)
Definition at line 3588 of file eez-flow.h.
{
  return utf8dup_ex(src, utf8_null, utf8_null);
}
References utf8_null, and utf8dup_ex().
utf8dup_ex()
utf8_int8_t * utf8dup_ex (const utf8_int8_t * src, utf8_int8_t *(* alloc_func_ptr)(utf8_int8_t *, size_t), utf8_int8_t * user_data)
Definition at line 3592 of file eez-flow.h.
{
  utf8_int8_t *n = utf8_null;
  /* figure out how many bytes (including the terminator) we need to copy first
   */
  size_t bytes = utf8size(src);
  if (alloc_func_ptr) {
    n = alloc_func_ptr(user_data, bytes);
  } else {
    n = (utf8_int8_t *)malloc(bytes);
  }
  if (utf8_null == n) {
    /* out of memory so we bail */
    return utf8_null;
  } else {
    bytes = 0;
    /* copy src byte-by-byte into our new utf8 string */
    while ('\0' != src[bytes]) {
      n[bytes] = src[bytes];
      bytes++;
    }
    /* append null terminating byte */
    n[bytes] = '\0';
    return n;
  }
}
References utf8_null, and utf8size().
Referenced by utf8dup().
utf8fry()
utf8_int8_t * utf8fry (const utf8_int8_t * str)
References utf8_constexpr14_impl.
utf8islower()
int utf8islower (utf8_int32_t chr)
Definition at line 4385 of file eez-flow.h.
{
  return chr != utf8uprcodepoint(chr);
}
References utf8_constexpr14_impl, and utf8uprcodepoint().
utf8isupper()
int utf8isupper (utf8_int32_t chr)
Definition at line 4389 of file eez-flow.h.
{
  return chr != utf8lwrcodepoint(chr);
}
References utf8_constexpr14_impl, and utf8lwrcodepoint().
utf8len()
size_t utf8len (const utf8_int8_t * str)
Definition at line 3627 of file eez-flow.h.
{
  return utf8nlen(str, SIZE_MAX);
}
References utf8_constexpr14_impl, and utf8nlen().
utf8lwr()
void utf8lwr (utf8_int8_t *utf8_restrict str)
Definition at line 4393 of file eez-flow.h.
{
  utf8_int32_t cp = 0;
  utf8_int8_t *pn = utf8codepoint(str, &cp);
  while (cp != 0) {
    const utf8_int32_t lwr_cp = utf8lwrcodepoint(cp);
    const size_t size = utf8codepointsize(lwr_cp);
    if (lwr_cp != cp) {
      utf8catcodepoint(str, lwr_cp, size);
    }
    str = pn;
    pn = utf8codepoint(str, &cp);
  }
}
References utf8catcodepoint(), utf8codepoint(), utf8codepointsize(), and utf8lwrcodepoint().
utf8lwrcodepoint()
utf8_int32_t utf8lwrcodepoint (utf8_int32_t cp)
Definition at line 4427 of file eez-flow.h.
{
  if (((0x0041 <= cp) && (0x005a >= cp)) ||
      ((0x00c0 <= cp) && (0x00d6 >= cp)) ||
      ((0x00d8 <= cp) && (0x00de >= cp)) ||
      ((0x0391 <= cp) && (0x03a1 >= cp)) ||
      ((0x03a3 <= cp) && (0x03ab >= cp)) ||
      ((0x0410 <= cp) && (0x042f >= cp))) {
    cp += 32;
  } else if ((0x0400 <= cp) && (0x040f >= cp)) {
    cp += 80;
  } else if (((0x0100 <= cp) && (0x012f >= cp)) ||
             ((0x0132 <= cp) && (0x0137 >= cp)) ||
             ((0x014a <= cp) && (0x0177 >= cp)) ||
             ((0x0182 <= cp) && (0x0185 >= cp)) ||
             ((0x01a0 <= cp) && (0x01a5 >= cp)) ||
             ((0x01de <= cp) && (0x01ef >= cp)) ||
             ((0x01f8 <= cp) && (0x021f >= cp)) ||
             ((0x0222 <= cp) && (0x0233 >= cp)) ||
             ((0x0246 <= cp) && (0x024f >= cp)) ||
             ((0x03d8 <= cp) && (0x03ef >= cp)) ||
             ((0x0460 <= cp) && (0x0481 >= cp)) ||
             ((0x048a <= cp) && (0x04ff >= cp))) {
    cp |= 0x1;
  } else if (((0x0139 <= cp) && (0x0148 >= cp)) ||
             ((0x0179 <= cp) && (0x017e >= cp)) ||
             ((0x01af <= cp) && (0x01b0 >= cp)) ||
             ((0x01b3 <= cp) && (0x01b6 >= cp)) ||
             ((0x01cd <= cp) && (0x01dc >= cp))) {
    cp += 1;
    cp &= ~0x1;
  } else {
    switch (cp) {
    default:
      break;
    case 0x0178:
      cp = 0x00ff;
      break;
    case 0x0243:
      cp = 0x0180;
      break;
    case 0x018e:
      cp = 0x01dd;
      break;
    case 0x023d:
      cp = 0x019a;
      break;
    case 0x0220:
      cp = 0x019e;
      break;
    case 0x01b7:
      cp = 0x0292;
      break;
    case 0x01c4:
      cp = 0x01c6;
      break;
    case 0x01c7:
      cp = 0x01c9;
      break;
    case 0x01ca:
      cp = 0x01cc;
      break;
    case 0x01f1:
      cp = 0x01f3;
      break;
    case 0x01f7:
      cp = 0x01bf;
      break;
    case 0x0187:
      cp = 0x0188;
      break;
    case 0x018b:
      cp = 0x018c;
      break;
    case 0x0191:
      cp = 0x0192;
      break;
    case 0x0198:
      cp = 0x0199;
      break;
    case 0x01a7:
      cp = 0x01a8;
      break;
    case 0x01ac:
      cp = 0x01ad;
      break;
    case 0x01af:
      cp = 0x01b0;
      break;
    case 0x01b8:
      cp = 0x01b9;
      break;
    case 0x01bc:
      cp = 0x01bd;
      break;
    case 0x01f4:
      cp = 0x01f5;
      break;
    case 0x023b:
      cp = 0x023c;
      break;
    case 0x0241:
      cp = 0x0242;
      break;
    case 0x03fd:
      cp = 0x037b;
      break;
    case 0x03fe:
      cp = 0x037c;
      break;
    case 0x03ff:
      cp = 0x037d;
      break;
    case 0x037f:
      cp = 0x03f3;
      break;
    case 0x0386:
      cp = 0x03ac;
      break;
    case 0x0388:
      cp = 0x03ad;
      break;
    case 0x0389:
      cp = 0x03ae;
      break;
    case 0x038a:
      cp = 0x03af;
      break;
    case 0x038c:
      cp = 0x03cc;
      break;
    case 0x038e:
      cp = 0x03cd;
      break;
    case 0x038f:
      cp = 0x03ce;
      break;
    case 0x0370:
      cp = 0x0371;
      break;
    case 0x0372:
      cp = 0x0373;
      break;
    case 0x0376:
      cp = 0x0377;
      break;
    case 0x03f4:
      cp = 0x03b8;
      break;
    case 0x03cf:
      cp = 0x03d7;
      break;
    case 0x03f9:
      cp = 0x03f2;
      break;
    case 0x03f7:
      cp = 0x03f8;
      break;
    case 0x03fa:
      cp = 0x03fb;
      break;
    }
  }
  return cp;
}
References utf8_constexpr14_impl.
Referenced by utf8casecmp(), utf8casestr(), utf8isupper(), utf8lwr(), and utf8ncasecmp().
utf8makevalid()
int utf8makevalid (utf8_int8_t * str, const utf8_int32_t replacement)
Definition at line 4222 of file eez-flow.h.
{
  utf8_int8_t *read = str;
  utf8_int8_t *write = read;
  const utf8_int8_t r = (utf8_int8_t)replacement;
  utf8_int32_t codepoint = 0;
  if (replacement > 0x7f) {
    return -1;
  }
  while ('\0' != *read) {
    if (0xf0 == (0xf8 & *read)) {
      /* ensure each of the 3 following bytes in this 4-byte
       * utf8 codepoint began with 0b10xxxxxx */
      if ((0x80 != (0xc0 & read[1])) || (0x80 != (0xc0 & read[2])) ||
          (0x80 != (0xc0 & read[3]))) {
        *write++ = r;
        read++;
        continue;
      }
      /* 4-byte utf8 code point (began with 0b11110xxx) */
      read = utf8codepoint(read, &codepoint);
      write = utf8catcodepoint(write, codepoint, 4);
    } else if (0xe0 == (0xf0 & *read)) {
      /* ensure each of the 2 following bytes in this 3-byte
       * utf8 codepoint began with 0b10xxxxxx */
      if ((0x80 != (0xc0 & read[1])) || (0x80 != (0xc0 & read[2]))) {
        *write++ = r;
        read++;
        continue;
      }
      /* 3-byte utf8 code point (began with 0b1110xxxx) */
      read = utf8codepoint(read, &codepoint);
      write = utf8catcodepoint(write, codepoint, 3);
    } else if (0xc0 == (0xe0 & *read)) {
      /* ensure the 1 following byte in this 2-byte
       * utf8 codepoint began with 0b10xxxxxx */
      if (0x80 != (0xc0 & read[1])) {
        *write++ = r;
        read++;
        continue;
      }
      /* 2-byte utf8 code point (began with 0b110xxxxx) */
      read = utf8codepoint(read, &codepoint);
      write = utf8catcodepoint(write, codepoint, 2);
    } else if (0x00 == (0x80 & *read)) {
      /* 1-byte ascii (began with 0b0xxxxxxx) */
      read = utf8codepoint(read, &codepoint);
      write = utf8catcodepoint(write, codepoint, 1);
    } else {
      /* if we got here then we've got a dangling continuation (0b10xxxxxx) */
      *write++ = r;
      read++;
      continue;
    }
  }
  *write = '\0';
  return 0;
}
References utf8catcodepoint(), and utf8codepoint().
utf8ncasecmp()
int utf8ncasecmp (const utf8_int8_t * src1, const utf8_int8_t * src2, size_t n)
Definition at line 3661 of file eez-flow.h.
{
  utf8_int32_t src1_lwr_cp = 0, src2_lwr_cp = 0, src1_upr_cp = 0,
               src2_upr_cp = 0, src1_orig_cp = 0, src2_orig_cp = 0;
  do {
    const utf8_int8_t *const s1 = src1;
    const utf8_int8_t *const s2 = src2;
    /* first check that we have enough bytes left in n to contain an entire
     * codepoint */
    if (0 == n) {
      return 0;
    }
    if ((1 == n) && ((0xc0 == (0xe0 & *s1)) || (0xc0 == (0xe0 & *s2)))) {
      const utf8_int32_t c1 = (0xe0 & *s1);
      const utf8_int32_t c2 = (0xe0 & *s2);
      if (c1 < c2) {
        return c1 - c2;
      } else {
        return 0;
      }
    }
    if ((2 >= n) && ((0xe0 == (0xf0 & *s1)) || (0xe0 == (0xf0 & *s2)))) {
      const utf8_int32_t c1 = (0xf0 & *s1);
      const utf8_int32_t c2 = (0xf0 & *s2);
      if (c1 < c2) {
        return c1 - c2;
      } else {
        return 0;
      }
    }
    if ((3 >= n) && ((0xf0 == (0xf8 & *s1)) || (0xf0 == (0xf8 & *s2)))) {
      const utf8_int32_t c1 = (0xf8 & *s1);
      const utf8_int32_t c2 = (0xf8 & *s2);
      if (c1 < c2) {
        return c1 - c2;
      } else {
        return 0;
      }
    }
    src1 = utf8codepoint(src1, &src1_orig_cp);
    src2 = utf8codepoint(src2, &src2_orig_cp);
    n -= utf8codepointsize(src1_orig_cp);
    src1_lwr_cp = utf8lwrcodepoint(src1_orig_cp);
    src2_lwr_cp = utf8lwrcodepoint(src2_orig_cp);
    src1_upr_cp = utf8uprcodepoint(src1_orig_cp);
    src2_upr_cp = utf8uprcodepoint(src2_orig_cp);
    /* check if the lowered codepoints match */
    if ((0 == src1_orig_cp) && (0 == src2_orig_cp)) {
      return 0;
    } else if ((src1_lwr_cp == src2_lwr_cp) || (src1_upr_cp == src2_upr_cp)) {
      continue;
    }
    /* if they don't match, then we return the difference between the characters
     */
    return src1_lwr_cp - src2_lwr_cp;
  } while (0 < n);
  /* both utf8 strings matched */
  return 0;
}
References c1, c2, utf8_constexpr14_impl, utf8codepoint(), utf8codepointsize(), utf8lwrcodepoint(), and utf8uprcodepoint().
utf8ncat()
utf8_int8_t * utf8ncat (utf8_int8_t *utf8_restrict dst, const utf8_int8_t *utf8_restrict src, size_t n)
Definition at line 3735 of file eez-flow.h.
{
  utf8_int8_t *d = dst;
  /* find the null terminating byte in dst */
  while ('\0' != *d) {
    d++;
  }
  /* overwriting the null terminating byte in dst, append src byte-by-byte
   * stopping if we run out of space */
  while (('\0' != *src) && (0 != n--)) {
    *d++ = *src++;
  }
  /* write out a new null terminating byte into dst */
  *d = '\0';
  return dst;
}
utf8ncmp()
int utf8ncmp (const utf8_int8_t * src1, const utf8_int8_t * src2, size_t n)
Definition at line 3756 of file eez-flow.h.
{
  while ((0 != n--) && (('\0' != *src1) || ('\0' != *src2))) {
    if (*src1 < *src2) {
      return -1;
    } else if (*src1 > *src2) {
      return 1;
    }
    src1++;
    src2++;
  }
  /* both utf8 strings matched */
  return 0;
}
References utf8_constexpr14_impl.
utf8ncpy()
utf8_int8_t * utf8ncpy (utf8_int8_t *utf8_restrict dst, const utf8_int8_t *utf8_restrict src, size_t n)
Definition at line 3773 of file eez-flow.h.
{
  utf8_int8_t *d = dst;
  size_t index = 0, check_index = 0;
  if (n == 0) {
    return dst;
  }
  /* overwriting anything previously in dst, write byte-by-byte
   * from src */
  for (index = 0; index < n; index++) {
    d[index] = src[index];
    if ('\0' == src[index]) {
      break;
    }
  }
  for (check_index = index - 1;
       check_index > 0 && 0x80 == (0xc0 & d[check_index]); check_index--) {
    /* just moving the index */
  }
  if (check_index < index &&
      (index - check_index) < utf8codepointsize(d[check_index])) {
    index = check_index;
  }
  /* append null terminating byte */
  for (; index < n; index++) {
    d[index] = 0;
  }
  return dst;
}
References utf8codepointsize().
utf8ndup()
utf8_int8_t * utf8ndup (const utf8_int8_t * src, size_t n)
Definition at line 3809 of file eez-flow.h.
{
  return utf8ndup_ex(src, n, utf8_null, utf8_null);
}
References utf8_null, and utf8ndup_ex().
utf8ndup_ex()
utf8_int8_t * utf8ndup_ex (const utf8_int8_t * src, size_t n, utf8_int8_t *(* alloc_func_ptr)(utf8_int8_t *, size_t), utf8_int8_t * user_data)
Definition at line 3813 of file eez-flow.h.
{
  utf8_int8_t *c = utf8_null;
  size_t bytes = 0;
  /* Find the end of the string or stop when n is reached */
  while ('\0' != src[bytes] && bytes < n) {
    bytes++;
  }
  /* In case bytes is actually less than n, we need to set it
   * to be used later in the copy byte by byte. */
  n = bytes;
  if (alloc_func_ptr) {
    c = alloc_func_ptr(user_data, bytes + 1);
  } else {
    c = (utf8_int8_t *)malloc(bytes + 1);
  }
  if (utf8_null == c) {
    /* out of memory so we bail */
    return utf8_null;
  }
  bytes = 0;
  /* copy src byte-by-byte into our new utf8 string */
  while ('\0' != src[bytes] && bytes < n) {
    c[bytes] = src[bytes];
    bytes++;
  }
  /* append null terminating byte */
  c[bytes] = '\0';
  return c;
}
References utf8_null.
Referenced by utf8ndup().
utf8nlen()
size_t utf8nlen (const utf8_int8_t * str, size_t n)
Definition at line 3631 of file eez-flow.h.
{
  const utf8_int8_t *t = str;
  size_t length = 0;
  while ((size_t)(str - t) < n && '\0' != *str) {
    if (0xf0 == (0xf8 & *str)) {
      /* 4-byte utf8 code point (began with 0b11110xxx) */
      str += 4;
    } else if (0xe0 == (0xf0 & *str)) {
      /* 3-byte utf8 code point (began with 0b1110xxxx) */
      str += 3;
    } else if (0xc0 == (0xe0 & *str)) {
      /* 2-byte utf8 code point (began with 0b110xxxxx) */
      str += 2;
    } else { /* if (0x00 == (0x80 & *s)) { */
      /* 1-byte ascii (began with 0b0xxxxxxx) */
      str += 1;
    }
    /* no matter the bytes we marched s forward by, it was
     * only 1 utf8 codepoint */
    length++;
  }
  if ((size_t)(str - t) > n) {
    length--;
  }
  return length;
}
References utf8_constexpr14_impl.
Referenced by utf8len().
utf8nsize_lazy()
size_t utf8nsize_lazy (const utf8_int8_t * str, size_t n)
Definition at line 3976 of file eez-flow.h.
{
  size_t size = 0;
  while (size < n && '\0' != str[size]) {
    size++;
  }
  return size;
}
References utf8_constexpr14_impl.
Referenced by utf8size_lazy().
utf8nvalid()
utf8_int8_t * utf8nvalid (const utf8_int8_t * str, size_t n)
Definition at line 4123 of file eez-flow.h.
{
  const utf8_int8_t *t = str;
  size_t consumed = 0, remained = 0;
  while ((void)(consumed = (size_t)(str - t)), consumed < n && '\0' != *str) {
    remained = n - consumed;
    if (0xf0 == (0xf8 & *str)) {
      /* ensure that there's 4 bytes or more remained */
      if (remained < 4) {
        return (utf8_int8_t *)str;
      }
      /* ensure each of the 3 following bytes in this 4-byte
       * utf8 codepoint began with 0b10xxxxxx */
      if ((0x80 != (0xc0 & str[1])) || (0x80 != (0xc0 & str[2])) ||
          (0x80 != (0xc0 & str[3]))) {
        return (utf8_int8_t *)str;
      }
      /* ensure that our utf8 codepoint ended after 4 bytes */
      if (0x80 == (0xc0 & str[4])) {
        return (utf8_int8_t *)str;
      }
      /* ensure that the top 5 bits of this 4-byte utf8
       * codepoint were not 0, as then we could have used
       * one of the smaller encodings */
      if ((0 == (0x07 & str[0])) && (0 == (0x30 & str[1]))) {
        return (utf8_int8_t *)str;
      }
      /* 4-byte utf8 code point (began with 0b11110xxx) */
      str += 4;
    } else if (0xe0 == (0xf0 & *str)) {
      /* ensure that there's 3 bytes or more remained */
      if (remained < 3) {
        return (utf8_int8_t *)str;
      }
      /* ensure each of the 2 following bytes in this 3-byte
       * utf8 codepoint began with 0b10xxxxxx */
      if ((0x80 != (0xc0 & str[1])) || (0x80 != (0xc0 & str[2]))) {
        return (utf8_int8_t *)str;
      }
      /* ensure that our utf8 codepoint ended after 3 bytes */
      if (0x80 == (0xc0 & str[3])) {
        return (utf8_int8_t *)str;
      }
      /* ensure that the top 5 bits of this 3-byte utf8
       * codepoint were not 0, as then we could have used
       * one of the smaller encodings */
      if ((0 == (0x0f & str[0])) && (0 == (0x20 & str[1]))) {
        return (utf8_int8_t *)str;
      }
      /* 3-byte utf8 code point (began with 0b1110xxxx) */
      str += 3;
    } else if (0xc0 == (0xe0 & *str)) {
      /* ensure that there's 2 bytes or more remained */
      if (remained < 2) {
        return (utf8_int8_t *)str;
      }
      /* ensure the 1 following byte in this 2-byte
       * utf8 codepoint began with 0b10xxxxxx */
      if (0x80 != (0xc0 & str[1])) {
        return (utf8_int8_t *)str;
      }
      /* ensure that our utf8 codepoint ended after 2 bytes */
      if (0x80 == (0xc0 & str[2])) {
        return (utf8_int8_t *)str;
      }
      /* ensure that the top 4 bits of this 2-byte utf8
       * codepoint were not 0, as then we could have used
       * one of the smaller encodings */
      if (0 == (0x1e & str[0])) {
        return (utf8_int8_t *)str;
      }
      /* 2-byte utf8 code point (began with 0b110xxxxx) */
      str += 2;
    } else if (0x00 == (0x80 & *str)) {
      /* 1-byte ascii (began with 0b0xxxxxxx) */
      str += 1;
    } else {
      /* we have an invalid 0b1xxxxxxx utf8 code point entry */
      return (utf8_int8_t *)str;
    }
  }
  return utf8_null;
}
References utf8_constexpr14_impl, and utf8_null.
Referenced by utf8valid().
utf8pbrk()
utf8_int8_t * utf8pbrk (const utf8_int8_t * str, const utf8_int8_t * accept)
Definition at line 3920 of file eez-flow.h.
{
  while ('\0' != *str) {
    const utf8_int8_t *a = accept;
    size_t offset = 0;
    while ('\0' != *a) {
      /* checking that if *a is the start of a utf8 codepoint
       * (it is not 0b10xxxxxx) and we have successfully matched
       * a previous character (0 < offset) - we found a match */
      if ((0x80 != (0xc0 & *a)) && (0 < offset)) {
        return (utf8_int8_t *)str;
      } else {
        if (*a == str[offset]) {
          /* part of a utf8 codepoint matched, so move our checking
           * onwards to the next byte */
          offset++;
          a++;
        } else {
          /* r could be in the middle of an unmatching utf8 code point,
           * so we need to march it on to the next character beginning, */
          do {
            a++;
          } while (0x80 == (0xc0 & *a));
          /* reset offset too as we found a mismatch */
          offset = 0;
        }
      }
    }
    /* we found a match on the last utf8 codepoint */
    if (0 < offset) {
      return (utf8_int8_t *)str;
    }
    /* the current utf8 codepoint in src did not match accept, but src
     * could have been partway through a utf8 codepoint, so we need to
     * march it onto the next utf8 codepoint starting byte */
    do {
      str++;
    } while ((0x80 == (0xc0 & *str)));
  }
  return utf8_null;
}
References utf8_constexpr14_impl, and utf8_null.
utf8rchr()
utf8_int8_t * utf8rchr (const utf8_int8_t * src, int chr)
Definition at line 3852 of file eez-flow.h.
{
  utf8_int8_t *match = utf8_null;
  utf8_int8_t c[5] = {'\0', '\0', '\0', '\0', '\0'};
  if (0 == chr) {
    /* being asked to return position of null terminating byte, so
     * just run s to the end, and return! */
    while ('\0' != *src) {
      src++;
    }
    return (utf8_int8_t *)src;
  } else if (0 == ((int)0xffffff80 & chr)) {
    /* 1-byte/7-bit ascii
     * (0b0xxxxxxx) */
    c[0] = (utf8_int8_t)chr;
  } else if (0 == ((int)0xfffff800 & chr)) {
    /* 2-byte/11-bit utf8 code point
     * (0b110xxxxx 0b10xxxxxx) */
    c[0] = (utf8_int8_t)(0xc0 | (utf8_int8_t)(chr >> 6));
    c[1] = (utf8_int8_t)(0x80 | (utf8_int8_t)(chr & 0x3f));
  } else if (0 == ((int)0xffff0000 & chr)) {
    /* 3-byte/16-bit utf8 code point
     * (0b1110xxxx 0b10xxxxxx 0b10xxxxxx) */
    c[0] = (utf8_int8_t)(0xe0 | (utf8_int8_t)(chr >> 12));
    c[1] = (utf8_int8_t)(0x80 | (utf8_int8_t)((chr >> 6) & 0x3f));
    c[2] = (utf8_int8_t)(0x80 | (utf8_int8_t)(chr & 0x3f));
  } else { /* if (0 == ((int)0xffe00000 & chr)) { */
    /* 4-byte/21-bit utf8 code point
     * (0b11110xxx 0b10xxxxxx 0b10xxxxxx 0b10xxxxxx) */
    c[0] = (utf8_int8_t)(0xf0 | (utf8_int8_t)(chr >> 18));
    c[1] = (utf8_int8_t)(0x80 | (utf8_int8_t)((chr >> 12) & 0x3f));
    c[2] = (utf8_int8_t)(0x80 | (utf8_int8_t)((chr >> 6) & 0x3f));
    c[3] = (utf8_int8_t)(0x80 | (utf8_int8_t)(chr & 0x3f));
  }
  /* we've created a 2 utf8 codepoint string in c that is
   * the utf8 character asked for by chr, and a null
   * terminating byte */
  while ('\0' != *src) {
    size_t offset = 0;
    while (src[offset] == c[offset]) {
      offset++;
    }
    if ('\0' == c[offset]) {
      /* we found a matching utf8 code point */
      match = (utf8_int8_t *)src;
      src += offset;
    } else {
      src += offset;
      /* need to march s along to next utf8 codepoint start
       * (the next byte that doesn't match 0b10xxxxxx) */
      if ('\0' != *src) {
        do {
          src++;
        } while (0x80 == (0xc0 & *src));
      }
    }
  }
  /* return the last match we found (or 0 if no match was found) */
  return match;
}
References utf8_constexpr14_impl, and utf8_null.
utf8rcodepoint()
utf8_int8_t * utf8rcodepoint (const utf8_int8_t *utf8_restrict str, utf8_int32_t *utf8_restrict out_codepoint)
Definition at line 4760 of file eez-flow.h.
{
  const utf8_int8_t *s = (const utf8_int8_t *)str;
  if (0xf0 == (0xf8 & s[0])) {
    /* 4 byte utf8 codepoint */
    *out_codepoint = ((0x07 & s[0]) << 18) | ((0x3f & s[1]) << 12) |
                     ((0x3f & s[2]) << 6) | (0x3f & s[3]);
  } else if (0xe0 == (0xf0 & s[0])) {
    /* 3 byte utf8 codepoint */
    *out_codepoint =
        ((0x0f & s[0]) << 12) | ((0x3f & s[1]) << 6) | (0x3f & s[2]);
  } else if (0xc0 == (0xe0 & s[0])) {
    /* 2 byte utf8 codepoint */
    *out_codepoint = ((0x1f & s[0]) << 6) | (0x3f & s[1]);
  } else {
    /* 1 byte utf8 codepoint otherwise */
    *out_codepoint = s[0];
  }
  do {
    s--;
  } while ((0 != (0x80 & s[0])) && (0x80 == (0xc0 & s[0])));
  return (utf8_int8_t *)s;
}
utf8size()
size_t utf8size (const utf8_int8_t * str)
Definition at line 3968 of file eez-flow.h.
{
  return utf8size_lazy(str) + 1;
}
References utf8_constexpr14_impl, and utf8size_lazy().
Referenced by utf8dup_ex().
utf8size_lazy()
size_t utf8size_lazy (const utf8_int8_t * str)
Definition at line 3972 of file eez-flow.h.
{
  return utf8nsize_lazy(str, SIZE_MAX);
}
References utf8_constexpr14_impl, and utf8nsize_lazy().
Referenced by utf8size().
utf8spn()
size_t utf8spn (const utf8_int8_t * src, const utf8_int8_t * accept)
Definition at line 3984 of file eez-flow.h.
{
  size_t chars = 0;
  while ('\0' != *src) {
    const utf8_int8_t *a = accept;
    size_t offset = 0;
    while ('\0' != *a) {
      /* checking that if *r is the start of a utf8 codepoint
       * (it is not 0b10xxxxxx) and we have successfully matched
       * a previous character (0 < offset) - we found a match */
      if ((0x80 != (0xc0 & *a)) && (0 < offset)) {
        /* found a match, so increment the number of utf8 codepoints
         * that have matched and stop checking whether any other utf8
         * codepoints in a match */
        chars++;
        src += offset;
        offset = 0;
        break;
      } else {
        if (*a == src[offset]) {
          offset++;
          a++;
        } else {
          /* a could be in the middle of an unmatching utf8 codepoint,
           * so we need to march it on to the next character beginning, */
          do {
            a++;
          } while (0x80 == (0xc0 & *a));
          /* reset offset too as we found a mismatch */
          offset = 0;
        }
      }
    }
    /* found a match at the end of *a, so didn't get a chance to test it */
    if (0 < offset) {
      chars++;
      src += offset;
      continue;
    }
    /* if a got to its terminating null byte, then we didn't find a match.
     * Return the current number of matched utf8 codepoints */
    if ('\0' == *a) {
      return chars;
    }
  }
  return chars;
}
References utf8_constexpr14_impl.
utf8str()
utf8_int8_t * utf8str (const utf8_int8_t * haystack, const utf8_int8_t * needle)
Definition at line 4038 of file eez-flow.h.
{
  utf8_int32_t throwaway_codepoint = 0;
  /* if needle has no utf8 codepoints before the null terminating
   * byte then return haystack */
  if ('\0' == *needle) {
    return (utf8_int8_t *)haystack;
  }
  while ('\0' != *haystack) {
    const utf8_int8_t *maybeMatch = haystack;
    const utf8_int8_t *n = needle;
    while (*haystack == *n && (*haystack != '\0' && *n != '\0')) {
      n++;
      haystack++;
    }
    if ('\0' == *n) {
      /* we found the whole utf8 string for needle in haystack at
       * maybeMatch, so return it */
      return (utf8_int8_t *)maybeMatch;
    } else {
      /* h could be in the middle of an unmatching utf8 codepoint,
       * so we need to march it on to the next character beginning
       * starting from the current character */
      haystack = utf8codepoint(maybeMatch, &throwaway_codepoint);
    }
  }
  /* no match */
  return utf8_null;
}
References utf8_constexpr14_impl, utf8_null, and utf8codepoint().
Referenced by utf8chr().
utf8upr()
void utf8upr (utf8_int8_t *utf8_restrict str)
Definition at line 4410 of file eez-flow.h.
{
  utf8_int32_t cp = 0;
  utf8_int8_t *pn = utf8codepoint(str, &cp);
  while (cp != 0) {
    const utf8_int32_t lwr_cp = utf8uprcodepoint(cp);
    const size_t size = utf8codepointsize(lwr_cp);
    if (lwr_cp != cp) {
      utf8catcodepoint(str, lwr_cp, size);
    }
    str = pn;
    pn = utf8codepoint(str, &cp);
  }
}
References utf8catcodepoint(), utf8codepoint(), utf8codepointsize(), and utf8uprcodepoint().
utf8uprcodepoint()
utf8_int32_t utf8uprcodepoint (utf8_int32_t cp)
Definition at line 4593 of file eez-flow.h.
{
  if (((0x0061 <= cp) && (0x007a >= cp)) ||
      ((0x00e0 <= cp) && (0x00f6 >= cp)) ||
      ((0x00f8 <= cp) && (0x00fe >= cp)) ||
      ((0x03b1 <= cp) && (0x03c1 >= cp)) ||
      ((0x03c3 <= cp) && (0x03cb >= cp)) ||
      ((0x0430 <= cp) && (0x044f >= cp))) {
    cp -= 32;
  } else if ((0x0450 <= cp) && (0x045f >= cp)) {
    cp -= 80;
  } else if (((0x0100 <= cp) && (0x012f >= cp)) ||
             ((0x0132 <= cp) && (0x0137 >= cp)) ||
             ((0x014a <= cp) && (0x0177 >= cp)) ||
             ((0x0182 <= cp) && (0x0185 >= cp)) ||
             ((0x01a0 <= cp) && (0x01a5 >= cp)) ||
             ((0x01de <= cp) && (0x01ef >= cp)) ||
             ((0x01f8 <= cp) && (0x021f >= cp)) ||
             ((0x0222 <= cp) && (0x0233 >= cp)) ||
             ((0x0246 <= cp) && (0x024f >= cp)) ||
             ((0x03d8 <= cp) && (0x03ef >= cp)) ||
             ((0x0460 <= cp) && (0x0481 >= cp)) ||
             ((0x048a <= cp) && (0x04ff >= cp))) {
    cp &= ~0x1;
  } else if (((0x0139 <= cp) && (0x0148 >= cp)) ||
             ((0x0179 <= cp) && (0x017e >= cp)) ||
             ((0x01af <= cp) && (0x01b0 >= cp)) ||
             ((0x01b3 <= cp) && (0x01b6 >= cp)) ||
             ((0x01cd <= cp) && (0x01dc >= cp))) {
    cp -= 1;
    cp |= 0x1;
  } else {
    switch (cp) {
    default:
      break;
    case 0x00ff:
      cp = 0x0178;
      break;
    case 0x0180:
      cp = 0x0243;
      break;
    case 0x01dd:
      cp = 0x018e;
      break;
    case 0x019a:
      cp = 0x023d;
      break;
    case 0x019e:
      cp = 0x0220;
      break;
    case 0x0292:
      cp = 0x01b7;
      break;
    case 0x01c6:
      cp = 0x01c4;
      break;
    case 0x01c9:
      cp = 0x01c7;
      break;
    case 0x01cc:
      cp = 0x01ca;
      break;
    case 0x01f3:
      cp = 0x01f1;
      break;
    case 0x01bf:
      cp = 0x01f7;
      break;
    case 0x0188:
      cp = 0x0187;
      break;
    case 0x018c:
      cp = 0x018b;
      break;
    case 0x0192:
      cp = 0x0191;
      break;
    case 0x0199:
      cp = 0x0198;
      break;
    case 0x01a8:
      cp = 0x01a7;
      break;
    case 0x01ad:
      cp = 0x01ac;
      break;
    case 0x01b0:
      cp = 0x01af;
      break;
    case 0x01b9:
      cp = 0x01b8;
      break;
    case 0x01bd:
      cp = 0x01bc;
      break;
    case 0x01f5:
      cp = 0x01f4;
      break;
    case 0x023c:
      cp = 0x023b;
      break;
    case 0x0242:
      cp = 0x0241;
      break;
    case 0x037b:
      cp = 0x03fd;
      break;
    case 0x037c:
      cp = 0x03fe;
      break;
    case 0x037d:
      cp = 0x03ff;
      break;
    case 0x03f3:
      cp = 0x037f;
      break;
    case 0x03ac:
      cp = 0x0386;
      break;
    case 0x03ad:
      cp = 0x0388;
      break;
    case 0x03ae:
      cp = 0x0389;
      break;
    case 0x03af:
      cp = 0x038a;
      break;
    case 0x03cc:
      cp = 0x038c;
      break;
    case 0x03cd:
      cp = 0x038e;
      break;
    case 0x03ce:
      cp = 0x038f;
      break;
    case 0x0371:
      cp = 0x0370;
      break;
    case 0x0373:
      cp = 0x0372;
      break;
    case 0x0377:
      cp = 0x0376;
      break;
    case 0x03d1:
      cp = 0x0398;
      break;
    case 0x03d7:
      cp = 0x03cf;
      break;
    case 0x03f2:
      cp = 0x03f9;
      break;
    case 0x03f8:
      cp = 0x03f7;
      break;
    case 0x03fb:
      cp = 0x03fa;
      break;
    }
  }
  return cp;
}
References utf8_constexpr14_impl.
Referenced by utf8casecmp(), utf8islower(), utf8ncasecmp(), and utf8upr().
utf8valid()
utf8_int8_t * utf8valid (const utf8_int8_t * str)
Definition at line 4119 of file eez-flow.h.
{
  return utf8nvalid(str, SIZE_MAX);
}
References utf8_constexpr14_impl, and utf8nvalid().
Variable Documentation
g_currentScreen
int16_t g_currentScreen extern
Definition at line 7613 of file eez-flow.cpp.
Referenced by eez::flow::do_OPERATION_TYPE_FLOW_IS_PAGE_ACTIVE(), eez_flow_get_current_screen(), eez_flow_push_screen(), replacePageHook(), and ui_tick().
g_eezFlowLvlgMeterTickIndex
int g_eezFlowLvlgMeterTickIndex extern
Definition at line 8064 of file eez-flow.cpp.
Referenced by eez::flow::do_OPERATION_TYPE_LVGL_METER_TICK_INDEX().
native_vars
native_var_t native_vars[] extern
Definition at line 36 of file ui.c.
{
    { NATIVE_VAR_TYPE_NONE, 0, 0 },
};
Referenced by eez::getVar(), and eez::setVar().