EARS-PIO-WSS3-LVGL-001: src/main.cpp File Reference
main.cpp File Reference
#include "EARS_versionDef.h"
#include <Arduino.h>
#include <lvgl.h>
#include <Arduino_GFX_Library.h>
#include "EARS_ws35tlcdPins.h"
#include "EARS_rgb565ColoursDef.h"
#include "EARS_rgb888ColoursDef.h"
#include "EARS_nvsEepromLib.h"
#include "Logger.h"
#include "EARS_sdCardLib.h"
Functions
void my_disp_flush (lv_display_t *display, const lv_area_t *area, uint8_t *px_map)
LVGL display flush callback.
uint32_t millis_cb (void)
Callback function to provide millis() to LVGL @description LVGL requires a millisecond tick source to manage its timing.
void init_logger ()
Initialize Logger.
void updateStatus (const char *message)
Update status message on display.
void Core0_NVSValidation (void *parameter)
Core 0 Task: NVS Validation @description Runs on Core 0, performs NVS validation while Core 1 shows animation.
void core0_loaderLogic ()
Core 0 Loader Logic Decision @description Called after validation completes to determine next action.
void Core1_DisplayHandler (void *parameter)
Core 1 Task: LVGL Display Handler @description Runs on Core 1, handles LVGL timer and display updates.
void setup ()
Primary setup function @description Initializes hardware and creates tasks for both cores Runs on Core 1 by default.
void loop ()
Main loop function @description During development, this loop monitors system status.
Variables
static const uint32_t screenWidth = 480
static const uint32_t screenHeight = 320
static lv_color_t buf1 [screenWidth *40]
static lv_color_t buf2 [screenWidth *40]
Arduino_DataBus * bus = new Arduino_ESP32SPI(3 , -1 , 5 , 1 , 2)
Arduino_GFX * gfx = new Arduino_ILI9488_18bit(bus, -1 , 1 , true)
lv_display_t * disp
lv_obj_t * spinner = NULL
lv_obj_t * status_label = NULL
NVSValidationResult g_nvsResult
EARS_nvsEepromLib using_nvs_eeprom
EARS_sdCard using_ears_sdcard
TaskHandle_t Core0_ValidationTask
TaskHandle_t Core1_DisplayTask
volatile bool validationComplete = false
SemaphoreHandle_t displayMutex
Function Documentation
core0_loaderLogic()
void core0_loaderLogic ()
Core 0 Loader Logic Decision @description Called after validation completes to determine next action.
Definition at line 265 of file main.cpp.
{
    LOG("=== Loader Decision ===");
    // Make decisions based on validation results
    switch (g_nvsResult.status) {
        case NVSStatus::VALID:
        case NVSStatus::UPGRADED:
            LOG("Decision: Proceed to login screen");
            LOGF("ZapNumber: %s", g_nvsResult.zapNumber);
            updateStatus("Ready - Login");
            // TODO: Show login screen, validate password
            break;
        case NVSStatus::MISSING_ZAPNUMBER:
            LOG("Decision: Show ZapNumber setup wizard");
            updateStatus("Setup: ZapNumber");
            // TODO: Launch setup wizard to collect ZapNumber
            break;
        case NVSStatus::MISSING_PASSWORD:
            LOG("Decision: Show password setup wizard");
            LOGF("Using ZapNumber: %s", g_nvsResult.zapNumber);
            updateStatus("Setup: Password");
            // TODO: Launch password setup wizard
            break;
        case NVSStatus::CRC_FAILED:
            LOG("Decision: SECURITY ALERT - Data tampering detected!");
            LOG("Action: Factory reset required");
            updateStatus("Factory Reset Needed");
            // TODO: Show security warning, require factory reset
            break;
        case NVSStatus::INVALID_VERSION:
            LOG("Decision: Version mismatch");
            LOGF("NVS version %d incompatible with code version %d",
                         g_nvsResult.currentVersion,
                         g_nvsResult.expectedVersion);
            updateStatus("Version Mismatch");
            // TODO: Show error, offer factory reset
            break;
        case NVSStatus::INITIALIZATION_FAILED:
            LOG("Decision: Hardware error");
            updateStatus("Hardware Error");
            // TODO: Show hardware error message
            break;
        default:
            LOG("Decision: Unknown state");
            updateStatus("Unknown State");
            break;
    }
    LOG("========================");
}
References CRC_FAILED, g_nvsResult, INITIALIZATION_FAILED, INVALID_VERSION, LOG, LOGF, MISSING_PASSWORD, MISSING_ZAPNUMBER, updateStatus(), UPGRADED, and VALID.
Referenced by Core1_DisplayHandler().
Core0_NVSValidation()
void Core0_NVSValidation (void * parameter)
Core 0 Task: NVS Validation @description Runs on Core 0, performs NVS validation while Core 1 shows animation.
Parameters
parameter Task parameters (unused)
Definition at line 173 of file main.cpp.
{
    LOG("[Core 0] NVS Validation Task Started");
    // Simulate some validation steps with status updates
    updateStatus("Checking NVS...");
    delay(500);
    // Step 1: Initialize NVS
    updateStatus("Initializing NVS...");
    if (!using_nvs_eeprom.begin()) {
        g_nvsResult.status = NVSStatus::INITIALIZATION_FAILED;
        updateStatus("NVS Init Failed!");
        validationComplete = true;
        vTaskDelete(NULL);
        return;
    }
    LOG("[Core 0] NVS Initialized");
    delay(500);
    // Step 2: Validate entire NVS
    updateStatus("Validating data...");
    g_nvsResult = using_nvs_eeprom.validateNVS();
    delay(500);
    // Step 3: Report results
    LOG("=== Core 0 NVS Validation Results ===");
    LOG("Status: ");
    switch (g_nvsResult.status) {
        case NVSStatus::VALID:
            LOG("VALID");
            updateStatus("Validation: PASSED");
            break;
        case NVSStatus::UPGRADED:
            LOG("UPGRADED");
            updateStatus("Validation: UPGRADED");
            break;
        case NVSStatus::INVALID_VERSION:
            LOG("INVALID_VERSION");
            updateStatus("Validation: BAD VERSION");
            break;
        case NVSStatus::MISSING_ZAPNUMBER:
            LOG("MISSING_ZAPNUMBER");
            updateStatus("Setup Required");
            break;
        case NVSStatus::MISSING_PASSWORD:
            LOG("MISSING_PASSWORD");
            updateStatus("Password Required");
            break;
        case NVSStatus::CRC_FAILED:
            LOG("CRC_FAILED - TAMPERING DETECTED!");
            updateStatus("SECURITY ALERT!");
            break;
        case NVSStatus::INITIALIZATION_FAILED:
            LOG("INITIALIZATION_FAILED");
            updateStatus("Hardware Error");
            break;
        default:
            LOG("NOT_CHECKED");
            updateStatus("Unknown Status");
            break;
    }
    LOGF("Version: Current=%d, Expected=%d",
                g_nvsResult.currentVersion,
                g_nvsResult.expectedVersion);
    LOGF("ZapNumber: Valid=%d, Value=%s",
                    g_nvsResult.zapNumberValid,
                    g_nvsResult.zapNumber);
    LOGF("Password: Valid=%d", g_nvsResult.passwordHashValid);
    LOGF("CRC: Valid=%d, Value=0x%08X",
                  g_nvsResult.crcValid,
                  g_nvsResult.calculatedCRC);
    LOGF("Upgraded: %d", g_nvsResult.wasUpgraded);
    LOG("====================================");
    delay(1000); // Show final status for 1 second
    // Mark validation as complete
    validationComplete = true;
    LOG("[Core 0] Validation Complete - Task Ending");
    // Task complete, delete itself
    vTaskDelete(NULL);
}
References CRC_FAILED, g_nvsResult, INITIALIZATION_FAILED, INVALID_VERSION, LOG, LOGF, MISSING_PASSWORD, MISSING_ZAPNUMBER, updateStatus(), UPGRADED, using_nvs_eeprom, VALID, and validationComplete.
Referenced by setup().
Core1_DisplayHandler()
void Core1_DisplayHandler (void * parameter)
Core 1 Task: LVGL Display Handler @description Runs on Core 1, handles LVGL timer and display updates.
Parameters
parameter Task parameters (unused)
Definition at line 328 of file main.cpp.
{
    LOG("[Core 1] Display Handler Task Started");
    while (true) {
        // Handle LVGL timer
        if (xSemaphoreTake(displayMutex, portMAX_DELAY)) {
            lv_timer_handler();
            xSemaphoreGive(displayMutex);
        }
        // Check if validation is complete
        if (validationComplete) {
            // Hide spinner
            if (spinner != NULL) {
                lv_obj_del(spinner);
                spinner = NULL;
            }
            // Run loader logic
            core0_loaderLogic();
            // End this task as validation phase is done
            LOG("[Core 1] Display task ending - validation complete");
            vTaskDelete(NULL);
            return;
        }
        delay(5);
    }
}
References core0_loaderLogic(), displayMutex, LOG, spinner, and validationComplete.
Referenced by setup().
init_logger()
void init_logger ()
Initialize Logger.
Definition at line 148 of file main.cpp.
                   {
    LOG_INIT("/logs/debug.log", &using_ears_sdcard);
    LOG("Setup started.");
    LOGF("Free memory: %d bytes", ESP.getFreeHeap());
}
References LOG, LOG_INIT, LOGF, and using_ears_sdcard.
Referenced by setup().
loop()
void loop ()
Main loop function @description During development, this loop monitors system status.
Returns
void
Definition at line 457 of file main.cpp.
            {
    // Development monitoring
    static uint32_t lastPrint = 0;
    if (millis() - lastPrint > 5000) {
        LOGF("[Monitor] Free heap: %d bytes", ESP.getFreeHeap());
        LOGF("[Monitor] Running on Core: %d", xPortGetCoreID());
        lastPrint = millis();
    }
    delay(1000);
}
References LOGF.
millis_cb()
uint32_t millis_cb (void)
Callback function to provide millis() to LVGL @description LVGL requires a millisecond tick source to manage its timing.
Returns
uint32_t
Definition at line 141 of file main.cpp.
{
    return millis();
}
Referenced by setup().
my_disp_flush()
void my_disp_flush (lv_display_t * display, const lv_area_t * area, uint8_t * px_map)
LVGL display flush callback.
Parameters
display
area
px_map
Definition at line 126 of file main.cpp.
{
    uint32_t w = lv_area_get_width(area);
    uint32_t h = lv_area_get_height(area);
    gfx->draw16bitRGBBitmap(area->x1, area->y1, (uint16_t *)px_map, w, h);
    lv_display_flush_ready(display);
}
References gfx.
Referenced by setup().
setup()
void setup ()
Primary setup function @description Initializes hardware and creates tasks for both cores Runs on Core 1 by default.
Returns
void
Definition at line 367 of file main.cpp.
             {
    // Initialize Serial for debugging (keep for emergency fallback)
    Serial.begin(115200);
    delay(1000);
    // Initialize Logger first
    init_logger();
    LOG("\n\n=== EARS Dual-Core System Starting ===");
    LOGF("Setup running on Core: %d", xPortGetCoreID());
    // Create mutex for display synchronization
    displayMutex = xSemaphoreCreateMutex();
    // Step 1: Initialize backlight
    pinMode(GFX_BL, OUTPUT);
    digitalWrite(GFX_BL, HIGH);
    LOG("Backlight: ON");
    // Step 2: Initialize display
    LOG("Initializing display...");
    gfx->begin();
    gfx->fillScreen(EARS_RGB565_BLACK);
    LOG("Display: Initialized");
    // Step 3: Initialize LVGL
    LOG("Initializing LVGL...");
    lv_init();
    lv_tick_set_cb(millis_cb);
    disp = lv_display_create(screenWidth, screenHeight);
    lv_display_set_flush_cb(disp, my_disp_flush);
    lv_display_set_buffers(disp, buf1, buf2, sizeof(buf1), LV_DISPLAY_RENDER_MODE_PARTIAL);
    LOG("LVGL: Initialized");
    // Step 4: Create loading screen with spinner
    LOG("Creating loading screen...");
    lv_obj_t *scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, lv_color_hex(EARS_RGB888_BLACK), 0);
    // Create spinner (loading animation)
    spinner = lv_spinner_create(scr);
    lv_obj_set_size(spinner, 80, 80);
    lv_obj_center(spinner);
    lv_obj_set_style_arc_color(spinner, lv_color_hex(0x00FF00), LV_PART_INDICATOR);
    // Create status label below spinner
    status_label = lv_label_create(scr);
    lv_label_set_text(status_label, "Starting...");
    lv_obj_set_style_text_color(status_label, lv_color_hex(EARS_RGB888_WHITE), 0);
    lv_obj_set_style_text_font(status_label, &lv_font_montserrat_16, 0);
    lv_obj_align(status_label, LV_ALIGN_CENTER, 0, 60);
    LOG("Loading screen: Created");
    // Step 5: Create Core 0 task for NVS validation
    LOG("Creating Core 0 validation task...");
    xTaskCreatePinnedToCore(
        Core0_NVSValidation,      // Task function
        "NVS_Validation",         // Name
        4096,                     // Stack size (bytes)
        NULL,                     // Parameters
        1,                        // Priority (1 = low, higher = more priority)
        &Core0_ValidationTask,    // Task handle
        0                         // Core 0
    );
    // Step 6: Create Core 1 task for display handling
    LOG("Creating Core 1 display task...");
    xTaskCreatePinnedToCore(
        Core1_DisplayHandler,     // Task function
        "Display_Handler",        // Name
        8192,                     // Stack size (bytes) - larger for LVGL
        NULL,                     // Parameters
        2,                        // Priority (higher than validation)
        &Core1_DisplayTask,       // Task handle
        1                         // Core 1
    );
    LOG("=== Setup Complete ===");
    LOG("Core 0: Running NVS validation");
    LOG("Core 1: Running display animation\n");
}
References buf1, buf2, Core0_NVSValidation(), Core0_ValidationTask, Core1_DisplayHandler(), Core1_DisplayTask, disp, displayMutex, EARS_RGB565_BLACK, EARS_RGB888_BLACK, EARS_RGB888_WHITE, gfx, GFX_BL, init_logger(), LOG, LOGF, millis_cb(), my_disp_flush(), screenHeight, screenWidth, spinner, and status_label.
updateStatus()
void updateStatus (const char * message)
Update status message on display.
Parameters
message Status message to display
Definition at line 158 of file main.cpp.
{
    if (xSemaphoreTake(displayMutex, portMAX_DELAY)) {
        if (status_label != NULL) {
            lv_label_set_text(status_label, message);
        }
        xSemaphoreGive(displayMutex);
    }
}
References displayMutex, and status_label.
Referenced by core0_loaderLogic(), and Core0_NVSValidation().
Variable Documentation
buf1
lv_color_t buf1[screenWidth *40] static
Definition at line 68 of file main.cpp.
Referenced by setup().
buf2
lv_color_t buf2[screenWidth *40] static
Definition at line 69 of file main.cpp.
Referenced by setup().
bus
Arduino_DataBus* bus = new Arduino_ESP32SPI(3 , -1 , 5 , 1 , 2)
Definition at line 74 of file main.cpp.
Core0_ValidationTask
TaskHandle_t Core0_ValidationTask
Definition at line 106 of file main.cpp.
Referenced by setup().
Core1_DisplayTask
TaskHandle_t Core1_DisplayTask
Definition at line 107 of file main.cpp.
Referenced by setup().
disp
lv_display_t* disp
Definition at line 80 of file main.cpp.
Referenced by setup().
displayMutex
SemaphoreHandle_t displayMutex
Definition at line 113 of file main.cpp.
Referenced by Core1_DisplayHandler(), setup(), and updateStatus().
g_nvsResult
NVSValidationResult g_nvsResult
Definition at line 92 of file main.cpp.
Referenced by core0_loaderLogic(), and Core0_NVSValidation().
gfx
Arduino_GFX* gfx = new Arduino_ILI9488_18bit(bus, -1 , 1 , true)
Definition at line 75 of file main.cpp.
Referenced by my_disp_flush(), and setup().
screenHeight
const uint32_t screenHeight = 320 static
Definition at line 63 of file main.cpp.
Referenced by setup().
screenWidth
const uint32_t screenWidth = 480 static
Definition at line 62 of file main.cpp.
Referenced by setup().
spinner
lv_obj_t* spinner = NULL
Definition at line 85 of file main.cpp.
Referenced by Core1_DisplayHandler(), and setup().
status_label
lv_obj_t* status_label = NULL
Definition at line 86 of file main.cpp.
Referenced by setup(), and updateStatus().
using_ears_sdcard
EARS_sdCard using_ears_sdcard
Definition at line 101 of file main.cpp.
Referenced by init_logger().
using_nvs_eeprom
EARS_nvsEepromLib using_nvs_eeprom
Definition at line 95 of file main.cpp.
Referenced by Core0_NVSValidation().
validationComplete
volatile bool validationComplete = false
Definition at line 112 of file main.cpp.
Referenced by Core0_NVSValidation(), and Core1_DisplayHandler().