EARS-PIO-WSS3-LVGL-001: eez::flow::date Namespace Reference
eez::flow::date Namespace Reference
Data Structures
struct TimeChangeRule
Enumerations
enum Week {
Last , First , Second , Third ,
Fourth
}
enum DayOfWeek {
Sun = 1 , Mon , Tue , Wed ,
Thu , Fri , Sat
}
enum Month {
Jan = 1 , Feb , Mar , Apr ,
May , Jun , Jul , Aug ,
Sep , Oct , Nov , Dec
}
Functions
static void convertTime24to12 (int &hours, bool &am)
static bool isDst (Date time, DstRule dstRule)
static uint8_t dayOfWeek (int y, int m, int d)
static Date timeChangeRuleToLocal (TimeChangeRule &r, int year)
Date now ()
void toString (Date time, char *str, uint32_t strLen)
void toLocaleString (Date time, char *str, uint32_t strLen)
Date fromString (const char *str)
Date makeDate (int year, int month, int day, int hours, int minutes, int seconds, int milliseconds)
void breakDate (Date time, int &result_year, int &result_month, int &result_day, int &result_hours, int &result_minutes, int &result_seconds, int &result_milliseconds)
int getYear (Date time)
int getMonth (Date time)
int getDay (Date time)
int getHours (Date time)
int getMinutes (Date time)
int getSeconds (Date time)
int getMilliseconds (Date time)
Date utcToLocal (Date utc)
Date localToUtc (Date local)
Variables
static const uint8_t monthDays [] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }
struct {
TimeChangeRule eez::flow::date::dstStart
TimeChangeRule eez::flow::date::dstEnd
} g_dstRules []
Format g_localeFormat = FORMAT_DMY_24
int g_timeZone = 0
DstRule g_dstRule = DST_RULE_OFF
Enumeration Type Documentation
DayOfWeek
enum eez::flow::date::DayOfWeek
Enumerator
Sun
Mon
Tue
Wed
Thu
Fri
Sat
Definition at line 5807 of file eez-flow.cpp.
{ Sun = 1, Mon, Tue, Wed, Thu, Fri, Sat };
Month
enum eez::flow::date::Month
Enumerator
Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sep
Oct
Nov
Dec
Definition at line 5808 of file eez-flow.cpp.
{ Jan = 1, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec };
Week
enum eez::flow::date::Week
Enumerator
Last
First
Second
Third
Fourth
Definition at line 5806 of file eez-flow.cpp.
{ Last, First, Second, Third, Fourth };
Function Documentation
breakDate()
void eez::flow::date::breakDate (Date time, int & result_year, int & result_month, int & result_day, int & result_hours, int & result_minutes, int & result_seconds, int & result_milliseconds)
Definition at line 5883 of file eez-flow.cpp.
{
    uint8_t year;
    uint8_t month, monthLength;
    uint32_t days;
    result_milliseconds = time % 1000;
    time /= 1000;
    result_seconds = time % 60;
    time /= 60;
    result_minutes = time % 60;
    time /= 60;
    result_hours = time % 24;
    time /= 24;
    year = 0;
    days = 0;
    while ((unsigned)(days += (LEAP_YEAR(year) ? 366 : 365)) <= time) {
        year++;
    }
    result_year = year + 1970;
    days -= LEAP_YEAR(year) ? 366 : 365;
    time -= days;
    days = 0;
    month = 0;
    monthLength = 0;
    for (month = 0; month < 12; ++month) {
        if (month == 1) {
            if (LEAP_YEAR(year)) {
                monthLength = 29;
            } else {
                monthLength = 28;
            }
        } else {
            monthLength = monthDays[month];
        }
        if (time >= monthLength) {
            time -= monthLength;
        } else {
            break;
        }
    }
    result_month = month + 1;
    result_day = time + 1;
}
References LEAP_YEAR, and monthDays.
Referenced by getDay(), getHours(), getMilliseconds(), getMinutes(), getMonth(), getSeconds(), getYear(), isDst(), toLocaleString(), and toString().
convertTime24to12()
void eez::flow::date::convertTime24to12 (int & hours, bool & am) static
Definition at line 5974 of file eez-flow.cpp.
{
    if (hours == 0) {
        hours = 12;
        am = true;
    } else if (hours < 12) {
        am = true;
    } else if (hours == 12) {
        am = false;
    } else {
        hours = hours - 12;
        am = false;
    }
}
Referenced by toLocaleString().
dayOfWeek()
uint8_t eez::flow::date::dayOfWeek (int y, int m, int d) static
Definition at line 5998 of file eez-flow.cpp.
{
    static int t[] = { 0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4 };
    if (m < 3) {
        --y;
    }
    return (y + y / 4 - y / 100 + y / 400 + t[m - 1] + d) % 7 + 1;
}
Referenced by timeChangeRuleToLocal().
fromString()
Date eez::flow::date::fromString (const char * str)
Definition at line 5855 of file eez-flow.cpp.
{
    int year = 0, month = 0, day = 0, hours = 0, minutes = 0, seconds = 0, milliseconds = 0;
    sscanf(str, "%d-%d-%dT%d:%d:%d.%d", &year, &month, &day, &hours, &minutes, &seconds, &milliseconds);
    return makeDate(year, month, day, hours, minutes, seconds, milliseconds);
}
References makeDate().
Referenced by eez::flow::do_OPERATION_TYPE_DATE_FROM_STRING().
getDay()
int eez::flow::date::getDay (Date time)
Definition at line 5935 of file eez-flow.cpp.
                      {
    int year, month, day, hours, minutes, seconds, milliseconds;
    breakDate(time, year, month, day, hours, minutes, seconds, milliseconds);
    return day;
}
References breakDate().
Referenced by eez::flow::do_OPERATION_TYPE_DATE_GET_DAY().
getHours()
int eez::flow::date::getHours (Date time)
Definition at line 5940 of file eez-flow.cpp.
{
    int year, month, day, hours, minutes, seconds, milliseconds;
    breakDate(time, year, month, day, hours, minutes, seconds, milliseconds);
    return hours;
}
References breakDate().
Referenced by eez::flow::do_OPERATION_TYPE_DATE_GET_HOURS().
getMilliseconds()
int eez::flow::date::getMilliseconds (Date time)
Definition at line 5955 of file eez-flow.cpp.
{
    int year, month, day, hours, minutes, seconds, milliseconds;
    breakDate(time, year, month, day, hours, minutes, seconds, milliseconds);
    return milliseconds;
}
References breakDate().
Referenced by eez::flow::do_OPERATION_TYPE_DATE_GET_MILLISECONDS().
getMinutes()
int eez::flow::date::getMinutes (Date time)
Definition at line 5945 of file eez-flow.cpp.
{
    int year, month, day, hours, minutes, seconds, milliseconds;
    breakDate(time, year, month, day, hours, minutes, seconds, milliseconds);
    return minutes;
}
References breakDate().
Referenced by eez::flow::do_OPERATION_TYPE_DATE_GET_MINUTES().
getMonth()
int eez::flow::date::getMonth (Date time)
Definition at line 5930 of file eez-flow.cpp.
{
    int year, month, day, hours, minutes, seconds, milliseconds;
    breakDate(time, year, month, day, hours, minutes, seconds, milliseconds);
    return month;
}
References breakDate().
Referenced by eez::flow::do_OPERATION_TYPE_DATE_GET_MONTH().
getSeconds()
int eez::flow::date::getSeconds (Date time)
Definition at line 5950 of file eez-flow.cpp.
{
    int year, month, day, hours, minutes, seconds, milliseconds;
    breakDate(time, year, month, day, hours, minutes, seconds, milliseconds);
    return seconds;
}
References breakDate().
Referenced by eez::flow::do_OPERATION_TYPE_DATE_GET_SECONDS().
getYear()
int eez::flow::date::getYear (Date time)
Definition at line 5925 of file eez-flow.cpp.
                       {
    int year, month, day, hours, minutes, seconds, milliseconds;
    breakDate(time, year, month, day, hours, minutes, seconds, milliseconds);
    return year;
}
References breakDate().
Referenced by eez::flow::do_OPERATION_TYPE_DATE_GET_YEAR().
isDst()
bool eez::flow::date::isDst (Date time, DstRule dstRule) static
Definition at line 5987 of file eez-flow.cpp.
{
    if (dstRule == DST_RULE_OFF) {
        return false;
    }
    int year, month, day, hours, minutes, seconds, milliseconds;
    breakDate(local, year, month, day, hours, minutes, seconds, milliseconds);
    Date dstStart = timeChangeRuleToLocal(g_dstRules[dstRule - 1].dstStart, year);
    Date dstEnd = timeChangeRuleToLocal(g_dstRules[dstRule - 1].dstEnd, year);
    return (dstStart < dstEnd && (local >= dstStart && local < dstEnd)) ||
           (dstStart > dstEnd && (local >= dstStart || local < dstEnd));
}
References breakDate(), dstEnd, dstStart, g_dstRules, and timeChangeRuleToLocal().
Referenced by localToUtc(), and utcToLocal().
localToUtc()
Date eez::flow::date::localToUtc (Date local)
Definition at line 5967 of file eez-flow.cpp.
{
    Date utc = local - ((g_timeZone / 100) * 60 + g_timeZone % 100) * 60L * 1000L;
    if (isDst(local, g_dstRule)) {
        utc -= SECONDS_PER_HOUR * 1000L;
    }
    return utc;
}
References g_dstRule, g_timeZone, isDst(), and SECONDS_PER_HOUR.
makeDate()
Date eez::flow::date::makeDate (int year, int month, int day, int hours, int minutes, int seconds, int milliseconds)
Definition at line 5860 of file eez-flow.cpp.
{
    year -= 1970;
    Date time = year * 365 * SECONDS_PER_DAY;
    for (int i = 0; i < year; i++) {
        if (LEAP_YEAR(i)) {
            time += SECONDS_PER_DAY;
        }
    }
    for (int i = 1; i < month; i++) {
        if ((i == 2) && LEAP_YEAR(year)) {
            time += SECONDS_PER_DAY * 29;
        } else {
            time += SECONDS_PER_DAY * monthDays[i - 1];
        }
    }
    time += (day - 1) * SECONDS_PER_DAY;
    time += hours * SECONDS_PER_HOUR;
    time += minutes * SECONDS_PER_MINUTE;
    time += seconds;
    time *= 1000;
    time += milliseconds;
    return time;
}
References LEAP_YEAR, monthDays, SECONDS_PER_DAY, SECONDS_PER_HOUR, and SECONDS_PER_MINUTE.
Referenced by eez::flow::do_OPERATION_TYPE_DATE_MAKE(), fromString(), and timeChangeRuleToLocal().
now()
Date eez::flow::date::now ()
Definition at line 5830 of file eez-flow.cpp.
           {
    return utcToLocal(getDateNowHook());
}
References eez::flow::getDateNowHook, and utcToLocal().
Referenced by eez::flow::do_OPERATION_TYPE_DATE_NOW().
timeChangeRuleToLocal()
Date eez::flow::date::timeChangeRuleToLocal (TimeChangeRule & r, int year) static
Definition at line 6005 of file eez-flow.cpp.
{
    uint8_t month = r.month;
    uint8_t week = r.week;
    if (week == 0) {
        if (++month > 12) {
            month = 1;
            ++year;
        }
        week = 1;
    }
    Date time = makeDate(year, month, 1, r.hours, 0, 0, 0);
    uint8_t dow = dayOfWeek(year, month, 1);
    time += (7 * (week - 1) + (r.dow - dow + 7) % 7) * SECONDS_PER_DAY;
    if (r.week == 0) {
        time -= 7 * SECONDS_PER_DAY;
    }
    return time;
}
References dayOfWeek(), eez::flow::date::TimeChangeRule::dow, eez::flow::date::TimeChangeRule::hours, makeDate(), eez::flow::date::TimeChangeRule::month, SECONDS_PER_DAY, and eez::flow::date::TimeChangeRule::week.
Referenced by isDst().
toLocaleString()
void eez::flow::date::toLocaleString (Date time, char * str, uint32_t strLen)
Definition at line 5838 of file eez-flow.cpp.
{
    int year, month, day, hours, minutes, seconds, milliseconds;
    breakDate(time, year, month, day, hours, minutes, seconds, milliseconds);
    if (g_localeFormat == FORMAT_DMY_24) {
        snprintf(str, strLen, "%02d-%02d-%02d %02d:%02d:%02d.%03d", day, month, year, hours, minutes, seconds, milliseconds);
    } else if (g_localeFormat == FORMAT_MDY_24) {
        snprintf(str, strLen, "%02d-%02d-%02d %02d:%02d:%02d.%03d", month, day, year, hours, minutes, seconds, milliseconds);
    } else if (g_localeFormat == FORMAT_DMY_12) {
        bool am;
        convertTime24to12(hours, am);
        snprintf(str, strLen, "%02d-%02d-%02d %02d:%02d:%02d.%03d %s", day, month, year, hours, minutes, seconds, milliseconds, am ? "AM" : "PM");
    } else if (g_localeFormat == FORMAT_MDY_12) {
        bool am;
        convertTime24to12(hours, am);
        snprintf(str, strLen, "%02d-%02d-%02d %02d:%02d:%02d.%03d %s", month, day, year, hours, minutes, seconds, milliseconds, am ? "AM" : "PM");
    }
}
References breakDate(), convertTime24to12(), and g_localeFormat.
Referenced by eez::DATE_value_to_text(), and eez::flow::do_OPERATION_TYPE_DATE_TO_LOCALE_STRING().
toString()
void eez::flow::date::toString (Date time, char * str, uint32_t strLen)
Definition at line 5833 of file eez-flow.cpp.
{
    int year, month, day, hours, minutes, seconds, milliseconds;
    breakDate(time, year, month, day, hours, minutes, seconds, milliseconds);
    snprintf(str, strLen, "%04d-%02d-%02dT%02d:%02d:%02d.%06d", year, month, day, hours, minutes, seconds, milliseconds);
}
References breakDate().
Referenced by eez::flow::do_OPERATION_TYPE_DATE_TO_STRING().
utcToLocal()
Date eez::flow::date::utcToLocal (Date utc)
Definition at line 5960 of file eez-flow.cpp.
{
    Date local = utc + ((g_timeZone / 100) * 60 + g_timeZone % 100) * 60L * 1000L;
    if (isDst(local, g_dstRule)) {
        local += SECONDS_PER_HOUR * 1000L;
    }
    return local;
}
References g_dstRule, g_timeZone, isDst(), and SECONDS_PER_HOUR.
Referenced by now().
Variable Documentation
dstEnd
TimeChangeRule eez::flow::date::dstEnd
Definition at line 5817 of file eez-flow.cpp.
Referenced by isDst().
dstStart
TimeChangeRule eez::flow::date::dstStart
Definition at line 5816 of file eez-flow.cpp.
Referenced by isDst().
g_dstRule
DstRule eez::flow::date::g_dstRule = DST_RULE_OFF
Definition at line 5825 of file eez-flow.cpp.
Referenced by localToUtc(), and utcToLocal().
[struct]
struct { ... } eez::flow::date::g_dstRules[]
Initial value:
= {
    { { Last, Sun, Mar, 2 }, { Last, Sun, Oct, 3 } },
    { { Second, Sun, Mar, 2 }, { First, Sun, Nov, 2 } },
    { { First, Sun, Oct, 2 }, { First, Sun, Apr, 3 } },
}
Referenced by isDst().
g_localeFormat
Format eez::flow::date::g_localeFormat = FORMAT_DMY_24
Definition at line 5823 of file eez-flow.cpp.
Referenced by toLocaleString().
g_timeZone
int eez::flow::date::g_timeZone = 0
Definition at line 5824 of file eez-flow.cpp.
Referenced by localToUtc(), and utcToLocal().
monthDays
const uint8_t eez::flow::date::monthDays[] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 } static
Definition at line 5805 of file eez-flow.cpp.
{ 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
Referenced by breakDate(), and makeDate().