EARS-PIO-WSS3-LVGL-001: eez::flow Namespace Reference
eez::flow Namespace Reference
Namespaces
namespace date
Data Structures
struct AnimateComponenentExecutionState
struct CompareActionComponent
struct ConstantActionComponent
struct CounterComponenentExecutionState
struct DelayComponenentExecutionState
struct LabelOutActionComponent
struct LoopComponenentExecutionState
struct LVGLExecutionState
struct LVGLApiExecutionState
struct LVGLUserWidgetComponent
struct MQTTEventActionComponenent
struct MQTTEvent
struct MQTTEventActionComponenentExecutionState
struct MQTTConnectionEventHandler
struct MQTTConnection
struct OutputActionComponent
struct ShowPageActionComponent
struct WatchVariableComponenentExecutionState
struct WatchListNode
struct WatchList
Typedefs
typedef void(* ExecuteComponentFunctionType) (FlowState *flowState, unsigned componentIndex)
typedef void(* ActionType) (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
Enumerations
enum PropertyCode {
NONE , ARC_VALUE , BAR_VALUE , BASIC_X ,
BASIC_Y , BASIC_WIDTH , BASIC_HEIGHT , BASIC_OPACITY ,
BASIC_HIDDEN , BASIC_CHECKED , BASIC_DISABLED , DROPDOWN_SELECTED ,
IMAGE_IMAGE , IMAGE_ANGLE , IMAGE_ZOOM , LABEL_TEXT ,
ROLLER_SELECTED , SLIDER_VALUE , KEYBOARD_TEXTAREA
}
enum GroupActions {
GROUP_ACTION_SET_WRAP = 0 , GROUP_ACTION_FOCUS_OBJ = 1 , GROUP_ACTION_FOCUS_NEXT = 2 , GROUP_ACTION_FOCUS_PREVIOUS = 3 ,
GROUP_ACTION_FOCUS_FREEZE = 4 , GROUP_ACTION_SET_EDITING = 5
}
enum MessagesToDebugger {
MESSAGE_TO_DEBUGGER_STATE_CHANGED , MESSAGE_TO_DEBUGGER_ADD_TO_QUEUE , MESSAGE_TO_DEBUGGER_REMOVE_FROM_QUEUE , MESSAGE_TO_DEBUGGER_GLOBAL_VARIABLE_INIT ,
MESSAGE_TO_DEBUGGER_LOCAL_VARIABLE_INIT , MESSAGE_TO_DEBUGGER_COMPONENT_INPUT_INIT , MESSAGE_TO_DEBUGGER_VALUE_CHANGED , MESSAGE_TO_DEBUGGER_FLOW_STATE_CREATED ,
MESSAGE_TO_DEBUGGER_FLOW_STATE_TIMELINE_CHANGED , MESSAGE_TO_DEBUGGER_FLOW_STATE_DESTROYED , MESSAGE_TO_DEBUGGER_FLOW_STATE_ERROR , MESSAGE_TO_DEBUGGER_LOG ,
MESSAGE_TO_DEBUGGER_PAGE_CHANGED , MESSAGE_TO_DEBUGGER_COMPONENT_EXECUTION_STATE_CHANGED , MESSAGE_TO_DEBUGGER_COMPONENT_ASYNC_STATE_CHANGED
}
enum MessagesFromDebugger {
MESSAGE_FROM_DEBUGGER_RESUME , MESSAGE_FROM_DEBUGGER_PAUSE , MESSAGE_FROM_DEBUGGER_SINGLE_STEP , MESSAGE_FROM_DEBUGGER_ADD_BREAKPOINT ,
MESSAGE_FROM_DEBUGGER_REMOVE_BREAKPOINT , MESSAGE_FROM_DEBUGGER_ENABLE_BREAKPOINT , MESSAGE_FROM_DEBUGGER_DISABLE_BREAKPOINT , MESSAGE_FROM_DEBUGGER_MODE
}
enum LogItemType {
LOG_ITEM_TYPE_FATAL , LOG_ITEM_TYPE_ERROR , LOG_ITEM_TYPE_WARNING , LOG_ITEM_TYPE_SCPI ,
LOG_ITEM_TYPE_INFO , LOG_ITEM_TYPE_DEBUG
}
enum DebuggerState { DEBUGGER_STATE_RESUMED , DEBUGGER_STATE_PAUSED , DEBUGGER_STATE_SINGLE_STEP , DEBUGGER_STATE_STOPPED }
enum FormatType {
type_int , type_signed_char , type_short_int , type_long_int ,
type_long_long_int , type_intmax_t , type_size_t , type_unsigned_int ,
type_unsigned_char , type_unsigned_short_int , type_unsigned_long_int , type_unsigned_long_long_int ,
type_uintmax_t , type_double , type_string
}
enum FormatLength {
length_none , length_hh , length_h , length_l ,
length_ll , length_j , length_z , length_t ,
length_L
}
Functions
void executeStartComponent (FlowState *flowState, unsigned componentIndex)
void executeEndComponent (FlowState *flowState, unsigned componentIndex)
void executeInputComponent (FlowState *flowState, unsigned componentIndex)
void executeOutputComponent (FlowState *flowState, unsigned componentIndex)
void executeWatchVariableComponent (FlowState *flowState, unsigned componentIndex)
void executeEvalExprComponent (FlowState *flowState, unsigned componentIndex)
void executeSetVariableComponent (FlowState *flowState, unsigned componentIndex)
void executeSwitchComponent (FlowState *flowState, unsigned componentIndex)
void executeCompareComponent (FlowState *flowState, unsigned componentIndex)
void executeIsTrueComponent (FlowState *flowState, unsigned componentIndex)
void executeConstantComponent (FlowState *flowState, unsigned componentIndex)
void executeLogComponent (FlowState *flowState, unsigned componentIndex)
void executeCallActionComponent (FlowState *flowState, unsigned componentIndex)
void executeDelayComponent (FlowState *flowState, unsigned componentIndex)
void executeErrorComponent (FlowState *flowState, unsigned componentIndex)
void executeCatchErrorComponent (FlowState *flowState, unsigned componentIndex)
void executeCounterComponent (FlowState *flowState, unsigned componentIndex)
void executeLoopComponent (FlowState *flowState, unsigned componentIndex)
void executeShowPageComponent (FlowState *flowState, unsigned componentIndex)
void executeSelectLanguageComponent (FlowState *flowState, unsigned componentIndex)
void executeAnimateComponent (FlowState *flowState, unsigned componentIndex)
void executeSetColorThemeComponent (FlowState *flowState, unsigned componentIndex)
void executeNoopComponent (FlowState *flowState, unsigned componentIndex)
void executeOnEventComponent (FlowState *flowState, unsigned componentIndex)
void executeLVGLComponent (FlowState *flowState, unsigned componentIndex)
void executeLVGLUserWidgetComponent (FlowState *flowState, unsigned componentIndex)
void executeSortArrayComponent (FlowState *flowState, unsigned componentIndex)
void executeTestAndSetComponent (FlowState *flowState, unsigned componentIndex)
void executeMQTTInitComponent (FlowState *flowState, unsigned componentIndex)
void executeMQTTConnectComponent (FlowState *flowState, unsigned componentIndex)
void executeMQTTDisconnectComponent (FlowState *flowState, unsigned componentIndex)
void executeMQTTEventComponent (FlowState *flowState, unsigned componentIndex)
void executeMQTTSubscribeComponent (FlowState *flowState, unsigned componentIndex)
void executeMQTTUnsubscribeComponent (FlowState *flowState, unsigned componentIndex)
void executeMQTTPublishComponent (FlowState *flowState, unsigned componentIndex)
void executeLabelInComponent (FlowState *flowState, unsigned componentIndex)
void executeLabelOutComponent (FlowState *flowState, unsigned componentIndex)
void executeLVGLApiComponent (FlowState *flowState, unsigned componentIndex)
void registerComponent (ComponentTypes componentType, ExecuteComponentFunctionType executeComponentFunction)
void executeComponent (FlowState *flowState, unsigned componentIndex)
void executeCallAction (FlowState *flowState, unsigned componentIndex, int flowIndex, const Value &inputValue)
bool getCallActionValue (FlowState *flowState, unsigned componentIndex, Value &value)
static void anim_callback_set_x (void *obj, int32_t v)
static int32_t anim_callback_get_x (lv_anim_t *a)
static void anim_callback_set_y (void *obj, int32_t v)
static int32_t anim_callback_get_y (lv_anim_t *a)
static void anim_callback_set_width (void *obj, int32_t v)
static int32_t anim_callback_get_width (lv_anim_t *a)
static void anim_callback_set_height (void *obj, int32_t v)
static int32_t anim_callback_get_height (lv_anim_t *a)
static void anim_callback_set_opacity (void *obj, int32_t v)
static int32_t anim_callback_get_opacity (lv_anim_t *a)
static void anim_callback_set_image_zoom (void *obj, int32_t v)
static int32_t anim_callback_get_image_zoom (lv_anim_t *a)
static void anim_callback_set_image_angle (void *obj, int32_t v)
static int32_t anim_callback_get_image_angle (lv_anim_t *a)
static void changeScreen (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void changeToPreviousScreen (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objSetX (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objGetX (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objSetY (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objGetY (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objSetWidth (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objGetWidth (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objSetHeight (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objGetHeight (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objSetStyleOpa (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objGetStyleOpa (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objAddStyle (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objRemoveStyle (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objSetFlagHidden (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objAddFlag (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objClearFlag (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objHasFlag (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objSetStateChecked (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objSetStateDisabled (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objAddState (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objClearState (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void objHasState (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void arcSetValue (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void barSetValue (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void dropdownSetSelected (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void imageSetSrc (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void imageSetAngle (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void imageSetZoom (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void labelSetText (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void qrCodeUpdate (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void rollerSetSelected (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void sliderSetValue (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void sliderSetValueLeft (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void sliderSetRange (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void keyboardSetTextarea (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void groupFocusObj (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void groupFocusNext (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void groupFocusPrev (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void groupGetFocused (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void groupFocusFreeze (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void groupSetWrap (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void groupSetEditing (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void playAnimation (lv_obj_t *obj, int32_t start, int32_t end, int32_t delay, int32_t time, bool relative, bool instant, int32_t path, lv_anim_exec_xcb_t set_callback, lv_anim_get_value_cb_t get_callback)
static void animX (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void animY (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void animWidth (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void animHeight (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void animOpacity (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void animImageZoom (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void animImageAngle (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void createScreen (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void deleteScreen (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void isScreenCreated (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void calendarSetTodayDate (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void calendarSetShowedDate (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void calendarSetHighlightedDate (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void calendarGetPressedDate (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void buttonMatrixSetButtonCtrl (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
static void buttonMatrixClearButtonCtrl (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
LVGLUserWidgetExecutionState * createUserWidgetFlowState (FlowState *flowState, unsigned userWidgetWidgetComponentIndex)
static MQTTConnection * addConnection (void *handle)
static MQTTConnection * findConnection (void *handle)
static void deleteConnection (void *handle)
static MQTTConnectionEventHandler * addConnectionEventHandler (void *handle, MQTTEventActionComponenentExecutionState *componentExecutionState)
static void removeEventHandler (MQTTEventActionComponenentExecutionState *componentExecutionState)
void onFreeMQTTConnection (ArrayValue *mqttConnectionValue)
static int elementCompare (const void *a, const void *b)
void sortArray (SortArrayActionComponent *component, ArrayValue *array)
void setDebuggerMessageSubsciptionFilter (uint32_t filter)
static bool isSubscribedTo (MessagesToDebugger messageType)
static void setDebuggerState (DebuggerState newState)
void onDebuggerClientConnected ()
void onDebuggerClientDisconnected ()
void processDebuggerInput (char *buffer, uint32_t length)
bool canExecuteStep (FlowState *&flowState, unsigned &componentIndex)
static void writeValueAddr (const void *pValue)
static void writeString (const char *str)
static void writeArrayType (uint32_t arrayType)
static void writeArray (const ArrayValue *arrayValue)
static void writeHex (char *dst, uint8_t *src, size_t srcLength)
static void writeValue (const Value &value)
void onStarted (Assets *assets)
void onStopped ()
void onAddToQueue (FlowState *flowState, int sourceComponentIndex, int sourceOutputIndex, unsigned targetComponentIndex, int targetInputIndex)
void onRemoveFromQueue ()
void onValueChanged (const Value *pValue)
void onFlowStateCreated (FlowState *flowState)
void onFlowStateDestroyed (FlowState *flowState)
void onFlowStateTimelineChanged (FlowState *flowState)
void onFlowError (FlowState *flowState, int componentIndex, const char *errorMessage)
void onComponentExecutionStateChanged (FlowState *flowState, int componentIndex)
void onComponentAsyncStateChanged (FlowState *flowState, int componentIndex)
static void writeLogMessage (const char *str)
static void writeLogMessage (const char *str, size_t len)
void logInfo (FlowState *flowState, unsigned componentIndex, const char *message)
void logScpiCommand (FlowState *flowState, unsigned componentIndex, const char *cmd)
void logScpiQuery (FlowState *flowState, unsigned componentIndex, const char *query)
void logScpiQueryResult (FlowState *flowState, unsigned componentIndex, const char *resultText, size_t resultTextLen)
void onPageChanged (int previousPageId, int activePageId, bool activePageIsFromStack, bool previousPageIsStillOnStack)
static void evalExpression (FlowState *flowState, const uint8_t *instructions, int *numInstructionBytes)
bool evalExpression (FlowState *flowState, int componentIndex, const uint8_t *instructions, Value &result, const FlowError &errorMessage, int *numInstructionBytes, const int32_t *iterators)
bool evalAssignableExpression (FlowState *flowState, int componentIndex, const uint8_t *instructions, Value &result, const FlowError &errorMessage, int *numInstructionBytes, const int32_t *iterators)
bool evalProperty (FlowState *flowState, int componentIndex, int propertyIndex, Value &result, const FlowError &errorMessage, int *numInstructionBytes, const int32_t *iterators)
bool evalAssignableProperty (FlowState *flowState, int componentIndex, int propertyIndex, Value &result, const FlowError &errorMessage, int *numInstructionBytes, const int32_t *iterators)
static void doStop ()
unsigned start (Assets *assets)
void tick ()
void stop ()
bool isFlowStopped ()
unsigned getTickMaxDurationCounter ()
FlowState * getPageFlowState (Assets *assets, int16_t pageIndex)
int getPageIndex (FlowState *flowState)
void deletePageFlowState (Assets *assets, int16_t pageIndex)
Value getGlobalVariable (uint32_t globalVariableIndex)
Value getGlobalVariable (Assets *assets, uint32_t globalVariableIndex)
void setGlobalVariable (uint32_t globalVariableIndex, const Value &value)
void setGlobalVariable (Assets *assets, uint32_t globalVariableIndex, const Value &value)
Value getUserProperty (unsigned propertyIndex)
void setUserProperty (unsigned propertyIndex, const Value &value)
AsyncAction * beginAsyncExecution ()
void endAsyncExecution (AsyncAction *asyncAction)
Value getUserPropertyAsync (AsyncAction *asyncAction, unsigned propertyIndex)
void setUserPropertyAsync (AsyncAction *asyncAction, unsigned propertyIndex, const Value &value)
void onArrayValueFree (ArrayValue *arrayValue)
static void replacePage (int16_t pageId, uint32_t animType, uint32_t speed, uint32_t delay)
static void showKeyboard (Value label, Value initialText, Value minChars, Value maxChars, bool isPassword, void(*onOk)(char *), void(*onCancel)())
static void showKeypad (Value label, Value initialValue, Value min, Value max, Unit unit, void(*onOk)(float), void(*onCancel)())
static void stopScript ()
static void scpiComponentInit ()
static void startToDebuggerMessage ()
static void writeDebuggerBuffer (const char *buffer, uint32_t length)
static void finishToDebuggerMessage ()
static void onDebuggerInputAvailable ()
static lv_obj_t * getLvglObjectFromIndex (int32_t index)
static lv_group_t * getLvglGroupFromIndex (int32_t index)
static int32_t getLvglScreenByName (const char *name)
static int32_t getLvglObjectByName (const char *name)
static int32_t getLvglGroupByName (const char *name)
static int32_t getLvglStyleByName (const char *name)
static const void * getLvglImageByName (const char *name)
static void executeLvglAction (int actionIndex)
static void lvglObjAddStyle (lv_obj_t *object, int32_t styleIndex)
static void lvglObjRemoveStyle (lv_obj_t *object, int32_t styleIndex)
static void lvglSetColorTheme (const char *themeName)
static double getDateNowDefaultImplementation ()
Value op_add (const Value &a1, const Value &b1)
Value op_sub (const Value &a1, const Value &b1)
Value op_mul (const Value &a1, const Value &b1)
Value op_div (const Value &a1, const Value &b1)
Value op_mod (const Value &a1, const Value &b1)
Value op_left_shift (const Value &a1, const Value &b1)
Value op_right_shift (const Value &a1, const Value &b1)
Value op_binary_and (const Value &a1, const Value &b1)
Value op_binary_or (const Value &a1, const Value &b1)
Value op_binary_xor (const Value &a1, const Value &b1)
static bool is_equal (const Value &a1, const Value &b1)
static bool is_less (const Value &a1, const Value &b1)
static bool is_great (const Value &a1, const Value &b1)
Value op_eq (const Value &a1, const Value &b1)
Value op_neq (const Value &a1, const Value &b1)
Value op_less (const Value &a1, const Value &b1)
Value op_great (const Value &a1, const Value &b1)
Value op_less_eq (const Value &a1, const Value &b1)
Value op_great_eq (const Value &a1, const Value &b1)
static void do_OPERATION_TYPE_ADD (EvalStack &stack)
static void do_OPERATION_TYPE_SUB (EvalStack &stack)
static void do_OPERATION_TYPE_MUL (EvalStack &stack)
static void do_OPERATION_TYPE_DIV (EvalStack &stack)
static void do_OPERATION_TYPE_MOD (EvalStack &stack)
static void do_OPERATION_TYPE_LEFT_SHIFT (EvalStack &stack)
static void do_OPERATION_TYPE_RIGHT_SHIFT (EvalStack &stack)
static void do_OPERATION_TYPE_BINARY_AND (EvalStack &stack)
static void do_OPERATION_TYPE_BINARY_OR (EvalStack &stack)
static void do_OPERATION_TYPE_BINARY_XOR (EvalStack &stack)
static void do_OPERATION_TYPE_EQUAL (EvalStack &stack)
static void do_OPERATION_TYPE_NOT_EQUAL (EvalStack &stack)
static void do_OPERATION_TYPE_LESS (EvalStack &stack)
static void do_OPERATION_TYPE_GREATER (EvalStack &stack)
static void do_OPERATION_TYPE_LESS_OR_EQUAL (EvalStack &stack)
static void do_OPERATION_TYPE_GREATER_OR_EQUAL (EvalStack &stack)
static void do_OPERATION_TYPE_LOGICAL_AND (EvalStack &stack)
static void do_OPERATION_TYPE_LOGICAL_OR (EvalStack &stack)
static void do_OPERATION_TYPE_UNARY_PLUS (EvalStack &stack)
static void do_OPERATION_TYPE_UNARY_MINUS (EvalStack &stack)
static void do_OPERATION_TYPE_BINARY_ONE_COMPLEMENT (EvalStack &stack)
static void do_OPERATION_TYPE_NOT (EvalStack &stack)
static void do_OPERATION_TYPE_CONDITIONAL (EvalStack &stack)
static void do_OPERATION_TYPE_SYSTEM_GET_TICK (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_INDEX (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_IS_PAGE_ACTIVE (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_PAGE_TIMELINE_POSITION (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_MAKE_ARRAY_VALUE (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_LANGUAGES (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_TRANSLATE (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_THEMES (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_PARSE_INTEGER (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_PARSE_FLOAT (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_PARSE_DOUBLE (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_TO_INTEGER (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_GET_BITMAP_INDEX (EvalStack &stack)
static void do_OPERATION_TYPE_FLOW_GET_BITMAP_AS_DATA_URL (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_NOW (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_TO_STRING (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_TO_LOCALE_STRING (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_FROM_STRING (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_GET_YEAR (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_GET_MONTH (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_GET_DAY (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_GET_HOURS (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_GET_MINUTES (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_GET_SECONDS (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_GET_MILLISECONDS (EvalStack &stack)
static void do_OPERATION_TYPE_DATE_MAKE (EvalStack &stack)
static void do_OPERATION_TYPE_MATH_SIN (EvalStack &stack)
static void do_OPERATION_TYPE_MATH_COS (EvalStack &stack)
static void do_OPERATION_TYPE_MATH_POW (EvalStack &stack)
static void do_OPERATION_TYPE_MATH_LOG (EvalStack &stack)
static void do_OPERATION_TYPE_MATH_LOG10 (EvalStack &stack)
static void do_OPERATION_TYPE_MATH_ABS (EvalStack &stack)
static void do_OPERATION_TYPE_MATH_FLOOR (EvalStack &stack)
static void do_OPERATION_TYPE_MATH_CEIL (EvalStack &stack)
static float roundN (float value, unsigned int numDigits)
static double roundN (double value, unsigned int numDigits)
static void do_OPERATION_TYPE_MATH_ROUND (EvalStack &stack)
static void do_OPERATION_TYPE_MATH_MIN (EvalStack &stack)
static void do_OPERATION_TYPE_MATH_MAX (EvalStack &stack)
static void do_OPERATION_TYPE_STRING_LENGTH (EvalStack &stack)
static void do_OPERATION_TYPE_STRING_SUBSTRING (EvalStack &stack)
static void do_OPERATION_TYPE_STRING_FIND (EvalStack &stack)
static size_t do_string_format (FormatType type, const Value &b, char *result, size_t result_size, const char *format)
static void do_OPERATION_TYPE_STRING_FORMAT (EvalStack &stack)
static void do_OPERATION_TYPE_STRING_FORMAT_PREFIX (EvalStack &stack)
static void do_OPERATION_TYPE_STRING_PAD_START (EvalStack &stack)
static void do_OPERATION_TYPE_STRING_SPLIT (EvalStack &stack)
static void do_OPERATION_TYPE_STRING_FROM_CODE_POINT (EvalStack &stack)
static void do_OPERATION_TYPE_STRING_CODE_POINT_AT (EvalStack &stack)
static void do_OPERATION_TYPE_ARRAY_LENGTH (EvalStack &stack)
static void do_OPERATION_TYPE_ARRAY_SLICE (EvalStack &stack)
static void do_OPERATION_TYPE_ARRAY_ALLOCATE (EvalStack &stack)
static void do_OPERATION_TYPE_ARRAY_APPEND (EvalStack &stack)
static void do_OPERATION_TYPE_ARRAY_INSERT (EvalStack &stack)
static void do_OPERATION_TYPE_ARRAY_REMOVE (EvalStack &stack)
static void do_OPERATION_TYPE_ARRAY_CLONE (EvalStack &stack)
static void do_OPERATION_TYPE_LVGL_METER_TICK_INDEX (EvalStack &stack)
static void do_OPERATION_TYPE_CRYPTO_SHA256 (EvalStack &stack)
static void do_OPERATION_TYPE_BLOB_ALLOCATE (EvalStack &stack)
static void do_OPERATION_TYPE_BLOB_TO_STRING (EvalStack &stack)
static void do_OPERATION_TYPE_JSON_GET (EvalStack &stack)
static void do_OPERATION_TYPE_JSON_CLONE (EvalStack &stack)
static void do_OPERATION_TYPE_EVENT_GET_CODE (EvalStack &stack)
static void do_OPERATION_TYPE_EVENT_GET_CURRENT_TARGET (EvalStack &stack)
static void do_OPERATION_TYPE_EVENT_GET_TARGET (EvalStack &stack)
static void do_OPERATION_TYPE_EVENT_GET_USER_DATA (EvalStack &stack)
static void do_OPERATION_TYPE_EVENT_GET_KEY (EvalStack &stack)
static void do_OPERATION_TYPE_EVENT_GET_GESTURE_DIR (EvalStack &stack)
static void do_OPERATION_TYPE_EVENT_GET_ROTARY_DIFF (EvalStack &stack)
bool isInputEmpty (const Value &inputValue)
Value getEmptyInputValue ()
void initGlobalVariables (Assets *assets)
static bool isComponentReadyToRun (FlowState *flowState, unsigned componentIndex)
static bool pingComponent (FlowState *flowState, unsigned componentIndex, int sourceComponentIndex=-1, int sourceOutputIndex=-1, int targetInputIndex=-1)
static FlowState * initFlowState (Assets *assets, int flowIndex, FlowState *parentFlowState, int parentComponentIndex, const Value &inputValue)
FlowState * initActionFlowState (int flowIndex, FlowState *parentFlowState, int parentComponentIndex, const Value &inputValue)
FlowState * initPageFlowState (Assets *assets, int flowIndex, FlowState *parentFlowState, int parentComponentIndex)
void incRefCounterForFlowState (FlowState *flowState)
void decRefCounterForFlowState (FlowState *flowState)
bool canFreeFlowState (FlowState *flowState)
void freeFlowState (FlowState *flowState)
void freeAllChildrenFlowStates (FlowState *firstChildFlowState)
void deallocateComponentExecutionState (FlowState *flowState, unsigned componentIndex)
void resetSequenceInputs (FlowState *flowState)
void propagateValue (FlowState *flowState, unsigned componentIndex, unsigned outputIndex, const Value &value)
void propagateValue (FlowState *flowState, unsigned componentIndex, unsigned outputIndex)
void propagateValueThroughSeqout (FlowState *flowState, unsigned componentIndex)
void assignValue (FlowState *flowState, int componentIndex, Value &dstValue, const Value &srcValue)
void clearInputValue (FlowState *flowState, int inputIndex)
void startAsyncExecution (FlowState *flowState, int componentIndex)
void endAsyncExecution (FlowState *flowState, int componentIndex)
void onEvent (FlowState *flowState, FlowEvent flowEvent, Value eventValue)
static bool findCatchErrorComponent (FlowState *flowState, FlowState *&catchErrorFlowState, int &catchErrorComponentIndex)
void throwError (FlowState *flowState, int componentIndex, const char *errorMessage)
void throwError (FlowState *flowState, int componentIndex, const FlowError &error)
void enableThrowError (bool enable)
void queueReset ()
size_t getQueueSize ()
size_t getMaxQueueSize ()
bool addToQueue (FlowState *flowState, unsigned componentIndex, int sourceComponentIndex, int sourceOutputIndex, int targetInputIndex, bool continuousTask)
bool peekNextTaskFromQueue (FlowState *&flowState, unsigned &componentIndex, bool &continuousTask)
void removeNextTaskFromQueue ()
bool isInQueue (FlowState *flowState, unsigned componentIndex)
void removeTasksFromQueueForFlowState (FlowState *flowState)
WatchListNode * watchListAdd (FlowState *flowState, unsigned componentIndex)
void watchListRemove (WatchListNode *node)
void visitWatchList ()
void watchListReset ()
void removeWatchesForFlowState (FlowState *flowState)
unsigned getWatchListSize ()
Variables
static ExecuteComponentFunctionType g_executeComponentFunctions []
FlowState * g_executeActionFlowState
unsigned g_executeActionComponentIndex
lv_anim_exec_xcb_t anim_set_callbacks []
lv_anim_get_value_cb_t anim_get_callbacks []
int32_t(* anim_path_callbacks [])(const lv_anim_t *a)
static ActionType actions []
MQTTConnection * g_firstMQTTConnection = nullptr
MQTTConnection * g_lastMQTTConnection = nullptr
SortArrayActionComponent * g_sortArrayActionComponent
bool g_debuggerIsConnected
static uint32_t g_messageSubsciptionFilter = 0xFFFFFFFF
static DebuggerState g_debuggerState
static bool g_skipNextBreakpoint
static char g_inputFromDebugger [64]
static unsigned g_inputFromDebuggerPosition
int g_debuggerMode = DEBUGGER_MODE_RUN
char outputBuffer [64]
int outputBufferPosition = 0
EvalStack g_stack
static const uint32_t FLOW_TICK_MAX_DURATION_MS = 5
static unsigned g_tick_max_duration_count = 0
int g_selectedLanguage = 0
FlowState * g_firstFlowState
FlowState * g_lastFlowState
static bool g_isStopping = false
static bool g_isStopped = true
void(* replacePageHook)(int16_t pageId, uint32_t animType, uint32_t speed, uint32_t delay) = replacePage
void(* showKeyboardHook)(Value label, Value initialText, Value minChars, Value maxChars, bool isPassword, void(*onOk)(char *), void(*onCancel)()) = showKeyboard
void(* showKeypadHook)(Value label, Value initialValue, Value min, Value max, Unit unit, void(*onOk)(float), void(*onCancel)()) = showKeypad
void(* stopScriptHook)() = stopScript
void(* scpiComponentInitHook)() = scpiComponentInit
void(* startToDebuggerMessageHook)() = startToDebuggerMessage
void(* writeDebuggerBufferHook)(const char *buffer, uint32_t length) = writeDebuggerBuffer
void(* finishToDebuggerMessageHook)() = finishToDebuggerMessage
void(* onDebuggerInputAvailableHook)() = onDebuggerInputAvailable
lv_obj_t *(* getLvglObjectFromIndexHook)(int32_t index) = getLvglObjectFromIndex
lv_group_t *(* getLvglGroupFromIndexHook)(int32_t index) = getLvglGroupFromIndex
int32_t(* getLvglScreenByNameHook)(const char *name) = getLvglScreenByName
int32_t(* getLvglObjectByNameHook)(const char *name) = getLvglObjectByName
int32_t(* getLvglGroupByNameHook)(const char *name) = getLvglGroupByName
int32_t(* getLvglStyleByNameHook)(const char *name) = getLvglStyleByName
const void *(* getLvglImageByNameHook)(const char *name) = getLvglImageByName
void(* executeLvglActionHook)(int actionIndex) = executeLvglAction
void(* lvglObjAddStyleHook)(lv_obj_t *object, int32_t styleIndex) = lvglObjAddStyle
void(* lvglObjRemoveStyleHook)(lv_obj_t *object, int32_t styleIndex) = lvglObjRemoveStyle
void(* lvglSetColorThemeHook)(const char *themeName) = lvglSetColorTheme
double(* getDateNowHook)() = getDateNowDefaultImplementation
void(* onFlowErrorHook)(FlowState *flowState, int componentIndex, const char *errorMessage) = nullptr
EvalOperation g_evalOperations []
GlobalVariables * g_globalVariables = nullptr
static const unsigned NO_COMPONENT_INDEX = 0xFFFFFFFF
static bool g_enableThrowError = true
static const unsigned QUEUE_SIZE = 1000
struct {
FlowState * eez::flow::flowState
unsigned eez::flow::componentIndex
bool eez::flow::continuousTask
} g_queue [QUEUE_SIZE]
static unsigned g_queueHead
static unsigned g_queueTail
static unsigned g_queueMax
static bool g_queueIsFull = false
unsigned g_numNonContinuousTaskInQueue
static WatchList g_watchList
Typedef Documentation
ActionType
typedef void(* eez::flow::ActionType) (FlowState *flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > &properties, uint32_t actionIndex)
Definition at line 4720 of file eez-flow.cpp.
ExecuteComponentFunctionType
typedef void(* eez::flow::ExecuteComponentFunctionType) (FlowState *flowState, unsigned componentIndex)
Definition at line 3070 of file eez-flow.cpp.
Enumeration Type Documentation
DebuggerState
enum eez::flow::DebuggerState
Enumerator
DEBUGGER_STATE_RESUMED
DEBUGGER_STATE_PAUSED
DEBUGGER_STATE_SINGLE_STEP
DEBUGGER_STATE_STOPPED
Definition at line 6071 of file eez-flow.cpp.
                   {
    DEBUGGER_STATE_RESUMED,
    DEBUGGER_STATE_PAUSED,
    DEBUGGER_STATE_SINGLE_STEP,
    DEBUGGER_STATE_STOPPED,
};
FormatLength
enum eez::flow::FormatLength
Enumerator
length_none
length_hh
length_h
length_l
length_ll
length_j
length_z
length_t
length_L
Definition at line 9555 of file eez-flow.cpp.
             {
    length_none,
    length_hh,
    length_h,
    length_l,
    length_ll,
    length_j,
    length_z,
    length_t,
    length_L
} FormatLength;
FormatType
enum eez::flow::FormatType
Enumerator
type_int
type_signed_char
type_short_int
type_long_int
type_long_long_int
type_intmax_t
type_size_t
type_unsigned_int
type_unsigned_char
type_unsigned_short_int
type_unsigned_long_int
type_unsigned_long_long_int
type_uintmax_t
type_double
type_string
Definition at line 9538 of file eez-flow.cpp.
             {
    type_int,
    type_signed_char,
    type_short_int,
    type_long_int,
    type_long_long_int,
    type_intmax_t,
    type_size_t,
    type_unsigned_int,
    type_unsigned_char,
    type_unsigned_short_int,
    type_unsigned_long_int,
    type_unsigned_long_long_int,
    type_uintmax_t,
    type_double,
    type_string
} FormatType;
GroupActions
enum eez::flow::GroupActions
Enumerator
GROUP_ACTION_SET_WRAP
GROUP_ACTION_FOCUS_OBJ
GROUP_ACTION_FOCUS_NEXT
GROUP_ACTION_FOCUS_PREVIOUS
GROUP_ACTION_FOCUS_FREEZE
GROUP_ACTION_SET_EDITING
Definition at line 3889 of file eez-flow.cpp.
                  {
    GROUP_ACTION_SET_WRAP = 0,
    GROUP_ACTION_FOCUS_OBJ = 1,
    GROUP_ACTION_FOCUS_NEXT = 2,
    GROUP_ACTION_FOCUS_PREVIOUS = 3,
    GROUP_ACTION_FOCUS_FREEZE = 4,
    GROUP_ACTION_SET_EDITING = 5
};
LogItemType
enum eez::flow::LogItemType
Enumerator
LOG_ITEM_TYPE_FATAL
LOG_ITEM_TYPE_ERROR
LOG_ITEM_TYPE_WARNING
LOG_ITEM_TYPE_SCPI
LOG_ITEM_TYPE_INFO
LOG_ITEM_TYPE_DEBUG
Definition at line 6063 of file eez-flow.cpp.
                 {
    LOG_ITEM_TYPE_FATAL,
    LOG_ITEM_TYPE_ERROR,
    LOG_ITEM_TYPE_WARNING ,
    LOG_ITEM_TYPE_SCPI,
    LOG_ITEM_TYPE_INFO,
    LOG_ITEM_TYPE_DEBUG
};
MessagesFromDebugger
enum eez::flow::MessagesFromDebugger
Enumerator
MESSAGE_FROM_DEBUGGER_RESUME
MESSAGE_FROM_DEBUGGER_PAUSE
MESSAGE_FROM_DEBUGGER_SINGLE_STEP
MESSAGE_FROM_DEBUGGER_ADD_BREAKPOINT
MESSAGE_FROM_DEBUGGER_REMOVE_BREAKPOINT
MESSAGE_FROM_DEBUGGER_ENABLE_BREAKPOINT
MESSAGE_FROM_DEBUGGER_DISABLE_BREAKPOINT
MESSAGE_FROM_DEBUGGER_MODE
Definition at line 6053 of file eez-flow.cpp.
{
    MESSAGE_FROM_DEBUGGER_RESUME,
    MESSAGE_FROM_DEBUGGER_PAUSE,
    MESSAGE_FROM_DEBUGGER_SINGLE_STEP,
    MESSAGE_FROM_DEBUGGER_ADD_BREAKPOINT,
    MESSAGE_FROM_DEBUGGER_REMOVE_BREAKPOINT,
    MESSAGE_FROM_DEBUGGER_ENABLE_BREAKPOINT,
    MESSAGE_FROM_DEBUGGER_DISABLE_BREAKPOINT,
    MESSAGE_FROM_DEBUGGER_MODE
};
MessagesToDebugger
enum eez::flow::MessagesToDebugger
Enumerator
MESSAGE_TO_DEBUGGER_STATE_CHANGED
MESSAGE_TO_DEBUGGER_ADD_TO_QUEUE
MESSAGE_TO_DEBUGGER_REMOVE_FROM_QUEUE
MESSAGE_TO_DEBUGGER_GLOBAL_VARIABLE_INIT
MESSAGE_TO_DEBUGGER_LOCAL_VARIABLE_INIT
MESSAGE_TO_DEBUGGER_COMPONENT_INPUT_INIT
MESSAGE_TO_DEBUGGER_VALUE_CHANGED
MESSAGE_TO_DEBUGGER_FLOW_STATE_CREATED
MESSAGE_TO_DEBUGGER_FLOW_STATE_TIMELINE_CHANGED
MESSAGE_TO_DEBUGGER_FLOW_STATE_DESTROYED
MESSAGE_TO_DEBUGGER_FLOW_STATE_ERROR
MESSAGE_TO_DEBUGGER_LOG
MESSAGE_TO_DEBUGGER_PAGE_CHANGED
MESSAGE_TO_DEBUGGER_COMPONENT_EXECUTION_STATE_CHANGED
MESSAGE_TO_DEBUGGER_COMPONENT_ASYNC_STATE_CHANGED
Definition at line 6036 of file eez-flow.cpp.
{
    MESSAGE_TO_DEBUGGER_STATE_CHANGED,
    MESSAGE_TO_DEBUGGER_ADD_TO_QUEUE,
    MESSAGE_TO_DEBUGGER_REMOVE_FROM_QUEUE,
    MESSAGE_TO_DEBUGGER_GLOBAL_VARIABLE_INIT,
    MESSAGE_TO_DEBUGGER_LOCAL_VARIABLE_INIT,
    MESSAGE_TO_DEBUGGER_COMPONENT_INPUT_INIT,
    MESSAGE_TO_DEBUGGER_VALUE_CHANGED,
    MESSAGE_TO_DEBUGGER_FLOW_STATE_CREATED,
    MESSAGE_TO_DEBUGGER_FLOW_STATE_TIMELINE_CHANGED,
    MESSAGE_TO_DEBUGGER_FLOW_STATE_DESTROYED,
    MESSAGE_TO_DEBUGGER_FLOW_STATE_ERROR,
    MESSAGE_TO_DEBUGGER_LOG,
    MESSAGE_TO_DEBUGGER_PAGE_CHANGED,
    MESSAGE_TO_DEBUGGER_COMPONENT_EXECUTION_STATE_CHANGED,
    MESSAGE_TO_DEBUGGER_COMPONENT_ASYNC_STATE_CHANGED
};
PropertyCode
enum eez::flow::PropertyCode
Enumerator
NONE
ARC_VALUE
BAR_VALUE
BASIC_X
BASIC_Y
BASIC_WIDTH
BASIC_HEIGHT
BASIC_OPACITY
BASIC_HIDDEN
BASIC_CHECKED
BASIC_DISABLED
DROPDOWN_SELECTED
IMAGE_IMAGE
IMAGE_ANGLE
IMAGE_ZOOM
LABEL_TEXT
ROLLER_SELECTED
SLIDER_VALUE
KEYBOARD_TEXTAREA
Definition at line 3868 of file eez-flow.cpp.
                  {
    NONE,
    ARC_VALUE,
    BAR_VALUE,
    BASIC_X,
    BASIC_Y,
    BASIC_WIDTH,
    BASIC_HEIGHT,
    BASIC_OPACITY,
    BASIC_HIDDEN,
    BASIC_CHECKED,
    BASIC_DISABLED,
    DROPDOWN_SELECTED,
    IMAGE_IMAGE,
    IMAGE_ANGLE,
    IMAGE_ZOOM,
    LABEL_TEXT,
    ROLLER_SELECTED,
    SLIDER_VALUE,
    KEYBOARD_TEXTAREA
};
Function Documentation
addConnection()
MQTTConnection * eez::flow::addConnection (void * handle) static
Definition at line 4949 of file eez-flow.cpp.
{
    auto connection = ObjectAllocator<MQTTConnection>::allocate(0x95d9f5d1);
    if (!connection) {
        return nullptr;
    }
    connection->handle = handle;
    connection->firstEventHandler = nullptr;
    connection->lastEventHandler = nullptr;
    if (!g_firstMQTTConnection) {
        g_firstMQTTConnection = connection;
        g_lastMQTTConnection = connection;
        connection->prev = nullptr;
        connection->next = nullptr;
    } else {
        g_lastMQTTConnection->next = connection;
        connection->prev = g_lastMQTTConnection;
        connection->next = nullptr;
        g_lastMQTTConnection = connection;
    }
    return connection;
}
References g_firstMQTTConnection, and g_lastMQTTConnection.
Referenced by executeMQTTInitComponent().
addConnectionEventHandler()
MQTTConnectionEventHandler * eez::flow::addConnectionEventHandler (void * handle, MQTTEventActionComponenentExecutionState * componentExecutionState) static
Definition at line 5002 of file eez-flow.cpp.
{
    auto connection = findConnection(handle);
    if (!connection) {
        return nullptr;
    }
    auto eventHandler = ObjectAllocator<MQTTConnectionEventHandler>::allocate(0x75ccf1eb);
    if (!eventHandler) {
        return nullptr;
    }
    eventHandler->componentExecutionState = componentExecutionState;
    if (!connection->firstEventHandler) {
        connection->firstEventHandler = eventHandler;
        connection->lastEventHandler = eventHandler;
        eventHandler->prev = nullptr;
        eventHandler->next = nullptr;
    } else {
        connection->lastEventHandler->next = eventHandler;
        eventHandler->prev = connection->lastEventHandler;
        eventHandler->next = nullptr;
        connection->lastEventHandler = eventHandler;
    }
    return eventHandler;
}
References findConnection().
Referenced by executeMQTTEventComponent().
addToQueue()
bool eez::flow::addToQueue (FlowState * flowState, unsigned componentIndex, int sourceComponentIndex, int sourceOutputIndex, int targetInputIndex, bool continuousTask)
Definition at line 11092 of file eez-flow.cpp.
{
    if (g_queueIsFull) {
        throwError(flowState, componentIndex, "Execution queue is full\n");
        return false;
    }
    g_queue[g_queueTail].flowState = flowState;
    g_queue[g_queueTail].componentIndex = componentIndex;
    g_queue[g_queueTail].continuousTask = continuousTask;
    g_queueTail = (g_queueTail + 1) % QUEUE_SIZE;
    if (g_queueHead == g_queueTail) {
        g_queueIsFull = true;
    }
    size_t queueSize = getQueueSize();
    g_queueMax = g_queueMax < queueSize ? queueSize : g_queueMax;
    if (!continuousTask) {
        ++g_numNonContinuousTaskInQueue;
        onAddToQueue(flowState, sourceComponentIndex, sourceOutputIndex, componentIndex, targetInputIndex);
    }
    incRefCounterForFlowState(flowState);
    return true;
}
References addToQueue(), componentIndex, continuousTask, flowState, g_numNonContinuousTaskInQueue, g_queue, g_queueHead, g_queueIsFull, g_queueMax, g_queueTail, getQueueSize(), incRefCounterForFlowState(), onAddToQueue(), QUEUE_SIZE, and throwError().
Referenced by addToQueue(), executeAnimateComponent(), executeDelayComponent(), executeLVGLComponent(), executeLVGLUserWidgetComponent(), executeMQTTEventComponent(), executeTestAndSetComponent(), onEvent(), pingComponent(), throwError(), and tick().
anim_callback_get_height()
int32_t eez::flow::anim_callback_get_height (lv_anim_t * a) static
Definition at line 3835 of file eez-flow.cpp.
{ return lv_obj_get_height((lv_obj_t *)a->user_data); }
Referenced by animHeight().
anim_callback_get_image_angle()
int32_t eez::flow::anim_callback_get_image_angle (lv_anim_t * a) static
Definition at line 3841 of file eez-flow.cpp.
{ return lv_img_get_angle((lv_obj_t *)a->user_data); }
Referenced by animImageAngle().
anim_callback_get_image_zoom()
int32_t eez::flow::anim_callback_get_image_zoom (lv_anim_t * a) static
Definition at line 3839 of file eez-flow.cpp.
{ return lv_img_get_zoom((lv_obj_t *)a->user_data); }
Referenced by animImageZoom().
anim_callback_get_opacity()
int32_t eez::flow::anim_callback_get_opacity (lv_anim_t * a) static
Definition at line 3837 of file eez-flow.cpp.
{ return lv_obj_get_style_opa((lv_obj_t *)a->user_data, 0); }
Referenced by animOpacity().
anim_callback_get_width()
int32_t eez::flow::anim_callback_get_width (lv_anim_t * a) static
Definition at line 3833 of file eez-flow.cpp.
{ return lv_obj_get_width((lv_obj_t *)a->user_data); }
Referenced by animWidth().
anim_callback_get_x()
int32_t eez::flow::anim_callback_get_x (lv_anim_t * a) static
Definition at line 3829 of file eez-flow.cpp.
{ return lv_obj_get_x_aligned((lv_obj_t *)a->user_data); }
Referenced by animX().
anim_callback_get_y()
int32_t eez::flow::anim_callback_get_y (lv_anim_t * a) static
Definition at line 3831 of file eez-flow.cpp.
{ return lv_obj_get_y_aligned((lv_obj_t *)a->user_data); }
Referenced by animY().
anim_callback_set_height()
void eez::flow::anim_callback_set_height (void * obj, int32_t v) static
Definition at line 3834 of file eez-flow.cpp.
{ lv_obj_set_height((lv_obj_t *)obj, v); }
Referenced by animHeight().
anim_callback_set_image_angle()
void eez::flow::anim_callback_set_image_angle (void * obj, int32_t v) static
Definition at line 3840 of file eez-flow.cpp.
{ lv_img_set_angle((lv_obj_t *)obj, v); }
Referenced by animImageAngle().
anim_callback_set_image_zoom()
void eez::flow::anim_callback_set_image_zoom (void * obj, int32_t v) static
Definition at line 3838 of file eez-flow.cpp.
{ lv_img_set_zoom((lv_obj_t *)obj, v); }
Referenced by animImageZoom().
anim_callback_set_opacity()
void eez::flow::anim_callback_set_opacity (void * obj, int32_t v) static
Definition at line 3836 of file eez-flow.cpp.
{ lv_obj_set_style_opa((lv_obj_t *)obj, v, 0); }
Referenced by animOpacity().
anim_callback_set_width()
void eez::flow::anim_callback_set_width (void * obj, int32_t v) static
Definition at line 3832 of file eez-flow.cpp.
{ lv_obj_set_width((lv_obj_t *)obj, v); }
Referenced by animWidth().
anim_callback_set_x()
void eez::flow::anim_callback_set_x (void * obj, int32_t v) static
Definition at line 3828 of file eez-flow.cpp.
{ lv_obj_set_x((lv_obj_t *)obj, v); }
Referenced by animX().
anim_callback_set_y()
void eez::flow::anim_callback_set_y (void * obj, int32_t v) static
Definition at line 3830 of file eez-flow.cpp.
{ lv_obj_set_y((lv_obj_t *)obj, v); }
Referenced by animY().
animHeight()
void eez::flow::animHeight (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4639 of file eez-flow.cpp.
References ACTION_END, anim_callback_get_height(), anim_callback_set_height(), ANIM_PROPS, animHeight(), and start().
Referenced by animHeight().
animImageAngle()
void eez::flow::animImageAngle (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4651 of file eez-flow.cpp.
References ACTION_END, anim_callback_get_image_angle(), anim_callback_set_image_angle(), ANIM_PROPS, animImageAngle(), and start().
Referenced by animImageAngle().
animImageZoom()
void eez::flow::animImageZoom (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4647 of file eez-flow.cpp.
References ACTION_END, anim_callback_get_image_zoom(), anim_callback_set_image_zoom(), ANIM_PROPS, animImageZoom(), and start().
Referenced by animImageZoom().
animOpacity()
void eez::flow::animOpacity (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4643 of file eez-flow.cpp.
References ACTION_END, anim_callback_get_opacity(), anim_callback_set_opacity(), ANIM_PROPS, animOpacity(), and start().
Referenced by animOpacity().
animWidth()
void eez::flow::animWidth (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4635 of file eez-flow.cpp.
References ACTION_END, anim_callback_get_width(), anim_callback_set_width(), ANIM_PROPS, animWidth(), and start().
Referenced by animWidth().
animX()
void eez::flow::animX (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4627 of file eez-flow.cpp.
References ACTION_END, anim_callback_get_x(), anim_callback_set_x(), ANIM_PROPS, animX(), and start().
Referenced by animX().
animY()
void eez::flow::animY (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4631 of file eez-flow.cpp.
References ACTION_END, anim_callback_get_y(), anim_callback_set_y(), ANIM_PROPS, animY(), and start().
Referenced by animY().
arcSetValue()
void eez::flow::arcSetValue (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4471 of file eez-flow.cpp.
References ACTION_END, and arcSetValue().
Referenced by arcSetValue().
assignValue()
void eez::flow::assignValue (FlowState * flowState, int componentIndex, Value & dstValue, const Value & srcValue)
Definition at line 10728 of file eez-flow.cpp.
{
    if (dstValue.getType() == VALUE_TYPE_FLOW_OUTPUT) {
        propagateValue(flowState, componentIndex, dstValue.getUInt16(), srcValue);
    } else if (dstValue.getType() == VALUE_TYPE_NATIVE_VARIABLE) {
#if EEZ_OPTION_GUI
        set(g_widgetCursor, dstValue.getInt(), srcValue);
#else
        setVar(dstValue.getInt(), srcValue);
#endif
    } else {
        Value *pDstValue;
        uint32_t dstValueType = VALUE_TYPE_UNDEFINED;
        if (dstValue.getType() == VALUE_TYPE_ARRAY_ELEMENT_VALUE) {
            auto arrayElementValue = (ArrayElementValue *)dstValue.refValue;
            if (arrayElementValue->arrayValue.isBlob()) {
                auto blobRef = arrayElementValue->arrayValue.getBlob();
                if (arrayElementValue->elementIndex < 0 || arrayElementValue->elementIndex >= (int)blobRef->len) {
                    throwError(flowState, componentIndex, FlowError::Plain("Can not assign, blob element index out of bounds"));
                    return;
                }
                int err;
                int32_t elementValue = srcValue.toInt32(&err);
                if (err != 0) {
                    throwError(flowState, componentIndex, FlowError::Plain("Can not non-integer to blob"));
                } else if (elementValue < 0 || elementValue > 255) {
                    char errorMessage[100];
                    snprintf(errorMessage, sizeof(errorMessage), "Can not assign %d to blob", (int)elementValue);
                    throwError(flowState, componentIndex, FlowError::Plain(errorMessage));
                } else {
                    blobRef->blob[arrayElementValue->elementIndex] = elementValue;
                }
                return;
            } else {
                auto array = arrayElementValue->arrayValue.getArray();
                if (arrayElementValue->elementIndex < 0 || arrayElementValue->elementIndex >= (int)array->arraySize) {
                    throwError(flowState, componentIndex, FlowError::Plain("Can not assign, array element index out of bounds"));
                    return;
                }
                pDstValue = &array->values[arrayElementValue->elementIndex];
            }
        }
#if defined(EEZ_DASHBOARD_API)
        else if (dstValue.getType() == VALUE_TYPE_JSON_MEMBER_VALUE) {
            auto jsonMemberValue = (JsonMemberValue *)dstValue.refValue;
            int err = operationJsonSet(jsonMemberValue->jsonValue.getInt(), jsonMemberValue->propertyName.getString(), &srcValue);
            if (err) {
                throwError(flowState, componentIndex, FlowError::Plain("Can not assign to JSON member"));
            }
            return;
        }
#endif
        else {
            pDstValue = dstValue.pValueValue;
            dstValueType = dstValue.dstValueType;
        }
        while (true) {
            if (pDstValue->type == VALUE_TYPE_ARRAY_ELEMENT_VALUE) {
                assignValue(flowState, componentIndex, *pDstValue, srcValue);
                return;
            }
#if defined(EEZ_DASHBOARD_API)
            if (pDstValue->type == VALUE_TYPE_JSON_MEMBER_VALUE) {
                assignValue(flowState, componentIndex, *pDstValue, srcValue);
                return;
            }
#endif
            if (pDstValue->type == VALUE_TYPE_PROPERTY_REF) {
                auto propertyRef = pDstValue->getPropertyRef();
                Value dstValue;
                if (evalAssignableProperty(propertyRef->flowState, propertyRef->componentIndex, propertyRef->propertyIndex, dstValue, FlowError::Plain("Failed to evaluate an assignable user property in UserWidget"), nullptr, nullptr)) {
                    if (dstValue.getType() == VALUE_TYPE_FLOW_OUTPUT) {
                        propagateValue(propertyRef->flowState, propertyRef->componentIndex, dstValue.getUInt16(), srcValue);
                    } else {
                        assignValue(flowState, componentIndex, dstValue, srcValue);
                        onValueChanged(pDstValue);
                    }
                }
                return;
            }
            if (pDstValue->type == VALUE_TYPE_VALUE_PTR) {
                onValueChanged(pDstValue);
                pDstValue = pDstValue->pValueValue;
            } else {
                break;
            }
        }
        if (assignValue(*pDstValue, srcValue, dstValueType)) {
            onValueChanged(pDstValue);
        } else {
            char errorMessage[100];
            snprintf(errorMessage, sizeof(errorMessage), "Can not assign %s to %s\n",
                g_valueTypeNames[pDstValue->type](srcValue), g_valueTypeNames[srcValue.type](*pDstValue)
            );
            throwError(flowState, componentIndex, FlowError::Plain(errorMessage));
        }
    }
}
References assignValue(), componentIndex, evalAssignableProperty(), flowState, eez::g_valueTypeNames, onValueChanged(), propagateValue(), eez::setVar(), and throwError().
Referenced by _assignBooleanProperty(), _assignIntegerProperty(), _assignStringProperty(), assignValue(), executeLoopComponent(), executeMQTTInitComponent(), executeSetVariableComponent(), executeTestAndSetComponent(), setUserProperty(), and setUserPropertyAsync().
barSetValue()
void eez::flow::barSetValue (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4476 of file eez-flow.cpp.
                                                       : LV_ANIM_OFF);
ACTION_END
References ACTION_END, and barSetValue().
Referenced by barSetValue().
beginAsyncExecution()
AsyncAction * eez::flow::beginAsyncExecution ()
Definition at line 7224 of file eez-flow.cpp.
{
    startAsyncExecution(g_executeActionFlowState, g_executeActionComponentIndex);
    AsyncAction *asyncAction = (AsyncAction *) alloc(sizeof(AsyncAction), 0xcb44f51e);
    asyncAction->flowState = g_executeActionFlowState;
    asyncAction->componentIndex = g_executeActionComponentIndex;
    return asyncAction;
}
References eez::alloc(), g_executeActionComponentIndex, g_executeActionFlowState, and startAsyncExecution().
buttonMatrixClearButtonCtrl()
void eez::flow::buttonMatrixClearButtonCtrl (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4710 of file eez-flow.cpp.
References ACTION_END, and buttonMatrixClearButtonCtrl().
Referenced by buttonMatrixClearButtonCtrl().
buttonMatrixSetButtonCtrl()
void eez::flow::buttonMatrixSetButtonCtrl (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4700 of file eez-flow.cpp.
References ACTION_END, and buttonMatrixSetButtonCtrl().
Referenced by buttonMatrixSetButtonCtrl().
calendarGetPressedDate()
void eez::flow::calendarGetPressedDate (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4692 of file eez-flow.cpp.
References ACTION_END, and calendarGetPressedDate().
Referenced by calendarGetPressedDate().
calendarSetHighlightedDate()
void eez::flow::calendarSetHighlightedDate (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4681 of file eez-flow.cpp.
References ACTION_END, and calendarSetHighlightedDate().
Referenced by calendarSetHighlightedDate().
calendarSetShowedDate()
void eez::flow::calendarSetShowedDate (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4675 of file eez-flow.cpp.
References ACTION_END, and calendarSetShowedDate().
Referenced by calendarSetShowedDate().
calendarSetTodayDate()
void eez::flow::calendarSetTodayDate (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4668 of file eez-flow.cpp.
References ACTION_END, and calendarSetTodayDate().
Referenced by calendarSetTodayDate().
canExecuteStep()
bool eez::flow::canExecuteStep (FlowState *& flowState, unsigned & componentIndex)
Definition at line 6164 of file eez-flow.cpp.
{
    if (!g_debuggerIsConnected) {
        return true;
    }
    if (!isSubscribedTo(MESSAGE_TO_DEBUGGER_ADD_TO_QUEUE)) {
        return true;
    }
    if (g_debuggerState == DEBUGGER_STATE_PAUSED) {
        return false;
    }
    if (g_debuggerState == DEBUGGER_STATE_SINGLE_STEP) {
        g_skipNextBreakpoint = false;
        setDebuggerState(DEBUGGER_STATE_PAUSED);
        return true;
    }
    auto component = flowState->flow->components[componentIndex];
    if (g_skipNextBreakpoint) {
        if (component->breakpoint) {
            g_skipNextBreakpoint = false;
        }
    } else {
        if (component->breakpoint) {
            g_skipNextBreakpoint = true;
            setDebuggerState(DEBUGGER_STATE_PAUSED);
            return false;
        }
    }
    return true;
}
References componentIndex, DEBUGGER_STATE_PAUSED, DEBUGGER_STATE_SINGLE_STEP, flowState, g_debuggerIsConnected, g_debuggerState, g_skipNextBreakpoint, isSubscribedTo(), MESSAGE_TO_DEBUGGER_ADD_TO_QUEUE, and setDebuggerState().
Referenced by tick(), and visitWatchList().
canFreeFlowState()
bool eez::flow::canFreeFlowState (FlowState * flowState)
Definition at line 10575 of file eez-flow.cpp.
{
    if (!flowState->isAction) {
        return false;
    }
    if (flowState->refCounter > 0) {
        return false;
    }
    return true;
}
References canFreeFlowState(), and flowState.
Referenced by canFreeFlowState(), endAsyncExecution(), executeCallAction(), tick(), and visitWatchList().
changeScreen()
void eez::flow::changeScreen (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4307 of file eez-flow.cpp.
{
        BOOL_PROP(useStack);
        if (useStack) {
            eez_flow_push_screen(screen, (lv_scr_load_anim_t)fadeMode, speed, delay);
        } else {
            eez::flow::replacePageHook(screen, (lv_scr_load_anim_t)fadeMode, speed, delay);
        }
    } else {
        eez_flow_push_screen(screen, (lv_scr_load_anim_t)fadeMode, speed, delay);
    }
ACTION_END
References changeScreen().
Referenced by changeScreen().
changeToPreviousScreen()
void eez::flow::changeToPreviousScreen (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4323 of file eez-flow.cpp.
References ACTION_END, and changeToPreviousScreen().
Referenced by changeToPreviousScreen().
clearInputValue()
void eez::flow::clearInputValue (FlowState * flowState, int inputIndex)
Definition at line 10825 of file eez-flow.cpp.
{
    flowState->values[inputIndex] = Value();
    onValueChanged(flowState->values + inputIndex);
}
References clearInputValue(), flowState, and onValueChanged().
Referenced by clearInputValue().
createScreen()
void eez::flow::createScreen (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4655 of file eez-flow.cpp.
References ACTION_END, and createScreen().
Referenced by createScreen().
createUserWidgetFlowState()
LVGLUserWidgetExecutionState * eez::flow::createUserWidgetFlowState (FlowState * flowState, unsigned userWidgetWidgetComponentIndex)
Definition at line 4820 of file eez-flow.cpp.
{
    auto component = (LVGLUserWidgetComponent *)flowState->flow->components[userWidgetWidgetComponentIndex];
    auto userWidgetFlowState = initPageFlowState(flowState->assets, component->flowIndex, flowState, userWidgetWidgetComponentIndex);
    userWidgetFlowState->lvglWidgetStartIndex = component->widgetStartIndex;
    auto offset = defs_v3::LVGL_USER_WIDGET_WIDGET_USER_PROPERTIES_START;
    for (uint32_t i = offset; i < component->properties.count; i++) {
        Value value = Value::makePropertyRef(flowState, userWidgetWidgetComponentIndex, i, 0x5166d8a4);
        auto propValuePtr = userWidgetFlowState->values + userWidgetFlowState->flow->componentInputs.count + (i - offset);
        *propValuePtr = value;
        onValueChanged(propValuePtr);
    }
    auto userWidgetWidgetExecutionState = allocateComponentExecutionState<LVGLUserWidgetExecutionState>(flowState, userWidgetWidgetComponentIndex);
    userWidgetWidgetExecutionState->flowState = userWidgetFlowState;
    return userWidgetWidgetExecutionState;
}
References flowState, initPageFlowState(), and onValueChanged().
Referenced by executeLVGLUserWidgetComponent(), and getFlowState().
deallocateComponentExecutionState()
void eez::flow::deallocateComponentExecutionState (FlowState * flowState, unsigned componentIndex)
Definition at line 10638 of file eez-flow.cpp.
{
    auto executionState = flowState->componenentExecutionStates[componentIndex];
    if (executionState) {
        auto component = flowState->flow->components[componentIndex];
        if (TRACK_REF_COUNTER_FOR_COMPONENT_STATE(component)) {
            decRefCounterForFlowState(flowState);
        }
        flowState->componenentExecutionStates[componentIndex] = nullptr;
        onComponentExecutionStateChanged(flowState, componentIndex);
        ObjectAllocator<ComponenentExecutionState>::deallocate(executionState);
    }
}
References componentIndex, deallocateComponentExecutionState(), decRefCounterForFlowState(), flowState, and onComponentExecutionStateChanged().
Referenced by deallocateComponentExecutionState(), deleteConnection(), executeAnimateComponent(), executeCatchErrorComponent(), executeCounterComponent(), executeDelayComponent(), executeLoopComponent(), freeFlowState(), and tick().
decRefCounterForFlowState()
void eez::flow::decRefCounterForFlowState (FlowState * flowState)
Definition at line 10569 of file eez-flow.cpp.
{
    flowState->refCounter--;
    for (auto parent = flowState->parentFlowState; parent; parent = parent->parentFlowState) {
        parent->refCounter--;
    }
}
References decRefCounterForFlowState(), and flowState.
Referenced by deallocateComponentExecutionState(), decRefCounterForFlowState(), endAsyncExecution(), removeNextTaskFromQueue(), and visitWatchList().
deleteConnection()
void eez::flow::deleteConnection (void * handle) static
Definition at line 4978 of file eez-flow.cpp.
{
    auto connection = findConnection(handle);
    if (!connection) {
        return;
    }
    while (connection->firstEventHandler) {
        deallocateComponentExecutionState(
            connection->firstEventHandler->componentExecutionState->flowState,
            connection->firstEventHandler->componentExecutionState->componentIndex
        );
    }
    eez_mqtt_deinit(connection->handle);
    if (connection->prev) {
        connection->prev->next = connection->next;
    } else {
        g_firstMQTTConnection = connection->next;
    }
    if (connection->next) {
        connection->next->prev = connection->prev;
    } else {
        g_lastMQTTConnection = connection->prev;
    }
    ObjectAllocator<MQTTConnection>::deallocate(connection);
}
References deallocateComponentExecutionState(), eez_mqtt_deinit(), findConnection(), g_firstMQTTConnection, and g_lastMQTTConnection.
Referenced by onFreeMQTTConnection().
deletePageFlowState()
void eez::flow::deletePageFlowState (Assets * assets, int16_t pageIndex)
Definition at line 7182 of file eez-flow.cpp.
{
    EEZ_UNUSED(assets);
    for (FlowState *flowState = g_firstFlowState; flowState; flowState = flowState->nextSibling) {
        if (flowState->flowIndex == pageIndex) {
            flowState->deleteOnNextTick = true;
            return;
        }
    }
}
References assets, EEZ_UNUSED, flowState, and g_firstFlowState.
Referenced by deletePageFlowState().
deleteScreen()
void eez::flow::deleteScreen (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4659 of file eez-flow.cpp.
References ACTION_END, and deleteScreen().
Referenced by deleteScreen().
do_OPERATION_TYPE_ADD()
void eez::flow::do_OPERATION_TYPE_ADD (EvalStack & stack) static
Definition at line 8449 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    auto result = op_add(a, b);
    if (result.getType() == VALUE_TYPE_UNDEFINED) {
        result = Value::makeError();
    }
    stack.push(result);
}
References do_OPERATION_TYPE_ADD(), and op_add().
Referenced by do_OPERATION_TYPE_ADD().
do_OPERATION_TYPE_ARRAY_ALLOCATE()
void eez::flow::do_OPERATION_TYPE_ARRAY_ALLOCATE (EvalStack & stack) static
Definition at line 9939 of file eez-flow.cpp.
{
    auto sizeValue = stack.pop();
    if (sizeValue.isError()) {
        stack.push(sizeValue);
        return;
    }
    int err;
    auto size = sizeValue.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    auto resultArrayValue = Value::makeArrayRef(size, defs_v3::ARRAY_TYPE_ANY, 0xe2d78c65);
    stack.push(resultArrayValue);
}
References do_OPERATION_TYPE_ARRAY_ALLOCATE().
Referenced by do_OPERATION_TYPE_ARRAY_ALLOCATE().
do_OPERATION_TYPE_ARRAY_APPEND()
void eez::flow::do_OPERATION_TYPE_ARRAY_APPEND (EvalStack & stack) static
Definition at line 9954 of file eez-flow.cpp.
{
    auto arrayValue = stack.pop().getValue();
    if (arrayValue.isError()) {
        stack.push(arrayValue);
        return;
    }
    auto value = stack.pop().getValue();
    if (value.isError()) {
        stack.push(value);
        return;
    }
#if defined(EEZ_DASHBOARD_API)
    if (arrayValue.isJson()) {
        stack.push(operationJsonArrayAppend(arrayValue.getInt(), &value));
        return;
    }
#endif
    if (!arrayValue.isArray()) {
        stack.push(Value::makeError());
        return;
    }
    auto array = arrayValue.getArray();
    auto resultArrayValue = Value::makeArrayRef(array->arraySize + 1, array->arrayType, 0x664c3199);
    auto resultArray = resultArrayValue.getArray();
    for (uint32_t elementIndex = 0; elementIndex < array->arraySize; elementIndex++) {
        resultArray->values[elementIndex] = array->values[elementIndex];
    }
    resultArray->values[array->arraySize] = value;
    stack.push(resultArrayValue);
}
References do_OPERATION_TYPE_ARRAY_APPEND().
Referenced by do_OPERATION_TYPE_ARRAY_APPEND().
do_OPERATION_TYPE_ARRAY_CLONE()
void eez::flow::do_OPERATION_TYPE_ARRAY_CLONE (EvalStack & stack) static
Definition at line 10075 of file eez-flow.cpp.
{
    auto arrayValue = stack.pop().getValue();
    if (arrayValue.isError()) {
        stack.push(arrayValue);
        return;
    }
    auto resultArray = arrayValue.clone();
    stack.push(resultArray);
}
References do_OPERATION_TYPE_ARRAY_CLONE().
Referenced by do_OPERATION_TYPE_ARRAY_CLONE().
do_OPERATION_TYPE_ARRAY_INSERT()
void eez::flow::do_OPERATION_TYPE_ARRAY_INSERT (EvalStack & stack) static
Definition at line 9984 of file eez-flow.cpp.
{
    auto arrayValue = stack.pop().getValue();
    if (arrayValue.isError()) {
        stack.push(arrayValue);
        return;
    }
    auto positionValue = stack.pop().getValue();
    if (positionValue.isError()) {
        stack.push(positionValue);
        return;
    }
    auto value = stack.pop().getValue();
    if (value.isError()) {
        stack.push(value);
        return;
    }
    int err;
    auto position = positionValue.toInt32(&err);
    if (err != 0) {
        stack.push(Value::makeError());
        return;
    }
#if defined(EEZ_DASHBOARD_API)
    if (arrayValue.isJson()) {
        stack.push(operationJsonArrayInsert(arrayValue.getInt(), position, &value));
        return;
    }
#endif
    if (!arrayValue.isArray()) {
        stack.push(Value::makeError());
        return;
    }
    auto array = arrayValue.getArray();
    auto resultArrayValue = Value::makeArrayRef(array->arraySize + 1, array->arrayType, 0xc4fa9cd9);
    auto resultArray = resultArrayValue.getArray();
    if (position < 0) {
        position = 0;
    } else if ((uint32_t)position > array->arraySize) {
        position = array->arraySize;
    }
    for (uint32_t elementIndex = 0; (int)elementIndex < position; elementIndex++) {
        resultArray->values[elementIndex] = array->values[elementIndex];
    }
    resultArray->values[position] = value;
    for (uint32_t elementIndex = position; elementIndex < array->arraySize; elementIndex++) {
        resultArray->values[elementIndex + 1] = array->values[elementIndex];
    }
    stack.push(resultArrayValue);
}
References do_OPERATION_TYPE_ARRAY_INSERT().
Referenced by do_OPERATION_TYPE_ARRAY_INSERT().
do_OPERATION_TYPE_ARRAY_LENGTH()
void eez::flow::do_OPERATION_TYPE_ARRAY_LENGTH (EvalStack & stack) static
Definition at line 9845 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.isArray()) {
        auto array = a.getArray();
        stack.push(Value(array->arraySize, VALUE_TYPE_UINT32));
        return;
    }
    if (a.isBlob()) {
        auto blobRef = a.getBlob();
        stack.push(Value(blobRef->len, VALUE_TYPE_UINT32));
        return;
    }
#if defined(EEZ_DASHBOARD_API)
    if (a.isJson()) {
        int length = operationJsonArrayLength(a.getInt());
        if (length >= 0) {
            stack.push(Value(length, VALUE_TYPE_UINT32));
            return;
        }
    }
#endif
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_ARRAY_LENGTH().
Referenced by do_OPERATION_TYPE_ARRAY_LENGTH().
do_OPERATION_TYPE_ARRAY_REMOVE()
void eez::flow::do_OPERATION_TYPE_ARRAY_REMOVE (EvalStack & stack) static
Definition at line 10033 of file eez-flow.cpp.
{
    auto arrayValue = stack.pop().getValue();
    if (arrayValue.isError()) {
        stack.push(arrayValue);
        return;
    }
    auto positionValue = stack.pop().getValue();
    if (positionValue.isError()) {
        stack.push(positionValue);
        return;
    }
    int err;
    auto position = positionValue.toInt32(&err);
    if (err != 0) {
        stack.push(Value::makeError());
        return;
    }
#if defined(EEZ_DASHBOARD_API)
    if (arrayValue.isJson()) {
        stack.push(operationJsonArrayRemove(arrayValue.getInt(), position));
        return;
    }
#endif
    if (!arrayValue.isArray()) {
        stack.push(Value::makeError());
        return;
    }
    auto array = arrayValue.getArray();
    if (position >= 0 && position < (int32_t)array->arraySize) {
        auto resultArrayValue = Value::makeArrayRef(array->arraySize - 1, array->arrayType, 0x40e9bb4b);
        auto resultArray = resultArrayValue.getArray();
        for (uint32_t elementIndex = 0; (int)elementIndex < position; elementIndex++) {
            resultArray->values[elementIndex] = array->values[elementIndex];
        }
        for (uint32_t elementIndex = position + 1; elementIndex < array->arraySize; elementIndex++) {
            resultArray->values[elementIndex - 1] = array->values[elementIndex];
        }
        stack.push(resultArrayValue);
    } else {
        stack.push(Value::makeError());
    }
}
References do_OPERATION_TYPE_ARRAY_REMOVE().
Referenced by do_OPERATION_TYPE_ARRAY_REMOVE().
do_OPERATION_TYPE_ARRAY_SLICE()
void eez::flow::do_OPERATION_TYPE_ARRAY_SLICE (EvalStack & stack) static
Definition at line 9872 of file eez-flow.cpp.
{
    auto numArgs = stack.pop().getInt();
    auto arrayValue = stack.pop().getValue();
    if (arrayValue.isError()) {
        stack.push(arrayValue);
        return;
    }
    int from = 0;
    if (numArgs > 1) {
        auto fromValue = stack.pop().getValue();
        if (fromValue.isError()) {
            stack.push(fromValue);
            return;
        }
        int err;
        from = fromValue.toInt32(&err);
        if (err) {
            stack.push(Value::makeError());
            return;
        }
        if (from < 0) {
            from = 0;
        }
    }
    int to = -1;
    if (numArgs > 2) {
        auto toValue = stack.pop().getValue();
        if (toValue.isError()) {
            stack.push(toValue);
            return;
        }
        int err;
        to = toValue.toInt32(&err);
        if (err) {
            stack.push(Value::makeError());
            return;
        }
        if (to < 0) {
            to = 0;
        }
    }
#if defined(EEZ_DASHBOARD_API)
    if (arrayValue.isJson()) {
        stack.push(operationJsonArraySlice(arrayValue.getInt(), from, to));
        return;
    }
#endif
    if (!arrayValue.isArray()) {
        stack.push(Value::makeError());
        return;
    }
    auto array = arrayValue.getArray();
    if (to == -1) {
        to = array->arraySize;
    }
    if (from > to) {
        stack.push(Value::makeError());
        return;
    }
    auto size = to - from;
    auto resultArrayValue = Value::makeArrayRef(size, array->arrayType, 0xe2d78c65);
    auto resultArray = resultArrayValue.getArray();
    for (int elementIndex = from; elementIndex < to && elementIndex < (int)array->arraySize; elementIndex++) {
        resultArray->values[elementIndex - from] = array->values[elementIndex];
    }
    stack.push(resultArrayValue);
}
References do_OPERATION_TYPE_ARRAY_SLICE().
Referenced by do_OPERATION_TYPE_ARRAY_SLICE().
do_OPERATION_TYPE_BINARY_AND()
void eez::flow::do_OPERATION_TYPE_BINARY_AND (EvalStack & stack) static
Definition at line 8512 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    auto result = op_binary_and(a, b);
    if (result.getType() == VALUE_TYPE_UNDEFINED) {
        result = Value::makeError();
    }
    stack.push(result);
}
References do_OPERATION_TYPE_BINARY_AND(), and op_binary_and().
Referenced by do_OPERATION_TYPE_BINARY_AND().
do_OPERATION_TYPE_BINARY_ONE_COMPLEMENT()
void eez::flow::do_OPERATION_TYPE_BINARY_ONE_COMPLEMENT (EvalStack & stack) static
Definition at line 8659 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isInt64()) {
        stack.push(Value(~a.uint64Value, VALUE_TYPE_UINT64));
        return;
    }
    if (a.isInt32()) {
        stack.push(Value(~a.uint32Value, VALUE_TYPE_UINT32));
        return;
    }
    if (a.isInt16()) {
        stack.push(Value(~a.uint16Value, VALUE_TYPE_UINT16));
        return;
    }
    if (a.isInt8()) {
        stack.push(Value(~a.uint8Value, VALUE_TYPE_UINT8));
        return;
    }
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_BINARY_ONE_COMPLEMENT().
Referenced by do_OPERATION_TYPE_BINARY_ONE_COMPLEMENT().
do_OPERATION_TYPE_BINARY_OR()
void eez::flow::do_OPERATION_TYPE_BINARY_OR (EvalStack & stack) static
Definition at line 8521 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    auto result = op_binary_or(a, b);
    if (result.getType() == VALUE_TYPE_UNDEFINED) {
        result = Value::makeError();
    }
    stack.push(result);
}
References do_OPERATION_TYPE_BINARY_OR(), and op_binary_or().
Referenced by do_OPERATION_TYPE_BINARY_OR().
do_OPERATION_TYPE_BINARY_XOR()
void eez::flow::do_OPERATION_TYPE_BINARY_XOR (EvalStack & stack) static
Definition at line 8530 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    auto result = op_binary_xor(a, b);
    if (result.getType() == VALUE_TYPE_UNDEFINED) {
        result = Value::makeError();
    }
    stack.push(result);
}
References do_OPERATION_TYPE_BINARY_XOR(), and op_binary_xor().
Referenced by do_OPERATION_TYPE_BINARY_XOR().
do_OPERATION_TYPE_BLOB_ALLOCATE()
void eez::flow::do_OPERATION_TYPE_BLOB_ALLOCATE (EvalStack & stack) static
Definition at line 10119 of file eez-flow.cpp.
{
    auto sizeValue = stack.pop();
    if (sizeValue.isError()) {
        stack.push(sizeValue);
        return;
    }
    int err;
    auto size = sizeValue.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    auto result = Value::makeBlobRef(nullptr, size, 0xd3de43f1);
    stack.push(result);
}
References do_OPERATION_TYPE_BLOB_ALLOCATE().
Referenced by do_OPERATION_TYPE_BLOB_ALLOCATE().
do_OPERATION_TYPE_BLOB_TO_STRING()
void eez::flow::do_OPERATION_TYPE_BLOB_TO_STRING (EvalStack & stack) static
Definition at line 10134 of file eez-flow.cpp.
{
#if defined(EEZ_DASHBOARD_API)
    auto blobValue = stack.pop().getValue();
    if (blobValue.isError()) {
        stack.push(blobValue);
        return;
    }
    if (!blobValue.isBlob()) {
        stack.push(Value::makeError());
        return;
    }
    auto blobRef = blobValue.getBlob();
    stack.push(operationBlobToString(blobRef->blob, blobRef->len));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_BLOB_TO_STRING().
Referenced by do_OPERATION_TYPE_BLOB_TO_STRING().
do_OPERATION_TYPE_CONDITIONAL()
void eez::flow::do_OPERATION_TYPE_CONDITIONAL (EvalStack & stack) static
Definition at line 8693 of file eez-flow.cpp.
{
    auto alternate = stack.pop();
    auto consequent = stack.pop();
    auto conditionValue = stack.pop();
    if (conditionValue.isError()) {
        stack.push(conditionValue);
        return;
    }
    int err;
    auto condition = conditionValue.toBool(&err);
    if (err != 0) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(condition ? consequent : alternate);
}
References do_OPERATION_TYPE_CONDITIONAL().
Referenced by do_OPERATION_TYPE_CONDITIONAL().
do_OPERATION_TYPE_CRYPTO_SHA256()
void eez::flow::do_OPERATION_TYPE_CRYPTO_SHA256 (EvalStack & stack) static
Definition at line 10087 of file eez-flow.cpp.
{
#if EEZ_FOR_LVGL_SHA256_OPTION
    auto value = stack.pop().getValue();
    if (value.isError()) {
        stack.push(value);
        return;
    }
    const uint8_t *data;
    uint32_t dataLen;
    if (value.isString()) {
        const char *str = value.getString();
        data = (uint8_t *)str;
        dataLen = strlen(str);
    } else if (value.isBlob()) {
        auto blobRef = value.getBlob();
        data = blobRef->blob;
        dataLen = blobRef->len;
    } else {
        stack.push(Value::makeError());
        return;
    }
    BYTE buf[SHA256_BLOCK_SIZE];
    SHA256_CTX ctx;
    sha256_init(&ctx);
    sha256_update(&ctx, data, dataLen);
    sha256_final(&ctx, buf);
    auto result = Value::makeBlobRef(buf, SHA256_BLOCK_SIZE, 0x1f0c0c0c);
    stack.push(result);
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_CRYPTO_SHA256().
Referenced by do_OPERATION_TYPE_CRYPTO_SHA256().
do_OPERATION_TYPE_DATE_FROM_STRING()
void eez::flow::do_OPERATION_TYPE_DATE_FROM_STRING (EvalStack & stack) static
Definition at line 8979 of file eez-flow.cpp.
{
#ifndef ARDUINO
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    Value dateStrValue = a.toString(0x99cb1a93);
    auto date = (double)date::fromString(dateStrValue.getString());
    stack.push(Value(date, VALUE_TYPE_DATE));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_DATE_FROM_STRING(), and eez::flow::date::fromString().
Referenced by do_OPERATION_TYPE_DATE_FROM_STRING().
do_OPERATION_TYPE_DATE_GET_DAY()
void eez::flow::do_OPERATION_TYPE_DATE_GET_DAY (EvalStack & stack) static
Definition at line 9017 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.getType() != VALUE_TYPE_DATE) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(date::getDay(a.getDouble()));
}
References do_OPERATION_TYPE_DATE_GET_DAY(), and eez::flow::date::getDay().
Referenced by do_OPERATION_TYPE_DATE_GET_DAY().
do_OPERATION_TYPE_DATE_GET_HOURS()
void eez::flow::do_OPERATION_TYPE_DATE_GET_HOURS (EvalStack & stack) static
Definition at line 9029 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.getType() != VALUE_TYPE_DATE) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(date::getHours(a.getDouble()));
}
References do_OPERATION_TYPE_DATE_GET_HOURS(), and eez::flow::date::getHours().
Referenced by do_OPERATION_TYPE_DATE_GET_HOURS().
do_OPERATION_TYPE_DATE_GET_MILLISECONDS()
void eez::flow::do_OPERATION_TYPE_DATE_GET_MILLISECONDS (EvalStack & stack) static
Definition at line 9065 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.getType() != VALUE_TYPE_DATE) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(date::getMilliseconds(a.getDouble()));
}
References do_OPERATION_TYPE_DATE_GET_MILLISECONDS(), and eez::flow::date::getMilliseconds().
Referenced by do_OPERATION_TYPE_DATE_GET_MILLISECONDS().
do_OPERATION_TYPE_DATE_GET_MINUTES()
void eez::flow::do_OPERATION_TYPE_DATE_GET_MINUTES (EvalStack & stack) static
Definition at line 9041 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.getType() != VALUE_TYPE_DATE) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(date::getMinutes(a.getDouble()));
}
References do_OPERATION_TYPE_DATE_GET_MINUTES(), and eez::flow::date::getMinutes().
Referenced by do_OPERATION_TYPE_DATE_GET_MINUTES().
do_OPERATION_TYPE_DATE_GET_MONTH()
void eez::flow::do_OPERATION_TYPE_DATE_GET_MONTH (EvalStack & stack) static
Definition at line 9005 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.getType() != VALUE_TYPE_DATE) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(date::getMonth(a.getDouble()));
}
References do_OPERATION_TYPE_DATE_GET_MONTH(), and eez::flow::date::getMonth().
Referenced by do_OPERATION_TYPE_DATE_GET_MONTH().
do_OPERATION_TYPE_DATE_GET_SECONDS()
void eez::flow::do_OPERATION_TYPE_DATE_GET_SECONDS (EvalStack & stack) static
Definition at line 9053 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.getType() != VALUE_TYPE_DATE) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(date::getSeconds(a.getDouble()));
}
References do_OPERATION_TYPE_DATE_GET_SECONDS(), and eez::flow::date::getSeconds().
Referenced by do_OPERATION_TYPE_DATE_GET_SECONDS().
do_OPERATION_TYPE_DATE_GET_YEAR()
void eez::flow::do_OPERATION_TYPE_DATE_GET_YEAR (EvalStack & stack) static
Definition at line 8993 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.getType() != VALUE_TYPE_DATE) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(date::getYear(a.getDouble()));
}
References do_OPERATION_TYPE_DATE_GET_YEAR(), and eez::flow::date::getYear().
Referenced by do_OPERATION_TYPE_DATE_GET_YEAR().
do_OPERATION_TYPE_DATE_MAKE()
void eez::flow::do_OPERATION_TYPE_DATE_MAKE (EvalStack & stack) static
Definition at line 9077 of file eez-flow.cpp.
{
    int err;
    Value value;
    value = stack.pop().getValue();
    if (value.isError()) {
        stack.push(value);
        return;
    }
    int year = value.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    value = stack.pop().getValue();
    if (value.isError()) {
        stack.push(value);
        return;
    }
    int month = value.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    value = stack.pop().getValue();
    if (value.isError()) {
        stack.push(value);
        return;
    }
    int day = value.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    value = stack.pop().getValue();
    if (value.isError()) {
        stack.push(value);
        return;
    }
    int hours = value.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    value = stack.pop().getValue();
    if (value.isError()) {
        stack.push(value);
        return;
    }
    int minutes = value.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    value = stack.pop().getValue();
    if (value.isError()) {
        stack.push(value);
        return;
    }
    int seconds = value.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    value = stack.pop().getValue();
    if (value.isError()) {
        stack.push(value);
        return;
    }
    int milliseconds = value.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    auto date = (double)date::makeDate(year, month, day, hours, minutes, seconds, milliseconds);
    stack.push(Value(date, VALUE_TYPE_DATE));
}
References do_OPERATION_TYPE_DATE_MAKE(), and eez::flow::date::makeDate().
Referenced by do_OPERATION_TYPE_DATE_MAKE().
do_OPERATION_TYPE_DATE_NOW()
void eez::flow::do_OPERATION_TYPE_DATE_NOW (EvalStack & stack) static
Definition at line 8940 of file eez-flow.cpp.
{
    stack.push(Value((double)date::now(), VALUE_TYPE_DATE));
}
References do_OPERATION_TYPE_DATE_NOW(), and eez::flow::date::now().
Referenced by do_OPERATION_TYPE_DATE_NOW().
do_OPERATION_TYPE_DATE_TO_LOCALE_STRING()
void eez::flow::do_OPERATION_TYPE_DATE_TO_LOCALE_STRING (EvalStack & stack) static
Definition at line 8961 of file eez-flow.cpp.
{
#ifndef ARDUINO
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.getType() != VALUE_TYPE_DATE) {
        stack.push(Value::makeError());
        return;
    }
    char str[128];
    date::toLocaleString(a.getDouble(), str, sizeof(str));
    stack.push(Value::makeStringRef(str, -1, 0xbe440ec8));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_DATE_TO_LOCALE_STRING(), and eez::flow::date::toLocaleString().
Referenced by do_OPERATION_TYPE_DATE_TO_LOCALE_STRING().
do_OPERATION_TYPE_DATE_TO_STRING()
void eez::flow::do_OPERATION_TYPE_DATE_TO_STRING (EvalStack & stack) static
Definition at line 8943 of file eez-flow.cpp.
{
#ifndef ARDUINO
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.getType() != VALUE_TYPE_DATE) {
        stack.push(Value::makeError());
        return;
    }
    char str[128];
    date::toString(a.getDouble(), str, sizeof(str));
    stack.push(Value::makeStringRef(str, -1, 0xbe440ec8));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_DATE_TO_STRING(), and eez::flow::date::toString().
Referenced by do_OPERATION_TYPE_DATE_TO_STRING().
do_OPERATION_TYPE_DIV()
void eez::flow::do_OPERATION_TYPE_DIV (EvalStack & stack) static
Definition at line 8476 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    auto result = op_div(a, b);
    if (result.getType() == VALUE_TYPE_UNDEFINED) {
        result = Value::makeError();
    }
    stack.push(result);
}
References do_OPERATION_TYPE_DIV(), and op_div().
Referenced by do_OPERATION_TYPE_DIV().
do_OPERATION_TYPE_EQUAL()
void eez::flow::do_OPERATION_TYPE_EQUAL (EvalStack & stack) static
Definition at line 8539 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    stack.push(op_eq(a, b));
}
References do_OPERATION_TYPE_EQUAL(), and op_eq().
Referenced by do_OPERATION_TYPE_EQUAL().
do_OPERATION_TYPE_EVENT_GET_CODE()
void eez::flow::do_OPERATION_TYPE_EVENT_GET_CODE (EvalStack & stack) static
Definition at line 10188 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
    auto eventValue = stack.pop().getValue();
    if (eventValue.type != VALUE_TYPE_EVENT) {
        stack.push(Value::makeError());
        return;
    }
    auto event = eventValue.getLVGLEventRef();
    stack.push(Value(event->code, VALUE_TYPE_UINT32));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_EVENT_GET_CODE().
Referenced by do_OPERATION_TYPE_EVENT_GET_CODE().
do_OPERATION_TYPE_EVENT_GET_CURRENT_TARGET()
void eez::flow::do_OPERATION_TYPE_EVENT_GET_CURRENT_TARGET (EvalStack & stack) static
Definition at line 10201 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
    auto eventValue = stack.pop().getValue();
    if (eventValue.type != VALUE_TYPE_EVENT) {
        stack.push(Value::makeError());
        return;
    }
    auto event = eventValue.getLVGLEventRef();
    stack.push(Value(event->currentTarget, VALUE_TYPE_WIDGET));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_EVENT_GET_CURRENT_TARGET().
Referenced by do_OPERATION_TYPE_EVENT_GET_CURRENT_TARGET().
do_OPERATION_TYPE_EVENT_GET_GESTURE_DIR()
void eez::flow::do_OPERATION_TYPE_EVENT_GET_GESTURE_DIR (EvalStack & stack) static
Definition at line 10253 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
    auto eventValue = stack.pop().getValue();
    if (eventValue.type != VALUE_TYPE_EVENT) {
        stack.push(Value::makeError());
        return;
    }
    auto event = eventValue.getLVGLEventRef();
    stack.push(Value((int)event->gestureDir, VALUE_TYPE_INT32));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_EVENT_GET_GESTURE_DIR().
Referenced by do_OPERATION_TYPE_EVENT_GET_GESTURE_DIR().
do_OPERATION_TYPE_EVENT_GET_KEY()
void eez::flow::do_OPERATION_TYPE_EVENT_GET_KEY (EvalStack & stack) static
Definition at line 10240 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
    auto eventValue = stack.pop().getValue();
    if (eventValue.type != VALUE_TYPE_EVENT) {
        stack.push(Value::makeError());
        return;
    }
    auto event = eventValue.getLVGLEventRef();
    stack.push(Value(event->key, VALUE_TYPE_UINT32));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_EVENT_GET_KEY().
Referenced by do_OPERATION_TYPE_EVENT_GET_KEY().
do_OPERATION_TYPE_EVENT_GET_ROTARY_DIFF()
void eez::flow::do_OPERATION_TYPE_EVENT_GET_ROTARY_DIFF (EvalStack & stack) static
Definition at line 10266 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
    auto eventValue = stack.pop().getValue();
    if (eventValue.type != VALUE_TYPE_EVENT) {
        stack.push(Value::makeError());
        return;
    }
    auto event = eventValue.getLVGLEventRef();
    stack.push(Value((int)event->rotaryDiff, VALUE_TYPE_INT32));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_EVENT_GET_ROTARY_DIFF().
Referenced by do_OPERATION_TYPE_EVENT_GET_ROTARY_DIFF().
do_OPERATION_TYPE_EVENT_GET_TARGET()
void eez::flow::do_OPERATION_TYPE_EVENT_GET_TARGET (EvalStack & stack) static
Definition at line 10214 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
    auto eventValue = stack.pop().getValue();
    if (eventValue.type != VALUE_TYPE_EVENT) {
        stack.push(Value::makeError());
        return;
    }
    auto event = eventValue.getLVGLEventRef();
    stack.push(Value(event->target, VALUE_TYPE_WIDGET));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_EVENT_GET_TARGET().
Referenced by do_OPERATION_TYPE_EVENT_GET_TARGET().
do_OPERATION_TYPE_EVENT_GET_USER_DATA()
void eez::flow::do_OPERATION_TYPE_EVENT_GET_USER_DATA (EvalStack & stack) static
Definition at line 10227 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
    auto eventValue = stack.pop().getValue();
    if (eventValue.type != VALUE_TYPE_EVENT) {
        stack.push(Value::makeError());
        return;
    }
    auto event = eventValue.getLVGLEventRef();
    stack.push(Value((int)event->userData, VALUE_TYPE_INT32));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_EVENT_GET_USER_DATA().
Referenced by do_OPERATION_TYPE_EVENT_GET_USER_DATA().
do_OPERATION_TYPE_FLOW_GET_BITMAP_AS_DATA_URL()
void eez::flow::do_OPERATION_TYPE_FLOW_GET_BITMAP_AS_DATA_URL (EvalStack & stack) static
Definition at line 8927 of file eez-flow.cpp.
{
#if defined(EEZ_DASHBOARD_API)
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    Value bitmapName = a.toString(0xcdc34cc3);
    stack.push(getBitmapAsDataURL(bitmapName.getString()));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_FLOW_GET_BITMAP_AS_DATA_URL().
Referenced by do_OPERATION_TYPE_FLOW_GET_BITMAP_AS_DATA_URL().
do_OPERATION_TYPE_FLOW_GET_BITMAP_INDEX()
void eez::flow::do_OPERATION_TYPE_FLOW_GET_BITMAP_INDEX (EvalStack & stack) static
Definition at line 8913 of file eez-flow.cpp.
{
#if EEZ_OPTION_GUI
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    Value bitmapName = a.toString(0x244c1880);
    int bitmapId = getBitmapIdByName(bitmapName.getString());
    stack.push(Value(bitmapId, VALUE_TYPE_INT32));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_FLOW_GET_BITMAP_INDEX().
Referenced by do_OPERATION_TYPE_FLOW_GET_BITMAP_INDEX().
do_OPERATION_TYPE_FLOW_INDEX()
void eez::flow::do_OPERATION_TYPE_FLOW_INDEX (EvalStack & stack) static
Definition at line 8712 of file eez-flow.cpp.
{
    if (!stack.iterators) {
        stack.push(Value::makeError());
        return;
    }
    auto a = stack.pop();
    int err;
    auto iteratorIndex = a.toInt32(&err);
    if (err != 0) {
        stack.push(Value::makeError());
        return;
    }
    if (iteratorIndex < 0 || iteratorIndex >= (int)MAX_ITERATORS) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(stack.iterators[iteratorIndex]);
}
References do_OPERATION_TYPE_FLOW_INDEX().
Referenced by do_OPERATION_TYPE_FLOW_INDEX().
do_OPERATION_TYPE_FLOW_IS_PAGE_ACTIVE()
void eez::flow::do_OPERATION_TYPE_FLOW_IS_PAGE_ACTIVE (EvalStack & stack) static
Definition at line 8730 of file eez-flow.cpp.
{
#if EEZ_OPTION_GUI
    bool isActive = false;
    auto pageIndex = getPageIndex(stack.flowState);
    if (pageIndex >= 0) {
        int16_t pageId = (int16_t)(pageIndex + 1);
        if (stack.flowState->assets == g_externalAssets) {
            pageId = -pageId;
        }
        for (int16_t appContextId = 0; ; appContextId++) {
            auto appContext = getAppContextFromId(appContextId);
            if (!appContext) {
                break;
            }
            if (appContext->isPageOnStack(pageId)) {
                isActive = true;
                break;
            }
        }
    }
    stack.push(Value(isActive, VALUE_TYPE_BOOLEAN));
#elif defined(EEZ_FOR_LVGL)
    auto pageIndex = getPageIndex(stack.flowState);
    stack.push(Value(pageIndex == g_currentScreen, VALUE_TYPE_BOOLEAN));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_FLOW_IS_PAGE_ACTIVE(), g_currentScreen, eez::g_externalAssets, and getPageIndex().
Referenced by do_OPERATION_TYPE_FLOW_IS_PAGE_ACTIVE().
do_OPERATION_TYPE_FLOW_LANGUAGES()
void eez::flow::do_OPERATION_TYPE_FLOW_LANGUAGES (EvalStack & stack) static
Definition at line 8820 of file eez-flow.cpp.
{
    auto &languages = stack.flowState->assets->languages;
    auto arrayValue = Value::makeArrayRef(languages.count, VALUE_TYPE_STRING, 0xff4787fc);
    auto array = arrayValue.getArray();
    for (uint32_t i = 0; i < languages.count; i++) {
        array->values[i] = Value((const char *)(languages[i]->languageID));
    }
    stack.push(arrayValue);
}
References do_OPERATION_TYPE_FLOW_LANGUAGES().
Referenced by do_OPERATION_TYPE_FLOW_LANGUAGES().
do_OPERATION_TYPE_FLOW_MAKE_ARRAY_VALUE()
void eez::flow::do_OPERATION_TYPE_FLOW_MAKE_ARRAY_VALUE (EvalStack & stack) static
Definition at line 8761 of file eez-flow.cpp.
{
    auto arrayTypeValue = stack.pop();
    if (arrayTypeValue.isError()) {
        stack.push(arrayTypeValue);
        return;
    }
    auto arraySizeValue = stack.pop();
    if (arraySizeValue.isError()) {
        stack.push(arraySizeValue);
        return;
    }
    auto numInitElementsValue = stack.pop();
    if (numInitElementsValue.isError()) {
        stack.push(numInitElementsValue);
        return;
    }
    int arrayType = arrayTypeValue.getInt();
    int err;
    int arraySize = arraySizeValue.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    int numInitElements = numInitElementsValue.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
#if defined(EEZ_DASHBOARD_API)
    if (arrayType == VALUE_TYPE_JSON) {
        Value jsonValue = operationJsonMake();
        for (int i = 0; i < arraySize; i += 2) {
            Value propertyName = stack.pop().getValue();
            if (!propertyName.isString()) {
                stack.push(Value::makeError());
                return;
            }
            Value propertyValue = stack.pop().getValue();
            if (propertyValue.isError()) {
                stack.push(propertyValue);
                return;
            }
            operationJsonSet(jsonValue.getInt(), propertyName.getString(), &propertyValue);
        }
        stack.push(jsonValue);
        return;
    }
#endif
    auto arrayValue = Value::makeArrayRef(arraySize, arrayType, 0x837260d4);
    auto array = arrayValue.getArray();
    for (int i = 0; i < arraySize; i++) {
        if (i < numInitElements) {
            array->values[i] = stack.pop().getValue();
        } else {
            array->values[i] = Value();
        }
    }
    stack.push(arrayValue);
}
References do_OPERATION_TYPE_FLOW_MAKE_ARRAY_VALUE().
Referenced by do_OPERATION_TYPE_FLOW_MAKE_ARRAY_VALUE().
do_OPERATION_TYPE_FLOW_PAGE_TIMELINE_POSITION()
void eez::flow::do_OPERATION_TYPE_FLOW_PAGE_TIMELINE_POSITION (EvalStack & stack) static
Definition at line 8758 of file eez-flow.cpp.
{
    stack.push(Value(stack.flowState->timelinePosition, VALUE_TYPE_FLOAT));
}
References do_OPERATION_TYPE_FLOW_PAGE_TIMELINE_POSITION().
Referenced by do_OPERATION_TYPE_FLOW_PAGE_TIMELINE_POSITION().
do_OPERATION_TYPE_FLOW_PARSE_DOUBLE()
void eez::flow::do_OPERATION_TYPE_FLOW_PARSE_DOUBLE (EvalStack & stack) static
Definition at line 8885 of file eez-flow.cpp.
{
    auto str = stack.pop();
    if (str.isError()) {
        stack.push(str);
        return;
    }
    int err;
    auto value = str.toDouble(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(Value(value, VALUE_TYPE_DOUBLE));
}
References do_OPERATION_TYPE_FLOW_PARSE_DOUBLE().
Referenced by do_OPERATION_TYPE_FLOW_PARSE_DOUBLE().
do_OPERATION_TYPE_FLOW_PARSE_FLOAT()
void eez::flow::do_OPERATION_TYPE_FLOW_PARSE_FLOAT (EvalStack & stack) static
Definition at line 8871 of file eez-flow.cpp.
{
    auto str = stack.pop();
    if (str.isError()) {
        stack.push(str);
        return;
    }
    int err;
    auto value = str.toFloat(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(Value(value, VALUE_TYPE_FLOAT));
}
References do_OPERATION_TYPE_FLOW_PARSE_FLOAT().
Referenced by do_OPERATION_TYPE_FLOW_PARSE_FLOAT().
do_OPERATION_TYPE_FLOW_PARSE_INTEGER()
void eez::flow::do_OPERATION_TYPE_FLOW_PARSE_INTEGER (EvalStack & stack) static
Definition at line 8857 of file eez-flow.cpp.
{
    auto str = stack.pop();
    if (str.isError()) {
        stack.push(str);
        return;
    }
    int err;
    auto value = str.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(Value((int)value, VALUE_TYPE_INT32));
}
References do_OPERATION_TYPE_FLOW_PARSE_INTEGER().
Referenced by do_OPERATION_TYPE_FLOW_PARSE_INTEGER().
do_OPERATION_TYPE_FLOW_THEMES()
void eez::flow::do_OPERATION_TYPE_FLOW_THEMES (EvalStack & stack) static
Definition at line 8848 of file eez-flow.cpp.
{
    auto &themes = stack.flowState->assets->colorsDefinition->themes;
    auto arrayValue = Value::makeArrayRef(themes.count, VALUE_TYPE_STRING, 0x03906e8f);
    auto array = arrayValue.getArray();
    for (uint32_t i = 0; i < themes.count; i++) {
        array->values[i] = Value((const char *)(themes[i]->name));
    }
    stack.push(arrayValue);
}
References do_OPERATION_TYPE_FLOW_THEMES().
Referenced by do_OPERATION_TYPE_FLOW_THEMES().
do_OPERATION_TYPE_FLOW_TO_INTEGER()
void eez::flow::do_OPERATION_TYPE_FLOW_TO_INTEGER (EvalStack & stack) static
Definition at line 8899 of file eez-flow.cpp.
{
    auto str = stack.pop();
    if (str.isError()) {
        stack.push(str);
        return;
    }
    int err;
    int value = str.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(Value(value, VALUE_TYPE_INT32));
}
References do_OPERATION_TYPE_FLOW_TO_INTEGER().
Referenced by do_OPERATION_TYPE_FLOW_TO_INTEGER().
do_OPERATION_TYPE_FLOW_TRANSLATE()
void eez::flow::do_OPERATION_TYPE_FLOW_TRANSLATE (EvalStack & stack) static
Definition at line 8829 of file eez-flow.cpp.
{
    auto textResourceIndexValue = stack.pop();
    int err;
    int textResourceIndex = textResourceIndexValue.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    int languageIndex = g_selectedLanguage;
    auto &languages = stack.flowState->assets->languages;
    if (languageIndex >= 0 && languageIndex < (int)languages.count) {
        auto &translations = languages[languageIndex]->translations;
        if (textResourceIndex >= 0 && textResourceIndex < (int)translations.count) {
            stack.push(translations[textResourceIndex]);
            return;
        }
    }
    stack.push("");
}
References do_OPERATION_TYPE_FLOW_TRANSLATE(), and g_selectedLanguage.
Referenced by do_OPERATION_TYPE_FLOW_TRANSLATE().
do_OPERATION_TYPE_GREATER()
void eez::flow::do_OPERATION_TYPE_GREATER (EvalStack & stack) static
Definition at line 8554 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    stack.push(op_great(a, b));
}
References do_OPERATION_TYPE_GREATER(), and op_great().
Referenced by do_OPERATION_TYPE_GREATER().
do_OPERATION_TYPE_GREATER_OR_EQUAL()
void eez::flow::do_OPERATION_TYPE_GREATER_OR_EQUAL (EvalStack & stack) static
Definition at line 8564 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    stack.push(op_great_eq(a, b));
}
References do_OPERATION_TYPE_GREATER_OR_EQUAL(), and op_great_eq().
Referenced by do_OPERATION_TYPE_GREATER_OR_EQUAL().
do_OPERATION_TYPE_JSON_CLONE()
void eez::flow::do_OPERATION_TYPE_JSON_CLONE (EvalStack & stack) static
Definition at line 10172 of file eez-flow.cpp.
{
#if defined(EEZ_DASHBOARD_API)
    auto jsonValue = stack.pop().getValue();
    if (jsonValue.isError()) {
        stack.push(jsonValue);
        return;
    }
    if (jsonValue.type != VALUE_TYPE_JSON) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(operationJsonClone(jsonValue.getInt()));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_JSON_CLONE().
Referenced by do_OPERATION_TYPE_JSON_CLONE().
do_OPERATION_TYPE_JSON_GET()
void eez::flow::do_OPERATION_TYPE_JSON_GET (EvalStack & stack) static
Definition at line 10151 of file eez-flow.cpp.
{
#if defined(EEZ_DASHBOARD_API)
    auto jsonValue = stack.pop().getValue();
    auto propertyValue = stack.pop();
    if (jsonValue.isError()) {
        stack.push(jsonValue);
        return;
    }
    if (jsonValue.type != VALUE_TYPE_JSON) {
        stack.push(Value::makeError());
        return;
    }
    if (propertyValue.isError()) {
        stack.push(propertyValue);
        return;
    }
    stack.push(Value::makeJsonMemberRef(jsonValue, propertyValue.toString(0xc73d02e7), 0xebcc230a));
#else
    stack.push(Value::makeError());
#endif
}
References do_OPERATION_TYPE_JSON_GET().
Referenced by do_OPERATION_TYPE_JSON_GET().
do_OPERATION_TYPE_LEFT_SHIFT()
void eez::flow::do_OPERATION_TYPE_LEFT_SHIFT (EvalStack & stack) static
Definition at line 8494 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    auto result = op_left_shift(a, b);
    if (result.getType() == VALUE_TYPE_UNDEFINED) {
        result = Value::makeError();
    }
    stack.push(result);
}
References do_OPERATION_TYPE_LEFT_SHIFT(), and op_left_shift().
Referenced by do_OPERATION_TYPE_LEFT_SHIFT().
do_OPERATION_TYPE_LESS()
void eez::flow::do_OPERATION_TYPE_LESS (EvalStack & stack) static
Definition at line 8549 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    stack.push(op_less(a, b));
}
References do_OPERATION_TYPE_LESS(), and op_less().
Referenced by do_OPERATION_TYPE_LESS().
do_OPERATION_TYPE_LESS_OR_EQUAL()
void eez::flow::do_OPERATION_TYPE_LESS_OR_EQUAL (EvalStack & stack) static
Definition at line 8559 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    stack.push(op_less_eq(a, b));
}
References do_OPERATION_TYPE_LESS_OR_EQUAL(), and op_less_eq().
Referenced by do_OPERATION_TYPE_LESS_OR_EQUAL().
do_OPERATION_TYPE_LOGICAL_AND()
void eez::flow::do_OPERATION_TYPE_LOGICAL_AND (EvalStack & stack) static
Definition at line 8569 of file eez-flow.cpp.
{
    auto bValue = stack.pop().getValue();
    auto aValue = stack.pop().getValue();
    if (aValue.isError()) {
        stack.push(aValue);
        return;
    }
    if (!aValue.toBool()) {
        stack.push(Value(false, VALUE_TYPE_BOOLEAN));
        return;
    }
    if (bValue.isError()) {
        stack.push(bValue);
        return;
    }
    stack.push(Value(bValue.toBool(), VALUE_TYPE_BOOLEAN));
}
References do_OPERATION_TYPE_LOGICAL_AND().
Referenced by do_OPERATION_TYPE_LOGICAL_AND().
do_OPERATION_TYPE_LOGICAL_OR()
void eez::flow::do_OPERATION_TYPE_LOGICAL_OR (EvalStack & stack) static
Definition at line 8586 of file eez-flow.cpp.
{
    auto bValue = stack.pop().getValue();
    auto aValue = stack.pop().getValue();
    if (aValue.isError()) {
        stack.push(aValue);
        return;
    }
    if (aValue.toBool()) {
        stack.push(Value(true, VALUE_TYPE_BOOLEAN));
        return;
    }
    if (bValue.isError()) {
        stack.push(bValue);
        return;
    }
    stack.push(Value(bValue.toBool(), VALUE_TYPE_BOOLEAN));
}
References do_OPERATION_TYPE_LOGICAL_OR().
Referenced by do_OPERATION_TYPE_LOGICAL_OR().
do_OPERATION_TYPE_LVGL_METER_TICK_INDEX()
void eez::flow::do_OPERATION_TYPE_LVGL_METER_TICK_INDEX (EvalStack & stack) static
Definition at line 10084 of file eez-flow.cpp.
{
    stack.push(g_eezFlowLvlgMeterTickIndex);
}
References do_OPERATION_TYPE_LVGL_METER_TICK_INDEX(), and g_eezFlowLvlgMeterTickIndex.
Referenced by do_OPERATION_TYPE_LVGL_METER_TICK_INDEX().
do_OPERATION_TYPE_MATH_ABS()
void eez::flow::do_OPERATION_TYPE_MATH_ABS (EvalStack & stack) static
Definition at line 9298 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.isDouble()) {
        stack.push(Value(abs(a.getDouble()), VALUE_TYPE_DOUBLE));
        return;
    }
    if (a.isFloat()) {
        stack.push(Value(abs(a.toFloat()), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt64()) {
        stack.push(Value((int64_t)abs(a.getInt64()), VALUE_TYPE_INT64));
        return;
    }
    if (a.isInt32()) {
        stack.push(Value((int)abs(a.getInt32()), VALUE_TYPE_INT32));
        return;
    }
    if (a.isInt16()) {
        stack.push(Value(abs(a.getInt16()), VALUE_TYPE_INT16));
        return;
    }
    if (a.isInt8()) {
        stack.push(Value(abs(a.getInt8()), VALUE_TYPE_INT8));
        return;
    }
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_MATH_ABS().
Referenced by do_OPERATION_TYPE_MATH_ABS().
do_OPERATION_TYPE_MATH_CEIL()
void eez::flow::do_OPERATION_TYPE_MATH_CEIL (EvalStack & stack) static
Definition at line 9350 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.isInt32OrLess()) {
        stack.push(a);
        return;
    }
    if (a.isDouble()) {
        stack.push(Value(ceil(a.getDouble()), VALUE_TYPE_DOUBLE));
        return;
    }
    if (a.isFloat()) {
        stack.push(Value(ceilf(a.toFloat()), VALUE_TYPE_FLOAT));
        return;
    }
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_MATH_CEIL().
Referenced by do_OPERATION_TYPE_MATH_CEIL().
do_OPERATION_TYPE_MATH_COS()
void eez::flow::do_OPERATION_TYPE_MATH_COS (EvalStack & stack) static
Definition at line 9177 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.isDouble()) {
        stack.push(Value(cos(a.getDouble()), VALUE_TYPE_DOUBLE));
        return;
    }
    if (a.isFloat()) {
        stack.push(Value(cosf(a.toFloat()), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt64()) {
        stack.push(Value(cos(a.toInt64()), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt32OrLess()) {
        stack.push(Value(cosf(a.int32Value), VALUE_TYPE_FLOAT));
        return;
    }
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_MATH_COS().
Referenced by do_OPERATION_TYPE_MATH_COS().
do_OPERATION_TYPE_MATH_FLOOR()
void eez::flow::do_OPERATION_TYPE_MATH_FLOOR (EvalStack & stack) static
Definition at line 9330 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.isInt32OrLess()) {
        stack.push(a);
        return;
    }
    if (a.isDouble()) {
        stack.push(Value(floor(a.getDouble()), VALUE_TYPE_DOUBLE));
        return;
    }
    if (a.isFloat()) {
        stack.push(Value(floorf(a.toFloat()), VALUE_TYPE_FLOAT));
        return;
    }
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_MATH_FLOOR().
Referenced by do_OPERATION_TYPE_MATH_FLOOR().
do_OPERATION_TYPE_MATH_LOG()
void eez::flow::do_OPERATION_TYPE_MATH_LOG (EvalStack & stack) static
Definition at line 9250 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.isDouble()) {
        stack.push(Value(log(a.getDouble()), VALUE_TYPE_DOUBLE));
        return;
    }
    if (a.isFloat()) {
        stack.push(Value(logf(a.toFloat()), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt64()) {
        stack.push(Value(log(a.toInt64()), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt32OrLess()) {
        stack.push(Value(logf(a.int32Value), VALUE_TYPE_FLOAT));
        return;
    }
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_MATH_LOG().
Referenced by do_OPERATION_TYPE_MATH_LOG().
do_OPERATION_TYPE_MATH_LOG10()
void eez::flow::do_OPERATION_TYPE_MATH_LOG10 (EvalStack & stack) static
Definition at line 9274 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.isDouble()) {
        stack.push(Value(log10(a.getDouble()), VALUE_TYPE_DOUBLE));
        return;
    }
    if (a.isFloat()) {
        stack.push(Value(log10f(a.toFloat()), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt64()) {
        stack.push(Value(log10(a.toInt64()), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt32OrLess()) {
        stack.push(Value(log10f(a.int32Value), VALUE_TYPE_FLOAT));
        return;
    }
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_MATH_LOG10().
Referenced by do_OPERATION_TYPE_MATH_LOG10().
do_OPERATION_TYPE_MATH_MAX()
void eez::flow::do_OPERATION_TYPE_MATH_MAX (EvalStack & stack) static
Definition at line 9425 of file eez-flow.cpp.
{
    auto numArgs = stack.pop().getInt();
    Value maxValue;
    for (int i = 0; i < numArgs; i++) {
        auto value = stack.pop().getValue();
        if (value.isError()) {
            stack.push(value);
            return;
        }
        if (maxValue.isUndefinedOrNull() || is_great(value, maxValue)) {
            maxValue = value;
        }
    }
    stack.push(maxValue);
}
References do_OPERATION_TYPE_MATH_MAX(), and is_great().
Referenced by do_OPERATION_TYPE_MATH_MAX().
do_OPERATION_TYPE_MATH_MIN()
void eez::flow::do_OPERATION_TYPE_MATH_MIN (EvalStack & stack) static
Definition at line 9410 of file eez-flow.cpp.
{
    auto numArgs = stack.pop().getInt();
    Value minValue;
    for (int i = 0; i < numArgs; i++) {
        auto value = stack.pop().getValue();
        if (value.isError()) {
            stack.push(value);
            return;
        }
        if (minValue.isUndefinedOrNull() || is_less(value, minValue)) {
            minValue = value;
        }
    }
    stack.push(minValue);
}
References do_OPERATION_TYPE_MATH_MIN(), and is_less().
Referenced by do_OPERATION_TYPE_MATH_MIN().
do_OPERATION_TYPE_MATH_POW()
void eez::flow::do_OPERATION_TYPE_MATH_POW (EvalStack & stack) static
Definition at line 9201 of file eez-flow.cpp.
{
    auto baseValue = stack.pop().getValue();
    if (baseValue.isError()) {
        stack.push(Value::makeError());
        return;
    }
    if (!baseValue.isInt32OrLess() && !baseValue.isFloat() && !baseValue.isDouble()) {
        stack.push(Value::makeError());
        return;
    }
    auto exponentValue = stack.pop().getValue();
    if (exponentValue.isError()) {
        stack.push(Value::makeError());
        return;
    }
    if (!exponentValue.isInt32OrLess() && !exponentValue.isFloat() && !exponentValue.isDouble()) {
        stack.push(Value::makeError());
        return;
    }
    if (baseValue.isFloat() && (exponentValue.isFloat() || exponentValue.isInt32OrLess())) {
        int err;
        float base = baseValue.toFloat(&err);
        if (err) {
            stack.push(Value::makeError());
            return;
        }
        float exponent = exponentValue.toFloat(&err);
        if (err) {
            stack.push(Value::makeError());
            return;
        }
        float result = powf(base, exponent);
        stack.push(Value(result, VALUE_TYPE_FLOAT));
    } else {
        int err;
        double base = baseValue.toDouble(&err);
        if (err) {
            stack.push(Value::makeError());
            return;
        }
        double exponent = exponentValue.toDouble(&err);
        if (err) {
            stack.push(Value::makeError());
            return;
        }
        double result = pow(base, exponent);
        stack.push(Value(result, VALUE_TYPE_DOUBLE));
    }
}
References do_OPERATION_TYPE_MATH_POW().
Referenced by do_OPERATION_TYPE_MATH_POW().
do_OPERATION_TYPE_MATH_ROUND()
void eez::flow::do_OPERATION_TYPE_MATH_ROUND (EvalStack & stack) static
Definition at line 9378 of file eez-flow.cpp.
{
    auto numArgs = stack.pop().getInt();
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    unsigned int numDigits;
    if (numArgs > 1) {
        auto b = stack.pop().getValue();
        numDigits = b.toInt32();
    } else {
        numDigits = 0;
    }
    if (a.isInt32OrLess()) {
        stack.push(a);
        return;
    }
    if (a.isDouble()) {
        stack.push(Value(roundN(a.getDouble(), numDigits), VALUE_TYPE_DOUBLE));
        return;
    }
    if (a.isFloat()) {
        stack.push(Value(roundN(a.toFloat(), numDigits), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt32OrLess()) {
        stack.push(a);
        return;
    }
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_MATH_ROUND(), and roundN().
Referenced by do_OPERATION_TYPE_MATH_ROUND().
do_OPERATION_TYPE_MATH_SIN()
void eez::flow::do_OPERATION_TYPE_MATH_SIN (EvalStack & stack) static
Definition at line 9153 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    if (a.isDouble()) {
        stack.push(Value(sin(a.getDouble()), VALUE_TYPE_DOUBLE));
        return;
    }
    if (a.isFloat()) {
        stack.push(Value(sinf(a.toFloat()), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt64()) {
        stack.push(Value(sin(a.toInt64()), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt32OrLess()) {
        stack.push(Value(sinf(a.int32Value), VALUE_TYPE_FLOAT));
        return;
    }
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_MATH_SIN().
Referenced by do_OPERATION_TYPE_MATH_SIN().
do_OPERATION_TYPE_MOD()
void eez::flow::do_OPERATION_TYPE_MOD (EvalStack & stack) static
Definition at line 8485 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    auto result = op_mod(a, b);
    if (result.getType() == VALUE_TYPE_UNDEFINED) {
        result = Value::makeError();
    }
    stack.push(result);
}
References do_OPERATION_TYPE_MOD(), and op_mod().
Referenced by do_OPERATION_TYPE_MOD().
do_OPERATION_TYPE_MUL()
void eez::flow::do_OPERATION_TYPE_MUL (EvalStack & stack) static
Definition at line 8467 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    auto result = op_mul(a, b);
    if (result.getType() == VALUE_TYPE_UNDEFINED) {
        result = Value::makeError();
    }
    stack.push(result);
}
References do_OPERATION_TYPE_MUL(), and op_mul().
Referenced by do_OPERATION_TYPE_MUL().
do_OPERATION_TYPE_NOT()
void eez::flow::do_OPERATION_TYPE_NOT (EvalStack & stack) static
Definition at line 8679 of file eez-flow.cpp.
{
    auto aValue = stack.pop();
    if (aValue.isError()) {
        stack.push(aValue);
        return;
    }
    int err;
    auto a = aValue.toBool(&err);
    if (err != 0) {
        stack.push(Value::makeError());
        return;
    }
    stack.push(Value(!a, VALUE_TYPE_BOOLEAN));
}
References do_OPERATION_TYPE_NOT().
Referenced by do_OPERATION_TYPE_NOT().
do_OPERATION_TYPE_NOT_EQUAL()
void eez::flow::do_OPERATION_TYPE_NOT_EQUAL (EvalStack & stack) static
Definition at line 8544 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    stack.push(op_neq(a, b));
}
References do_OPERATION_TYPE_NOT_EQUAL(), and op_neq().
Referenced by do_OPERATION_TYPE_NOT_EQUAL().
do_OPERATION_TYPE_RIGHT_SHIFT()
void eez::flow::do_OPERATION_TYPE_RIGHT_SHIFT (EvalStack & stack) static
Definition at line 8503 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    auto result = op_right_shift(a, b);
    if (result.getType() == VALUE_TYPE_UNDEFINED) {
        result = Value::makeError();
    }
    stack.push(result);
}
References do_OPERATION_TYPE_RIGHT_SHIFT(), and op_right_shift().
Referenced by do_OPERATION_TYPE_RIGHT_SHIFT().
do_OPERATION_TYPE_STRING_CODE_POINT_AT()
void eez::flow::do_OPERATION_TYPE_STRING_CODE_POINT_AT (EvalStack & stack) static
Definition at line 9821 of file eez-flow.cpp.
{
    auto strValue = stack.pop().getValue();
    if (strValue.isError()) {
        stack.push(strValue);
        return;
    }
    Value indexValue = stack.pop().getValue();
    if (indexValue.isError()) {
        stack.push(indexValue);
        return;
    }
    utf8_int32_t codePoint = 0;
    const char *str = strValue.getString();
    if (str) {
        int index = indexValue.toInt32();
        if (index >= 0) {
            do {
                str = utf8codepoint(str, &codePoint);
            } while (codePoint && --index >= 0);
        }
    }
    stack.push(Value((int)codePoint, VALUE_TYPE_INT32));
    return;
}
References do_OPERATION_TYPE_STRING_CODE_POINT_AT(), and utf8codepoint().
Referenced by do_OPERATION_TYPE_STRING_CODE_POINT_AT().
do_OPERATION_TYPE_STRING_FIND()
void eez::flow::do_OPERATION_TYPE_STRING_FIND (EvalStack & stack) static
Definition at line 9513 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    auto b = stack.pop().getValue();
    if (b.isError()) {
        stack.push(b);
        return;
    }
    Value aStr = a.toString(0xf616bf4d);
    Value bStr = b.toString(0x81229133);
    if (!aStr.getString() || !bStr.getString()) {
        stack.push(Value(-1, VALUE_TYPE_INT32));
        return;
    }
    const char *pos = strstr(aStr.getString(), bStr.getString());
    if (pos) {
        stack.push(Value((int)(pos - aStr.getString()), VALUE_TYPE_INT32));
        return;
    }
    stack.push(Value(-1, VALUE_TYPE_INT32));
}
References do_OPERATION_TYPE_STRING_FIND().
Referenced by do_OPERATION_TYPE_STRING_FIND().
do_OPERATION_TYPE_STRING_FORMAT()
void eez::flow::do_OPERATION_TYPE_STRING_FORMAT (EvalStack & stack) static
Definition at line 9590 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    auto b = stack.pop().getValue();
    if (b.isError()) {
        stack.push(b);
        return;
    }
    if (!a.isString()) {
        stack.push(Value::makeError());
        return;
    }
#if defined(EEZ_DASHBOARD_API)
    stack.push(operationStringFormat(a.getString(), &b));
#else
    const char *format = a.getString();
    size_t formatLength = strlen(format);
    if (formatLength == 0) {
        stack.push(Value::makeError());
        return;
    }
    char specifier = format[formatLength-1];
    char l1 = formatLength > 1 ? format[formatLength-2] : 0;
    char l2 = formatLength > 2 ? format[formatLength-3] : 0;
    FormatLength length = length_none;
    if (l1 == 'h' && l2 == 'h') length = length_hh;
    else if (l1 == 'h') length = length_h;
    else if (l1 == 'l') length = length_l;
    else if (l1 == 'l' && l2 == 'l') length = length_ll;
    else if (l1 == 'j') length = length_j;
    else if (l1 == 'z') length = length_z;
    else if (l1 == 't') length = length_t;
    else if (l1 == 'L') length = length_L;
    FormatType type = type_int;
    if (specifier == 'd' || specifier == 'i') {
        if (length == length_none) {
            type = type_int;
        } else if (length == length_hh) {
            type = type_signed_char;
        } else if (length == length_h) {
            type = type_short_int;
        } else if (length == length_l) {
            type = type_long_int;
        } else if (length == length_ll) {
            type = type_long_long_int;
        } else if (length == length_j) {
            type = type_intmax_t;
        } else if (length == length_z) {
            type = type_size_t;
        } else {
            stack.push(Value::makeError());
            return;
        }
    } else if (specifier == 'u' || specifier == 'o' || specifier == 'x' || specifier == 'X') {
        if (length == length_none) {
            type = type_unsigned_int;
        } else if (length == length_hh) {
            type = type_unsigned_char;
        } else if (length == length_h) {
            type = type_unsigned_short_int;
        } else if (length == length_l) {
            type = type_unsigned_long_int;
        } else if (length == length_ll) {
            type = type_unsigned_long_long_int;
        } else if (length == length_j) {
            type = type_uintmax_t;
        } else if (length == length_z) {
            type = type_size_t;
        } else {
            stack.push(Value::makeError());
            return;
        }
    } else if (specifier == 'f' || specifier == 'F' || specifier == 'e' || specifier == 'E' || specifier == 'g' || specifier == 'G' || specifier == 'a' || specifier == 'A') {
        type = type_double;
    } else if (specifier == 'c') {
        type = type_int;
    } else if (specifier == 's') {
        type = type_string;
    } else {
        stack.push(Value::makeError());
        return;
    }
    int resultStrLen = do_string_format(type, b, NULL, 0, format);
    char *resultStr = (char *)eez::alloc(resultStrLen + 1, 0x987ee4eb);
    do_string_format(type, b, resultStr, resultStrLen + 1, format);
    stack.push(Value::makeStringRef(resultStr, -1, 0x1e1227fd));
    eez::free(resultStr);
#endif
}
References eez::alloc(), do_OPERATION_TYPE_STRING_FORMAT(), do_string_format(), eez::free(), length_h, length_hh, length_j, length_L, length_l, length_ll, length_none, length_t, length_z, type_double, type_int, type_intmax_t, type_long_int, type_long_long_int, type_short_int, type_signed_char, type_size_t, type_string, type_uintmax_t, type_unsigned_char, type_unsigned_int, type_unsigned_long_int, type_unsigned_long_long_int, and type_unsigned_short_int.
Referenced by do_OPERATION_TYPE_STRING_FORMAT().
do_OPERATION_TYPE_STRING_FORMAT_PREFIX()
void eez::flow::do_OPERATION_TYPE_STRING_FORMAT_PREFIX (EvalStack & stack) static
Definition at line 9682 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    auto b = stack.pop().getValue();
    if (b.isError()) {
        stack.push(b);
        return;
    }
    auto c = stack.pop().getValue();
    if (c.isError()) {
        stack.push(c);
        return;
    }
    if (!a.isString()) {
        stack.push(Value::makeError());
        return;
    }
#if defined(EEZ_DASHBOARD_API)
    stack.push(operationStringFormatPrefix(a.getString(), &b, &c));
#else
    stack.push(Value::makeError());
    return;
#endif
}
References do_OPERATION_TYPE_STRING_FORMAT_PREFIX().
Referenced by do_OPERATION_TYPE_STRING_FORMAT_PREFIX().
do_OPERATION_TYPE_STRING_FROM_CODE_POINT()
void eez::flow::do_OPERATION_TYPE_STRING_FROM_CODE_POINT (EvalStack & stack) static
Definition at line 9803 of file eez-flow.cpp.
{
    Value charCodeValue = stack.pop().getValue();
    if (charCodeValue.isError()) {
        stack.push(charCodeValue);
        return;
    }
    int err = 0;
    int32_t charCode = charCodeValue.toInt32(&err);
    if (err != 0) {
        stack.push(Value::makeError());
        return;
    }
    char str[16] = {0};
    utf8catcodepoint(str, charCode, sizeof(str));
    Value resultValue = Value::makeStringRef(str, strlen(str), 0x02c2e778);
    stack.push(resultValue);
    return;
}
References do_OPERATION_TYPE_STRING_FROM_CODE_POINT(), and utf8catcodepoint().
Referenced by do_OPERATION_TYPE_STRING_FROM_CODE_POINT().
do_OPERATION_TYPE_STRING_LENGTH()
void eez::flow::do_OPERATION_TYPE_STRING_LENGTH (EvalStack & stack) static
Definition at line 9440 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    const char *aStr = a.getString();
    if (!aStr) {
        stack.push(Value::makeError());
        return;
    }
    int aStrLen = strlen(aStr);
    stack.push(Value(aStrLen, VALUE_TYPE_INT32));
}
References do_OPERATION_TYPE_STRING_LENGTH().
Referenced by do_OPERATION_TYPE_STRING_LENGTH().
do_OPERATION_TYPE_STRING_PAD_START()
void eez::flow::do_OPERATION_TYPE_STRING_PAD_START (EvalStack & stack) static
Definition at line 9709 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isError()) {
        stack.push(a);
        return;
    }
    auto b = stack.pop().getValue();
    if (b.isError()) {
        stack.push(b);
        return;
    }
    auto c = stack.pop().getValue();
    if (c.isError()) {
        stack.push(c);
        return;
    }
    auto str = a.toString(0xcf6aabe6);
    if (!str.getString()) {
        stack.push(Value::makeError());
        return;
    }
    int strLen = strlen(str.getString());
    int err;
    int targetLength = b.toInt32(&err);
    if (err) {
        stack.push(Value::makeError());
        return;
    }
    if (targetLength < strLen) {
        targetLength = strLen;
    }
    auto padStr = c.toString(0x81353bd7);
    if (!padStr.getString()) {
        stack.push(Value::makeError());
        return;
    }
    int padStrLen = strlen(padStr.getString());
    Value resultValue = Value::makeStringRef("", targetLength, 0xf43b14dd);
    if (resultValue.type == VALUE_TYPE_NULL) {
        stack.push(Value::makeError());
        return;
    }
    char *resultStr = (char *)resultValue.getString();
    auto n = targetLength - strLen;
    stringCopy(resultStr + (targetLength - strLen), strLen + 1, str.getString());
    for (int i = 0; i < n; i++) {
        resultStr[i] = padStr.getString()[i % padStrLen];
    }
    stack.push(resultValue);
}
References do_OPERATION_TYPE_STRING_PAD_START(), and eez::stringCopy().
Referenced by do_OPERATION_TYPE_STRING_PAD_START().
do_OPERATION_TYPE_STRING_SPLIT()
void eez::flow::do_OPERATION_TYPE_STRING_SPLIT (EvalStack & stack) static
Definition at line 9759 of file eez-flow.cpp.
{
    auto strValue = stack.pop().getValue();
    if (strValue.isError()) {
        stack.push(strValue);
        return;
    }
    auto delimValue = stack.pop().getValue();
    if (delimValue.isError()) {
        stack.push(delimValue);
        return;
    }
    auto str = strValue.getString();
    if (!str) {
        stack.push(Value::makeError());
        return;
    }
    auto delim = delimValue.getString();
    if (!delim) {
        stack.push(Value::makeError());
        return;
    }
    auto strLen = strlen(str);
    char *strCopy = (char *)eez::alloc(strLen + 1, 0xea9d0bc0);
    stringCopy(strCopy, strLen + 1, str);
    size_t arraySize = 0;
    char *token = strtok(strCopy, delim);
    while (token != NULL) {
        arraySize++;
        token = strtok(NULL, delim);
    }
    eez::free(strCopy);
    strCopy = (char *)eez::alloc(strLen + 1, 0xea9d0bc1);
    stringCopy(strCopy, strLen + 1, str);
    auto arrayValue = Value::makeArrayRef(arraySize, VALUE_TYPE_STRING, 0xe82675d4);
    auto array = arrayValue.getArray();
    int i = 0;
    token = strtok(strCopy, delim);
    while (token != NULL) {
        array->values[i++] = Value::makeStringRef(token, -1, 0x45209ec0);
        token = strtok(NULL, delim);
    }
    eez::free(strCopy);
    stack.push(arrayValue);
}
References eez::alloc(), do_OPERATION_TYPE_STRING_SPLIT(), eez::free(), and eez::stringCopy().
Referenced by do_OPERATION_TYPE_STRING_SPLIT().
do_OPERATION_TYPE_STRING_SUBSTRING()
void eez::flow::do_OPERATION_TYPE_STRING_SUBSTRING (EvalStack & stack) static
Definition at line 9454 of file eez-flow.cpp.
{
    auto numArgs = stack.pop().getInt();
    Value strValue = stack.pop().getValue();
    if (strValue.isError()) {
        stack.push(strValue);
        return;
    }
    Value startValue = stack.pop().getValue();
    if (startValue.isError()) {
        stack.push(startValue);
        return;
    }
    Value endValue;
    if (numArgs == 3) {
        endValue = stack.pop().getValue();
        if (endValue.isError()) {
            stack.push(endValue);
            return;
        }
    }
    const char *str = strValue.getString();
    if (!str) {
        stack.push(Value::makeError());
        return;
    }
    int strLen = (int)strlen(str);
    int err = 0;
    int start = startValue.toInt32(&err);
    if (err != 0) {
        stack.push(Value::makeError());
        return;
    }
    int end;
    if (endValue.getType() == VALUE_TYPE_UNDEFINED) {
        end = strLen;
    } else {
        end = endValue.toInt32(&err);
        if (err != 0) {
            stack.push(Value::makeError());
            return;
        }
    }
    if (start < 0) {
        start = 0;
    } else if (start > strLen) {
        start = strLen;
    }
    if (end < 0) {
        end = 0;
    } else if (end > strLen) {
        end = strLen;
    }
    if (start < end) {
        Value resultValue = Value::makeStringRef(str + start, end - start, 0x203b08a2);
        stack.push(resultValue);
        return;
    }
    stack.push(Value("", VALUE_TYPE_STRING));
}
References do_OPERATION_TYPE_STRING_SUBSTRING(), and start().
Referenced by do_OPERATION_TYPE_STRING_SUBSTRING().
do_OPERATION_TYPE_SUB()
void eez::flow::do_OPERATION_TYPE_SUB (EvalStack & stack) static
Definition at line 8458 of file eez-flow.cpp.
{
    auto b = stack.pop();
    auto a = stack.pop();
    auto result = op_sub(a, b);
    if (result.getType() == VALUE_TYPE_UNDEFINED) {
        result = Value::makeError();
    }
    stack.push(result);
}
References do_OPERATION_TYPE_SUB(), and op_sub().
Referenced by do_OPERATION_TYPE_SUB().
do_OPERATION_TYPE_SYSTEM_GET_TICK()
void eez::flow::do_OPERATION_TYPE_SYSTEM_GET_TICK (EvalStack & stack) static
Definition at line 8709 of file eez-flow.cpp.
{
    stack.push(Value(millis(), VALUE_TYPE_UINT32));
}
References do_OPERATION_TYPE_SYSTEM_GET_TICK(), and eez::millis().
Referenced by do_OPERATION_TYPE_SYSTEM_GET_TICK().
do_OPERATION_TYPE_UNARY_MINUS()
void eez::flow::do_OPERATION_TYPE_UNARY_MINUS (EvalStack & stack) static
Definition at line 8631 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isDouble()) {
        stack.push(Value(-a.getDouble(), VALUE_TYPE_DOUBLE));
        return;
    }
    if (a.isFloat()) {
        stack.push(Value(-a.toFloat(), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt64()) {
        stack.push(Value((int64_t)-a.getInt64(), VALUE_TYPE_INT64));
        return;
    }
    if (a.isInt32()) {
        stack.push(Value((int)-a.getInt32(), VALUE_TYPE_INT32));
        return;
    }
    if (a.isInt16()) {
        stack.push(Value((int16_t)-a.getInt16(), VALUE_TYPE_INT16));
        return;
    }
    if (a.isInt8()) {
        stack.push(Value((int8_t)-a.getInt8(), VALUE_TYPE_INT8));
        return;
    }
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_UNARY_MINUS().
Referenced by do_OPERATION_TYPE_UNARY_MINUS().
do_OPERATION_TYPE_UNARY_PLUS()
void eez::flow::do_OPERATION_TYPE_UNARY_PLUS (EvalStack & stack) static
Definition at line 8603 of file eez-flow.cpp.
{
    auto a = stack.pop().getValue();
    if (a.isDouble()) {
        stack.push(Value(a.getDouble(), VALUE_TYPE_DOUBLE));
        return;
    }
    if (a.isFloat()) {
        stack.push(Value(a.toFloat(), VALUE_TYPE_FLOAT));
        return;
    }
    if (a.isInt64()) {
        stack.push(Value((int64_t)a.getInt64(), VALUE_TYPE_INT64));
        return;
    }
    if (a.isInt32()) {
        stack.push(Value((int)a.getInt32(), VALUE_TYPE_INT32));
        return;
    }
    if (a.isInt16()) {
        stack.push(Value((int16_t)a.getInt16(), VALUE_TYPE_INT16));
        return;
    }
    if (a.isInt8()) {
        stack.push(Value((int8_t)a.getInt8(), VALUE_TYPE_INT8));
        return;
    }
    stack.push(Value::makeError());
}
References do_OPERATION_TYPE_UNARY_PLUS().
Referenced by do_OPERATION_TYPE_UNARY_PLUS().
do_string_format()
size_t eez::flow::do_string_format (FormatType type, const Value & b, char * result, size_t result_size, const char * format) static
Definition at line 9566 of file eez-flow.cpp.
{
    if (type == type_int) return snprintf(result, result_size, format, (int)b.getInt());
    if (type == type_signed_char) return snprintf(result, result_size, format, (signed char)b.getInt32());
    if (type == type_short_int) return snprintf(result, result_size, format, (short int)b.getInt32());
    if (type == type_long_int) return snprintf(result, result_size, format, (long int)b.getInt64());
    if (type == type_long_long_int) return snprintf(result, result_size, format, (long long int)b.getInt64());
    if (type == type_intmax_t) return snprintf(result, result_size, format, (intmax_t)b.getInt64());
    if (type == type_size_t) return snprintf(result, result_size, format, (size_t)b.getInt64());
    if (type == type_unsigned_int) return snprintf(result, result_size, format, (unsigned int)b.getUInt32());
    if (type == type_unsigned_char) return snprintf(result, result_size, format, (unsigned char)b.getUInt32());
    if (type == type_unsigned_short_int) return snprintf(result, result_size, format, (unsigned short int)b.getUInt32());
    if (type == type_unsigned_long_int) return snprintf(result, result_size, format, (unsigned long int)b.getUInt64());
    if (type == type_unsigned_long_long_int) return snprintf(result, result_size, format, (unsigned long long int)b.getUInt64());
    if (type == type_uintmax_t) return snprintf(result, result_size, format, (uintmax_t)b.getUInt64());
    if (type == type_double) {
        if (b.isDouble()) {
            return snprintf(result, result_size, format, b.getDouble());
        }
        float f = b.toFloat();
        return snprintf(result, result_size, format, f);
    }
    return snprintf(result, result_size, format, b.getString());
}
References do_string_format(), type_double, type_int, type_intmax_t, type_long_int, type_long_long_int, type_short_int, type_signed_char, type_size_t, type_uintmax_t, type_unsigned_char, type_unsigned_int, type_unsigned_long_int, type_unsigned_long_long_int, and type_unsigned_short_int.
Referenced by do_OPERATION_TYPE_STRING_FORMAT(), and do_string_format().
doStop()
void eez::flow::doStop () static
Definition at line 7106 of file eez-flow.cpp.
              {
    onStopped();
    finishToDebuggerMessageHook();
    g_debuggerIsConnected = false;
    freeAllChildrenFlowStates(g_firstFlowState);
    g_firstFlowState = nullptr;
    g_lastFlowState = nullptr;
    g_isStopped = true;
    queueReset();
    watchListReset();
}
References finishToDebuggerMessageHook, freeAllChildrenFlowStates(), g_debuggerIsConnected, g_firstFlowState, g_isStopped, g_lastFlowState, onStopped(), queueReset(), and watchListReset().
Referenced by tick().
dropdownSetSelected()
void eez::flow::dropdownSetSelected (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4482 of file eez-flow.cpp.
References ACTION_END, and dropdownSetSelected().
Referenced by dropdownSetSelected().
elementCompare()
int eez::flow::elementCompare (const void * a, const void * b) static
Definition at line 5616 of file eez-flow.cpp.
{
    auto aValue = *(const Value *)a;
    auto bValue = *(const Value *)b;
    if (g_sortArrayActionComponent->arrayType != -1) {
        if (!aValue.isArray()) {
            return 0;
        }
        auto aArray = aValue.getArray();
        if ((uint32_t)g_sortArrayActionComponent->structFieldIndex >= aArray->arraySize) {
            return 0;
        }
        aValue = aArray->values[g_sortArrayActionComponent->structFieldIndex];
        if (!bValue.isArray()) {
            return 0;
        }
        auto bArray = bValue.getArray();
        if ((uint32_t)g_sortArrayActionComponent->structFieldIndex >= bArray->arraySize) {
            return 0;
        }
        bValue = bArray->values[g_sortArrayActionComponent->structFieldIndex];
    }
    int result;
    if (aValue.isString() && bValue.isString()) {
        if (g_sortArrayActionComponent->flags & SORT_ARRAY_FLAG_IGNORE_CASE) {
            result = utf8casecmp(aValue.getString(), bValue.getString());
        } else {
            result = utf8cmp(aValue.getString(), bValue.getString());
        }
    } else {
        int err;
        float aDouble = aValue.toDouble(&err);
        if (err) {
            return 0;
        }
        float bDouble = bValue.toDouble(&err);
        if (err) {
            return 0;
        }
        auto diff = aDouble - bDouble;
        result = diff < 0 ? -1 : diff > 0 ? 1 : 0;
    }
    if (!(g_sortArrayActionComponent->flags & SORT_ARRAY_FLAG_ASCENDING)) {
        result = -result;
    }
    return result;
}
References g_sortArrayActionComponent, utf8casecmp(), and utf8cmp().
Referenced by sortArray().
enableThrowError()
void eez::flow::enableThrowError (bool enable)
Definition at line 11046 of file eez-flow.cpp.
{
    g_enableThrowError = enable;
}
References enableThrowError(), and g_enableThrowError.
Referenced by enableThrowError().
endAsyncExecution() [1/2]
void eez::flow::endAsyncExecution (AsyncAction * asyncAction)
Definition at line 7231 of file eez-flow.cpp.
{
    endAsyncExecution(asyncAction->flowState, asyncAction->componentIndex);
    propagateValueThroughSeqout(asyncAction->flowState, asyncAction->componentIndex);
    eez::free(asyncAction);
}
References endAsyncExecution(), eez::free(), and propagateValueThroughSeqout().
Referenced by endAsyncExecution(), and endAsyncExecution().
endAsyncExecution() [2/2]
void eez::flow::endAsyncExecution (FlowState * flowState, int componentIndex)
Definition at line 10836 of file eez-flow.cpp.
{
    if (!g_firstFlowState) {
        return;
    }
    if (flowState->componenentAsyncStates[componentIndex]) {
        flowState->componenentAsyncStates[componentIndex] = false;
        onComponentAsyncStateChanged(flowState, componentIndex);
        decRefCounterForFlowState(flowState);
        do {
            if (!canFreeFlowState(flowState)) {
                break;
            }
            auto temp = flowState->parentFlowState;
            freeFlowState(flowState);
            flowState = temp;
        } while (flowState);
    }
}
References canFreeFlowState(), componentIndex, decRefCounterForFlowState(), endAsyncExecution(), flowState, freeFlowState(), g_firstFlowState, and onComponentAsyncStateChanged().
evalAssignableExpression()
bool eez::flow::evalAssignableExpression (FlowState * flowState, int componentIndex, const uint8_t * instructions, Value & result, const FlowError & errorMessage, int * numInstructionBytes, const int32_t * iterators)
Definition at line 6893 of file eez-flow.cpp.
{
    FlowState *savedFlowState = g_stack.flowState;
    int savedComponentIndex = g_stack.componentIndex;
    const int32_t *savedIterators = g_stack.iterators;
    const char *savedErrorMessage = g_stack.errorMessage;
    g_stack.flowState = flowState;
    g_stack.componentIndex = componentIndex;
    g_stack.iterators = iterators;
    g_stack.errorMessage = nullptr;
    evalExpression(flowState, instructions, numInstructionBytes);
    g_stack.flowState = savedFlowState;
    g_stack.componentIndex = savedComponentIndex;
    g_stack.iterators = savedIterators;
    g_stack.errorMessage = savedErrorMessage;
    if (g_stack.sp == 1) {
        auto finalResult = g_stack.pop();
        if (
            finalResult.getType() == VALUE_TYPE_VALUE_PTR ||
            finalResult.getType() == VALUE_TYPE_NATIVE_VARIABLE ||
            finalResult.getType() == VALUE_TYPE_FLOW_OUTPUT ||
            finalResult.getType() == VALUE_TYPE_ARRAY_ELEMENT_VALUE ||
            finalResult.getType() == VALUE_TYPE_JSON_MEMBER_VALUE
        ) {
            result = finalResult;
            return true;
        }
    }
    errorMessage.setDescription(g_stack.errorMessage);
    throwError(flowState, componentIndex, errorMessage);
    return false;
}
References componentIndex, evalExpression(), flowState, g_stack, and throwError().
Referenced by _assignBooleanProperty(), _assignIntegerProperty(), _assignStringProperty(), evalAssignableProperty(), and executeSetVariableComponent().
evalAssignableProperty()
bool eez::flow::evalAssignableProperty (FlowState * flowState, int componentIndex, int propertyIndex, Value & result, const FlowError & errorMessage, int * numInstructionBytes, const int32_t * iterators)
Definition at line 6950 of file eez-flow.cpp.
{
    if (componentIndex < 0 || componentIndex >= (int)flowState->flow->components.count) {
        char message[256];
        snprintf(message, sizeof(message), "invalid component index %d in flow at index %d", componentIndex, flowState->flowIndex);
        FlowError flowError = errorMessage.setDescription(message);
        throwError(flowState, componentIndex, flowError);
        return false;
    }
    auto component = flowState->flow->components[componentIndex];
    if (propertyIndex < 0 || propertyIndex >= (int)component->properties.count) {
        char message[256];
        snprintf(message, sizeof(message), "invalid property index %d in component at index %d in flow at index %d", propertyIndex, componentIndex, flowState->flowIndex);
        FlowError flowError = errorMessage.setDescription(message);
        throwError(flowState, componentIndex, flowError);
        return false;
    }
    return evalAssignableExpression(flowState, componentIndex, component->properties[propertyIndex]->evalInstructions, result, errorMessage, numInstructionBytes, iterators);
}
References componentIndex, evalAssignableExpression(), flowState, and throwError().
Referenced by assignValue(), executeCallAction(), executeLoopComponent(), executeMQTTInitComponent(), executeTestAndSetComponent(), setUserProperty(), and setUserPropertyAsync().
evalExpression() [1/2]
void eez::flow::evalExpression (FlowState * flowState, const uint8_t * instructions, int * numInstructionBytes) static
Definition at line 6729 of file eez-flow.cpp.
{
    auto flowDefinition = flowState->flowDefinition;
    auto flow = flowState->flow;
    int i = 0;
    while (true) {
        uint16_t instruction = instructions[i] + (instructions[i + 1] << 8);
        auto instructionType = instruction & EXPR_EVAL_INSTRUCTION_TYPE_MASK;
        auto instructionArg = instruction & EXPR_EVAL_INSTRUCTION_PARAM_MASK;
        if (instructionType == EXPR_EVAL_INSTRUCTION_TYPE_PUSH_CONSTANT) {
            g_stack.push(*flowDefinition->constants[instructionArg]);
        } else if (instructionType == EXPR_EVAL_INSTRUCTION_TYPE_PUSH_INPUT) {
            g_stack.push(flowState->values[instructionArg]);
        } else if (instructionType == EXPR_EVAL_INSTRUCTION_TYPE_PUSH_LOCAL_VAR) {
            g_stack.push(&flowState->values[flow->componentInputs.count + instructionArg]);
        } else if (instructionType == EXPR_EVAL_INSTRUCTION_TYPE_PUSH_GLOBAL_VAR) {
            if ((uint32_t)instructionArg < flowDefinition->globalVariables.count) {
                if (g_globalVariables) {
                    g_stack.push(g_globalVariables->values + instructionArg);
                } else {
                    g_stack.push(flowDefinition->globalVariables[instructionArg]);
                }
            } else {
                g_stack.push(Value((int)(instructionArg - flowDefinition->globalVariables.count + 1), VALUE_TYPE_NATIVE_VARIABLE));
            }
        } else if (instructionType == EXPR_EVAL_INSTRUCTION_TYPE_PUSH_OUTPUT) {
            g_stack.push(Value((uint16_t)instructionArg, VALUE_TYPE_FLOW_OUTPUT));
        } else if (instructionType == EXPR_EVAL_INSTRUCTION_ARRAY_ELEMENT) {
            auto elementIndexValue = g_stack.pop().getValue();
            auto arrayValue = g_stack.pop().getValue();
            if (arrayValue.getType() == VALUE_TYPE_UNDEFINED || arrayValue.getType() == VALUE_TYPE_NULL) {
                g_stack.push(Value(0, VALUE_TYPE_UNDEFINED));
            } else {
                if (arrayValue.isArray()) {
                    auto array = arrayValue.getArray();
                    int err;
                    auto elementIndex = elementIndexValue.toInt32(&err);
                    if (!err) {
                        if (elementIndex >= 0 && elementIndex < (int)array->arraySize) {
                            g_stack.push(Value::makeArrayElementRef(arrayValue, elementIndex, 0x132e0e2f));
                        } else {
                            g_stack.push(Value::makeError());
                            g_stack.setErrorMessage("Array element index out of bounds\n");
                        }
                    } else {
                        g_stack.push(Value::makeError());
                        g_stack.setErrorMessage("Integer value expected for array element index\n");
                    }
                } else if (arrayValue.isBlob()) {
                    auto blobRef = arrayValue.getBlob();
                    int err;
                    auto elementIndex = elementIndexValue.toInt32(&err);
                    if (!err) {
                        if (elementIndex >= 0 && elementIndex < (int)blobRef->len) {
                            g_stack.push(Value::makeArrayElementRef(arrayValue, elementIndex, 0x132e0e2f));
                        } else {
                            g_stack.push(Value::makeError());
                            g_stack.setErrorMessage("Blob element index out of bounds\n");
                        }
                    } else {
                        g_stack.push(Value::makeError());
                        g_stack.setErrorMessage("Integer value expected for blob element index\n");
                    }
                } else {
                    g_stack.push(Value::makeError());
                    g_stack.setErrorMessage("Array value expected\n");
                }
            }
        } else if (instructionType == EXPR_EVAL_INSTRUCTION_TYPE_OPERATION) {
            g_evalOperations[instructionArg](g_stack);
        } else {
            if (instruction == EXPR_EVAL_INSTRUCTION_TYPE_END_WITH_DST_VALUE_TYPE) {
                i += 2;
                if (g_stack.sp == 1) {
                    auto finalResult = g_stack.pop();
                    #define VALUE_TYPE (instructions[i] + (instructions[i + 1] << 8) + (instructions[i + 2] << 16) + (instructions[i + 3] << 24))
                    if (finalResult.getType() == VALUE_TYPE_VALUE_PTR) {
                        finalResult.dstValueType = VALUE_TYPE;
                    } else if (finalResult.getType() == VALUE_TYPE_ARRAY_ELEMENT_VALUE) {
                        auto arrayElementValue = (ArrayElementValue *)finalResult.refValue;
                        arrayElementValue->dstValueType = VALUE_TYPE;
                    }
                    g_stack.push(finalResult);
                }
                i += 4;
                break;
            } else {
                i += 2;
                break;
            }
        }
        i += 2;
    }
    if (numInstructionBytes) {
        *numInstructionBytes = i;
    }
}
References flowState, g_evalOperations, g_globalVariables, g_stack, and VALUE_TYPE.
Referenced by evalAssignableExpression(), evalExpression(), evalProperty(), executeCompareComponent(), executeLVGLComponent(), executeSetVariableComponent(), and executeSwitchComponent().
evalExpression() [2/2]
bool eez::flow::evalExpression (FlowState * flowState, int componentIndex, const uint8_t * instructions, Value & result, const FlowError & errorMessage, int * numInstructionBytes, const int32_t * iterators)
Definition at line 6828 of file eez-flow.cpp.
{
#endif
    size_t savedSp = g_stack.sp;
    FlowState *savedFlowState = g_stack.flowState;
    int savedComponentIndex = g_stack.componentIndex;
    const int32_t *savedIterators = g_stack.iterators;
    const char *savedErrorMessage = g_stack.errorMessage;
    g_stack.flowState = flowState;
    g_stack.componentIndex = componentIndex;
    g_stack.iterators = iterators;
    g_stack.errorMessage = nullptr;
    evalExpression(flowState, instructions, numInstructionBytes);
    g_stack.flowState = savedFlowState;
    g_stack.componentIndex = savedComponentIndex;
    g_stack.iterators = savedIterators;
    g_stack.errorMessage = savedErrorMessage;
    if (g_stack.sp == savedSp + 1) {
#if EEZ_OPTION_GUI
        if (operation == DATA_OPERATION_GET_TEXT_REFRESH_RATE) {
            result = g_stack.pop();
            if (!result.isError()) {
                if (result.getType() == VALUE_TYPE_NATIVE_VARIABLE) {
                    auto nativeVariableId = result.getInt();
                    result = Value(getTextRefreshRate(g_widgetCursor, nativeVariableId), VALUE_TYPE_UINT32);
                } else {
                    result = 0;
                }
                return true;
            }
        } else if (operation == DATA_OPERATION_GET_TEXT_CURSOR_POSITION) {
            result = g_stack.pop();
            if (!result.isError()) {
                if (result.getType() == VALUE_TYPE_NATIVE_VARIABLE) {
                    auto nativeVariableId = result.getInt();
                    result = Value(getTextCursorPosition(g_widgetCursor, nativeVariableId), VALUE_TYPE_INT32);
                } else {
                    result = Value();
                }
                return true;
            }
        }  else if (operation == DATA_OPERATION_GET_CANVAS_REFRESH_STATE) {
            result = g_stack.pop();
            if (!result.isError()) {
                if (result.getType() == VALUE_TYPE_NATIVE_VARIABLE) {
                    auto nativeVariableId = result.getInt();
                    result = getCanvasRefreshState(g_widgetCursor, nativeVariableId);
                } else {
                    result = Value();
                }
                return true;
            }
        } else {
#endif
            result = g_stack.pop().getValue();
            if (!result.isError()) {
                return true;
            }
#if EEZ_OPTION_GUI
        }
#endif
    }
    FlowError flowError = errorMessage.setDescription(g_stack.errorMessage);
    throwError(flowState, componentIndex, flowError);
    return false;
}
References componentIndex, evalExpression(), flowState, g_stack, and throwError().
evalProperty()
bool eez::flow::evalProperty (FlowState * flowState, int componentIndex, int propertyIndex, Value & result, const FlowError & errorMessage, int * numInstructionBytes, const int32_t * iterators)
Definition at line 6927 of file eez-flow.cpp.
{
#endif
    if (componentIndex < 0 || componentIndex >= (int)flowState->flow->components.count) {
        char message[256];
        snprintf(message, sizeof(message), "invalid component index %d in flow at index %d", componentIndex, flowState->flowIndex);
        FlowError flowError = errorMessage.setDescription(message);
        throwError(flowState, componentIndex, flowError);
        return false;
    }
    auto component = flowState->flow->components[componentIndex];
    if (propertyIndex < 0 || propertyIndex >= (int)component->properties.count) {
        char message[256];
        snprintf(message, sizeof(message), "invalid property index %d in component at index %d in flow at index %d", propertyIndex, componentIndex, flowState->flowIndex);
        FlowError flowError = errorMessage.setDescription(message);
        throwError(flowState, componentIndex, flowError);
        return false;
    }
#if EEZ_OPTION_GUI
    return evalExpression(flowState, componentIndex, component->properties[propertyIndex]->evalInstructions, result, errorMessage, numInstructionBytes, iterators, operation);
#else
    return evalExpression(flowState, componentIndex, component->properties[propertyIndex]->evalInstructions, result, errorMessage, numInstructionBytes, iterators);
#endif
}
References componentIndex, evalExpression(), flowState, and throwError().
Referenced by _evalBooleanProperty(), _evalIntegerProperty(), _evalStringArrayPropertyAndJoin(), _evalTextProperty(), _evalUnsignedIntegerProperty(), executeAnimateComponent(), executeCallAction(), executeCounterComponent(), executeDelayComponent(), executeErrorComponent(), executeEvalExprComponent(), executeIsTrueComponent(), executeLogComponent(), executeLoopComponent(), executeMQTTConnectComponent(), executeMQTTDisconnectComponent(), executeMQTTEventComponent(), executeMQTTInitComponent(), executeMQTTPublishComponent(), executeMQTTSubscribeComponent(), executeMQTTUnsubscribeComponent(), executeSelectLanguageComponent(), executeSetColorThemeComponent(), executeSortArrayComponent(), executeWatchVariableComponent(), getUserProperty(), and getUserPropertyAsync().
executeAnimateComponent()
void eez::flow::executeAnimateComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3183 of file eez-flow.cpp.
{
    FlowState *timelineFlowState = flowState;
    while (timelineFlowState->isAction && timelineFlowState->parentFlowState) {
        timelineFlowState = timelineFlowState->parentFlowState;
    }
    auto state = (AnimateComponenentExecutionState *)flowState->componenentExecutionStates[componentIndex];
    if (!state) {
        Value fromValue;
        if (!evalProperty(flowState, componentIndex, defs_v3::ANIMATE_ACTION_COMPONENT_PROPERTY_FROM, fromValue, FlowError::Property("Animate", "From"))) {
            return;
        }
        Value toValue;
        if (!evalProperty(flowState, componentIndex, defs_v3::ANIMATE_ACTION_COMPONENT_PROPERTY_TO, toValue, FlowError::Property("Animate", "To"))) {
            return;
        }
        Value speedValue;
        if (!evalProperty(flowState, componentIndex, defs_v3::ANIMATE_ACTION_COMPONENT_PROPERTY_SPEED, speedValue, FlowError::Property("Animate", "Speed"))) {
            return;
        }
        float from = fromValue.toFloat();
        float to = toValue.toFloat();
        float speed = speedValue.toFloat();
        if (speed == 0) {
            timelineFlowState->timelinePosition = to;
            onFlowStateTimelineChanged(flowState);
            propagateValueThroughSeqout(flowState, componentIndex);
        } else {
            state = allocateComponentExecutionState<AnimateComponenentExecutionState>(flowState, componentIndex);
            state->startPosition = from;
            state->endPosition = to;
            state->speed = speed;
            state->startTimestamp = millis();
            if (!addToQueue(flowState, componentIndex, -1, -1, -1, true)) {
                return;
            }
        }
    } else {
        float currentTime;
        if (state->startPosition < state->endPosition) {
            currentTime = state->startPosition + state->speed * (millis() - state->startTimestamp) / 1000.0f;
            if (currentTime >= state->endPosition) {
                currentTime = state->endPosition;
            }
        } else {
            currentTime = state->startPosition - state->speed * (millis() - state->startTimestamp) / 1000.0f;
            if (currentTime <= state->endPosition) {
                currentTime = state->endPosition;
            }
        }
        timelineFlowState->timelinePosition = currentTime;
        onFlowStateTimelineChanged(flowState);
        if (currentTime == state->endPosition) {
            deallocateComponentExecutionState(flowState, componentIndex);
            propagateValueThroughSeqout(flowState, componentIndex);
        } else {
            if (!addToQueue(flowState, componentIndex, -1, -1, -1, true)) {
                return;
            }
        }
    }
}
References addToQueue(), componentIndex, deallocateComponentExecutionState(), evalProperty(), flowState, eez::millis(), onFlowStateTimelineChanged(), and propagateValueThroughSeqout().
executeCallAction()
void eez::flow::executeCallAction (FlowState * flowState, unsigned componentIndex, int flowIndex, const Value & inputValue)
Definition at line 3254 of file eez-flow.cpp.
{
    if (flowIndex >= (int)flowState->flowDefinition->flows.count) {
        g_executeActionFlowState = flowState;
        g_executeActionComponentIndex = componentIndex;
        executeActionFunction(flowIndex - flowState->flowDefinition->flows.count);
        if ((int)componentIndex != -1 && !flowState->componenentAsyncStates[componentIndex]) {
            propagateValueThroughSeqout(flowState, componentIndex);
        }
        return;
    }
    FlowState *actionFlowState = initActionFlowState(flowIndex, flowState, componentIndex, inputValue);
    if ((int)componentIndex != -1) {
        for (uint32_t i = 0; i < actionFlowState->flow->userPropertiesAssignable.count; i++) {
            auto isAssignable = actionFlowState->flow->userPropertiesAssignable.items[i];
            Value value;
            if (isAssignable) {
                if (!evalAssignableProperty(flowState, componentIndex, i, value, FlowError::UserProperty("CallAction", i))) {
                    break;
                }
                if (value.getType() == VALUE_TYPE_FLOW_OUTPUT) {
                    value = Value::makePropertyRef(flowState, componentIndex, i, 0x5696e703);
                }
            } else {
                if (!evalProperty(flowState, componentIndex, i, value, FlowError::UserAssignableProperty("CallAction", i))) {
                    break;
                }
            }
            auto propValuePtr = actionFlowState->values + actionFlowState->flow->componentInputs.count + i;
            *propValuePtr = value;
            onValueChanged(propValuePtr);
        }
    }
    if (canFreeFlowState(actionFlowState)) {
        freeFlowState(actionFlowState);
        if ((int)componentIndex != -1) {
            propagateValueThroughSeqout(flowState, componentIndex);
        }
    }
}
References canFreeFlowState(), componentIndex, evalAssignableProperty(), evalProperty(), eez::executeActionFunction(), flowState, freeFlowState(), g_executeActionComponentIndex, g_executeActionFlowState, initActionFlowState(), onValueChanged(), and propagateValueThroughSeqout().
Referenced by executeCallActionComponent(), and propagateValue().
executeCallActionComponent()
void eez::flow::executeCallActionComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3293 of file eez-flow.cpp.
{
    auto component = (CallActionActionComponent *)flowState->flow->components[componentIndex];
    auto flowIndex = component->flowIndex;
    if (flowIndex < 0) {
        throwError(flowState, componentIndex, FlowError::Plain("Invalid action flow index in CallAction"));
        return;
    }
    executeCallAction(flowState, componentIndex, flowIndex, Value());
}
References componentIndex, executeCallAction(), flowState, and throwError().
executeCatchErrorComponent()
void eez::flow::executeCatchErrorComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3309 of file eez-flow.cpp.
{
    auto catchErrorComponentExecutionState = (CatchErrorComponenentExecutionState *)flowState->componenentExecutionStates[componentIndex];
    propagateValue(flowState, componentIndex, 1, catchErrorComponentExecutionState->message);
    deallocateComponentExecutionState(flowState, componentIndex);
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, deallocateComponentExecutionState(), flowState, propagateValue(), and propagateValueThroughSeqout().
executeCompareComponent()
void eez::flow::executeCompareComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3325 of file eez-flow.cpp.
{
    auto component = (CompareActionComponent *)flowState->flow->components[componentIndex];
    Value conditionValue;
    if (!evalExpression(flowState, componentIndex, component->conditionInstructions, conditionValue, FlowError::Property("Compare", "Condition"))) {
        return;
    }
    int err;
    bool result = conditionValue.toBool(&err);
    if (err == 0) {
        if (result) {
            propagateValue(flowState, componentIndex, 1, Value(true, VALUE_TYPE_BOOLEAN));
        } else {
            propagateValue(flowState, componentIndex, 2, Value(false, VALUE_TYPE_BOOLEAN));
        }
    } else {
        throwError(flowState, componentIndex, FlowError::PropertyConvert("Compare", "Condition", "boolean"));
        return;
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, evalExpression(), flowState, propagateValue(), propagateValueThroughSeqout(), and throwError().
executeComponent()
void eez::flow::executeComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3137 of file eez-flow.cpp.
{
    auto component = flowState->flow->components[componentIndex];
    if (component->type >= defs_v3::FIRST_DASHBOARD_ACTION_COMPONENT_TYPE) {
#if defined(EEZ_DASHBOARD_API)
        executeDashboardComponent(component->type, getFlowStateIndex(flowState), componentIndex);
#endif
        return;
    } else if (component->type >= defs_v3::COMPONENT_TYPE_START_ACTION) {
        auto executeComponentFunction = g_executeComponentFunctions[component->type - defs_v3::COMPONENT_TYPE_START_ACTION];
        if (executeComponentFunction != nullptr) {
            executeComponentFunction(flowState, componentIndex);
            return;
        }
    }
#if EEZ_OPTION_GUI
    else if (component->type < 1000) {
        if (component->type == defs_v3::COMPONENT_TYPE_USER_WIDGET_WIDGET) {
            executeUserWidgetWidgetComponent(flowState, componentIndex);
        } else if (component->type == defs_v3::COMPONENT_TYPE_LINE_CHART_EMBEDDED_WIDGET) {
            executeLineChartWidgetComponent(flowState, componentIndex);
        } else if (component->type == defs_v3::COMPONENT_TYPE_ROLLER_WIDGET) {
            executeRollerWidgetComponent(flowState, componentIndex);
        }
        return;
    }
#endif
    char errorMessage[100];
    snprintf(errorMessage, sizeof(errorMessage), "Unknown component at index = %d, type = %d\n", componentIndex, component->type);
    throwError(flowState, componentIndex, errorMessage);
}
References componentIndex, flowState, g_executeComponentFunctions, and throwError().
Referenced by tick().
executeConstantComponent()
void eez::flow::executeConstantComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3355 of file eez-flow.cpp.
{
    auto component = (ConstantActionComponent *)flowState->flow->components[componentIndex];
    auto &sourceValue = *flowState->flowDefinition->constants[component->valueIndex];
    propagateValue(flowState, componentIndex, 1, sourceValue);
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, flowState, propagateValue(), and propagateValueThroughSeqout().
executeCounterComponent()
void eez::flow::executeCounterComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3371 of file eez-flow.cpp.
{
    auto counterComponenentExecutionState = (CounterComponenentExecutionState *)flowState->componenentExecutionStates[componentIndex];
    if (!counterComponenentExecutionState) {
        Value counterValue;
        if (!evalProperty(flowState, componentIndex, defs_v3::COUNTER_ACTION_COMPONENT_PROPERTY_COUNT_VALUE, counterValue, FlowError::Property("Counter", "Count value"))) {
            return;
        }
        counterComponenentExecutionState = allocateComponentExecutionState<CounterComponenentExecutionState>(flowState, componentIndex);
        counterComponenentExecutionState->counter = counterValue.getInt();
    }
    if (counterComponenentExecutionState->counter > 0) {
        counterComponenentExecutionState->counter--;
        propagateValueThroughSeqout(flowState, componentIndex);
    } else {
        deallocateComponentExecutionState(flowState, componentIndex);
        propagateValue(flowState, componentIndex, 1);
    }
}
References componentIndex, deallocateComponentExecutionState(), evalProperty(), flowState, propagateValue(), and propagateValueThroughSeqout().
executeDelayComponent()
void eez::flow::executeDelayComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3399 of file eez-flow.cpp.
{
    auto delayComponentExecutionState = (DelayComponenentExecutionState *)flowState->componenentExecutionStates[componentIndex];
    if (!delayComponentExecutionState) {
        Value value;
        if (!evalProperty(flowState, componentIndex, defs_v3::DELAY_ACTION_COMPONENT_PROPERTY_MILLISECONDS, value, FlowError::Property("Delay", "Milliseconds"))) {
            return;
        }
        double milliseconds = value.toDouble();
        if (!isNaN(milliseconds)) {
            delayComponentExecutionState = allocateComponentExecutionState<DelayComponenentExecutionState>(flowState, componentIndex);
            delayComponentExecutionState->waitUntil = millis() + (uint32_t)floor(milliseconds);
        } else {
            throwError(flowState, componentIndex, FlowError::PropertyInvalid("Delay", "Milliseconds"));
            return;
        }
        if (!addToQueue(flowState, componentIndex, -1, -1, -1, true)) {
            return;
        }
    } else {
        if (millis() >= delayComponentExecutionState->waitUntil) {
            deallocateComponentExecutionState(flowState, componentIndex);
            propagateValueThroughSeqout(flowState, componentIndex);
        } else {
            if (!addToQueue(flowState, componentIndex, -1, -1, -1, true)) {
                return;
            }
        }
    }
}
References addToQueue(), componentIndex, deallocateComponentExecutionState(), evalProperty(), flowState, eez::isNaN(), eez::millis(), propagateValueThroughSeqout(), and throwError().
executeEndComponent()
void eez::flow::executeEndComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3435 of file eez-flow.cpp.
{
    EEZ_UNUSED(componentIndex);
    if (flowState->parentFlowState && flowState->isAction) {
        if (flowState->parentComponentIndex != -1) {
            propagateValueThroughSeqout(flowState->parentFlowState, flowState->parentComponentIndex);
        }
    } else {
        stopScriptHook();
    }
}
References componentIndex, EEZ_UNUSED, flowState, propagateValueThroughSeqout(), and stopScriptHook.
executeErrorComponent()
void eez::flow::executeErrorComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3452 of file eez-flow.cpp.
{
    Value expressionValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::EVAL_EXPR_ACTION_COMPONENT_PROPERTY_EXPRESSION, expressionValue, FlowError::Property("Error", "Message"))) {
        return;
    }
    throwError(flowState, componentIndex, FlowError::Plain(expressionValue.getString()));
}
References componentIndex, evalProperty(), flowState, and throwError().
executeEvalExprComponent()
void eez::flow::executeEvalExprComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3466 of file eez-flow.cpp.
{
    Value expressionValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::EVAL_EXPR_ACTION_COMPONENT_PROPERTY_EXPRESSION, expressionValue, FlowError::Property("Evalute", "Expression"))) {
        return;
    }
    propagateValue(flowState, componentIndex, 1, expressionValue);
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, evalProperty(), flowState, propagateValue(), and propagateValueThroughSeqout().
executeInputComponent()
void eez::flow::executeInputComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3518 of file eez-flow.cpp.
{
    Value value;
    if (getCallActionValue(flowState, componentIndex, value)) {
        auto inputActionComponentExecutionState = (InputActionComponentExecutionState *)flowState->componenentExecutionStates[componentIndex];
        if (!inputActionComponentExecutionState) {
            inputActionComponentExecutionState = allocateComponentExecutionState<InputActionComponentExecutionState>(flowState, componentIndex);
        }
        propagateValue(flowState, componentIndex, 0, value);
        inputActionComponentExecutionState->value = value;
    }
}
References componentIndex, flowState, getCallActionValue(), and propagateValue().
executeIsTrueComponent()
void eez::flow::executeIsTrueComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3536 of file eez-flow.cpp.
{
    Value srcValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::IS_TRUE_ACTION_COMPONENT_PROPERTY_VALUE, srcValue, FlowError::Property("IsTrue", "Value"))) {
        return;
    }
    int err;
    bool result = srcValue.toBool(&err);
    if (err == 0) {
        if (result) {
            propagateValue(flowState, componentIndex, 1, Value(true, VALUE_TYPE_BOOLEAN));
        } else {
            propagateValue(flowState, componentIndex, 2, Value(false, VALUE_TYPE_BOOLEAN));
        }
    } else {
        throwError(flowState, componentIndex, FlowError::PropertyConvert("IsTrue", "Value", "boolean"));
        return;
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, evalProperty(), flowState, propagateValue(), propagateValueThroughSeqout(), and throwError().
executeLabelInComponent()
void eez::flow::executeLabelInComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3562 of file eez-flow.cpp.
{
    EEZ_UNUSED(flowState);
    EEZ_UNUSED(componentIndex);
}
References componentIndex, EEZ_UNUSED, and flowState.
executeLabelOutComponent()
void eez::flow::executeLabelOutComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3576 of file eez-flow.cpp.
{
    auto component = (LabelOutActionComponent *)flowState->flow->components[componentIndex];
    if (component->labelInComponentIndex != -1) {
        propagateValueThroughSeqout(flowState, component->labelInComponentIndex);
    }
}
References componentIndex, flowState, and propagateValueThroughSeqout().
executeLogComponent()
void eez::flow::executeLogComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3729 of file eez-flow.cpp.
{
    Value value;
    if (!evalProperty(flowState, componentIndex, defs_v3::LOG_ACTION_COMPONENT_PROPERTY_VALUE, value, FlowError::Property("Log", "Message"))) {
        return;
    }
    Value strValue = value.toString(0x0f9812ee);
    const char *valueStr = strValue.getString();
    if (valueStr && *valueStr) {
      logInfo(flowState, componentIndex, valueStr);
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, evalProperty(), flowState, logInfo(), and propagateValueThroughSeqout().
executeLoopComponent()
void eez::flow::executeLoopComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3753 of file eez-flow.cpp.
{
    auto component = flowState->flow->components[componentIndex];
    auto loopComponentExecutionState = (LoopComponenentExecutionState *)flowState->componenentExecutionStates[componentIndex];
    static const unsigned START_INPUT_INDEX = 0;
    auto startInputIndex = component->inputs[START_INPUT_INDEX];
    if (flowState->values[startInputIndex].type != VALUE_TYPE_UNDEFINED) {
        if (loopComponentExecutionState) {
            deallocateComponentExecutionState(flowState, componentIndex);
            loopComponentExecutionState = nullptr;
        }
    } else {
        if (!loopComponentExecutionState) {
            return;
        }
    }
    Value stepValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::LOOP_ACTION_COMPONENT_PROPERTY_STEP, stepValue, FlowError::Property("Loop", "Step"))) {
        return;
    }
    Value currentValue;
    if (!loopComponentExecutionState) {
        Value dstValue;
        if (!evalAssignableProperty(flowState, componentIndex, defs_v3::LOOP_ACTION_COMPONENT_PROPERTY_VARIABLE, dstValue, FlowError::Property("Loop", "Variable"))) {
            return;
        }
        Value fromValue;
        if (!evalProperty(flowState, componentIndex, defs_v3::LOOP_ACTION_COMPONENT_PROPERTY_FROM, fromValue, FlowError::Property("Loop", "From"))) {
            return;
        }
        Value toValue;
        if (!evalProperty(flowState, componentIndex, defs_v3::LOOP_ACTION_COMPONENT_PROPERTY_TO, toValue, FlowError::Property("Loop", "To"))) {
            return;
        }
        loopComponentExecutionState = allocateComponentExecutionState<LoopComponenentExecutionState>(flowState, componentIndex);
        loopComponentExecutionState->dstValue = dstValue;
        loopComponentExecutionState->toValue = toValue;
        currentValue = fromValue;
    } else {
        if (loopComponentExecutionState->dstValue.getType() == VALUE_TYPE_FLOW_OUTPUT) {
            currentValue = op_add(loopComponentExecutionState->currentValue, stepValue);
        } else {
            currentValue = op_add(loopComponentExecutionState->dstValue, stepValue);
        }
    }
    if (loopComponentExecutionState->dstValue.getType() == VALUE_TYPE_FLOW_OUTPUT) {
        loopComponentExecutionState->currentValue = currentValue;
    } else {
        assignValue(flowState, componentIndex, loopComponentExecutionState->dstValue, currentValue);
    }
    bool condition;
    if (stepValue.toDouble(nullptr) > 0) {
        condition = op_great(currentValue, loopComponentExecutionState->toValue).toBool();
    } else {
        condition = op_less(currentValue, loopComponentExecutionState->toValue).toBool();
    }
    if (condition) {
        deallocateComponentExecutionState(flowState, componentIndex);
        propagateValue(flowState, componentIndex, 1);
    } else {
        if (loopComponentExecutionState->dstValue.getType() == VALUE_TYPE_FLOW_OUTPUT) {
            assignValue(flowState, componentIndex, loopComponentExecutionState->dstValue, currentValue);
        }
        propagateValueThroughSeqout(flowState, componentIndex);
    }
}
References assignValue(), componentIndex, deallocateComponentExecutionState(), evalAssignableProperty(), evalProperty(), flowState, op_add(), op_great(), op_less(), propagateValue(), and propagateValueThroughSeqout().
executeLvglAction()
void eez::flow::executeLvglAction (int actionIndex) static
Definition at line 7557 of file eez-flow.cpp.
{
    EEZ_UNUSED(actionIndex);
}
References EEZ_UNUSED.
executeLVGLApiComponent()
void eez::flow::executeLVGLApiComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 4785 of file eez-flow.cpp.
{
    auto component = (LVGLApiComponent *)flowState->flow->components[componentIndex];
    auto executionState = (LVGLApiExecutionState *)flowState->componenentExecutionStates[componentIndex];
    for (uint32_t actionIndex = executionState ? executionState->actionIndex : 0; actionIndex < component->actions.count; actionIndex++) {
        auto actionType = (LVGLApiComponent_ActionType *)component->actions[actionIndex];
        (*actions[actionType->action])(flowState, componentIndex, actionType->properties, actionIndex);
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References actions, componentIndex, flowState, and propagateValueThroughSeqout().
executeLVGLComponent()
void eez::flow::executeLVGLComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 3900 of file eez-flow.cpp.
{
    auto component = (LVGLComponent *)flowState->flow->components[componentIndex];
    auto executionState = (LVGLExecutionState *)flowState->componenentExecutionStates[componentIndex];
    for (uint32_t actionIndex = executionState ? executionState->actionIndex : 0; actionIndex < component->actions.count; actionIndex++) {
        auto general = (LVGLComponent_ActionType *)component->actions[actionIndex];
        if (general->action == CHANGE_SCREEN) {
            auto specific = (LVGLComponent_ChangeScreen_ActionType *)general;
            if (specific->screen == -1) {
                eez_flow_pop_screen((lv_scr_load_anim_t)specific->fadeMode, specific->speed, specific->delay);
            } else {
                eez_flow_push_screen(specific->screen, (lv_scr_load_anim_t)specific->fadeMode, specific->speed, specific->delay);
            }
        } else if (general->action == PLAY_ANIMATION) {
            auto specific = (LVGLComponent_PlayAnimation_ActionType *)general;
            auto target = getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + specific->target);
            if (!target) {
                if (!executionState) {
                    executionState = allocateComponentExecutionState<LVGLExecutionState>(flowState, componentIndex);
                }
                executionState->actionIndex = actionIndex;
                addToQueue(flowState, componentIndex, -1, -1, -1, true);
                return;
            }
            lv_anim_t anim;
            lv_anim_init(&anim);
            lv_anim_set_time(&anim, specific->time);
            lv_anim_set_user_data(&anim, target);
            lv_anim_set_var(&anim, target);
            lv_anim_set_exec_cb(&anim, anim_set_callbacks[specific->property]);
            lv_anim_set_values(&anim, specific->start, specific->end);
            lv_anim_set_path_cb(&anim, anim_path_callbacks[specific->path]);
            lv_anim_set_delay(&anim, specific->delay);
            lv_anim_set_early_apply(&anim, specific->flags & ANIMATION_ITEM_FLAG_INSTANT ? true : false);
            if (specific->flags & ANIMATION_ITEM_FLAG_RELATIVE) {
                lv_anim_set_get_value_cb(&anim, anim_get_callbacks[specific->property]);
            }
            lv_anim_start(&anim);
        } else if (general->action == SET_PROPERTY) {
            auto specific = (LVGLComponent_SetProperty_ActionType *)general;
            auto target = getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + specific->target);
            if (!target) {
                if (!executionState) {
                    executionState = allocateComponentExecutionState<LVGLExecutionState>(flowState, componentIndex);
                }
                executionState->actionIndex = actionIndex;
                addToQueue(flowState, componentIndex, -1, -1, -1, true);
                return;
            }
            if (specific->property == KEYBOARD_TEXTAREA) {
                auto textarea = specific->textarea != -1 ? getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + specific->textarea) : nullptr;
                if (!textarea) {
                    if (!executionState) {
                        executionState = allocateComponentExecutionState<LVGLExecutionState>(flowState, componentIndex);
                    }
                    executionState->actionIndex = actionIndex;
                    addToQueue(flowState, componentIndex, -1, -1, -1, true);
                    return;
                }
                lv_keyboard_set_textarea(target, textarea);
            } else {
                Value value;
                if (!evalExpression(flowState, componentIndex, specific->value, value, FlowError::PropertyInAction("LVGL Set Property", "Value", actionIndex))) {
                    return;
                }
                if (specific->property == IMAGE_IMAGE || specific->property == LABEL_TEXT) {
                    const char *strValue = value.toString(0xe42b3ca2).getString();
                    if (specific->property == IMAGE_IMAGE) {
                        const void *src = getLvglImageByNameHook(strValue);
                        if (src) {
                            lv_img_set_src(target, src);
                        } else {
                            throwError(flowState, componentIndex, FlowError::NotFoundInAction("Image", strValue, "LVGL Set Property", actionIndex));
                        }
                    } else {
                        lv_label_set_text(target, strValue ? strValue : "");
                    }
                } else if (specific->property == BASIC_HIDDEN) {
                    int err;
                    bool booleanValue = value.toBool(&err);
                    if (err) {
                        throwError(flowState, componentIndex, FlowError::PropertyInActionConvert("LVGL Set Property", "Value", "boolean", actionIndex));
                        return;
                    }
                    lv_obj_flag_t flag = LV_OBJ_FLAG_HIDDEN;
                    if (booleanValue) lv_obj_add_flag(target, flag);
                    else lv_obj_clear_flag(target, flag);
                } else if (specific->property == BASIC_CHECKED || specific->property == BASIC_DISABLED) {
                    int err;
                    bool booleanValue = value.toBool(&err);
                    if (err) {
                        throwError(flowState, componentIndex, FlowError::PropertyInActionConvert("LVGL Set Property", "Value", "boolean", actionIndex));
                        return;
                    }
                    lv_state_t state = specific->property == BASIC_CHECKED ? LV_STATE_CHECKED : LV_STATE_DISABLED;
                    if (booleanValue) lv_obj_add_state(target, state);
                    else lv_obj_clear_state(target, state);
                } else {
                    int err;
                    int32_t intValue = value.toInt32(&err);
                    if (err) {
                        throwError(flowState, componentIndex, FlowError::PropertyInActionConvert("LVGL Set Property", "Value", "integer", actionIndex));
                        return;
                    }
                    if (specific->property == ARC_VALUE) {
                        lv_arc_set_value(target, intValue);
                    } else if (specific->property == BAR_VALUE) {
                        lv_bar_set_value(target, intValue, specific->animated ? LV_ANIM_ON : LV_ANIM_OFF);
                    } else if (specific->property == BASIC_X) {
                        lv_obj_set_x(target, intValue);
                    } else if (specific->property == BASIC_Y) {
                        lv_obj_set_y(target, intValue);
                    } else if (specific->property == BASIC_WIDTH) {
                        lv_obj_set_width(target, intValue);
                    } else if (specific->property == BASIC_HEIGHT) {
                        lv_obj_set_height(target, intValue);
                    } else if (specific->property == BASIC_OPACITY) {
                        lv_obj_set_style_opa(target, intValue, 0);
                    } else if (specific->property == DROPDOWN_SELECTED) {
 #if LVGL_VERSION_MAJOR >= 9 && LVGL_VERSION_MINOR >= 3
                        lv_dropdown_set_selected(target, intValue);
#else
                        lv_dropdown_set_selected(target, intValue);
#endif
                    } else if (specific->property == IMAGE_ANGLE) {
                        lv_img_set_angle(target, intValue);
                    } else if (specific->property == IMAGE_ZOOM) {
                        lv_img_set_zoom(target, intValue);
                    } else if (specific->property == ROLLER_SELECTED) {
                        lv_roller_set_selected(target, intValue, specific->animated ? LV_ANIM_ON : LV_ANIM_OFF);
                    } else if (specific->property == SLIDER_VALUE) {
                        lv_slider_set_value(target, intValue, specific->animated ? LV_ANIM_ON : LV_ANIM_OFF);
                    }
                }
            }
            lv_obj_update_layout(target);
        } else if (general->action == ADD_STYLE) {
            auto specific = (LVGLComponent_AddStyle_ActionType *)general;
            auto target = getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + specific->target);
            if (!target) {
                if (!executionState) {
                    executionState = allocateComponentExecutionState<LVGLExecutionState>(flowState, componentIndex);
                }
                executionState->actionIndex = actionIndex;
                addToQueue(flowState, componentIndex, -1, -1, -1, true);
                return;
            } else {
                lvglObjAddStyleHook(target, specific->style);
            }
        } else if (general->action == REMOVE_STYLE) {
            auto specific = (LVGLComponent_RemoveStyle_ActionType *)general;
            auto target = getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + specific->target);
            if (!target) {
                if (!executionState) {
                    executionState = allocateComponentExecutionState<LVGLExecutionState>(flowState, componentIndex);
                }
                executionState->actionIndex = actionIndex;
                addToQueue(flowState, componentIndex, -1, -1, -1, true);
                return;
            } else {
                lvglObjRemoveStyleHook(target, specific->style);
            }
        } else if (general->action == ADD_FLAG) {
            auto specific = (LVGLComponent_AddFlag_ActionType *)general;
            auto target = getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + specific->target);
            if (!target) {
                if (!executionState) {
                    executionState = allocateComponentExecutionState<LVGLExecutionState>(flowState, componentIndex);
                }
                executionState->actionIndex = actionIndex;
                addToQueue(flowState, componentIndex, -1, -1, -1, true);
                return;
            } else {
                lv_obj_add_flag(target, (lv_obj_flag_t)specific->flag);
            }
        } else if (general->action == CLEAR_FLAG) {
            auto specific = (LVGLComponent_ClearFlag_ActionType *)general;
            auto target = getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + specific->target);
            if (!target) {
                if (!executionState) {
                    executionState = allocateComponentExecutionState<LVGLExecutionState>(flowState, componentIndex);
                }
                executionState->actionIndex = actionIndex;
                addToQueue(flowState, componentIndex, -1, -1, -1, true);
                return;
            } else {
                lv_obj_clear_flag(target, (lv_obj_flag_t)specific->flag);
            }
        } else if (general->action == GROUP) {
            auto specific = (LVGLComponent_Group_ActionType *)general;
            if (specific->groupAction == GROUP_ACTION_SET_WRAP) {
                auto target = getLvglGroupFromIndexHook(specific->target);
                if (target) {
                    lv_group_set_wrap(target, specific->enable ? true : false);
                }
            } else if (specific->groupAction == GROUP_ACTION_FOCUS_OBJ) {
                auto target = getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + specific->target);
                if (!target) {
                    if (!executionState) {
                        executionState = allocateComponentExecutionState<LVGLExecutionState>(flowState, componentIndex);
                    }
                    executionState->actionIndex = actionIndex;
                    addToQueue(flowState, componentIndex, -1, -1, -1, true);
                    return;
                } else {
                    lv_group_focus_obj(target);
                }
            } else if (specific->groupAction == GROUP_ACTION_FOCUS_NEXT) {
                auto target = getLvglGroupFromIndexHook(specific->target);
                if (target) {
                    lv_group_focus_next(target);
                }
            } else if (specific->groupAction == GROUP_ACTION_FOCUS_PREVIOUS) {
                auto target = getLvglGroupFromIndexHook(specific->target);
                if (target) {
                    lv_group_focus_prev(target);
                }
            } else if (specific->groupAction == GROUP_ACTION_FOCUS_FREEZE) {
                auto target = getLvglGroupFromIndexHook(specific->target);
                if (target) {
                    lv_group_focus_freeze(target, specific->enable ? true : false);
                }
            } else {
                auto target = getLvglGroupFromIndexHook(specific->target);
                if (target) {
                    lv_group_set_editing(target, specific->enable ? true : false);
                }
            }
        } else if (general->action == ADD_STATE) {
            auto specific = (LVGLComponent_AddState_ActionType *)general;
            auto target = getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + specific->target);
            if (!target) {
                if (!executionState) {
                    executionState = allocateComponentExecutionState<LVGLExecutionState>(flowState, componentIndex);
                }
                executionState->actionIndex = actionIndex;
                addToQueue(flowState, componentIndex, -1, -1, -1, true);
                return;
            } else {
                lv_obj_add_state(target, (lv_state_t)specific->state);
            }
        } else if (general->action == CLEAR_STATE) {
            auto specific = (LVGLComponent_ClearState_ActionType *)general;
            auto target = getLvglObjectFromIndexHook(flowState->lvglWidgetStartIndex + specific->target);
            if (!target) {
                if (!executionState) {
                    executionState = allocateComponentExecutionState<LVGLExecutionState>(flowState, componentIndex);
                }
                executionState->actionIndex = actionIndex;
                addToQueue(flowState, componentIndex, -1, -1, -1, true);
                return;
            } else {
                lv_obj_clear_state(target, (lv_state_t)specific->state);
            }
        }
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References actions, addToQueue(), anim_get_callbacks, anim_path_callbacks, anim_set_callbacks, ARC_VALUE, BAR_VALUE, BASIC_CHECKED, BASIC_DISABLED, BASIC_HEIGHT, BASIC_HIDDEN, BASIC_OPACITY, BASIC_WIDTH, BASIC_X, BASIC_Y, componentIndex, DROPDOWN_SELECTED, eez_flow_pop_screen(), eez_flow_push_screen(), evalExpression(), flowState, getLvglGroupFromIndexHook, getLvglImageByNameHook, getLvglObjectFromIndexHook, GROUP_ACTION_FOCUS_FREEZE, GROUP_ACTION_FOCUS_NEXT, GROUP_ACTION_FOCUS_OBJ, GROUP_ACTION_FOCUS_PREVIOUS, GROUP_ACTION_SET_WRAP, IMAGE_ANGLE, IMAGE_IMAGE, IMAGE_ZOOM, KEYBOARD_TEXTAREA, LABEL_TEXT, lvglObjAddStyleHook, lvglObjRemoveStyleHook, propagateValueThroughSeqout(), ROLLER_SELECTED, SLIDER_VALUE, and throwError().
executeLVGLUserWidgetComponent()
void eez::flow::executeLVGLUserWidgetComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 4835 of file eez-flow.cpp.
{
    auto userWidgetWidgetExecutionState = (LVGLUserWidgetExecutionState *)flowState->componenentExecutionStates[componentIndex];
    if (!userWidgetWidgetExecutionState) {
        userWidgetWidgetExecutionState = createUserWidgetFlowState(flowState, componentIndex);
    }
    auto userWidgetFlowState = userWidgetWidgetExecutionState->flowState;
    for (
        unsigned userWidgetComponentIndex = 0;
        userWidgetComponentIndex < userWidgetFlowState->flow->components.count;
        userWidgetComponentIndex++
    ) {
        auto userWidgetComponent = userWidgetFlowState->flow->components[userWidgetComponentIndex];
        if (userWidgetComponent->type == defs_v3::COMPONENT_TYPE_INPUT_ACTION) {
            auto inputActionComponentExecutionState = (InputActionComponentExecutionState *)userWidgetFlowState->componenentExecutionStates[userWidgetComponentIndex];
            if (inputActionComponentExecutionState) {
                Value value;
                if (getCallActionValue(userWidgetFlowState, userWidgetComponentIndex, value)) {
                    if (inputActionComponentExecutionState->value != value) {
                        addToQueue(userWidgetWidgetExecutionState->flowState, userWidgetComponentIndex, -1, -1, -1, false);
                        inputActionComponentExecutionState->value = value;
                    }
                } else {
                    return;
                }
            }
        } else if (userWidgetComponent->type == defs_v3::COMPONENT_TYPE_START_ACTION) {
            Value value;
            if (getCallActionValue(userWidgetFlowState, userWidgetComponentIndex, value)) {
                if (value.getType() != VALUE_TYPE_UNDEFINED) {
                    addToQueue(userWidgetWidgetExecutionState->flowState, userWidgetComponentIndex, -1, -1, -1, false);
                }
            } else {
                return;
            }
        }
    }
}
References addToQueue(), componentIndex, createUserWidgetFlowState(), flowState, and getCallActionValue().
executeMQTTConnectComponent()
void eez::flow::executeMQTTConnectComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5129 of file eez-flow.cpp.
{
    Value connectionValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_CONNECT_ACTION_COMPONENT_PROPERTY_CONNECTION, connectionValue, FlowError::Property("MQTTConnect", "Connection"))) {
        return;
    }
    if (!connectionValue.isArray() || connectionValue.getArray()->arrayType != defs_v3::OBJECT_TYPE_MQTT_CONNECTION) {
        throwError(flowState, componentIndex, FlowError::Plain("Connection must be a object:MQTTConnection"));
        return;
    }
    auto connectionArray = connectionValue.getArray();
    void *handle = connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_ID].getVoidPointer();
    auto result = eez_mqtt_connect(handle);
    if (result != MQTT_ERROR_OK) {
        char errorMessage[256];
        snprintf(errorMessage, sizeof(errorMessage), "Failed to connect to MQTT broker with error code: %d", (int)result);
        throwError(flowState, componentIndex, FlowError::Plain(errorMessage));
        return;
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, eez_mqtt_connect(), evalProperty(), flowState, propagateValueThroughSeqout(), and throwError().
executeMQTTDisconnectComponent()
void eez::flow::executeMQTTDisconnectComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5149 of file eez-flow.cpp.
{
    Value connectionValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_DISCONNECT_ACTION_COMPONENT_PROPERTY_CONNECTION, connectionValue, FlowError::Property("MQTTDisconnect", "Connection"))) {
        return;
    }
    if (!connectionValue.isArray() || connectionValue.getArray()->arrayType != defs_v3::OBJECT_TYPE_MQTT_CONNECTION) {
        throwError(flowState, componentIndex, FlowError::Plain("Connection must be a object:MQTTConnection"));
        return;
    }
    auto connectionArray = connectionValue.getArray();
    void *handle = connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_ID].getVoidPointer();
    auto result = eez_mqtt_disconnect(handle);
    if (result != MQTT_ERROR_OK) {
        char errorMessage[256];
        snprintf(errorMessage, sizeof(errorMessage), "Failed to disconnect from MQTT broker with error code: %d", (int)result);
        throwError(flowState, componentIndex, FlowError::Plain(errorMessage));
        return;
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, eez_mqtt_disconnect(), evalProperty(), flowState, propagateValueThroughSeqout(), and throwError().
executeMQTTEventComponent()
void eez::flow::executeMQTTEventComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5169 of file eez-flow.cpp.
{
    Value connectionValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_EVENT_ACTION_COMPONENT_PROPERTY_CONNECTION, connectionValue, FlowError::Property("MQTTEvent", "Connection"))) {
        return;
    }
    if (!connectionValue.isArray() || connectionValue.getArray()->arrayType != defs_v3::OBJECT_TYPE_MQTT_CONNECTION) {
        throwError(flowState, componentIndex, FlowError::Plain("Connection must be a object:MQTTConnection"));
        return;
    }
    auto componentExecutionState = (MQTTEventActionComponenentExecutionState *)flowState->componenentExecutionStates[componentIndex];
    if (!componentExecutionState) {
        componentExecutionState = allocateComponentExecutionState<MQTTEventActionComponenentExecutionState>(flowState, componentIndex);
        componentExecutionState->flowState = flowState;
        componentExecutionState->componentIndex = componentIndex;
        auto connectionArray = connectionValue.getArray();
        void *handle = connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_ID].getVoidPointer();
        addConnectionEventHandler(handle, componentExecutionState);
        propagateValueThroughSeqout(flowState, componentIndex);
        addToQueue(flowState, componentIndex, -1, -1, -1, true);
    } else {
        auto event = componentExecutionState->removeEvent();
        if (event) {
            propagateValue(flowState, componentIndex, event->outputIndex, event->value);
            ObjectAllocator<MQTTEvent>::deallocate(event);
        } else {
            addToQueue(flowState, componentIndex, -1, -1, -1, true);
        }
    }
}
References addConnectionEventHandler(), addToQueue(), componentIndex, evalProperty(), flowState, propagateValue(), propagateValueThroughSeqout(), and throwError().
executeMQTTInitComponent()
void eez::flow::executeMQTTInitComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5056 of file eez-flow.cpp.
{
    Value connectionDstValue;
    if (!evalAssignableProperty(flowState, componentIndex, defs_v3::MQTT_INIT_ACTION_COMPONENT_PROPERTY_CONNECTION, connectionDstValue, FlowError::Property("MQTTInit", "Connection"))) {
        return;
    }
    Value protocolValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_INIT_ACTION_COMPONENT_PROPERTY_PROTOCOL, protocolValue, FlowError::Property("MQTTInit", "Protocol"))) {
        return;
    }
    if (!protocolValue.isString()) {
        throwError(flowState, componentIndex, FlowError::Plain("Protocol must be a string"));
        return;
    }
    Value hostValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_INIT_ACTION_COMPONENT_PROPERTY_HOST, hostValue, FlowError::Property("MQTTInit", "Host"))) {
        return;
    }
    if (!hostValue.isString()) {
        throwError(flowState, componentIndex, FlowError::Plain("Host must be a string"));
        return;
    }
    Value portValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_INIT_ACTION_COMPONENT_PROPERTY_PORT, portValue, FlowError::Property("MQTTInit", "Port"))) {
        return;
    }
    if (portValue.getType() != VALUE_TYPE_INT32) {
        throwError(flowState, componentIndex, FlowError::Plain("Port must be an integer"));
        return;
    }
    Value usernameValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_INIT_ACTION_COMPONENT_PROPERTY_USER_NAME, usernameValue, FlowError::Property("MQTTInit", "Username"))) {
        return;
    }
    if (usernameValue.getType() != VALUE_TYPE_UNDEFINED && !usernameValue.isString()) {
        throwError(flowState, componentIndex, FlowError::Plain("Username must be a string"));
        return;
    }
    Value passwordValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_INIT_ACTION_COMPONENT_PROPERTY_PASSWORD, passwordValue, FlowError::Property("MQTTInit", "Password"))) {
        return;
    }
    if (passwordValue.getType() != VALUE_TYPE_UNDEFINED && !passwordValue.isString()) {
        throwError(flowState, componentIndex, FlowError::Plain("Password must be a string"));
        return;
    }
    void *handle;
    auto result = eez_mqtt_init(protocolValue.getString(), hostValue.getString(), portValue.getInt32(), usernameValue.getString(), passwordValue.getString(), &handle);
    if (result != MQTT_ERROR_OK) {
        char errorMessage[256];
        snprintf(errorMessage, sizeof(errorMessage), "Failed to initialize MQTT connection with error code: %d", (int)result);
        throwError(flowState, componentIndex, FlowError::Plain(errorMessage));
        return;
    }
    addConnection(handle);
    Value connectionValue = Value::makeArrayRef(defs_v3::OBJECT_TYPE_MQTT_CONNECTION_NUM_FIELDS, defs_v3::OBJECT_TYPE_MQTT_CONNECTION, 0x51ba2203);
    auto connectionArray = connectionValue.getArray();
    connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_PROTOCOL] = protocolValue;
    connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_HOST] = hostValue;
    connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_PORT] = portValue;
    connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_USER_NAME] = usernameValue;
    connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_PASSWORD] = passwordValue;
    connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_IS_CONNECTED] = Value(false, VALUE_TYPE_BOOLEAN);
    connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_ID] = Value(handle, VALUE_TYPE_POINTER);
    Value statusValue = Value::makeArrayRef(defs_v3::SYSTEM_STRUCTURE_OBJECT_VARIABLE_STATUS_NUM_FIELDS, defs_v3::SYSTEM_STRUCTURE_OBJECT_VARIABLE_STATUS, 0x51ba2203);
    auto statusArray = statusValue.getArray();
    statusArray->values[defs_v3::SYSTEM_STRUCTURE_OBJECT_VARIABLE_STATUS_FIELD_LABEL] = Value("", VALUE_TYPE_STRING);
    statusArray->values[defs_v3::SYSTEM_STRUCTURE_OBJECT_VARIABLE_STATUS_FIELD_IMAGE] = Value("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAItSURBVEhL1dZNSBVRGMbxmcjCiFz14aJVlKtcVFjUJghCIlq5aBHoQiwoyJaRCzdRUUhQUIuIyKiEdoLuolCQEgQzyk8KjTZhidEnwe3/nJl3ermc8m5c9MCPmTtn5rz3zMw596alUilZzqzIt8uWYgRpmp5ncxQ/4YelL/EJ9/AQ87CkOIMT4VOS/MIq9NDvuXBEBfIiL/VxCW/Qjmr4tMG+mMwU/boCW7ETB3EKdzEFu8h7jr3w0XUandrHYwViWYdDeAT/DeUbTsPnAL5jOlZAw9b9+1v2oB++iFyGzzFER9CHEfTiAhpRg/KcxGf4Ilfh0xIrMAN/kUyjE7Xw2Yc5+HM7UCRWQJ35C7x3aIVPPWbhzzuCkFgBPczj6MIQyh+q3MEaWBqgOWLteo03IVrAR5NrF26jvJCe1VpYmuHbr2PJAj778Qq+kx74ZeYBrO0r6mMF9CbcQAs264CLHvIgrBM5C8s2LMDabsUK6P7ZCR9wCf413YgXsHMWsR2Wa7C2iViBcXeCGcYWWHbjC6y9G5Yd0CzW8ehEixWQUWyA5QqsTROuDopW1gHoeFGgkt8Dve8Xs92Qm9DtUfQ2Hc52Q8ePs90/qfQHR+uLXltFE/JpthuiBc7yLN9qNCGVFqhCU7Yb8iTfKrpFWnWVt/iBaAF18q9o/bFM5FtFr/D6bDf5CBUoVmVf4D40fD3s12V0XPd9NZT30OSbzK2Eokk2Bk28kP/9X0WS/AaVCm1sgeHGuwAAAABJRU5ErkJggg==", VALUE_TYPE_STRING);
    statusArray->values[defs_v3::SYSTEM_STRUCTURE_OBJECT_VARIABLE_STATUS_FIELD_COLOR] = Value("gray", VALUE_TYPE_STRING);
    statusArray->values[defs_v3::SYSTEM_STRUCTURE_OBJECT_VARIABLE_STATUS_FIELD_ERROR] = Value();
    connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_STATUS] = statusValue;
    assignValue(flowState, componentIndex, connectionDstValue, connectionValue);
    propagateValueThroughSeqout(flowState, componentIndex);
}
References addConnection(), assignValue(), componentIndex, eez_mqtt_init(), evalAssignableProperty(), evalProperty(), flowState, propagateValueThroughSeqout(), and throwError().
executeMQTTPublishComponent()
void eez::flow::executeMQTTPublishComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5254 of file eez-flow.cpp.
{
    Value connectionValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_PUBLISH_ACTION_COMPONENT_PROPERTY_CONNECTION, connectionValue, FlowError::Property("MQTTPublish", "Connection"))) {
        return;
    }
    if (!connectionValue.isArray() || connectionValue.getArray()->arrayType != defs_v3::OBJECT_TYPE_MQTT_CONNECTION) {
        throwError(flowState, componentIndex, FlowError::Plain("Connection must be a object:MQTTConnection"));
        return;
    }
    Value topicValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_PUBLISH_ACTION_COMPONENT_PROPERTY_TOPIC, topicValue, FlowError::Property("MQTTPublish", "Topic"))) {
        return;
    }
    if (!topicValue.isString()) {
        throwError(flowState, componentIndex, FlowError::Plain("Topic must be a string"));
        return;
    }
    Value payloadValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_PUBLISH_ACTION_COMPONENT_PROPERTY_PAYLOAD, payloadValue, FlowError::Property("MQTTPublish", "Payload"))) {
        return;
    }
    if (!payloadValue.isString()) {
        throwError(flowState, componentIndex, FlowError::Plain("Payload must be a string"));
        return;
    }
    auto connectionArray = connectionValue.getArray();
    void *handle = connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_ID].getVoidPointer();
    auto result = eez_mqtt_publish(handle, topicValue.getString(), payloadValue.getString());
    if (result != MQTT_ERROR_OK) {
        char errorMessage[256];
        snprintf(errorMessage, sizeof(errorMessage), "Failed to subscribe to MQTT topic with error code: %d", (int)result);
        throwError(flowState, componentIndex, FlowError::Plain(errorMessage));
        return;
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, eez_mqtt_publish(), evalProperty(), flowState, propagateValueThroughSeqout(), and throwError().
executeMQTTSubscribeComponent()
void eez::flow::executeMQTTSubscribeComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5198 of file eez-flow.cpp.
{
    Value connectionValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_SUBSCRIBE_ACTION_COMPONENT_PROPERTY_CONNECTION, connectionValue, FlowError::Property("MQTTSubscribe", "Connection"))) {
        return;
    }
    if (!connectionValue.isArray() || connectionValue.getArray()->arrayType != defs_v3::OBJECT_TYPE_MQTT_CONNECTION) {
        throwError(flowState, componentIndex, FlowError::Plain("Connection must be a object:MQTTConnection"));
        return;
    }
    Value topicValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_SUBSCRIBE_ACTION_COMPONENT_PROPERTY_TOPIC, topicValue, FlowError::Property("MQTTSubscribe", "Topic"))) {
        return;
    }
    if (!topicValue.isString()) {
        throwError(flowState, componentIndex, FlowError::Plain("Topic must be a string"));
        return;
    }
    auto connectionArray = connectionValue.getArray();
    void *handle = connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_ID].getVoidPointer();
    auto result = eez_mqtt_subscribe(handle, topicValue.getString());
    if (result != MQTT_ERROR_OK) {
        char errorMessage[256];
        snprintf(errorMessage, sizeof(errorMessage), "Failed to subscribe to MQTT topic with error code: %d", (int)result);
        throwError(flowState, componentIndex, FlowError::Plain(errorMessage));
        return;
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, eez_mqtt_subscribe(), evalProperty(), flowState, propagateValueThroughSeqout(), and throwError().
executeMQTTUnsubscribeComponent()
void eez::flow::executeMQTTUnsubscribeComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5226 of file eez-flow.cpp.
{
    Value connectionValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_UNSUBSCRIBE_ACTION_COMPONENT_PROPERTY_CONNECTION, connectionValue, FlowError::Property("MQTTUnsubscribe", "Connection"))) {
        return;
    }
    if (!connectionValue.isArray() || connectionValue.getArray()->arrayType != defs_v3::OBJECT_TYPE_MQTT_CONNECTION) {
        throwError(flowState, componentIndex, FlowError::Plain("Connection must be a object:MQTTConnection"));
        return;
    }
    Value topicValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::MQTT_UNSUBSCRIBE_ACTION_COMPONENT_PROPERTY_TOPIC, topicValue, FlowError::Property("MQTTUnsubscribe", "Topic"))) {
        return;
    }
    if (!topicValue.isString()) {
        throwError(flowState, componentIndex, FlowError::Plain("Topic must be a string"));
        return;
    }
    auto connectionArray = connectionValue.getArray();
    void *handle = connectionArray->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_ID].getVoidPointer();
    auto result = eez_mqtt_unsubscribe(handle, topicValue.getString());
    if (result != MQTT_ERROR_OK) {
        char errorMessage[256];
        snprintf(errorMessage, sizeof(errorMessage), "Failed to unsubscribe from MQTT topic with error code: %d", (int)result);
        throwError(flowState, componentIndex, FlowError::Plain(errorMessage));
        return;
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, eez_mqtt_unsubscribe(), evalProperty(), flowState, propagateValueThroughSeqout(), and throwError().
executeNoopComponent()
void eez::flow::executeNoopComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5447 of file eez-flow.cpp.
{
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, flowState, and propagateValueThroughSeqout().
executeOnEventComponent()
void eez::flow::executeOnEventComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5457 of file eez-flow.cpp.
{
    propagateValue(flowState, componentIndex, 1, flowState->eventValue);
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, flowState, propagateValue(), and propagateValueThroughSeqout().
executeOutputComponent()
void eez::flow::executeOutputComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5471 of file eez-flow.cpp.
{
    auto component = (OutputActionComponent *)flowState->flow->components[componentIndex];
    if (!flowState->parentFlowState) {
        throwError(flowState, componentIndex, FlowError::Plain("No parentFlowState in Output"));
        return;
    }
    if (!flowState->parentComponent) {
        throwError(flowState, componentIndex, FlowError::Plain("No parentComponent in Output"));
        return;
    }
    auto inputIndex = component->inputs[0];
    if (inputIndex >= flowState->flow->componentInputs.count) {
        throwError(flowState, componentIndex, FlowError::Plain("Invalid input index in Output"));
        return;
    }
    auto value = flowState->values[inputIndex];
    auto callActionComponent = (CallActionActionComponent *)flowState->parentComponent;
    uint8_t parentComponentOutputIndex = callActionComponent->outputsStartIndex + component->outputIndex;
    if (parentComponentOutputIndex >= flowState->parentComponent->outputs.count) {
        throwError(flowState, componentIndex, FlowError::Plain("Output action component, invalid output index"));
        return;
    }
    propagateValue(flowState->parentFlowState, flowState->parentComponentIndex, parentComponentOutputIndex, value);
}
References componentIndex, flowState, propagateValue(), and throwError().
executeSelectLanguageComponent()
void eez::flow::executeSelectLanguageComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5504 of file eez-flow.cpp.
{
    Value languageValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::SELECT_LANGUAGE_ACTION_COMPONENT_PROPERTY_LANGUAGE, languageValue, FlowError::Property("SelectLanguage", "Language"))) {
        return;
    }
    const char *language = languageValue.getString();
    auto &languages = flowState->assets->languages;
    for (uint32_t languageIndex = 0; languageIndex < languages.count; languageIndex++) {
        if (strcmp(languages[languageIndex]->languageID, language) == 0) {
            g_selectedLanguage = languageIndex;
            propagateValueThroughSeqout(flowState, componentIndex);
            return;
        }
    }
    char message[256];
    snprintf(message, sizeof(message), "Unknown language %s", language);
    throwError(flowState, componentIndex, FlowError::Plain(message));
}
References componentIndex, evalProperty(), flowState, g_selectedLanguage, propagateValueThroughSeqout(), and throwError().
executeSetColorThemeComponent()
void eez::flow::executeSetColorThemeComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5535 of file eez-flow.cpp.
{
    Value themeValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::SET_COLOR_THEME_ACTION_COMPONENT_PROPERTY_THEME, themeValue, FlowError::Property("SetColorTheme", "Theme"))) {
        return;
    }
    const char *theme = themeValue.getString();
#if defined(EEZ_FOR_LVGL)
    lvglSetColorThemeHook(theme);
#elif EEZ_OPTION_GUI
#if defined(EEZ_DASHBOARD_API)
    if (g_mainAssets->assetsType == ASSETS_TYPE_DASHBOARD) {
        setDashboardColorTheme(theme);
        propagateValueThroughSeqout(flowState, componentIndex);
    } else {
#endif
        auto &themes = flowState->assets->colorsDefinition->themes;
        for (uint32_t themeIndex = 0; themeIndex < themes.count; themeIndex++) {
            if (strcmp(themes[themeIndex]->name, theme) == 0) {
                eez::gui::g_selectedThemeIndex = themeIndex;
                eez::gui::display::onThemeChanged();
                propagateValueThroughSeqout(flowState, componentIndex);
                return;
            }
        }
        char message[256];
        snprintf(message, sizeof(message), "Unknown theme %s", theme);
        throwError(flowState, componentIndex, FlowError::Plain(message));
#if defined(EEZ_DASHBOARD_API)
    }
#endif
#endif
}
References componentIndex, evalProperty(), flowState, eez::g_mainAssets, lvglSetColorThemeHook, propagateValueThroughSeqout(), and throwError().
executeSetVariableComponent()
void eez::flow::executeSetVariableComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5575 of file eez-flow.cpp.
{
    auto component = (SetVariableActionComponent *)flowState->flow->components[componentIndex];
    for (uint32_t entryIndex = 0; entryIndex < component->entries.count; entryIndex++) {
        auto entry = component->entries[entryIndex];
        Value dstValue;
        if (!evalAssignableExpression(flowState, componentIndex, entry->variable, dstValue, FlowError::PropertyInArray("SetVariable", "Variable", entryIndex))) {
            return;
        }
        Value srcValue;
        if (!evalExpression(flowState, componentIndex, entry->value, srcValue, FlowError::PropertyInArray("SetVariable", "Value", entryIndex))) {
            return;
        }
        assignValue(flowState, componentIndex, dstValue, srcValue);
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References assignValue(), componentIndex, evalAssignableExpression(), evalExpression(), flowState, and propagateValueThroughSeqout().
executeShowPageComponent()
void eez::flow::executeShowPageComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5601 of file eez-flow.cpp.
{
    auto component = (ShowPageActionComponent *)flowState->flow->components[componentIndex];
    replacePageHook(component->page, 0, 0, 0);
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, flowState, propagateValueThroughSeqout(), and replacePageHook.
executeSortArrayComponent()
void eez::flow::executeSortArrayComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5666 of file eez-flow.cpp.
{
    auto component = (SortArrayActionComponent *)flowState->flow->components[componentIndex];
    Value srcArrayValue;
    if (!evalProperty(flowState, componentIndex, defs_v3::SORT_ARRAY_ACTION_COMPONENT_PROPERTY_ARRAY, srcArrayValue, FlowError::Property("SortArray", "Array"))) {
        return;
    }
    if (!srcArrayValue.isArray()) {
        throwError(flowState, componentIndex, FlowError::Plain("SortArray: not an array\n"));
        return;
    }
    auto arrayValue = srcArrayValue.clone();
    auto array = arrayValue.getArray();
    if (component->arrayType != -1) {
        if (array->arrayType != (uint32_t)component->arrayType) {
            throwError(flowState, componentIndex, FlowError::Plain("SortArray: invalid array type\n"));
            return;
        }
        if (component->structFieldIndex < 0) {
            throwError(flowState, componentIndex, FlowError::Plain("SortArray: invalid struct field index\n"));
        }
    } else {
        if (array->arrayType != defs_v3::ARRAY_TYPE_INTEGER && array->arrayType != defs_v3::ARRAY_TYPE_FLOAT && array->arrayType != defs_v3::ARRAY_TYPE_DOUBLE && array->arrayType != defs_v3::ARRAY_TYPE_STRING) {
            throwError(flowState, componentIndex, FlowError::Plain("SortArray: array type is neither array:integer or array:float or array:double or array:string\n"));
            return;
        }
    }
    sortArray(component, array);
    propagateValue(flowState, componentIndex, component->outputs.count - 1, arrayValue);
}
References componentIndex, evalProperty(), flowState, propagateValue(), sortArray(), and throwError().
executeStartComponent()
void eez::flow::executeStartComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5702 of file eez-flow.cpp.
{
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, flowState, and propagateValueThroughSeqout().
executeSwitchComponent()
void eez::flow::executeSwitchComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5713 of file eez-flow.cpp.
{
    auto component = (SwitchActionComponent *)flowState->flow->components[componentIndex];
    for (uint32_t testIndex = 0; testIndex < component->tests.count; testIndex++) {
        auto test = component->tests[testIndex];
        Value conditionValue;
        if (!evalExpression(flowState, componentIndex, test->condition, conditionValue, FlowError::PropertyInArray("Switch", "Test condition", testIndex))) {
            return;
        }
        int err;
        bool result = conditionValue.toBool(&err);
        if (err) {
            throwError(flowState, componentIndex, FlowError::PropertyInArrayConvert("Switch", "Test condition", "boolean", testIndex));
            return;
        }
        if (result) {
            Value outputValue;
            if (!evalExpression(flowState, componentIndex, test->outputValue, outputValue, FlowError::PropertyInArray("Switch", "Test output", testIndex))) {
                return;
            }
            propagateValue(flowState, componentIndex, test->outputIndex, outputValue);
            break;
        }
    }
    propagateValueThroughSeqout(flowState, componentIndex);
}
References componentIndex, evalExpression(), flowState, propagateValue(), propagateValueThroughSeqout(), and throwError().
executeTestAndSetComponent()
void eez::flow::executeTestAndSetComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5745 of file eez-flow.cpp.
{
    Value dstValue;
    if (!evalAssignableProperty(flowState, componentIndex, defs_v3::TEST_AND_SET_ACTION_COMPONENT_PROPERTY_VARIABLE, dstValue, FlowError::Property("TestAndSet", "Variable"))) {
        return;
    }
    if (dstValue.getValue().type != VALUE_TYPE_BOOLEAN) {
        throwError(flowState, componentIndex, FlowError::PropertyConvert("TestAndSet", "Variable", "boolean"));
        return;
    }
    if (!dstValue.getValue().getBoolean()) {
        assignValue(flowState, componentIndex, dstValue, Value(true, VALUE_TYPE_BOOLEAN));
        propagateValueThroughSeqout(flowState, componentIndex);
    } else {
        addToQueue(flowState, componentIndex, -1, -1, -1, true);
    }
}
References addToQueue(), assignValue(), componentIndex, evalAssignableProperty(), flowState, propagateValueThroughSeqout(), and throwError().
executeWatchVariableComponent()
void eez::flow::executeWatchVariableComponent (FlowState * flowState, unsigned componentIndex)
Definition at line 5773 of file eez-flow.cpp.
{
    auto watchVariableComponentExecutionState = (WatchVariableComponenentExecutionState *)flowState->componenentExecutionStates[componentIndex];
    Value value;
    if (!evalProperty(flowState, componentIndex, defs_v3::WATCH_VARIABLE_ACTION_COMPONENT_PROPERTY_VARIABLE, value, FlowError::Property("WatchVariable", "Variable"))) {
        return;
    }
    if (!watchVariableComponentExecutionState) {
        watchVariableComponentExecutionState = allocateComponentExecutionState<WatchVariableComponenentExecutionState>(flowState, componentIndex);
        watchVariableComponentExecutionState->value = value.type == VALUE_TYPE_STRING ? value.clone() : value;
        watchVariableComponentExecutionState->node = watchListAdd(flowState, componentIndex);
        propagateValue(flowState, componentIndex, 1, value);
    } else {
        if (value != watchVariableComponentExecutionState->value) {
            watchVariableComponentExecutionState->value = value.type == VALUE_TYPE_STRING ? value.clone() : value;
            propagateValue(flowState, componentIndex, 1, value);
        }
    }
}
References componentIndex, evalProperty(), flowState, propagateValue(), and watchListAdd().
Referenced by visitWatchList().
findCatchErrorComponent()
bool eez::flow::findCatchErrorComponent (FlowState * flowState, FlowState *& catchErrorFlowState, int & catchErrorComponentIndex) static
Definition at line 10875 of file eez-flow.cpp.
{
    if (!flowState) {
        return false;
    }
    for (unsigned componentIndex = 0; componentIndex < flowState->flow->components.count; componentIndex++) {
        auto component = flowState->flow->components[componentIndex];
        if (component->type == defs_v3::COMPONENT_TYPE_CATCH_ERROR_ACTION) {
            catchErrorFlowState = flowState;
            catchErrorComponentIndex = componentIndex;
            return true;
        }
    }
    if (flowState->parentFlowState && flowState->parentComponent && flowState->parentComponent->errorCatchOutput != -1) {
        catchErrorFlowState = flowState->parentFlowState;
        catchErrorComponentIndex = flowState->parentComponentIndex;
        return true;
    }
    return findCatchErrorComponent(flowState->parentFlowState, catchErrorFlowState, catchErrorComponentIndex);
}
References componentIndex, findCatchErrorComponent(), and flowState.
Referenced by findCatchErrorComponent(), and throwError().
findConnection()
MQTTConnection * eez::flow::findConnection (void * handle) static
Definition at line 4970 of file eez-flow.cpp.
{
    for (auto connection = g_firstMQTTConnection; connection; connection = connection->next) {
        if (connection->handle == handle) {
            return connection;
        }
    }
    return nullptr;
}
References g_firstMQTTConnection.
Referenced by addConnectionEventHandler(), and deleteConnection().
finishToDebuggerMessage()
void eez::flow::finishToDebuggerMessage () static
Definition at line 7515 of file eez-flow.cpp.
{
}
References finishToDebuggerMessage().
Referenced by finishToDebuggerMessage().
freeAllChildrenFlowStates()
void eez::flow::freeAllChildrenFlowStates (FlowState * firstChildFlowState)
Definition at line 10629 of file eez-flow.cpp.
{
    auto flowState = firstChildFlowState;
    while (flowState != nullptr) {
        auto nextFlowState = flowState->nextSibling;
        freeAllChildrenFlowStates(flowState->firstChild);
        freeFlowState(flowState);
        flowState = nextFlowState;
    }
}
References flowState, freeAllChildrenFlowStates(), and freeFlowState().
Referenced by doStop(), freeAllChildrenFlowStates(), and freeFlowState().
freeFlowState()
void eez::flow::freeFlowState (FlowState * flowState)
Definition at line 10584 of file eez-flow.cpp.
{
    auto parentFlowState = flowState->parentFlowState;
    if (parentFlowState) {
        if (flowState->parentComponentIndex != -1) {
            auto componentExecutionState = parentFlowState->componenentExecutionStates[flowState->parentComponentIndex];
            if (componentExecutionState) {
                deallocateComponentExecutionState(parentFlowState, flowState->parentComponentIndex);
                return;
            }
        }
        if (parentFlowState->firstChild == flowState) {
            parentFlowState->firstChild = flowState->nextSibling;
        }
        if (parentFlowState->lastChild == flowState) {
            parentFlowState->lastChild = flowState->previousSibling;
        }
    } else {
        if (g_firstFlowState == flowState) {
            g_firstFlowState = flowState->nextSibling;
        }
        if (g_lastFlowState == flowState) {
            g_lastFlowState = flowState->previousSibling;
        }
    }
    if (flowState->previousSibling) {
        flowState->previousSibling->nextSibling = flowState->nextSibling;
    }
    if (flowState->nextSibling) {
        flowState->nextSibling->previousSibling = flowState->previousSibling;
    }
    auto flow = flowState->flow;
    auto valuesCount = flow->componentInputs.count + flow->localVariables.count;
    for (unsigned int i = 0; i < valuesCount; i++) {
        (flowState->values + i)->~Value();
    }
    for (unsigned i = 0; i < flow->components.count; i++) {
        deallocateComponentExecutionState(flowState, i);
    }
    removeTasksFromQueueForFlowState(flowState);
    removeWatchesForFlowState(flowState);
    freeAllChildrenFlowStates(flowState->firstChild);
    onFlowStateDestroyed(flowState);
    flowState->~FlowState();
    free(flowState);
}
References deallocateComponentExecutionState(), flowState, eez::free(), freeAllChildrenFlowStates(), freeFlowState(), g_firstFlowState, g_lastFlowState, onFlowStateDestroyed(), removeTasksFromQueueForFlowState(), and removeWatchesForFlowState().
Referenced by endAsyncExecution(), executeCallAction(), freeAllChildrenFlowStates(), freeFlowState(), tick(), and visitWatchList().
getCallActionValue()
bool eez::flow::getCallActionValue (FlowState * flowState, unsigned componentIndex, Value & value)
Definition at line 3482 of file eez-flow.cpp.
{
    auto component = flowState->flow->components[componentIndex];
    if (!flowState->parentFlowState) {
        throwError(flowState, componentIndex, FlowError::Plain("No parentFlowState in Input"));
        return false;
    }
    if (!flowState->parentComponent) {
        if (flowState->parentComponentIndex == -1) {
            value = flowState->inputValue;
            return true;
        }
        throwError(flowState, componentIndex, FlowError::Plain("No parentComponent in Input"));
        return false;
    }
    auto callActionComponent = (CallActionActionComponent *)flowState->parentComponent;
    uint8_t callActionComponentInputIndex = callActionComponent->inputsStartIndex;
    if (component->type == defs_v3::COMPONENT_TYPE_INPUT_ACTION) {
        auto inputActionComponent = (InputActionComponent *)component;
        callActionComponentInputIndex += inputActionComponent->inputIndex;
    } else {
        callActionComponentInputIndex -= 1;
    }
    if (callActionComponentInputIndex >= callActionComponent->inputs.count) {
        throwError(flowState, componentIndex, FlowError::Plain("Invalid input index in Input"));
        return false;
    }
    auto &parentComponentInputs = callActionComponent->inputs;
    auto parentFlowInputIndex = parentComponentInputs[callActionComponentInputIndex];
    auto parentFlow = flowState->flowDefinition->flows[flowState->parentFlowState->flowIndex];
    if (parentFlowInputIndex >= parentFlow->componentInputs.count) {
        throwError(flowState, componentIndex, FlowError::Plain("Invalid input index of parent component in Input"));
        return false;
    }
    value = flowState->parentFlowState->values[parentFlowInputIndex];
    return true;
}
References componentIndex, flowState, and throwError().
Referenced by executeInputComponent(), and executeLVGLUserWidgetComponent().
getDateNowDefaultImplementation()
double eez::flow::getDateNowDefaultImplementation () static
Definition at line 7583 of file eez-flow.cpp.
{
    using namespace std::chrono;
    milliseconds ms = duration_cast<milliseconds>(system_clock::now().time_since_epoch());
    return (double)ms.count();
}
References getDateNowDefaultImplementation().
Referenced by getDateNowDefaultImplementation().
getEmptyInputValue()
Value eez::flow::getEmptyInputValue () inline
Definition at line 10391 of file eez-flow.cpp.
{
    Value emptyInputValue;
    emptyInputValue.int32Value = 1;
    return emptyInputValue;
}
References getEmptyInputValue().
Referenced by getEmptyInputValue(), initFlowState(), and resetSequenceInputs().
getGlobalVariable() [1/2]
Value eez::flow::getGlobalVariable (Assets * assets, uint32_t globalVariableIndex)
Definition at line 7194 of file eez-flow.cpp.
{
    if (globalVariableIndex < assets->flowDefinition->globalVariables.count) {
        return g_globalVariables ? g_globalVariables->values[globalVariableIndex] : *assets->flowDefinition->globalVariables[globalVariableIndex];
    }
    return Value();
}
References assets, and g_globalVariables.
getGlobalVariable() [2/2]
Value eez::flow::getGlobalVariable (uint32_t globalVariableIndex)
Definition at line 7191 of file eez-flow.cpp.
{
    return getGlobalVariable(g_mainAssets, globalVariableIndex);
}
References eez::g_mainAssets, and getGlobalVariable().
Referenced by getGlobalVariable().
getLvglGroupByName()
int32_t eez::flow::getLvglGroupByName (const char * name) static
Definition at line 7545 of file eez-flow.cpp.
{
    EEZ_UNUSED(name);
    return -1;
}
References EEZ_UNUSED.
getLvglGroupFromIndex()
lv_group_t * eez::flow::getLvglGroupFromIndex (int32_t index) static
Definition at line 7533 of file eez-flow.cpp.
{
    EEZ_UNUSED(index);
    return 0;
}
References EEZ_UNUSED.
getLvglImageByName()
const void * eez::flow::getLvglImageByName (const char * name) static
Definition at line 7553 of file eez-flow.cpp.
{
    EEZ_UNUSED(name);
    return 0;
}
References EEZ_UNUSED.
getLvglObjectByName()
int32_t eez::flow::getLvglObjectByName (const char * name) static
Definition at line 7541 of file eez-flow.cpp.
{
    EEZ_UNUSED(name);
    return -1;
}
References EEZ_UNUSED.
getLvglObjectFromIndex()
lv_obj_t * eez::flow::getLvglObjectFromIndex (int32_t index) static
Definition at line 7529 of file eez-flow.cpp.
{
    EEZ_UNUSED(index);
    return 0;
}
References EEZ_UNUSED.
getLvglScreenByName()
int32_t eez::flow::getLvglScreenByName (const char * name) static
Definition at line 7537 of file eez-flow.cpp.
{
    EEZ_UNUSED(name);
    return -1;
}
References EEZ_UNUSED.
getLvglStyleByName()
int32_t eez::flow::getLvglStyleByName (const char * name) static
Definition at line 7549 of file eez-flow.cpp.
{
    EEZ_UNUSED(name);
    return -1;
}
References EEZ_UNUSED.
getMaxQueueSize()
size_t eez::flow::getMaxQueueSize ()
Definition at line 11089 of file eez-flow.cpp.
{
    return g_queueMax;
}
References g_queueMax, and getMaxQueueSize().
Referenced by getMaxQueueSize().
getPageFlowState()
FlowState * eez::flow::getPageFlowState (Assets * assets, int16_t pageIndex)
Definition at line 7158 of file eez-flow.cpp.
{
    if (!assets->flowDefinition) {
        return nullptr;
    }
    if (isFlowStopped()) {
        return nullptr;
    }
    FlowState *flowState;
    for (flowState = g_firstFlowState; flowState; flowState = flowState->nextSibling) {
        if (flowState->flowIndex == pageIndex) {
            break;
        }
    }
    if (flowState) {
        flowState->deleteOnNextTick = false;
    } else {
        flowState = initPageFlowState(assets, pageIndex, nullptr, 0);
    }
    return flowState;
}
References assets, flowState, g_firstFlowState, initPageFlowState(), and isFlowStopped().
Referenced by flowOnPageLoaded(), getFlowState(), and onPageChanged().
getPageIndex()
int eez::flow::getPageIndex (FlowState * flowState)
Definition at line 7179 of file eez-flow.cpp.
{
    return flowState->flowIndex;
}
References flowState.
Referenced by do_OPERATION_TYPE_FLOW_IS_PAGE_ACTIVE().
getQueueSize()
size_t eez::flow::getQueueSize ()
Definition at line 11077 of file eez-flow.cpp.
                      {
    if (g_queueHead == g_queueTail) {
        if (g_queueIsFull) {
            return QUEUE_SIZE;
        }
        return 0;
    }
    if (g_queueHead < g_queueTail) {
        return g_queueTail - g_queueHead;
    }
    return QUEUE_SIZE - g_queueHead + g_queueTail;
}
References g_queueHead, g_queueIsFull, g_queueTail, getQueueSize(), and QUEUE_SIZE.
Referenced by addToQueue(), getQueueSize(), and tick().
getTickMaxDurationCounter()
unsigned eez::flow::getTickMaxDurationCounter ()
Definition at line 7120 of file eez-flow.cpp.
{
    return g_tick_max_duration_count;
}
References g_tick_max_duration_count.
getUserProperty()
Value eez::flow::getUserProperty (unsigned propertyIndex)
Definition at line 7212 of file eez-flow.cpp.
{
    Value value;
    evalProperty(g_executeActionFlowState, g_executeActionComponentIndex, propertyIndex, value, FlowError::PropertyNum("CallAction", propertyIndex));
    return value;
}
References evalProperty(), g_executeActionComponentIndex, and g_executeActionFlowState.
getUserPropertyAsync()
Value eez::flow::getUserPropertyAsync (AsyncAction * asyncAction, unsigned propertyIndex)
Definition at line 7236 of file eez-flow.cpp.
{
    Value value;
    evalProperty(asyncAction->flowState, asyncAction->componentIndex, propertyIndex, value, FlowError::PropertyNum("CallAction", propertyIndex));
    return value;
}
References evalProperty().
getWatchListSize()
unsigned eez::flow::getWatchListSize ()
Definition at line 11247 of file eez-flow.cpp.
{
    return g_watchList.size;
}
References g_watchList, and getWatchListSize().
Referenced by getWatchListSize().
groupFocusFreeze()
void eez::flow::groupFocusFreeze (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4577 of file eez-flow.cpp.
References ACTION_END, and groupFocusFreeze().
Referenced by groupFocusFreeze().
groupFocusNext()
void eez::flow::groupFocusNext (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4564 of file eez-flow.cpp.
References ACTION_END, and groupFocusNext().
Referenced by groupFocusNext().
groupFocusObj()
void eez::flow::groupFocusObj (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4560 of file eez-flow.cpp.
References ACTION_END, and groupFocusObj().
Referenced by groupFocusObj().
groupFocusPrev()
void eez::flow::groupFocusPrev (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4568 of file eez-flow.cpp.
References ACTION_END, and groupFocusPrev().
Referenced by groupFocusPrev().
groupGetFocused()
void eez::flow::groupGetFocused (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4572 of file eez-flow.cpp.
References ACTION_END, and groupGetFocused().
Referenced by groupGetFocused().
groupSetEditing()
void eez::flow::groupSetEditing (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4587 of file eez-flow.cpp.
References ACTION_END, and groupSetEditing().
Referenced by groupSetEditing().
groupSetWrap()
void eez::flow::groupSetWrap (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4582 of file eez-flow.cpp.
References ACTION_END, and groupSetWrap().
Referenced by groupSetWrap().
imageSetAngle()
void eez::flow::imageSetAngle (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4505 of file eez-flow.cpp.
References ACTION_END, and imageSetAngle().
Referenced by imageSetAngle().
imageSetSrc()
void eez::flow::imageSetSrc (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4495 of file eez-flow.cpp.
             {
        lv_img_set_src(obj, src);
    } else {
        throwError(flowState, componentIndex, FlowError::NotFoundInAction("Image", str, "imageSetSrc", actionIndex));
    }
ACTION_END
References imageSetSrc().
Referenced by imageSetSrc().
imageSetZoom()
void eez::flow::imageSetZoom (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4510 of file eez-flow.cpp.
References ACTION_END, and imageSetZoom().
Referenced by imageSetZoom().
incRefCounterForFlowState()
void eez::flow::incRefCounterForFlowState (FlowState * flowState)
Definition at line 10563 of file eez-flow.cpp.
{
    flowState->refCounter++;
    for (auto parent = flowState->parentFlowState; parent; parent = parent->parentFlowState) {
        parent->refCounter++;
    }
}
References flowState, and incRefCounterForFlowState().
Referenced by addToQueue(), incRefCounterForFlowState(), startAsyncExecution(), visitWatchList(), and watchListAdd().
initActionFlowState()
FlowState * eez::flow::initActionFlowState (int flowIndex, FlowState * parentFlowState, int parentComponentIndex, const Value & inputValue)
Definition at line 10549 of file eez-flow.cpp.
{
    auto flowState = initFlowState(parentFlowState->assets, flowIndex, parentFlowState, parentComponentIndex, inputValue);
    if (flowState) {
        flowState->isAction = true;
    }
    return flowState;
}
References flowState, initActionFlowState(), and initFlowState().
Referenced by executeCallAction(), and initActionFlowState().
initFlowState()
FlowState * eez::flow::initFlowState (Assets * assets, int flowIndex, FlowState * parentFlowState, int parentComponentIndex, const Value & inputValue) static
Definition at line 10469 of file eez-flow.cpp.
{
    auto flowDefinition = static_cast<FlowDefinition *>(assets->flowDefinition);
    auto flow = flowDefinition->flows[flowIndex];
    auto nValues = flow->componentInputs.count + flow->localVariables.count;
    FlowState *flowState = new (
        alloc(
            sizeof(FlowState) +
            nValues * sizeof(Value) +
            flow->components.count * sizeof(ComponenentExecutionState *) +
            flow->components.count * sizeof(bool),
            0x4c3b6ef5
        )
    ) FlowState;
    flowState->flowStateIndex = (int)((uint8_t *)flowState - ALLOC_BUFFER);
    flowState->assets = assets;
    flowState->flowDefinition = static_cast<FlowDefinition *>(assets->flowDefinition);
    flowState->flow = flowDefinition->flows[flowIndex];
    flowState->flowIndex = flowIndex;
    flowState->error = false;
    flowState->deleteOnNextTick = false;
    flowState->refCounter = 0;
    flowState->parentFlowState = parentFlowState;
    flowState->executingComponentIndex = NO_COMPONENT_INDEX;
    flowState->timelinePosition = 0;
#if defined(EEZ_FOR_LVGL)
    flowState->lvglWidgetStartIndex = 0;
#endif
    if (parentFlowState) {
        if (parentFlowState->lastChild) {
            parentFlowState->lastChild->nextSibling = flowState;
            flowState->previousSibling = parentFlowState->lastChild;
            parentFlowState->lastChild = flowState;
        } else {
            flowState->previousSibling = nullptr;
            parentFlowState->firstChild = flowState;
            parentFlowState->lastChild = flowState;
        }
        flowState->parentComponentIndex = parentComponentIndex;
        flowState->parentComponent = parentComponentIndex == -1 ? nullptr : parentFlowState->flow->components[parentComponentIndex];
    } else {
        if (g_lastFlowState) {
            g_lastFlowState->nextSibling = flowState;
            flowState->previousSibling = g_lastFlowState;
            g_lastFlowState = flowState;
        } else {
            flowState->previousSibling = nullptr;
            g_firstFlowState = flowState;
            g_lastFlowState = flowState;
        }
        flowState->parentComponentIndex = -1;
        flowState->parentComponent = nullptr;
    }
    flowState->inputValue = inputValue;
    flowState->firstChild = nullptr;
    flowState->lastChild = nullptr;
    flowState->nextSibling = nullptr;
    flowState->values = (Value *)(flowState + 1);
    flowState->componenentExecutionStates = (ComponenentExecutionState **)(flowState->values + nValues);
    flowState->componenentAsyncStates = (bool *)(flowState->componenentExecutionStates + flow->components.count);
    for (unsigned i = 0; i < nValues; i++) {
        new (flowState->values + i) Value();
    }
    Value emptyInputValue = getEmptyInputValue();
    for (unsigned i = 0; i < flow->componentInputs.count; i++) {
        flowState->values[i] = emptyInputValue;
    }
    for (unsigned i = 0; i < flow->localVariables.count; i++) {
        auto value = flow->localVariables[i];
        flowState->values[flow->componentInputs.count + i] = *value;
    }
    for (unsigned i = 0; i < flow->components.count; i++) {
        flowState->componenentExecutionStates[i] = nullptr;
        flowState->componenentAsyncStates[i] = false;
    }
    onFlowStateCreated(flowState);
    for (unsigned componentIndex = 0; componentIndex < flow->components.count; componentIndex++) {
        pingComponent(flowState, componentIndex);
    }
    return flowState;
}
References eez::alloc(), eez::ALLOC_BUFFER, assets, componentIndex, flowState, g_firstFlowState, g_lastFlowState, getEmptyInputValue(), initFlowState(), NO_COMPONENT_INDEX, onFlowStateCreated(), and pingComponent().
Referenced by initActionFlowState(), initFlowState(), and initPageFlowState().
initGlobalVariables()
void eez::flow::initGlobalVariables (Assets * assets)
Definition at line 10396 of file eez-flow.cpp.
{
    if (!g_mainAssetsUncompressed) {
        return;
    }
    auto flowDefinition = static_cast<FlowDefinition *>(assets->flowDefinition);
    auto numVars = flowDefinition->globalVariables.count;
    g_globalVariables = (GlobalVariables *) alloc(
        sizeof(GlobalVariables) +
        (numVars > 0 ? numVars - 1 : 0) * sizeof(Value),
        0xcc34ca8e
    );
    for (uint32_t i = 0; i < numVars; i++) {
        new (g_globalVariables->values + i) Value();
        g_globalVariables->values[i] = flowDefinition->globalVariables[i]->clone();
    }
}
References eez::alloc(), assets, g_globalVariables, eez::g_mainAssetsUncompressed, and initGlobalVariables().
Referenced by initGlobalVariables(), and start().
initPageFlowState()
FlowState * eez::flow::initPageFlowState (Assets * assets, int flowIndex, FlowState * parentFlowState, int parentComponentIndex)
Definition at line 10556 of file eez-flow.cpp.
{
    auto flowState = initFlowState(assets, flowIndex, parentFlowState, parentComponentIndex, Value());
    if (flowState) {
        flowState->isAction = false;
    }
    return flowState;
}
References assets, flowState, initFlowState(), and initPageFlowState().
Referenced by createUserWidgetFlowState(), getPageFlowState(), and initPageFlowState().
is_equal()
bool eez::flow::is_equal (const Value & a1, const Value & b1) static
Definition at line 8336 of file eez-flow.cpp.
{
    auto a = a1.getValue();
    auto b = b1.getValue();
    auto aIsUndefinedOrNull = a.getType() == VALUE_TYPE_UNDEFINED || a.getType() == VALUE_TYPE_NULL;
    auto bIsUndefinedOrNull = b.getType() == VALUE_TYPE_UNDEFINED || b.getType() == VALUE_TYPE_NULL;
    if (aIsUndefinedOrNull) {
        return bIsUndefinedOrNull;
    } else if (bIsUndefinedOrNull) {
        return false;
    }
    if (a.isString() && b.isString()) {
        const char *aStr = a.getString();
        const char *bStr = b.getString();
        if (!aStr && !bStr) {
            return true;
        }
        if (!aStr || !bStr) {
            return false;
        }
        return strcmp(aStr, bStr) == 0;
    }
    if (a.isBlob() && b.isBlob()) {
        auto aBlobRef = a.getBlob();
        auto bBlobRef = b.getBlob();
        if (!aBlobRef && !bBlobRef) {
            return true;
        }
        if (!aBlobRef || !bBlobRef) {
            return false;
        }
        if (aBlobRef->len != bBlobRef->len) {
            return false;
        }
        return memcmp(aBlobRef->blob, bBlobRef->blob, aBlobRef->len) == 0;
    }
    if (a.getType() == b.getType()) {
        return a == b;
    }
    if (a.isInt32OrLess() == b.isInt32OrLess()) {
        return a.toInt32() == b.toInt32();
    }
    return a.toDouble() == b.toDouble();
}
References is_equal().
Referenced by is_equal(), is_great(), op_eq(), op_less_eq(), and op_neq().
is_great()
bool eez::flow::is_great (const Value & a1, const Value & b1) static
Definition at line 8392 of file eez-flow.cpp.
{
    return !is_less(a1, b1) && !is_equal(a1, b1);
}
References is_equal(), is_great(), and is_less().
Referenced by do_OPERATION_TYPE_MATH_MAX(), is_great(), and op_great().
is_less()
bool eez::flow::is_less (const Value & a1, const Value & b1) static
Definition at line 8379 of file eez-flow.cpp.
{
    auto a = a1.getValue();
    auto b = b1.getValue();
    if (a.isString() && b.isString()) {
        const char *aStr = a.getString();
        const char *bStr = b.getString();
        if (!aStr || !bStr) {
            return false;
        }
        return strcmp(aStr, bStr) < 0;
    }
    return a.toDouble() < b.toDouble();
}
References is_less().
Referenced by do_OPERATION_TYPE_MATH_MIN(), is_great(), is_less(), op_great_eq(), op_less(), and op_less_eq().
isComponentReadyToRun()
bool eez::flow::isComponentReadyToRun (FlowState * flowState, unsigned componentIndex) static
Definition at line 10412 of file eez-flow.cpp.
{
    auto component = flowState->flow->components[componentIndex];
    if (component->type == defs_v3::COMPONENT_TYPE_CATCH_ERROR_ACTION) {
        return false;
    }
    if (component->type == defs_v3::COMPONENT_TYPE_ON_EVENT_ACTION) {
        return false;
    }
    if (component->type == defs_v3::COMPONENT_TYPE_LABEL_IN_ACTION) {
        return false;
    }
    if (component->type > defs_v3::FIRST_LVGL_WIDGET_COMPONENT_TYPE) {
        return false;
    }
    if ((component->type < defs_v3::COMPONENT_TYPE_START_ACTION && component->type != defs_v3::COMPONENT_TYPE_USER_WIDGET_WIDGET) || component->type >= defs_v3::FIRST_DASHBOARD_WIDGET_COMPONENT_TYPE) {
        return true;
    }
    if (component->type == defs_v3::COMPONENT_TYPE_START_ACTION) {
        if (flowState->parentComponent && flowState->parentComponentIndex != -1) {
            auto flowInputIndex = flowState->parentComponent->inputs[0];
            auto value = flowState->parentFlowState->values[flowInputIndex];
            return value.getType() != VALUE_TYPE_UNDEFINED;
        } else {
            return true;
        }
    }
    int numSeqInputs = 0;
    int numDefinedSeqInputs = 0;
    for (unsigned inputIndex = 0; inputIndex < component->inputs.count; inputIndex++) {
        auto inputValueIndex = component->inputs[inputIndex];
        auto input = flowState->flow->componentInputs[inputValueIndex];
        if (input & COMPONENT_INPUT_FLAG_IS_SEQ_INPUT) {
            numSeqInputs++;
            auto &value = flowState->values[inputValueIndex];
            if (!isInputEmpty(value)) {
                numDefinedSeqInputs++;
            }
        } else {
            if (!(input & COMPONENT_INPUT_FLAG_IS_OPTIONAL)) {
                auto &value = flowState->values[inputValueIndex];
                if (isInputEmpty(value)) {
                    return false;
                }
            }
        }
    }
    if (numSeqInputs && !numDefinedSeqInputs) {
        return false;
    }
    return true;
}
References componentIndex, flowState, isComponentReadyToRun(), and isInputEmpty().
Referenced by isComponentReadyToRun(), and pingComponent().
isFlowStopped()
bool eez::flow::isFlowStopped ()
Definition at line 7117 of file eez-flow.cpp.
                     {
    return g_isStopped;
}
References g_isStopped.
Referenced by eez_flow_is_stopped(), getPageFlowState(), onPageChanged(), and tick().
isInputEmpty()
bool eez::flow::isInputEmpty (const Value & inputValue) inline
Definition at line 10388 of file eez-flow.cpp.
{
    return inputValue.type == VALUE_TYPE_UNDEFINED && inputValue.int32Value > 0;
}
References isInputEmpty().
Referenced by isComponentReadyToRun(), isInputEmpty(), and resetSequenceInputs().
isInQueue()
bool eez::flow::isInQueue (FlowState * flowState, unsigned componentIndex)
Definition at line 11133 of file eez-flow.cpp.
{
    if (g_queueHead == g_queueTail && !g_queueIsFull) {
        return false;
    }
    unsigned int it = g_queueHead;
    while (true) {
        if (g_queue[it].flowState == flowState && g_queue[it].componentIndex == componentIndex) {
            return true;
        }
        it = (it + 1) % QUEUE_SIZE;
        if (it == g_queueTail) {
            break;
        }
    }
    return false;
}
References componentIndex, flowState, g_queue, g_queueHead, g_queueIsFull, g_queueTail, isInQueue(), and QUEUE_SIZE.
Referenced by isInQueue(), and onEvent().
isScreenCreated()
void eez::flow::isScreenCreated (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4663 of file eez-flow.cpp.
References ACTION_END, and isScreenCreated().
Referenced by isScreenCreated().
isSubscribedTo()
bool eez::flow::isSubscribedTo (MessagesToDebugger messageType) static
Definition at line 6087 of file eez-flow.cpp.
{
    if (g_debuggerIsConnected && (g_messageSubsciptionFilter & (1 << messageType)) != 0) {
        startToDebuggerMessageHook();
        return true;
    }
    return false;
}
References g_debuggerIsConnected, g_messageSubsciptionFilter, and startToDebuggerMessageHook.
Referenced by canExecuteStep(), logInfo(), logScpiCommand(), logScpiQuery(), logScpiQueryResult(), onAddToQueue(), onComponentAsyncStateChanged(), onComponentExecutionStateChanged(), onFlowError(), onFlowStateCreated(), onFlowStateDestroyed(), onFlowStateTimelineChanged(), onPageChanged(), onRemoveFromQueue(), onStarted(), onValueChanged(), and setDebuggerState().
keyboardSetTextarea()
void eez::flow::keyboardSetTextarea (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4555 of file eez-flow.cpp.
References ACTION_END, and keyboardSetTextarea().
Referenced by keyboardSetTextarea().
labelSetText()
void eez::flow::labelSetText (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4515 of file eez-flow.cpp.
References ACTION_END, and labelSetText().
Referenced by labelSetText().
logInfo()
void eez::flow::logInfo (FlowState * flowState, unsigned componentIndex, const char * message)
Definition at line 6585 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
    LV_LOG_USER("EEZ-FLOW: %s", message);
#endif
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_LOG)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%d\t%d\t%d\t",
            MESSAGE_TO_DEBUGGER_LOG,
            LOG_ITEM_TYPE_INFO,
            (int)flowState->flowStateIndex,
            componentIndex
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
        writeLogMessage(message);
    }
}
References componentIndex, flowState, isSubscribedTo(), LOG_ITEM_TYPE_INFO, MESSAGE_TO_DEBUGGER_LOG, writeDebuggerBufferHook, and writeLogMessage().
Referenced by executeLogComponent().
logScpiCommand()
void eez::flow::logScpiCommand (FlowState * flowState, unsigned componentIndex, const char * cmd)
Definition at line 6601 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_LOG)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%d\t%d\t%d\tSCPI COMMAND: ",
            MESSAGE_TO_DEBUGGER_LOG,
            LOG_ITEM_TYPE_SCPI,
            (int)flowState->flowStateIndex,
            componentIndex
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
        writeLogMessage(cmd);
    }
}
References componentIndex, flowState, isSubscribedTo(), LOG_ITEM_TYPE_SCPI, MESSAGE_TO_DEBUGGER_LOG, writeDebuggerBufferHook, and writeLogMessage().
logScpiQuery()
void eez::flow::logScpiQuery (FlowState * flowState, unsigned componentIndex, const char * query)
Definition at line 6614 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_LOG)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%d\t%d\t%d\tSCPI QUERY: ",
            MESSAGE_TO_DEBUGGER_LOG,
            LOG_ITEM_TYPE_SCPI,
            (int)flowState->flowStateIndex,
            componentIndex
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
        writeLogMessage(query);
    }
}
References componentIndex, flowState, isSubscribedTo(), LOG_ITEM_TYPE_SCPI, MESSAGE_TO_DEBUGGER_LOG, writeDebuggerBufferHook, and writeLogMessage().
logScpiQueryResult()
void eez::flow::logScpiQueryResult (FlowState * flowState, unsigned componentIndex, const char * resultText, size_t resultTextLen)
Definition at line 6627 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_LOG)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer) - 1, "%d\t%d\t%d\t%d\tSCPI QUERY RESULT: ",
            MESSAGE_TO_DEBUGGER_LOG,
            LOG_ITEM_TYPE_SCPI,
            (int)flowState->flowStateIndex,
            componentIndex
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
        writeLogMessage(resultText, resultTextLen);
    }
}
References componentIndex, flowState, isSubscribedTo(), LOG_ITEM_TYPE_SCPI, MESSAGE_TO_DEBUGGER_LOG, writeDebuggerBufferHook, and writeLogMessage().
lvglObjAddStyle()
void eez::flow::lvglObjAddStyle (lv_obj_t * object, int32_t styleIndex) static
Definition at line 7560 of file eez-flow.cpp.
{
    EEZ_UNUSED(object);
    EEZ_UNUSED(styleIndex);
}
References EEZ_UNUSED, and lvglObjAddStyle().
Referenced by lvglObjAddStyle().
lvglObjRemoveStyle()
void eez::flow::lvglObjRemoveStyle (lv_obj_t * object, int32_t styleIndex) static
Definition at line 7564 of file eez-flow.cpp.
{
    EEZ_UNUSED(object);
    EEZ_UNUSED(styleIndex);
}
References EEZ_UNUSED, and lvglObjRemoveStyle().
Referenced by lvglObjRemoveStyle().
lvglSetColorTheme()
void eez::flow::lvglSetColorTheme (const char * themeName) static
Definition at line 7568 of file eez-flow.cpp.
{
    EEZ_UNUSED(themeName);
}
References EEZ_UNUSED.
objAddFlag()
void eez::flow::objAddFlag (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4427 of file eez-flow.cpp.
References ACTION_END, and objAddFlag().
Referenced by objAddFlag().
objAddState()
void eez::flow::objAddState (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4455 of file eez-flow.cpp.
References ACTION_END, and objAddState().
Referenced by objAddState().
objAddStyle()
void eez::flow::objAddStyle (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4411 of file eez-flow.cpp.
References ACTION_END, and objAddStyle().
Referenced by objAddStyle().
objClearFlag()
void eez::flow::objClearFlag (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4432 of file eez-flow.cpp.
References ACTION_END, and objClearFlag().
Referenced by objClearFlag().
objClearState()
void eez::flow::objClearState (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4460 of file eez-flow.cpp.
References ACTION_END, and objClearState().
Referenced by objClearState().
objGetHeight()
void eez::flow::objGetHeight (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4392 of file eez-flow.cpp.
References ACTION_END, and objGetHeight().
Referenced by objGetHeight().
objGetStyleOpa()
void eez::flow::objGetStyleOpa (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4406 of file eez-flow.cpp.
References ACTION_END, and objGetStyleOpa().
Referenced by objGetStyleOpa().
objGetWidth()
void eez::flow::objGetWidth (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4374 of file eez-flow.cpp.
References ACTION_END, and objGetWidth().
Referenced by objGetWidth().
objGetX()
void eez::flow::objGetX (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4338 of file eez-flow.cpp.
References ACTION_END, and objGetX().
Referenced by objGetX().
objGetY()
void eez::flow::objGetY (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4356 of file eez-flow.cpp.
References ACTION_END, and objGetY().
Referenced by objGetY().
objHasFlag()
void eez::flow::objHasFlag (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4437 of file eez-flow.cpp.
References ACTION_END, and objHasFlag().
Referenced by objHasFlag().
objHasState()
void eez::flow::objHasState (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4465 of file eez-flow.cpp.
References ACTION_END, and objHasState().
Referenced by objHasState().
objRemoveStyle()
void eez::flow::objRemoveStyle (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4416 of file eez-flow.cpp.
References ACTION_END, and objRemoveStyle().
Referenced by objRemoveStyle().
objSetFlagHidden()
void eez::flow::objSetFlagHidden (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4421 of file eez-flow.cpp.
References ACTION_END, and objSetFlagHidden().
Referenced by objSetFlagHidden().
objSetHeight()
void eez::flow::objSetHeight (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4383 of file eez-flow.cpp.
References ACTION_END, and objSetHeight().
Referenced by objSetHeight().
objSetStateChecked()
void eez::flow::objSetStateChecked (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4443 of file eez-flow.cpp.
References ACTION_END, and objSetStateChecked().
Referenced by objSetStateChecked().
objSetStateDisabled()
void eez::flow::objSetStateDisabled (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4449 of file eez-flow.cpp.
References ACTION_END, and objSetStateDisabled().
Referenced by objSetStateDisabled().
objSetStyleOpa()
void eez::flow::objSetStyleOpa (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4401 of file eez-flow.cpp.
References ACTION_END, and objSetStyleOpa().
Referenced by objSetStyleOpa().
objSetWidth()
void eez::flow::objSetWidth (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4365 of file eez-flow.cpp.
References ACTION_END, and objSetWidth().
Referenced by objSetWidth().
objSetX()
void eez::flow::objSetX (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4329 of file eez-flow.cpp.
References ACTION_END, and objSetX().
Referenced by objSetX().
objSetY()
void eez::flow::objSetY (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4347 of file eez-flow.cpp.
References ACTION_END, and objSetY().
Referenced by objSetY().
onAddToQueue()
void eez::flow::onAddToQueue (FlowState * flowState, int sourceComponentIndex, int sourceOutputIndex, unsigned targetComponentIndex, int targetInputIndex)
Definition at line 6413 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_ADD_TO_QUEUE)) {
        uint32_t free;
        uint32_t alloc;
        getAllocInfo(free, alloc);
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%d\t%d\t%d\t%d\t%d\t%u\t%u\n",
            MESSAGE_TO_DEBUGGER_ADD_TO_QUEUE,
            (int)flowState->flowStateIndex,
            sourceComponentIndex,
            sourceOutputIndex,
            targetComponentIndex,
            targetInputIndex,
            (unsigned int)free,
            (unsigned int)ALLOC_BUFFER_SIZE
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
    }
}
References eez::alloc(), eez::ALLOC_BUFFER_SIZE, flowState, eez::free(), eez::getAllocInfo(), isSubscribedTo(), MESSAGE_TO_DEBUGGER_ADD_TO_QUEUE, and writeDebuggerBufferHook.
Referenced by addToQueue().
onArrayValueFree()
void eez::flow::onArrayValueFree (ArrayValue * arrayValue)
Definition at line 7446 of file eez-flow.cpp.
{
#if defined(EEZ_DASHBOARD_API)
    if (g_dashboardValueFree) {
        return;
    }
#endif
    if (arrayValue->arrayType == defs_v3::OBJECT_TYPE_MQTT_CONNECTION) {
        onFreeMQTTConnection(arrayValue);
    }
#if defined(EEZ_DASHBOARD_API)
    const uint32_t CATEGORY_SHIFT = 13;
    const uint32_t CATEGORY_MASK = 0x7;
    const uint32_t CATEGORY_OBJECT = 5;
    if (((arrayValue->arrayType >> CATEGORY_SHIFT) & CATEGORY_MASK) == CATEGORY_OBJECT) {
        eez::flow::onObjectArrayValueFree(arrayValue);
    }
#endif
}
References onFreeMQTTConnection().
onComponentAsyncStateChanged()
void eez::flow::onComponentAsyncStateChanged (FlowState * flowState, int componentIndex)
Definition at line 6543 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_COMPONENT_ASYNC_STATE_CHANGED)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%d\t%d\t%d\n",
            MESSAGE_TO_DEBUGGER_COMPONENT_ASYNC_STATE_CHANGED,
            (int)flowState->flowStateIndex,
            componentIndex,
            flowState->componenentAsyncStates[componentIndex] ? 1 : 0
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
    }
}
References componentIndex, flowState, isSubscribedTo(), MESSAGE_TO_DEBUGGER_COMPONENT_ASYNC_STATE_CHANGED, and writeDebuggerBufferHook.
Referenced by endAsyncExecution(), and startAsyncExecution().
onComponentExecutionStateChanged()
void eez::flow::onComponentExecutionStateChanged (FlowState * flowState, int componentIndex)
Definition at line 6531 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_COMPONENT_EXECUTION_STATE_CHANGED)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%d\t%d\t%p\n",
            MESSAGE_TO_DEBUGGER_COMPONENT_EXECUTION_STATE_CHANGED,
            (int)flowState->flowStateIndex,
            componentIndex,
            (void *)flowState->componenentExecutionStates[componentIndex]
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
    }
}
References componentIndex, flowState, isSubscribedTo(), MESSAGE_TO_DEBUGGER_COMPONENT_EXECUTION_STATE_CHANGED, and writeDebuggerBufferHook.
Referenced by deallocateComponentExecutionState().
onDebuggerClientConnected()
void eez::flow::onDebuggerClientConnected ()
Definition at line 6107 of file eez-flow.cpp.
{
    g_debuggerIsConnected = true;
    g_skipNextBreakpoint = false;
    g_inputFromDebuggerPosition = 0;
    setDebuggerState(DEBUGGER_STATE_PAUSED);
}
References DEBUGGER_STATE_PAUSED, g_debuggerIsConnected, g_inputFromDebuggerPosition, g_skipNextBreakpoint, and setDebuggerState().
onDebuggerClientDisconnected()
void eez::flow::onDebuggerClientDisconnected ()
Definition at line 6113 of file eez-flow.cpp.
{
    g_debuggerIsConnected = false;
    setDebuggerState(DEBUGGER_STATE_RESUMED);
}
References DEBUGGER_STATE_RESUMED, g_debuggerIsConnected, and setDebuggerState().
onDebuggerInputAvailable()
void eez::flow::onDebuggerInputAvailable () static
Definition at line 7517 of file eez-flow.cpp.
{
}
References onDebuggerInputAvailable().
Referenced by onDebuggerInputAvailable().
onEvent()
void eez::flow::onEvent (FlowState * flowState, FlowEvent flowEvent, Value eventValue)
Definition at line 10854 of file eez-flow.cpp.
{
    for (unsigned componentIndex = 0; componentIndex < flowState->flow->components.count; componentIndex++) {
        auto component = flowState->flow->components[componentIndex];
        if (component->type == defs_v3::COMPONENT_TYPE_ON_EVENT_ACTION) {
            auto onEventComponent = (OnEventComponent *)component;
            if (onEventComponent->event == flowEvent) {
                flowState->eventValue = eventValue;
                if (!isInQueue(flowState, componentIndex)) {
                    if (!addToQueue(flowState, componentIndex, -1, -1, -1, false)) {
                        return;
                    }
                }
            }
        }
    }
    if (flowEvent == FLOW_EVENT_KEYDOWN) {
        for (auto childFlowState = flowState->firstChild; childFlowState != nullptr; childFlowState = childFlowState->nextSibling) {
            onEvent(childFlowState, flowEvent, eventValue);
        }
    }
}
References addToQueue(), componentIndex, flowState, isInQueue(), and onEvent().
Referenced by onEvent(), and onPageChanged().
onFlowError()
void eez::flow::onFlowError (FlowState * flowState, int componentIndex, const char * errorMessage)
Definition at line 6516 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_FLOW_STATE_ERROR)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%d\t%d\t",
            MESSAGE_TO_DEBUGGER_FLOW_STATE_ERROR,
            (int)flowState->flowStateIndex,
            componentIndex
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
        writeString(errorMessage);
    }
    if (onFlowErrorHook) {
        onFlowErrorHook(flowState, componentIndex, errorMessage);
    }
}
References componentIndex, flowState, isSubscribedTo(), MESSAGE_TO_DEBUGGER_FLOW_STATE_ERROR, onFlowErrorHook, writeDebuggerBufferHook, and writeString().
Referenced by throwError().
onFlowStateCreated()
void eez::flow::onFlowStateCreated (FlowState * flowState)
Definition at line 6452 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_FLOW_STATE_CREATED)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%d\t%d\t%d\t%d\n",
            MESSAGE_TO_DEBUGGER_FLOW_STATE_CREATED,
            (int)flowState->flowStateIndex,
            (int)flowState->flowIndex,
            (int)(flowState->parentFlowState ? flowState->parentFlowState->flowStateIndex : -1),
            (int)flowState->parentComponentIndex
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
    }
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_LOCAL_VARIABLE_INIT)) {
        auto flow = flowState->flow;
        for (uint32_t i = 0; i < flow->localVariables.count; i++) {
            auto pValue = &flowState->values[flow->componentInputs.count + i];
            char buffer[256];
            snprintf(buffer, sizeof(buffer), "%d\t%d\t%d\t%p\t",
                MESSAGE_TO_DEBUGGER_LOCAL_VARIABLE_INIT,
                (int)flowState->flowStateIndex,
                (int)i,
                (const void *)pValue
            );
            writeDebuggerBufferHook(buffer, strlen(buffer));
            writeValue(*pValue);
        }
    }
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_COMPONENT_INPUT_INIT)) {
        auto flow = flowState->flow;
        for (uint32_t i = 0; i < flow->componentInputs.count; i++) {
                auto pValue = &flowState->values[i];
                char buffer[256];
                snprintf(buffer, sizeof(buffer), "%d\t%d\t%d\t%p\t",
                    MESSAGE_TO_DEBUGGER_COMPONENT_INPUT_INIT,
                    (int)flowState->flowStateIndex,
                    (int)i,
                    (const void *)pValue
                );
                writeDebuggerBufferHook(buffer, strlen(buffer));
                writeValue(*pValue);
        }
    }
}
References flowState, isSubscribedTo(), MESSAGE_TO_DEBUGGER_COMPONENT_INPUT_INIT, MESSAGE_TO_DEBUGGER_FLOW_STATE_CREATED, MESSAGE_TO_DEBUGGER_LOCAL_VARIABLE_INIT, writeDebuggerBufferHook, and writeValue().
Referenced by initFlowState().
onFlowStateDestroyed()
void eez::flow::onFlowStateDestroyed (FlowState * flowState)
Definition at line 6495 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_FLOW_STATE_DESTROYED)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%d\n",
            MESSAGE_TO_DEBUGGER_FLOW_STATE_DESTROYED,
            (int)flowState->flowStateIndex
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
    }
}
References flowState, isSubscribedTo(), MESSAGE_TO_DEBUGGER_FLOW_STATE_DESTROYED, and writeDebuggerBufferHook.
Referenced by freeFlowState().
onFlowStateTimelineChanged()
void eez::flow::onFlowStateTimelineChanged (FlowState * flowState)
Definition at line 6505 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_FLOW_STATE_TIMELINE_CHANGED)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%d\t%g\n",
            MESSAGE_TO_DEBUGGER_FLOW_STATE_TIMELINE_CHANGED,
            (int)flowState->flowStateIndex,
            flowState->timelinePosition
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
    }
}
References flowState, isSubscribedTo(), MESSAGE_TO_DEBUGGER_FLOW_STATE_TIMELINE_CHANGED, and writeDebuggerBufferHook.
Referenced by executeAnimateComponent().
onFreeMQTTConnection()
void eez::flow::onFreeMQTTConnection (ArrayValue * mqttConnectionValue)
Definition at line 5045 of file eez-flow.cpp.
{
    void *handle = mqttConnectionValue->values[defs_v3::OBJECT_TYPE_MQTT_CONNECTION_FIELD_ID].getVoidPointer();
    deleteConnection(handle);
}
References deleteConnection().
Referenced by onArrayValueFree().
onPageChanged()
void eez::flow::onPageChanged (int previousPageId, int activePageId, bool activePageIsFromStack, bool previousPageIsStillOnStack)
Definition at line 6684 of file eez-flow.cpp.
{
    if (flow::isFlowStopped()) {
        return;
    }
    if (previousPageId == activePageId) {
        return;
    }
    if (!previousPageIsStillOnStack) {
        if (previousPageId > 0) {
            auto flowState = getPageFlowState(g_mainAssets, previousPageId - 1);
            if (flowState) {
                onEvent(flowState, FLOW_EVENT_CLOSE_PAGE, Value());
            }
        }
    }
    if (!activePageIsFromStack) {
        if (activePageId > 0) {
            auto flowState = getPageFlowState(g_mainAssets, activePageId - 1);
            if (flowState) {
                onEvent(flowState, FLOW_EVENT_OPEN_PAGE, Value());
            }
        }
    }
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_PAGE_CHANGED)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%d\n",
            MESSAGE_TO_DEBUGGER_PAGE_CHANGED,
            activePageId
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
    }
}
References flowState, eez::g_mainAssets, getPageFlowState(), isFlowStopped(), isSubscribedTo(), MESSAGE_TO_DEBUGGER_PAGE_CHANGED, onEvent(), and writeDebuggerBufferHook.
Referenced by replacePageHook().
onRemoveFromQueue()
void eez::flow::onRemoveFromQueue ()
Definition at line 6432 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_REMOVE_FROM_QUEUE)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\n",
            MESSAGE_TO_DEBUGGER_REMOVE_FROM_QUEUE
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
    }
}
References isSubscribedTo(), MESSAGE_TO_DEBUGGER_REMOVE_FROM_QUEUE, and writeDebuggerBufferHook.
Referenced by removeNextTaskFromQueue().
onStarted()
void eez::flow::onStarted (Assets * assets)
Definition at line 6380 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_GLOBAL_VARIABLE_INIT)) {
        auto flowDefinition = static_cast<FlowDefinition *>(assets->flowDefinition);
        if (g_globalVariables) {
            for (uint32_t i = 0; i < g_globalVariables->count; i++) {
                auto pValue = g_globalVariables->values + i;
                char buffer[256];
                snprintf(buffer, sizeof(buffer), "%d\t%d\t%p\t",
                    MESSAGE_TO_DEBUGGER_GLOBAL_VARIABLE_INIT,
                    (int)i,
                    (const void *)pValue
                );
                writeDebuggerBufferHook(buffer, strlen(buffer));
                writeValue(*pValue);
            }
        } else {
            for (uint32_t i = 0; i < flowDefinition->globalVariables.count; i++) {
                auto pValue = flowDefinition->globalVariables[i];
                char buffer[256];
                snprintf(buffer, sizeof(buffer), "%d\t%d\t%p\t",
                    MESSAGE_TO_DEBUGGER_GLOBAL_VARIABLE_INIT,
                    (int)i,
                    (const void *)pValue
                );
                writeDebuggerBufferHook(buffer, strlen(buffer));
                writeValue(*pValue);
            }
        }
    }
}
References assets, g_globalVariables, isSubscribedTo(), MESSAGE_TO_DEBUGGER_GLOBAL_VARIABLE_INIT, writeDebuggerBufferHook, and writeValue().
Referenced by start().
onStopped()
void eez::flow::onStopped ()
Definition at line 6410 of file eez-flow.cpp.
                 {
    setDebuggerState(DEBUGGER_STATE_STOPPED);
}
References DEBUGGER_STATE_STOPPED, and setDebuggerState().
Referenced by doStop().
onValueChanged()
void eez::flow::onValueChanged (const Value * pValue)
Definition at line 6441 of file eez-flow.cpp.
{
    if (isSubscribedTo(MESSAGE_TO_DEBUGGER_VALUE_CHANGED)) {
        char buffer[256];
        snprintf(buffer, sizeof(buffer), "%d\t%p\t",
            MESSAGE_TO_DEBUGGER_VALUE_CHANGED,
            (const void *)pValue
        );
        writeDebuggerBufferHook(buffer, strlen(buffer));
        writeValue(pValue->getValue());
    }
}
References isSubscribedTo(), MESSAGE_TO_DEBUGGER_VALUE_CHANGED, writeDebuggerBufferHook, and writeValue().
Referenced by assignValue(), clearInputValue(), createUserWidgetFlowState(), executeCallAction(), propagateValue(), resetSequenceInputs(), and writeArray().
op_add()
Value eez::flow::op_add (const Value & a1, const Value & b1)
Definition at line 8067 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    auto a = a1.getValue();
    auto b = b1.getValue();
    if (a.isBlob() || b.isBlob()) {
        if (a.isBlob()) {
            if (b.isUndefinedOrNull()) {
                return a;
            }
            if (!b.isBlob()) {
                return Value::makeError();
            }
        } else {
            if (a.isUndefinedOrNull()) {
                return b;
            }
            return Value::makeError();
        }
        auto aBlob = a.getBlob();
        auto bBlob = b.getBlob();
        return Value::makeBlobRef(aBlob->blob, aBlob->len, bBlob->blob, bBlob->len, 0xc622dd24);
    }
    auto a_valid = a.isString() || a.isDouble() || a.isFloat() || a.isInt64() || a.isInt32OrLess();
    auto b_valid = b.isString() || b.isDouble() || b.isFloat() || b.isInt64() || b.isInt32OrLess();
    if (!a_valid && !b_valid) {
        return Value::makeError();
    }
    if (a.isString() || b.isString()) {
        Value value1 = a.toString(0x84eafaa8);
        Value value2 = b.toString(0xd273cab6);
        auto res = Value::concatenateString(value1, value2);
        char str1[128];
        res.toText(str1, sizeof(str1));
        return res;
    }
    if (a.isDouble() || b.isDouble()) {
        return Value(a.toDouble() + b.toDouble(), VALUE_TYPE_DOUBLE);
    }
    if (a.isFloat() || b.isFloat()) {
        return Value(a.toFloat() + b.toFloat(), VALUE_TYPE_FLOAT);
    }
    if (a.isInt64() || b.isInt64()) {
        return Value(a.toInt64() + b.toInt64(), VALUE_TYPE_INT64);
    }
    return Value((int)(a.int32Value + b.int32Value), VALUE_TYPE_INT32);
}
References op_add().
Referenced by do_OPERATION_TYPE_ADD(), executeLoopComponent(), and op_add().
op_binary_and()
Value eez::flow::op_binary_and (const Value & a1, const Value & b1)
Definition at line 8276 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    auto a = a1.getValue();
    auto b = b1.getValue();
    if (!(a.isInt64() || a.isInt32OrLess())) {
        return Value::makeError();
    }
    if (!(b.isInt64() || b.isInt32OrLess())) {
        return Value::makeError();
    }
    if (a.isInt64() || b.isInt64()) {
        return Value(a.toInt64() & b.toInt64(), VALUE_TYPE_INT64);
    }
    return Value((int)(a.toInt32() & b.toInt32()), VALUE_TYPE_INT32);
}
References op_binary_and().
Referenced by do_OPERATION_TYPE_BINARY_AND(), and op_binary_and().
op_binary_or()
Value eez::flow::op_binary_or (const Value & a1, const Value & b1)
Definition at line 8296 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    auto a = a1.getValue();
    auto b = b1.getValue();
    if (!(a.isInt64() || a.isInt32OrLess())) {
        return Value::makeError();
    }
    if (!(b.isInt64() || b.isInt32OrLess())) {
        return Value::makeError();
    }
    if (a.isInt64() || b.isInt64()) {
        return Value(a.toInt64() | b.toInt64(), VALUE_TYPE_INT64);
    }
    return Value((int)(a.toInt32() | b.toInt32()), VALUE_TYPE_INT32);
}
References op_binary_or().
Referenced by do_OPERATION_TYPE_BINARY_OR(), and op_binary_or().
op_binary_xor()
Value eez::flow::op_binary_xor (const Value & a1, const Value & b1)
Definition at line 8316 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    auto a = a1.getValue();
    auto b = b1.getValue();
    if (!(a.isInt64() || a.isInt32OrLess())) {
        return Value::makeError();
    }
    if (!(b.isInt64() || b.isInt32OrLess())) {
        return Value::makeError();
    }
    if (a.isInt64() || b.isInt64()) {
        return Value(a.toInt64() ^ b.toInt64(), VALUE_TYPE_INT64);
    }
    return Value((int)(a.toInt32() ^ b.toInt32()), VALUE_TYPE_INT32);
}
References op_binary_xor().
Referenced by do_OPERATION_TYPE_BINARY_XOR(), and op_binary_xor().
op_div()
Value eez::flow::op_div (const Value & a1, const Value & b1)
Definition at line 8170 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    auto a = a1.getValue();
    auto b = b1.getValue();
    if (!(a.isDouble() || a.isFloat() || a.isInt64() || a.isInt32OrLess())) {
        return Value::makeError();
    }
    if (!(b.isDouble() || b.isFloat() || b.isInt64() || b.isInt32OrLess())) {
        return Value::makeError();
    }
    if (a.isDouble() || b.isDouble()) {
        return Value(a.toDouble() / b.toDouble(), VALUE_TYPE_DOUBLE);
    }
    if (a.isFloat() || b.isFloat()) {
        return Value(a.toFloat() / b.toFloat(), VALUE_TYPE_FLOAT);
    }
    if (a.isInt64() || b.isInt64()) {
        auto d = b.toInt64();
        if (d == 0) {
            return Value::makeError();
        }
        return Value(1.0 * a.toInt64() / d, VALUE_TYPE_DOUBLE);
    }
    if (b.int32Value == 0) {
        return Value::makeError();
    }
    return Value(1.0 * a.int32Value / b.int32Value, VALUE_TYPE_DOUBLE);
}
References op_div().
Referenced by do_OPERATION_TYPE_DIV(), and op_div().
op_eq()
Value eez::flow::op_eq (const Value & a1, const Value & b1)
Definition at line 8395 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    return Value(is_equal(a1, b1), VALUE_TYPE_BOOLEAN);
}
References is_equal(), and op_eq().
Referenced by do_OPERATION_TYPE_EQUAL(), and op_eq().
op_great()
Value eez::flow::op_great (const Value & a1, const Value & b1)
Definition at line 8422 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    return Value(is_great(a1, b1), VALUE_TYPE_BOOLEAN);
}
References is_great(), and op_great().
Referenced by do_OPERATION_TYPE_GREATER(), executeLoopComponent(), and op_great().
op_great_eq()
Value eez::flow::op_great_eq (const Value & a1, const Value & b1)
Definition at line 8440 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    return Value(!is_less(a1, b1), VALUE_TYPE_BOOLEAN);
}
References is_less(), and op_great_eq().
Referenced by do_OPERATION_TYPE_GREATER_OR_EQUAL(), and op_great_eq().
op_left_shift()
Value eez::flow::op_left_shift (const Value & a1, const Value & b1)
Definition at line 8236 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    auto a = a1.getValue();
    auto b = b1.getValue();
    if (!(a.isInt64() || a.isInt32OrLess())) {
        return Value::makeError();
    }
    if (!(b.isInt64() || b.isInt32OrLess())) {
        return Value::makeError();
    }
    if (a.isInt64() || b.isInt64()) {
        return Value(a.toInt64() << b.toInt64(), VALUE_TYPE_INT64);
    }
    return Value((int)(a.toInt32() << b.toInt32()), VALUE_TYPE_INT32);
}
References op_left_shift().
Referenced by do_OPERATION_TYPE_LEFT_SHIFT(), and op_left_shift().
op_less()
Value eez::flow::op_less (const Value & a1, const Value & b1)
Definition at line 8413 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    return Value(is_less(a1, b1), VALUE_TYPE_BOOLEAN);
}
References is_less(), and op_less().
Referenced by do_OPERATION_TYPE_LESS(), executeLoopComponent(), and op_less().
op_less_eq()
Value eez::flow::op_less_eq (const Value & a1, const Value & b1)
Definition at line 8431 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    return Value(is_less(a1, b1) || is_equal(a1, b1), VALUE_TYPE_BOOLEAN);
}
References is_equal(), is_less(), and op_less_eq().
Referenced by do_OPERATION_TYPE_LESS_OR_EQUAL(), and op_less_eq().
op_mod()
Value eez::flow::op_mod (const Value & a1, const Value & b1)
Definition at line 8203 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    auto a = a1.getValue();
    auto b = b1.getValue();
    if (!(a.isDouble() || a.isFloat() || a.isInt64() || a.isInt32OrLess())) {
        return Value::makeError();
    }
    if (!(b.isDouble() || b.isFloat() || b.isInt64() || b.isInt32OrLess())) {
        return Value::makeError();
    }
    if (a.isDouble() || b.isDouble()) {
        return Value(a.toDouble() - floor(a.toDouble() / b.toDouble()) * b.toDouble(), VALUE_TYPE_DOUBLE);
    }
    if (a.isFloat() || b.isFloat()) {
        return Value(a.toFloat() - floor(a.toFloat() / b.toFloat()) * b.toFloat(), VALUE_TYPE_FLOAT);
    }
    if (a.isInt64() || b.isInt64()) {
        auto d = b.toInt64();
        if (d == 0) {
            return Value::makeError();
        }
        return Value(a.toInt64() % d, VALUE_TYPE_INT64);
    }
    if (b.int32Value == 0) {
        return Value::makeError();
    }
    return Value((int)(a.int32Value % b.int32Value), VALUE_TYPE_INT32);
}
References op_mod().
Referenced by do_OPERATION_TYPE_MOD(), and op_mod().
op_mul()
Value eez::flow::op_mul (const Value & a1, const Value & b1)
Definition at line 8144 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    auto a = a1.getValue();
    auto b = b1.getValue();
    if (!(a.isDouble() || a.isFloat() || a.isInt64() || a.isInt32OrLess())) {
        return Value::makeError();
    }
    if (!(b.isDouble() || b.isFloat() || b.isInt64() || b.isInt32OrLess())) {
        return Value::makeError();
    }
    if (a.isDouble() || b.isDouble()) {
        return Value(a.toDouble() * b.toDouble(), VALUE_TYPE_DOUBLE);
    }
    if (a.isFloat() || b.isFloat()) {
        return Value(a.toFloat() * b.toFloat(), VALUE_TYPE_FLOAT);
    }
    if (a.isInt64() || b.isInt64()) {
        return Value(a.toInt64() * b.toInt64(), VALUE_TYPE_INT64);
    }
    return Value((int)(a.int32Value * b.int32Value), VALUE_TYPE_INT32);
}
References op_mul().
Referenced by do_OPERATION_TYPE_MUL(), and op_mul().
op_neq()
Value eez::flow::op_neq (const Value & a1, const Value & b1)
Definition at line 8404 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    return Value(!is_equal(a1, b1), VALUE_TYPE_BOOLEAN);
}
References is_equal(), and op_neq().
Referenced by do_OPERATION_TYPE_NOT_EQUAL(), and op_neq().
op_right_shift()
Value eez::flow::op_right_shift (const Value & a1, const Value & b1)
Definition at line 8256 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    auto a = a1.getValue();
    auto b = b1.getValue();
    if (!(a.isInt64() || a.isInt32OrLess())) {
        return Value::makeError();
    }
    if (!(b.isInt64() || b.isInt32OrLess())) {
        return Value::makeError();
    }
    if (a.isInt64() || b.isInt64()) {
        return Value(a.toInt64() >> b.toInt64(), VALUE_TYPE_INT64);
    }
    return Value((int)(a.toInt32() >> b.toInt32()), VALUE_TYPE_INT32);
}
References op_right_shift().
Referenced by do_OPERATION_TYPE_RIGHT_SHIFT(), and op_right_shift().
op_sub()
Value eez::flow::op_sub (const Value & a1, const Value & b1)
Definition at line 8118 of file eez-flow.cpp.
{
    if (a1.isError()) {
        return a1;
    }
    if (b1.isError()) {
        return b1;
    }
    auto a = a1.getValue();
    auto b = b1.getValue();
    if (!(a.isDouble() || a.isFloat() || a.isInt64() || a.isInt32OrLess())) {
        return Value::makeError();
    }
    if (!(b.isDouble() || b.isFloat() || b.isInt64() || b.isInt32OrLess())) {
        return Value::makeError();
    }
    if (a.isDouble() || b.isDouble()) {
        return Value(a.toDouble() - b.toDouble(), VALUE_TYPE_DOUBLE);
    }
    if (a.isFloat() || b.isFloat()) {
        return Value(a.toFloat() - b.toFloat(), VALUE_TYPE_FLOAT);
    }
    if (a.isInt64() || b.isInt64()) {
        return Value(a.toInt64() - b.toInt64(), VALUE_TYPE_INT64);
    }
    return Value((int)(a.int32Value - b.int32Value), VALUE_TYPE_INT32);
}
References op_sub().
Referenced by do_OPERATION_TYPE_SUB(), and op_sub().
peekNextTaskFromQueue()
bool eez::flow::peekNextTaskFromQueue (FlowState *& flowState, unsigned & componentIndex, bool & continuousTask)
Definition at line 11113 of file eez-flow.cpp.
{
    if (g_queueHead == g_queueTail && !g_queueIsFull) {
        return false;
    }
    flowState = g_queue[g_queueHead].flowState;
    componentIndex = g_queue[g_queueHead].componentIndex;
    continuousTask = g_queue[g_queueHead].continuousTask;
    return true;
}
References componentIndex, continuousTask, flowState, g_queue, g_queueHead, g_queueIsFull, g_queueTail, and peekNextTaskFromQueue().
Referenced by peekNextTaskFromQueue(), and tick().
pingComponent()
bool eez::flow::pingComponent (FlowState * flowState, unsigned componentIndex, int sourceComponentIndex = -1, int sourceOutputIndex = -1, int targetInputIndex = -1) static
Definition at line 10463 of file eez-flow.cpp.
{
    if (isComponentReadyToRun(flowState, componentIndex)) {
        return addToQueue(flowState, componentIndex, sourceComponentIndex, sourceOutputIndex, targetInputIndex, false);
    }
    return false;
}
References addToQueue(), componentIndex, flowState, isComponentReadyToRun(), and pingComponent().
Referenced by initFlowState(), pingComponent(), and propagateValue().
playAnimation()
void eez::flow::playAnimation (lv_obj_t * obj, int32_t start, int32_t end, int32_t delay, int32_t time, bool relative, bool instant, int32_t path, lv_anim_exec_xcb_t set_callback, lv_anim_get_value_cb_t get_callback) static
Definition at line 4601 of file eez-flow.cpp.
  {
    lv_anim_t anim;
    lv_anim_init(&anim);
    lv_anim_set_time(&anim, time);
    lv_anim_set_user_data(&anim, obj);
    lv_anim_set_var(&anim, obj);
    lv_anim_set_exec_cb(&anim, set_callback);
    lv_anim_set_values(&anim, start, end);
    lv_anim_set_path_cb(&anim, anim_path_callbacks[path]);
    lv_anim_set_delay(&anim, delay);
    lv_anim_set_early_apply(&anim, instant ? true : false);
    if (relative) {
        lv_anim_set_get_value_cb(&anim, get_callback);
    }
    lv_anim_start(&anim);
}
References anim_path_callbacks, and start().
processDebuggerInput()
void eez::flow::processDebuggerInput (char * buffer, uint32_t length)
Definition at line 6117 of file eez-flow.cpp.
{
    for (uint32_t i = 0; i < length; i++) {
        if (buffer[i] == '\n') {
            int messageFromDebugger = g_inputFromDebugger[0] - '0';
            if (messageFromDebugger == MESSAGE_FROM_DEBUGGER_RESUME) {
                setDebuggerState(DEBUGGER_STATE_RESUMED);
            } else if (messageFromDebugger == MESSAGE_FROM_DEBUGGER_PAUSE) {
                setDebuggerState(DEBUGGER_STATE_PAUSED);
            } else if (messageFromDebugger == MESSAGE_FROM_DEBUGGER_SINGLE_STEP) {
                setDebuggerState(DEBUGGER_STATE_SINGLE_STEP);
            } else if (
                messageFromDebugger >= MESSAGE_FROM_DEBUGGER_ADD_BREAKPOINT &&
                messageFromDebugger <= MESSAGE_FROM_DEBUGGER_DISABLE_BREAKPOINT
            ) {
                char *p;
                auto flowIndex = (uint32_t)strtol(g_inputFromDebugger + 2, &p, 10);
                auto componentIndex = (uint32_t)strtol(p + 1, nullptr, 10);
                auto assets = g_firstFlowState->assets;
                auto flowDefinition = static_cast<FlowDefinition *>(assets->flowDefinition);
                if (flowIndex < flowDefinition->flows.count) {
                    auto flow = flowDefinition->flows[flowIndex];
                    if (componentIndex < flow->components.count) {
                        auto component = flow->components[componentIndex];
                        component->breakpoint = messageFromDebugger == MESSAGE_FROM_DEBUGGER_ADD_BREAKPOINT ||
                            messageFromDebugger == MESSAGE_FROM_DEBUGGER_ENABLE_BREAKPOINT ? 1 : 0;
                    } else {
                        ErrorTrace("Invalid breakpoint component index\n");
                    }
                } else {
                    ErrorTrace("Invalid breakpoint flow index\n");
                }
            } else if (messageFromDebugger == MESSAGE_FROM_DEBUGGER_MODE) {
                g_debuggerMode = strtol(g_inputFromDebugger + 2, nullptr, 10);
#if EEZ_OPTION_GUI
                gui::refreshScreen();
#endif
            }
            g_inputFromDebuggerPosition = 0;
        } else {
            if (g_inputFromDebuggerPosition < sizeof(g_inputFromDebugger)) {
                g_inputFromDebugger[g_inputFromDebuggerPosition++] = buffer[i];
            } else if (g_inputFromDebuggerPosition == sizeof(g_inputFromDebugger)) {
                ErrorTrace("Input from debugger buffer overflow\n");
            }
        }
    }
}
References assets, componentIndex, DEBUGGER_STATE_PAUSED, DEBUGGER_STATE_RESUMED, DEBUGGER_STATE_SINGLE_STEP, g_debuggerMode, g_firstFlowState, g_inputFromDebugger, g_inputFromDebuggerPosition, MESSAGE_FROM_DEBUGGER_ADD_BREAKPOINT, MESSAGE_FROM_DEBUGGER_DISABLE_BREAKPOINT, MESSAGE_FROM_DEBUGGER_ENABLE_BREAKPOINT, MESSAGE_FROM_DEBUGGER_MODE, MESSAGE_FROM_DEBUGGER_PAUSE, MESSAGE_FROM_DEBUGGER_RESUME, MESSAGE_FROM_DEBUGGER_SINGLE_STEP, and setDebuggerState().
propagateValue() [1/2]
void eez::flow::propagateValue (FlowState * flowState, unsigned componentIndex, unsigned outputIndex)
Definition at line 10688 of file eez-flow.cpp.
{
    auto &nullValue = *flowState->flowDefinition->constants[NULL_VALUE_INDEX];
    propagateValue(flowState, componentIndex, outputIndex, nullValue);
}
References componentIndex, flowState, and propagateValue().
propagateValue() [2/2]
void eez::flow::propagateValue (FlowState * flowState, unsigned componentIndex, unsigned outputIndex, const Value & value)
Definition at line 10668 of file eez-flow.cpp.
{
    if ((int)componentIndex == -1) {
        auto flowIndex = outputIndex;
        executeCallAction(flowState, -1, flowIndex, value);
        return;
    }
    resetSequenceInputs(flowState);
    auto component = flowState->flow->components[componentIndex];
    auto componentOutput = component->outputs[outputIndex];
    auto value2 = value.getValue();
    for (unsigned connectionIndex = 0; connectionIndex < componentOutput->connections.count; connectionIndex++) {
        auto connection = componentOutput->connections[connectionIndex];
        auto pValue = &flowState->values[connection->targetInputIndex];
        if (*pValue != value2) {
            *pValue = value2;
                onValueChanged(pValue);
        }
        pingComponent(flowState, connection->targetComponentIndex, componentIndex, outputIndex, connection->targetInputIndex);
    }
}
References componentIndex, executeCallAction(), flowState, onValueChanged(), pingComponent(), propagateValue(), and resetSequenceInputs().
Referenced by assignValue(), executeCatchErrorComponent(), executeCompareComponent(), executeConstantComponent(), executeCounterComponent(), executeEvalExprComponent(), executeInputComponent(), executeIsTrueComponent(), executeLoopComponent(), executeMQTTEventComponent(), executeOnEventComponent(), executeOutputComponent(), executeSortArrayComponent(), executeSwitchComponent(), executeWatchVariableComponent(), flowPropagateValue(), flowPropagateValueInt32(), flowPropagateValueLVGLEvent(), flowPropagateValueUint32(), propagateValue(), propagateValue(), propagateValueThroughSeqout(), and throwError().
propagateValueThroughSeqout()
void eez::flow::propagateValueThroughSeqout (FlowState * flowState, unsigned componentIndex)
Definition at line 10692 of file eez-flow.cpp.
{
    auto component = flowState->flow->components[componentIndex];
    for (uint32_t i = 0; i < component->outputs.count; i++) {
        if (component->outputs[i]->isSeqOut) {
            propagateValue(flowState, componentIndex, i);
            return;
        }
    }
}
References componentIndex, flowState, propagateValue(), and propagateValueThroughSeqout().
Referenced by endAsyncExecution(), executeAnimateComponent(), executeCallAction(), executeCatchErrorComponent(), executeCompareComponent(), executeConstantComponent(), executeCounterComponent(), executeDelayComponent(), executeEndComponent(), executeEvalExprComponent(), executeIsTrueComponent(), executeLabelOutComponent(), executeLogComponent(), executeLoopComponent(), executeLVGLApiComponent(), executeLVGLComponent(), executeMQTTConnectComponent(), executeMQTTDisconnectComponent(), executeMQTTEventComponent(), executeMQTTInitComponent(), executeMQTTPublishComponent(), executeMQTTSubscribeComponent(), executeMQTTUnsubscribeComponent(), executeNoopComponent(), executeOnEventComponent(), executeSelectLanguageComponent(), executeSetColorThemeComponent(), executeSetVariableComponent(), executeShowPageComponent(), executeStartComponent(), executeSwitchComponent(), executeTestAndSetComponent(), and propagateValueThroughSeqout().
qrCodeUpdate()
void eez::flow::qrCodeUpdate (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4520 of file eez-flow.cpp.
References ACTION_END, and qrCodeUpdate().
Referenced by qrCodeUpdate().
queueReset()
void eez::flow::queueReset ()
Definition at line 11070 of file eez-flow.cpp.
                  {
    g_queueHead = 0;
    g_queueTail = 0;
    g_queueMax  = 0;
    g_queueIsFull = false;
    g_numNonContinuousTaskInQueue = 0;
}
References g_numNonContinuousTaskInQueue, g_queueHead, g_queueIsFull, g_queueMax, g_queueTail, and queueReset().
Referenced by doStop(), queueReset(), and start().
registerComponent()
void eez::flow::registerComponent (ComponentTypes componentType, ExecuteComponentFunctionType executeComponentFunction)
Definition at line 3132 of file eez-flow.cpp.
{
    if (componentType >= defs_v3::COMPONENT_TYPE_START_ACTION) {
        g_executeComponentFunctions[componentType - defs_v3::COMPONENT_TYPE_START_ACTION] = executeComponentFunction;
    }
}
References g_executeComponentFunctions.
removeEventHandler()
void eez::flow::removeEventHandler (MQTTEventActionComponenentExecutionState * componentExecutionState) static
Definition at line 5025 of file eez-flow.cpp.
{
    for (auto connection = g_firstMQTTConnection; connection; connection = connection->next) {
        for (auto eventHandler = connection->firstEventHandler; eventHandler; eventHandler = eventHandler->next) {
            if (eventHandler->componentExecutionState == componentExecutionState) {
                if (eventHandler->prev) {
                    eventHandler->prev->next = eventHandler->next;
                } else {
                    connection->firstEventHandler = eventHandler->next;
                }
                if (eventHandler->next) {
                    eventHandler->next->prev = eventHandler->prev;
                } else {
                    connection->lastEventHandler = eventHandler->prev;
                }
                ObjectAllocator<MQTTConnectionEventHandler>::deallocate(eventHandler);
                return;
            }
        }
    }
}
References g_firstMQTTConnection.
Referenced by eez::flow::MQTTEventActionComponenentExecutionState::~MQTTEventActionComponenentExecutionState().
removeNextTaskFromQueue()
void eez::flow::removeNextTaskFromQueue ()
Definition at line 11122 of file eez-flow.cpp.
{
    auto flowState = g_queue[g_queueHead].flowState;
    decRefCounterForFlowState(flowState);
    auto continuousTask = g_queue[g_queueHead].continuousTask;
    g_queueHead = (g_queueHead + 1) % QUEUE_SIZE;
    g_queueIsFull = false;
    if (!continuousTask) {
        --g_numNonContinuousTaskInQueue;
        onRemoveFromQueue();
    }
}
References continuousTask, decRefCounterForFlowState(), flowState, g_numNonContinuousTaskInQueue, g_queue, g_queueHead, g_queueIsFull, onRemoveFromQueue(), QUEUE_SIZE, and removeNextTaskFromQueue().
Referenced by removeNextTaskFromQueue(), and tick().
removeTasksFromQueueForFlowState()
void eez::flow::removeTasksFromQueueForFlowState (FlowState * flowState)
Definition at line 11149 of file eez-flow.cpp.
{
    if (g_queueHead == g_queueTail && !g_queueIsFull) {
        return;
    }
    unsigned int it = g_queueHead;
    while (true) {
        if (g_queue[it].flowState == flowState) {
            g_queue[it].flowState = 0;
        }
        it = (it + 1) % QUEUE_SIZE;
        if (it == g_queueTail) {
            break;
        }
    }
}
References flowState, g_queue, g_queueHead, g_queueIsFull, g_queueTail, QUEUE_SIZE, and removeTasksFromQueueForFlowState().
Referenced by freeFlowState(), and removeTasksFromQueueForFlowState().
removeWatchesForFlowState()
void eez::flow::removeWatchesForFlowState (FlowState * flowState)
Definition at line 11238 of file eez-flow.cpp.
{
    for (auto node = g_watchList.first; node;) {
        auto nextNode = node->next;
        if (node->flowState == flowState) {
            watchListRemove(node);
        }
        node = nextNode;
    }
}
References flowState, g_watchList, removeWatchesForFlowState(), and watchListRemove().
Referenced by freeFlowState(), and removeWatchesForFlowState().
replacePage()
void eez::flow::replacePage (int16_t pageId, uint32_t animType, uint32_t speed, uint32_t delay) static
Definition at line 7476 of file eez-flow.cpp.
{
#if EEZ_OPTION_GUI
    eez::gui::getAppContextFromId(APP_CONTEXT_ID_DEVICE)->replacePage(pageId);
#else
    EEZ_UNUSED(pageId);
    EEZ_UNUSED(animType);
    EEZ_UNUSED(speed);
    EEZ_UNUSED(delay);
#endif
}
References EEZ_UNUSED, and replacePage().
Referenced by replacePage().
resetSequenceInputs()
void eez::flow::resetSequenceInputs (FlowState * flowState)
Definition at line 10650 of file eez-flow.cpp.
{
    if (flowState->executingComponentIndex != NO_COMPONENT_INDEX) {
        auto component = flowState->flow->components[flowState->executingComponentIndex];
        flowState->executingComponentIndex = NO_COMPONENT_INDEX;
        if (component->type != defs_v3::COMPONENT_TYPE_OUTPUT_ACTION) {
            for (uint32_t i = 0; i < component->inputs.count; i++) {
                auto inputIndex = component->inputs[i];
                if (flowState->flow->componentInputs[inputIndex] & COMPONENT_INPUT_FLAG_IS_SEQ_INPUT) {
                    auto pValue = &flowState->values[inputIndex];
                    if (!isInputEmpty(*pValue)) {
                        *pValue = getEmptyInputValue();
                        onValueChanged(pValue);
                    }
                }
            }
        }
    }
}
References flowState, getEmptyInputValue(), isInputEmpty(), NO_COMPONENT_INDEX, onValueChanged(), and resetSequenceInputs().
Referenced by propagateValue(), resetSequenceInputs(), and tick().
rollerSetSelected()
void eez::flow::rollerSetSelected (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4527 of file eez-flow.cpp.
                                                                : LV_ANIM_OFF);
#else
    lv_roller_set_selected(obj, (uint16_t)selected, animated ? LV_ANIM_ON : LV_ANIM_OFF);
#endif
ACTION_END
References ACTION_END, and rollerSetSelected().
Referenced by rollerSetSelected().
roundN() [1/2]
double eez::flow::roundN (double value, unsigned int numDigits) static
Definition at line 9374 of file eez-flow.cpp.
{
  float pow_10 = pow(10.0f, numDigits);
  return round(value * pow_10) / pow_10;
}
References roundN().
roundN() [2/2]
float eez::flow::roundN (float value, unsigned int numDigits) static
Definition at line 9370 of file eez-flow.cpp.
{
  float pow_10 = pow(10.0f, numDigits);
  return round(value * pow_10) / pow_10;
}
References roundN().
Referenced by do_OPERATION_TYPE_MATH_ROUND(), roundN(), and roundN().
scpiComponentInit()
void eez::flow::scpiComponentInit () static
Definition at line 7507 of file eez-flow.cpp.
{
}
References scpiComponentInit().
Referenced by scpiComponentInit().
setDebuggerMessageSubsciptionFilter()
void eez::flow::setDebuggerMessageSubsciptionFilter (uint32_t filter)
Definition at line 6084 of file eez-flow.cpp.
{
    g_messageSubsciptionFilter = filter;
}
References g_messageSubsciptionFilter.
setDebuggerState()
void eez::flow::setDebuggerState (DebuggerState newState) static
Definition at line 6094 of file eez-flow.cpp.
{
    if (newState != g_debuggerState) {
        g_debuggerState = newState;
        if (isSubscribedTo(MESSAGE_TO_DEBUGGER_STATE_CHANGED)) {
            char buffer[256];
            snprintf(buffer, sizeof(buffer), "%d\t%d\n",
                MESSAGE_TO_DEBUGGER_STATE_CHANGED,
                g_debuggerState
            );
            writeDebuggerBufferHook(buffer, strlen(buffer));
        }
    }
}
References g_debuggerState, isSubscribedTo(), MESSAGE_TO_DEBUGGER_STATE_CHANGED, and writeDebuggerBufferHook.
Referenced by canExecuteStep(), onDebuggerClientConnected(), onDebuggerClientDisconnected(), onStopped(), and processDebuggerInput().
setGlobalVariable() [1/2]
void eez::flow::setGlobalVariable (Assets * assets, uint32_t globalVariableIndex, const Value & value)
Definition at line 7203 of file eez-flow.cpp.
{
    if (globalVariableIndex < assets->flowDefinition->globalVariables.count) {
        if (g_globalVariables) {
            g_globalVariables->values[globalVariableIndex] = value;
        } else {
            *assets->flowDefinition->globalVariables[globalVariableIndex] = value;
        }
    }
}
References assets, and g_globalVariables.
setGlobalVariable() [2/2]
void eez::flow::setGlobalVariable (uint32_t globalVariableIndex, const Value & value)
Definition at line 7200 of file eez-flow.cpp.
{
    setGlobalVariable(g_mainAssets, globalVariableIndex, value);
}
References eez::g_mainAssets, and setGlobalVariable().
Referenced by setGlobalVariable().
setUserProperty()
void eez::flow::setUserProperty (unsigned propertyIndex, const Value & value)
Definition at line 7217 of file eez-flow.cpp.
{
    Value dstValue;
    if (!evalAssignableProperty(g_executeActionFlowState, g_executeActionComponentIndex, propertyIndex, dstValue, FlowError::PropertyInArray("CallAction", "Assignable property", propertyIndex))) {
        return;
    }
    assignValue(g_executeActionFlowState, g_executeActionComponentIndex, dstValue, value);
}
References assignValue(), evalAssignableProperty(), g_executeActionComponentIndex, and g_executeActionFlowState.
setUserPropertyAsync()
void eez::flow::setUserPropertyAsync (AsyncAction * asyncAction, unsigned propertyIndex, const Value & value)
Definition at line 7241 of file eez-flow.cpp.
{
    Value dstValue;
    if (!evalAssignableProperty(asyncAction->flowState, asyncAction->componentIndex, propertyIndex, dstValue, FlowError::PropertyInArray("CallAction", "Assignable property", propertyIndex))) {
        return;
    }
    assignValue(g_executeActionFlowState, g_executeActionComponentIndex, dstValue, value);
}
References assignValue(), evalAssignableProperty(), g_executeActionComponentIndex, and g_executeActionFlowState.
showKeyboard()
void eez::flow::showKeyboard (Value label, Value initialText, Value minChars, Value maxChars, bool isPassword, void(* onOk)(char *), void(* onCancel)()) static
Definition at line 7486 of file eez-flow.cpp.
{
    EEZ_UNUSED(label);
    EEZ_UNUSED(initialText);
    EEZ_UNUSED(minChars);
    EEZ_UNUSED(maxChars);
    EEZ_UNUSED(isPassword);
    EEZ_UNUSED(onOk);
    EEZ_UNUSED(onCancel);
}
References EEZ_UNUSED, and showKeyboard().
Referenced by showKeyboard().
showKeypad()
void eez::flow::showKeypad (Value label, Value initialValue, Value min, Value max, Unit unit, void(* onOk)(float), void(* onCancel)()) static
Definition at line 7495 of file eez-flow.cpp.
{
    EEZ_UNUSED(label);
    EEZ_UNUSED(initialValue);
    EEZ_UNUSED(min);
    EEZ_UNUSED(max);
    EEZ_UNUSED(unit);
    EEZ_UNUSED(onOk);
    EEZ_UNUSED(onCancel);
}
References EEZ_UNUSED, and showKeypad().
Referenced by showKeypad().
sliderSetRange()
void eez::flow::sliderSetRange (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4549 of file eez-flow.cpp.
References ACTION_END, and sliderSetRange().
Referenced by sliderSetRange().
sliderSetValue()
void eez::flow::sliderSetValue (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4537 of file eez-flow.cpp.
                                                          : LV_ANIM_OFF);
ACTION_END
References ACTION_END, and sliderSetValue().
Referenced by sliderSetValue().
sliderSetValueLeft()
void eez::flow::sliderSetValueLeft (FlowState * flowState, unsigned componentIndex, const ListOfAssetsPtr< Property > & properties, uint32_t actionIndex) static
Definition at line 4543 of file eez-flow.cpp.
                                                                   : LV_ANIM_OFF);
ACTION_END
References ACTION_END, and sliderSetValueLeft().
Referenced by sliderSetValueLeft().
sortArray()
void eez::flow::sortArray (SortArrayActionComponent * component, ArrayValue * array)
Definition at line 5662 of file eez-flow.cpp.
{
    g_sortArrayActionComponent = component;
    qsort(&array->values[0], array->arraySize, sizeof(Value), elementCompare);
}
References elementCompare(), and g_sortArrayActionComponent.
Referenced by executeSortArrayComponent().
start()
unsigned eez::flow::start (Assets * assets)
Definition at line 7028 of file eez-flow.cpp.
{
    auto flowDefinition = static_cast<FlowDefinition *>(assets->flowDefinition);
    if (flowDefinition->flows.count == 0) {
        return 0;
    }
    g_isStopped = false;
    g_isStopping = false;
    initGlobalVariables(assets);
    queueReset();
    watchListReset();
    scpiComponentInitHook();
    onStarted(assets);
    return 1;
}
References assets, g_isStopped, g_isStopping, initGlobalVariables(), onStarted(), queueReset(), scpiComponentInitHook, and watchListReset().
Referenced by animHeight(), animImageAngle(), animImageZoom(), animOpacity(), animWidth(), animX(), animY(), do_OPERATION_TYPE_STRING_SUBSTRING(), eez_flow_init(), and playAnimation().
startAsyncExecution()
void eez::flow::startAsyncExecution (FlowState * flowState, int componentIndex)
Definition at line 10829 of file eez-flow.cpp.
{
    if (!flowState->componenentAsyncStates[componentIndex]) {
        flowState->componenentAsyncStates[componentIndex] = true;
        onComponentAsyncStateChanged(flowState, componentIndex);
        incRefCounterForFlowState(flowState);
    }
}
References componentIndex, flowState, incRefCounterForFlowState(), onComponentAsyncStateChanged(), and startAsyncExecution().
Referenced by beginAsyncExecution(), and startAsyncExecution().
startToDebuggerMessage()
void eez::flow::startToDebuggerMessage () static
Definition at line 7509 of file eez-flow.cpp.
{
}
References startToDebuggerMessage().
Referenced by startToDebuggerMessage().
stop()
void eez::flow::stop ()
Definition at line 7103 of file eez-flow.cpp.
            {
    g_isStopping = true;
}
References g_isStopping.
stopScript()
void eez::flow::stopScript () static
Definition at line 7504 of file eez-flow.cpp.
{
    assert(false);
}
References stopScript().
Referenced by stopScript().
throwError() [1/2]
void eez::flow::throwError (FlowState * flowState, int componentIndex, const char * errorMessage)
Definition at line 10894 of file eez-flow.cpp.
{
    auto component = flowState->flow->components[componentIndex];
    if (!g_enableThrowError) {
        return;
    }
#if defined(EEZ_FOR_LVGL)
    LV_LOG_ERROR("EEZ-FLOW error: %s", errorMessage);
#elif defined(__EMSCRIPTEN__)
    printf("throwError: %s\n", errorMessage);
#endif
    if (component->errorCatchOutput != -1) {
        propagateValue(
            flowState,
            componentIndex,
            component->errorCatchOutput,
            Value::makeStringRef(errorMessage, strlen(errorMessage), 0xef6f8414)
        );
    } else {
        FlowState *catchErrorFlowState;
        int catchErrorComponentIndex;
        if (
            findCatchErrorComponent(
                component->type == defs_v3::COMPONENT_TYPE_ERROR_ACTION ? flowState->parentFlowState : flowState,
                catchErrorFlowState,
                catchErrorComponentIndex
            )
        ) {
            for (FlowState *fs = flowState; fs != catchErrorFlowState; fs = fs->parentFlowState) {
                if (fs->isAction) {
                    fs->error = true;
                }
            }
            auto component = catchErrorFlowState->flow->components[catchErrorComponentIndex];
            if (component->type == defs_v3::COMPONENT_TYPE_CATCH_ERROR_ACTION) {
                auto catchErrorComponentExecutionState = allocateComponentExecutionState<CatchErrorComponenentExecutionState>(catchErrorFlowState, catchErrorComponentIndex);
                catchErrorComponentExecutionState->message = Value::makeStringRef(errorMessage, strlen(errorMessage), 0x9473eef2);
                if (!addToQueue(catchErrorFlowState, catchErrorComponentIndex, -1, -1, -1, false)) {
                    onFlowError(flowState, componentIndex, errorMessage);
                    stopScriptHook();
                }
            } else {
                propagateValue(
                    catchErrorFlowState,
                    catchErrorComponentIndex,
                    component->errorCatchOutput,
                    Value::makeStringRef(errorMessage, strlen(errorMessage), 0x9473eef3)
                );
            }
        } else {
            onFlowError(flowState, componentIndex, errorMessage);
            stopScriptHook();
        }
    }
}
References addToQueue(), componentIndex, findCatchErrorComponent(), flowState, g_enableThrowError, onFlowError(), propagateValue(), stopScriptHook, and throwError().
Referenced by _evalBooleanProperty(), _evalIntegerProperty(), _evalUnsignedIntegerProperty(), addToQueue(), assignValue(), evalAssignableExpression(), evalAssignableProperty(), evalExpression(), evalProperty(), executeCallActionComponent(), executeCompareComponent(), executeComponent(), executeDelayComponent(), executeErrorComponent(), executeIsTrueComponent(), executeLVGLComponent(), executeMQTTConnectComponent(), executeMQTTDisconnectComponent(), executeMQTTEventComponent(), executeMQTTInitComponent(), executeMQTTPublishComponent(), executeMQTTSubscribeComponent(), executeMQTTUnsubscribeComponent(), executeOutputComponent(), executeSelectLanguageComponent(), executeSetColorThemeComponent(), executeSortArrayComponent(), executeSwitchComponent(), executeTestAndSetComponent(), getCallActionValue(), throwError(), and throwError().
throwError() [2/2]
void eez::flow::throwError (FlowState * flowState, int componentIndex, const FlowError & error)
Definition at line 11041 of file eez-flow.cpp.
{
    char errorMessageStr[512];
    const char *errorMessage = error.getMessage(errorMessageStr, sizeof(errorMessageStr), flowState->flowIndex, componentIndex);
    throwError(flowState, componentIndex, errorMessage);
}
References componentIndex, flowState, and throwError().
tick()
void eez::flow::tick ()
Definition at line 7042 of file eez-flow.cpp.
            {
    if (isFlowStopped()) {
        return;
    }
    if (g_isStopping) {
        doStop();
        return;
    }
    uint32_t startTickCount = millis();
    visitWatchList();
    auto queueSizeAtTickStart = getQueueSize();
    for (size_t i = 0; i < queueSizeAtTickStart || g_numNonContinuousTaskInQueue > 0; i++) {
        FlowState *flowState;
        unsigned componentIndex;
        bool continuousTask;
        if (!peekNextTaskFromQueue(flowState, componentIndex, continuousTask)) {
            break;
        }
        if (!flowState) {
            removeNextTaskFromQueue();
            continue;
        }
        if (!continuousTask && !canExecuteStep(flowState, componentIndex)) {
            break;
        }
        removeNextTaskFromQueue();
        flowState->executingComponentIndex = componentIndex;
        if (flowState->error) {
            deallocateComponentExecutionState(flowState, componentIndex);
        } else {
            if (continuousTask) {
                if (i < queueSizeAtTickStart) {
                    executeComponent(flowState, componentIndex);
                } else {
                    addToQueue(flowState, componentIndex, -1, -1, -1, true);
                }
            } else {
                executeComponent(flowState, componentIndex);
            }
        }
        if (isFlowStopped() || g_isStopping) {
            break;
        }
        resetSequenceInputs(flowState);
        if (canFreeFlowState(flowState)) {
            freeFlowState(flowState);
        }
        if ((i + 1) % 5 == 0) {
            if (millis() - startTickCount >= FLOW_TICK_MAX_DURATION_MS) {
                g_tick_max_duration_count++;
                break;
            }
        }
    }
    finishToDebuggerMessageHook();
    for (FlowState *flowState = g_firstFlowState; flowState; flowState = flowState->nextSibling) {
        if (flowState->deleteOnNextTick) {
            freeFlowState(flowState);
        }
    }
}
References addToQueue(), canExecuteStep(), canFreeFlowState(), componentIndex, continuousTask, deallocateComponentExecutionState(), doStop(), executeComponent(), finishToDebuggerMessageHook, FLOW_TICK_MAX_DURATION_MS, flowState, freeFlowState(), g_firstFlowState, g_isStopping, g_tick_max_duration_count, getQueueSize(), isFlowStopped(), eez::millis(), peekNextTaskFromQueue(), removeNextTaskFromQueue(), resetSequenceInputs(), and visitWatchList().
Referenced by eez_flow_tick().
visitWatchList()
void eez::flow::visitWatchList ()
Definition at line 11215 of file eez-flow.cpp.
                      {
    for (auto node = g_watchList.first; node; ) {
        auto nextNode = node->next;
        if (canExecuteStep(node->flowState, node->componentIndex)) {
            executeWatchVariableComponent(node->flowState, node->componentIndex);
        }
        decRefCounterForFlowState(node->flowState);
        if (canFreeFlowState(node->flowState)) {
            freeFlowState(node->flowState);
            watchListRemove(node);
        } else {
            incRefCounterForFlowState(node->flowState);
        }
        node = nextNode;
    }
}
References canExecuteStep(), canFreeFlowState(), decRefCounterForFlowState(), executeWatchVariableComponent(), freeFlowState(), g_watchList, incRefCounterForFlowState(), visitWatchList(), and watchListRemove().
Referenced by tick(), and visitWatchList().
watchListAdd()
WatchListNode * eez::flow::watchListAdd (FlowState * flowState, unsigned componentIndex)
Definition at line 11184 of file eez-flow.cpp.
{
    auto node = (WatchListNode *)alloc(sizeof(WatchListNode), 0x00864d67);
    node->prev = g_watchList.last;
    if (g_watchList.last != 0) {
        g_watchList.last->next = node;
    }
    g_watchList.last = node;
    if (g_watchList.first == 0) {
        g_watchList.first = node;
    }
    node->next = 0;
    node->flowState = flowState;
    node->componentIndex = componentIndex;
    incRefCounterForFlowState(flowState);
    (g_watchList.size)++;
    return node;
}
References eez::alloc(), componentIndex, flowState, g_watchList, incRefCounterForFlowState(), and watchListAdd().
Referenced by executeWatchVariableComponent(), and watchListAdd().
watchListRemove()
void eez::flow::watchListRemove (WatchListNode * node)
Definition at line 11201 of file eez-flow.cpp.
{
    if (node->prev) {
        node->prev->next = node->next;
    } else {
        g_watchList.first = node->next;
    }
    if (node->next) {
        node->next->prev = node->prev;
    } else {
        g_watchList.last = node->prev;
    }
    free(node);
    g_watchList.size > 0 ? (g_watchList.size)-- : 0;
}
References eez::free(), g_watchList, eez::flow::WatchListNode::next, eez::flow::WatchListNode::prev, and watchListRemove().
Referenced by removeWatchesForFlowState(), visitWatchList(), watchListRemove(), and watchListReset().
watchListReset()
void eez::flow::watchListReset ()
Definition at line 11231 of file eez-flow.cpp.
                      {
    for (auto node = g_watchList.first; node;) {
        auto nextNode = node->next;
        watchListRemove(node);
        node = nextNode;
    }
}
References g_watchList, watchListRemove(), and watchListReset().
Referenced by doStop(), start(), and watchListReset().
writeArray()
void eez::flow::writeArray (const ArrayValue * arrayValue) static
Definition at line 6257 of file eez-flow.cpp.
{
    WRITE_TO_OUTPUT_BUFFER('{');
    writeValueAddr(arrayValue);
    WRITE_TO_OUTPUT_BUFFER(',');
    writeArrayType(arrayValue->arraySize);
    WRITE_TO_OUTPUT_BUFFER(',');
    writeArrayType(arrayValue->arrayType);
    auto transferredSize = arrayValue->arraySize > MAX_ARRAY_SIZE_TRANSFERRED_IN_DEBUGGER ? MAX_ARRAY_SIZE_TRANSFERRED_IN_DEBUGGER : arrayValue->arraySize;
    for (uint32_t i = 0; i < transferredSize; i++) {
        WRITE_TO_OUTPUT_BUFFER(',');
        writeValueAddr(&arrayValue->values[i]);
    }
    WRITE_TO_OUTPUT_BUFFER('}');
    WRITE_TO_OUTPUT_BUFFER('\n');
    FLUSH_OUTPUT_BUFFER();
    for (uint32_t i = 0; i < transferredSize; i++) {
        onValueChanged(&arrayValue->values[i]);
    }
}
References FLUSH_OUTPUT_BUFFER, MAX_ARRAY_SIZE_TRANSFERRED_IN_DEBUGGER, onValueChanged(), WRITE_TO_OUTPUT_BUFFER, writeArrayType(), and writeValueAddr().
Referenced by writeValue().
writeArrayType()
void eez::flow::writeArrayType (uint32_t arrayType) static
Definition at line 6249 of file eez-flow.cpp.
{
    char tmpStr[32];
    snprintf(tmpStr, sizeof(tmpStr), "%x", (int)arrayType);
    auto len = strlen(tmpStr);
    for (size_t i = 0; i < len; i++) {
        WRITE_TO_OUTPUT_BUFFER(tmpStr[i]);
    }
}
References WRITE_TO_OUTPUT_BUFFER.
Referenced by writeArray().
writeDebuggerBuffer()
void eez::flow::writeDebuggerBuffer (const char * buffer, uint32_t length) static
Definition at line 7511 of file eez-flow.cpp.
{
    EEZ_UNUSED(buffer);
    EEZ_UNUSED(length);
}
References EEZ_UNUSED, and writeDebuggerBuffer().
Referenced by writeDebuggerBuffer().
writeHex()
void eez::flow::writeHex (char * dst, uint8_t * src, size_t srcLength) static
Definition at line 6276 of file eez-flow.cpp.
{
    *dst++ = 'H';
    for (size_t i = 0; i < srcLength; i++) {
        *dst++ = toHexDigit(src[i] / 16);
        *dst++ = toHexDigit(src[i] % 16);
    }
    *dst++ = 0;
}
References eez::toHexDigit().
Referenced by writeValue().
writeLogMessage() [1/2]
void eez::flow::writeLogMessage (const char * str) static
Definition at line 6555 of file eez-flow.cpp.
{
    for (const char *p = str; *p; p++) {
        if (*p == '\t') {
            WRITE_TO_OUTPUT_BUFFER('\\');
            WRITE_TO_OUTPUT_BUFFER('t');
        } if (*p == '\n') {
            WRITE_TO_OUTPUT_BUFFER('\\');
            WRITE_TO_OUTPUT_BUFFER('n');
        } else {
            WRITE_TO_OUTPUT_BUFFER(*p);
        }
    }
    WRITE_TO_OUTPUT_BUFFER('\n');
    FLUSH_OUTPUT_BUFFER();
}
References FLUSH_OUTPUT_BUFFER, and WRITE_TO_OUTPUT_BUFFER.
Referenced by logInfo(), logScpiCommand(), logScpiQuery(), and logScpiQueryResult().
writeLogMessage() [2/2]
void eez::flow::writeLogMessage (const char * str, size_t len) static
Definition at line 6570 of file eez-flow.cpp.
{
    for (size_t i = 0; i < len; i++) {
        if (str[i] == '\t') {
            WRITE_TO_OUTPUT_BUFFER('\\');
            WRITE_TO_OUTPUT_BUFFER('t');
        } if (str[i] == '\n') {
            WRITE_TO_OUTPUT_BUFFER('\\');
            WRITE_TO_OUTPUT_BUFFER('n');
        } else {
            WRITE_TO_OUTPUT_BUFFER(str[i]);
        }
    }
    WRITE_TO_OUTPUT_BUFFER('\n');
    FLUSH_OUTPUT_BUFFER();
}
References FLUSH_OUTPUT_BUFFER, and WRITE_TO_OUTPUT_BUFFER.
writeString()
void eez::flow::writeString (const char * str) static
Definition at line 6218 of file eez-flow.cpp.
{
    WRITE_TO_OUTPUT_BUFFER('"');
    while (true) {
        utf8_int32_t cp;
        str = utf8codepoint(str, &cp);
        if (!cp) {
            break;
        }
        if (cp == '"') {
            WRITE_TO_OUTPUT_BUFFER('\\');
            WRITE_TO_OUTPUT_BUFFER('"');
        } else if (cp == '\t') {
            WRITE_TO_OUTPUT_BUFFER('\\');
            WRITE_TO_OUTPUT_BUFFER('t');
        } else if (cp == '\n') {
            WRITE_TO_OUTPUT_BUFFER('\\');
            WRITE_TO_OUTPUT_BUFFER('n');
        } else if (cp >= 32 && cp < 127) {
            WRITE_TO_OUTPUT_BUFFER(cp);
        } else {
            char temp[32];
            snprintf(temp, sizeof(temp), "\\u%04x", (int)cp);
            for (size_t i = 0; i < strlen(temp); i++) {
                WRITE_TO_OUTPUT_BUFFER(temp[i]);
            }
        }
    }
    WRITE_TO_OUTPUT_BUFFER('"');
    WRITE_TO_OUTPUT_BUFFER('\n');
    FLUSH_OUTPUT_BUFFER();
}
References FLUSH_OUTPUT_BUFFER, utf8codepoint(), and WRITE_TO_OUTPUT_BUFFER.
Referenced by onFlowError(), and writeValue().
writeValue()
void eez::flow::writeValue (const Value & value) static
Definition at line 6284 of file eez-flow.cpp.
{
    char tempStr[64];
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4474)
#endif
    switch (value.getType()) {
    case VALUE_TYPE_UNDEFINED:
        stringCopy(tempStr, sizeof(tempStr) - 1, "undefined");
        break;
    case VALUE_TYPE_NULL:
        stringCopy(tempStr, sizeof(tempStr) - 1, "null");
        break;
    case VALUE_TYPE_BOOLEAN:
        stringCopy(tempStr, sizeof(tempStr) - 1, value.getBoolean() ? "true" : "false");
        break;
    case VALUE_TYPE_INT8:
        snprintf(tempStr, sizeof(tempStr) - 1, "%" PRId8 "", value.int8Value);
        break;
    case VALUE_TYPE_UINT8:
        snprintf(tempStr, sizeof(tempStr) - 1, "%" PRIu8 "", value.uint8Value);
        break;
    case VALUE_TYPE_INT16:
        snprintf(tempStr, sizeof(tempStr) - 1, "%" PRId16 "", value.int16Value);
        break;
    case VALUE_TYPE_UINT16:
        snprintf(tempStr, sizeof(tempStr) - 1, "%" PRIu16 "", value.uint16Value);
        break;
    case VALUE_TYPE_INT32:
        snprintf(tempStr, sizeof(tempStr) - 1, "%" PRId32 "", value.int32Value);
        break;
    case VALUE_TYPE_UINT32:
        snprintf(tempStr, sizeof(tempStr) - 1, "%" PRIu32 "", value.uint32Value);
        break;
    case VALUE_TYPE_INT64:
#ifdef PRId64
        snprintf(tempStr, sizeof(tempStr) - 1, "%" PRId64 "", value.int64Value);
#else
        snprintf(tempStr, sizeof(tempStr) - 1, "%" PRId32 "", (int32_t)value.int64Value);
#endif
        break;
    case VALUE_TYPE_UINT64:
#ifdef PRIu64
        snprintf(tempStr, sizeof(tempStr) - 1, "%" PRIu64 "", value.uint64Value);
#else
        snprintf(tempStr, sizeof(tempStr) - 1, "%" PRIu32 "", (uint32_t)value.uint64Value);
#endif
        break;
    case VALUE_TYPE_DOUBLE:
        writeHex(tempStr, (uint8_t *)&value.doubleValue, sizeof(double));
        break;
    case VALUE_TYPE_FLOAT:
        writeHex(tempStr, (uint8_t *)&value.floatValue, sizeof(float));
        break;
    case VALUE_TYPE_STRING:
    case VALUE_TYPE_STRING_ASSET:
    case VALUE_TYPE_STRING_REF:
        writeString(value.getString());
        return;
    case VALUE_TYPE_ARRAY:
    case VALUE_TYPE_ARRAY_ASSET:
    case VALUE_TYPE_ARRAY_REF:
        writeArray(value.getArray());
        return;
    case VALUE_TYPE_BLOB_REF:
        snprintf(tempStr, sizeof(tempStr) - 1, "@%d", (int)((BlobRef *)value.refValue)->len);
        break;
    case VALUE_TYPE_STREAM:
        snprintf(tempStr, sizeof(tempStr) - 1, ">%d", (int)(value.int32Value));
        break;
    case VALUE_TYPE_JSON:
        snprintf(tempStr, sizeof(tempStr) - 1, "#%d", (int)(value.int32Value));
        break;
    case VALUE_TYPE_DATE:
        tempStr[0] = '!';
        writeHex(tempStr + 1, (uint8_t *)&value.doubleValue, sizeof(double));
        break;
    case VALUE_TYPE_POINTER:
        snprintf(tempStr, sizeof(tempStr) - 1, "%p", value.getVoidPointer());
        break;
    case VALUE_TYPE_WIDGET:
        snprintf(tempStr, sizeof(tempStr) - 1, "*p%p", value.getVoidPointer());
        break;
    case VALUE_TYPE_EVENT:
        snprintf(tempStr, sizeof(tempStr) - 1, "!!%p", value.getVoidPointer());
        break;
    default:
        tempStr[0] = 0;
        break;
    }
#ifdef _MSC_VER
#pragma warning(pop)
#endif
    stringAppendString(tempStr, sizeof(tempStr), "\n");
    writeDebuggerBufferHook(tempStr, strlen(tempStr));
}
References eez::stringAppendString(), eez::stringCopy(), writeArray(), writeDebuggerBufferHook, writeHex(), and writeString().
Referenced by onFlowStateCreated(), onStarted(), and onValueChanged().
writeValueAddr()
void eez::flow::writeValueAddr (const void * pValue) static
Definition at line 6210 of file eez-flow.cpp.
{
    char tmpStr[32];
    snprintf(tmpStr, sizeof(tmpStr), "%p", pValue);
    auto len = strlen(tmpStr);
    for (size_t i = 0; i < len; i++) {
        WRITE_TO_OUTPUT_BUFFER(tmpStr[i]);
    }
}
References WRITE_TO_OUTPUT_BUFFER.
Referenced by writeArray().
Variable Documentation
actions
ActionType eez::flow::actions[] static
Definition at line 4721 of file eez-flow.cpp.
{
     &changeScreen,
     &changeToPreviousScreen,
     &objSetX,
     &objGetX,
     &objSetY,
     &objGetY,
     &objSetWidth,
     &objGetWidth,
     &objSetHeight,
     &objGetHeight,
     &objSetStyleOpa,
     &objGetStyleOpa,
     &objAddStyle,
     &objRemoveStyle,
     &objSetFlagHidden,
     &objAddFlag,
     &objClearFlag,
     &objHasFlag,
     &objSetStateChecked,
     &objSetStateDisabled,
     &objAddState,
     &objClearState,
     &objHasState,
     &arcSetValue,
     &barSetValue,
     &dropdownSetSelected,
     &imageSetSrc,
     &imageSetAngle,
     &imageSetZoom,
     &labelSetText,
     &rollerSetSelected,
     &sliderSetValue,
     &keyboardSetTextarea,
     &groupFocusObj,
     &groupFocusNext,
     &groupFocusPrev,
     &groupGetFocused,
     &groupFocusFreeze,
     &groupSetWrap,
     &groupSetEditing,
     &animX,
     &animY,
     &animWidth,
     &animHeight,
     &animOpacity,
     &animImageZoom,
     &animImageAngle,
     &createScreen,
     &deleteScreen,
     &isScreenCreated,
     &calendarSetTodayDate,
     &calendarSetShowedDate,
     &calendarSetHighlightedDate,
     &calendarGetPressedDate,
     &buttonMatrixSetButtonCtrl,
     &buttonMatrixClearButtonCtrl,
     &sliderSetValueLeft,
     &sliderSetRange,
     &qrCodeUpdate
};
Referenced by executeLVGLApiComponent(), and executeLVGLComponent().
anim_get_callbacks
lv_anim_get_value_cb_t eez::flow::anim_get_callbacks[]
Initial value:
= {
    anim_callback_get_x,
    anim_callback_get_y,
    anim_callback_get_width,
    anim_callback_get_height,
    anim_callback_get_opacity,
    anim_callback_get_image_zoom,
    anim_callback_get_image_angle
}
Definition at line 3851 of file eez-flow.cpp.
{
    anim_callback_get_x,
    anim_callback_get_y,
    anim_callback_get_width,
    anim_callback_get_height,
    anim_callback_get_opacity,
    anim_callback_get_image_zoom,
    anim_callback_get_image_angle
};
Referenced by executeLVGLComponent().
anim_path_callbacks
int32_t(* eez::flow::anim_path_callbacks[])(const lv_anim_t *a) (const lv_anim_t * a)
Initial value:
= {
    lv_anim_path_linear,
    lv_anim_path_ease_in,
    lv_anim_path_ease_out,
    lv_anim_path_ease_in_out,
    lv_anim_path_overshoot,
    lv_anim_path_bounce
}
Definition at line 3860 of file eez-flow.cpp.
{
    lv_anim_path_linear,
    lv_anim_path_ease_in,
    lv_anim_path_ease_out,
    lv_anim_path_ease_in_out,
    lv_anim_path_overshoot,
    lv_anim_path_bounce
};
Referenced by executeLVGLComponent(), and playAnimation().
anim_set_callbacks
lv_anim_exec_xcb_t eez::flow::anim_set_callbacks[]
Initial value:
= {
    anim_callback_set_x,
    anim_callback_set_y,
    anim_callback_set_width,
    anim_callback_set_height,
    anim_callback_set_opacity,
    anim_callback_set_image_zoom,
    anim_callback_set_image_angle
}
Definition at line 3842 of file eez-flow.cpp.
{
    anim_callback_set_x,
    anim_callback_set_y,
    anim_callback_set_width,
    anim_callback_set_height,
    anim_callback_set_opacity,
    anim_callback_set_image_zoom,
    anim_callback_set_image_angle
};
Referenced by executeLVGLComponent().
componentIndex
unsigned eez::flow::componentIndex
Definition at line 11062 of file eez-flow.cpp.
Referenced by _assignBooleanProperty(), _assignIntegerProperty(), _assignStringProperty(), _evalBooleanProperty(), _evalIntegerProperty(), _evalStringArrayPropertyAndJoin(), _evalTextProperty(), _evalUnsignedIntegerProperty(), addToQueue(), assignValue(), canExecuteStep(), deallocateComponentExecutionState(), endAsyncExecution(), evalAssignableExpression(), evalAssignableProperty(), evalExpression(), evalProperty(), executeAnimateComponent(), executeCallAction(), executeCallActionComponent(), executeCatchErrorComponent(), executeCompareComponent(), executeComponent(), executeConstantComponent(), executeCounterComponent(), executeDelayComponent(), executeEndComponent(), executeErrorComponent(), executeEvalExprComponent(), executeInputComponent(), executeIsTrueComponent(), executeLabelInComponent(), executeLabelOutComponent(), executeLogComponent(), executeLoopComponent(), executeLVGLApiComponent(), executeLVGLComponent(), executeLVGLUserWidgetComponent(), executeMQTTConnectComponent(), executeMQTTDisconnectComponent(), executeMQTTEventComponent(), executeMQTTInitComponent(), executeMQTTPublishComponent(), executeMQTTSubscribeComponent(), executeMQTTUnsubscribeComponent(), executeNoopComponent(), executeOnEventComponent(), executeOutputComponent(), executeSelectLanguageComponent(), executeSetColorThemeComponent(), executeSetVariableComponent(), executeShowPageComponent(), executeSortArrayComponent(), executeStartComponent(), executeSwitchComponent(), executeTestAndSetComponent(), executeWatchVariableComponent(), findCatchErrorComponent(), flowPropagateValue(), flowPropagateValueInt32(), flowPropagateValueLVGLEvent(), flowPropagateValueUint32(), getCallActionValue(), initFlowState(), isComponentReadyToRun(), isInQueue(), logInfo(), logScpiCommand(), logScpiQuery(), logScpiQueryResult(), onComponentAsyncStateChanged(), onComponentExecutionStateChanged(), onEvent(), onFlowError(), peekNextTaskFromQueue(), pingComponent(), processDebuggerInput(), propagateValue(), propagateValue(), propagateValueThroughSeqout(), startAsyncExecution(), throwError(), throwError(), tick(), and watchListAdd().
continuousTask
bool eez::flow::continuousTask
Definition at line 11063 of file eez-flow.cpp.
Referenced by addToQueue(), peekNextTaskFromQueue(), removeNextTaskFromQueue(), and tick().
executeLvglActionHook
void(* eez::flow::executeLvglActionHook) (int actionIndex) (int actionIndex) = executeLvglAction
Definition at line 7578 of file eez-flow.cpp.
Referenced by eez_flow_init(), and eez::executeActionFunction().
finishToDebuggerMessageHook
void(* eez::flow::finishToDebuggerMessageHook) () () = finishToDebuggerMessage
Definition at line 7526 of file eez-flow.cpp.
Referenced by doStop(), and tick().
FLOW_TICK_MAX_DURATION_MS
const uint32_t eez::flow::FLOW_TICK_MAX_DURATION_MS = 5 static
Definition at line 7020 of file eez-flow.cpp.
Referenced by tick().
flowState
FlowState* eez::flow::flowState
Definition at line 11061 of file eez-flow.cpp.
Referenced by _assignBooleanProperty(), _assignIntegerProperty(), _assignStringProperty(), _evalBooleanProperty(), _evalIntegerProperty(), _evalStringArrayPropertyAndJoin(), _evalTextProperty(), _evalUnsignedIntegerProperty(), addToQueue(), assignValue(), canExecuteStep(), canFreeFlowState(), clearInputValue(), createUserWidgetFlowState(), deallocateComponentExecutionState(), decRefCounterForFlowState(), deletePageFlowState(), endAsyncExecution(), evalAssignableExpression(), evalAssignableProperty(), evalExpression(), evalExpression(), evalProperty(), executeAnimateComponent(), executeCallAction(), executeCallActionComponent(), executeCatchErrorComponent(), executeCompareComponent(), executeComponent(), executeConstantComponent(), executeCounterComponent(), executeDelayComponent(), executeEndComponent(), executeErrorComponent(), executeEvalExprComponent(), executeInputComponent(), executeIsTrueComponent(), executeLabelInComponent(), executeLabelOutComponent(), executeLogComponent(), executeLoopComponent(), executeLVGLApiComponent(), executeLVGLComponent(), executeLVGLUserWidgetComponent(), executeMQTTConnectComponent(), executeMQTTDisconnectComponent(), executeMQTTEventComponent(), executeMQTTInitComponent(), executeMQTTPublishComponent(), executeMQTTSubscribeComponent(), executeMQTTUnsubscribeComponent(), executeNoopComponent(), executeOnEventComponent(), executeOutputComponent(), executeSelectLanguageComponent(), executeSetColorThemeComponent(), executeSetVariableComponent(), executeShowPageComponent(), executeSortArrayComponent(), executeStartComponent(), executeSwitchComponent(), executeTestAndSetComponent(), executeWatchVariableComponent(), findCatchErrorComponent(), flowPropagateValue(), flowPropagateValueInt32(), flowPropagateValueLVGLEvent(), flowPropagateValueUint32(), freeAllChildrenFlowStates(), freeFlowState(), getCallActionValue(), getFlowState(), getPageFlowState(), getPageIndex(), getTimelinePosition(), incRefCounterForFlowState(), initActionFlowState(), initFlowState(), initPageFlowState(), isComponentReadyToRun(), isInQueue(), logInfo(), logScpiCommand(), logScpiQuery(), logScpiQueryResult(), onAddToQueue(), onComponentAsyncStateChanged(), onComponentExecutionStateChanged(), onEvent(), onFlowError(), onFlowStateCreated(), onFlowStateDestroyed(), onFlowStateTimelineChanged(), onPageChanged(), peekNextTaskFromQueue(), pingComponent(), propagateValue(), propagateValue(), propagateValueThroughSeqout(), removeNextTaskFromQueue(), removeTasksFromQueueForFlowState(), removeWatchesForFlowState(), resetSequenceInputs(), startAsyncExecution(), throwError(), throwError(), tick(), and watchListAdd().
g_debuggerIsConnected
bool eez::flow::g_debuggerIsConnected
Definition at line 6077 of file eez-flow.cpp.
Referenced by canExecuteStep(), doStop(), isSubscribedTo(), onDebuggerClientConnected(), and onDebuggerClientDisconnected().
g_debuggerMode
int eez::flow::g_debuggerMode = DEBUGGER_MODE_RUN
Definition at line 6083 of file eez-flow.cpp.
Referenced by processDebuggerInput().
g_debuggerState
DebuggerState eez::flow::g_debuggerState static
Definition at line 6079 of file eez-flow.cpp.
Referenced by canExecuteStep(), and setDebuggerState().
g_enableThrowError
bool eez::flow::g_enableThrowError = true static
Definition at line 10387 of file eez-flow.cpp.
Referenced by enableThrowError(), and throwError().
g_evalOperations
EvalOperation eez::flow::g_evalOperations[]
Definition at line 10279 of file eez-flow.cpp.
{
    do_OPERATION_TYPE_ADD,
    do_OPERATION_TYPE_SUB,
    do_OPERATION_TYPE_MUL,
    do_OPERATION_TYPE_DIV,
    do_OPERATION_TYPE_MOD,
    do_OPERATION_TYPE_LEFT_SHIFT,
    do_OPERATION_TYPE_RIGHT_SHIFT,
    do_OPERATION_TYPE_BINARY_AND,
    do_OPERATION_TYPE_BINARY_OR,
    do_OPERATION_TYPE_BINARY_XOR,
    do_OPERATION_TYPE_EQUAL,
    do_OPERATION_TYPE_NOT_EQUAL,
    do_OPERATION_TYPE_LESS,
    do_OPERATION_TYPE_GREATER,
    do_OPERATION_TYPE_LESS_OR_EQUAL,
    do_OPERATION_TYPE_GREATER_OR_EQUAL,
    do_OPERATION_TYPE_LOGICAL_AND,
    do_OPERATION_TYPE_LOGICAL_OR,
    do_OPERATION_TYPE_UNARY_PLUS,
    do_OPERATION_TYPE_UNARY_MINUS,
    do_OPERATION_TYPE_BINARY_ONE_COMPLEMENT,
    do_OPERATION_TYPE_NOT,
    do_OPERATION_TYPE_CONDITIONAL,
    do_OPERATION_TYPE_SYSTEM_GET_TICK,
    do_OPERATION_TYPE_FLOW_INDEX,
    do_OPERATION_TYPE_FLOW_IS_PAGE_ACTIVE,
    do_OPERATION_TYPE_FLOW_PAGE_TIMELINE_POSITION,
    do_OPERATION_TYPE_FLOW_MAKE_ARRAY_VALUE,
    do_OPERATION_TYPE_FLOW_MAKE_ARRAY_VALUE,
    do_OPERATION_TYPE_FLOW_LANGUAGES,
    do_OPERATION_TYPE_FLOW_TRANSLATE,
    do_OPERATION_TYPE_FLOW_PARSE_INTEGER,
    do_OPERATION_TYPE_FLOW_PARSE_FLOAT,
    do_OPERATION_TYPE_FLOW_PARSE_DOUBLE,
    do_OPERATION_TYPE_DATE_NOW,
    do_OPERATION_TYPE_DATE_TO_STRING,
    do_OPERATION_TYPE_DATE_FROM_STRING,
    do_OPERATION_TYPE_MATH_SIN,
    do_OPERATION_TYPE_MATH_COS,
    do_OPERATION_TYPE_MATH_LOG,
    do_OPERATION_TYPE_MATH_LOG10,
    do_OPERATION_TYPE_MATH_ABS,
    do_OPERATION_TYPE_MATH_FLOOR,
    do_OPERATION_TYPE_MATH_CEIL,
    do_OPERATION_TYPE_MATH_ROUND,
    do_OPERATION_TYPE_MATH_MIN,
    do_OPERATION_TYPE_MATH_MAX,
    do_OPERATION_TYPE_STRING_LENGTH,
    do_OPERATION_TYPE_STRING_SUBSTRING,
    do_OPERATION_TYPE_STRING_FIND,
    do_OPERATION_TYPE_STRING_PAD_START,
    do_OPERATION_TYPE_STRING_SPLIT,
    do_OPERATION_TYPE_ARRAY_LENGTH,
    do_OPERATION_TYPE_ARRAY_SLICE,
    do_OPERATION_TYPE_ARRAY_ALLOCATE,
    do_OPERATION_TYPE_ARRAY_APPEND,
    do_OPERATION_TYPE_ARRAY_INSERT,
    do_OPERATION_TYPE_ARRAY_REMOVE,
    do_OPERATION_TYPE_ARRAY_CLONE,
    do_OPERATION_TYPE_DATE_TO_LOCALE_STRING,
    do_OPERATION_TYPE_DATE_GET_YEAR,
    do_OPERATION_TYPE_DATE_GET_MONTH,
    do_OPERATION_TYPE_DATE_GET_DAY,
    do_OPERATION_TYPE_DATE_GET_HOURS,
    do_OPERATION_TYPE_DATE_GET_MINUTES,
    do_OPERATION_TYPE_DATE_GET_SECONDS,
    do_OPERATION_TYPE_DATE_GET_MILLISECONDS,
    do_OPERATION_TYPE_DATE_MAKE,
    do_OPERATION_TYPE_MATH_POW,
    do_OPERATION_TYPE_LVGL_METER_TICK_INDEX,
    do_OPERATION_TYPE_FLOW_GET_BITMAP_INDEX,
    do_OPERATION_TYPE_FLOW_TO_INTEGER,
    do_OPERATION_TYPE_STRING_FROM_CODE_POINT,
    do_OPERATION_TYPE_STRING_CODE_POINT_AT,
    do_OPERATION_TYPE_CRYPTO_SHA256,
    do_OPERATION_TYPE_BLOB_ALLOCATE,
    do_OPERATION_TYPE_JSON_GET,
    do_OPERATION_TYPE_JSON_CLONE,
    do_OPERATION_TYPE_FLOW_GET_BITMAP_AS_DATA_URL,
    do_OPERATION_TYPE_STRING_FORMAT,
    do_OPERATION_TYPE_STRING_FORMAT_PREFIX,
    do_OPERATION_TYPE_EVENT_GET_CODE,
    do_OPERATION_TYPE_EVENT_GET_CURRENT_TARGET,
    do_OPERATION_TYPE_EVENT_GET_TARGET,
    do_OPERATION_TYPE_EVENT_GET_USER_DATA,
    do_OPERATION_TYPE_EVENT_GET_KEY,
    do_OPERATION_TYPE_EVENT_GET_GESTURE_DIR,
    do_OPERATION_TYPE_EVENT_GET_ROTARY_DIFF,
    do_OPERATION_TYPE_BLOB_TO_STRING,
    do_OPERATION_TYPE_FLOW_THEMES,
};
Referenced by evalExpression().
g_executeActionComponentIndex
unsigned eez::flow::g_executeActionComponentIndex
Definition at line 3253 of file eez-flow.cpp.
Referenced by beginAsyncExecution(), executeCallAction(), getUserProperty(), setUserProperty(), and setUserPropertyAsync().
g_executeActionFlowState
FlowState* eez::flow::g_executeActionFlowState
Definition at line 3252 of file eez-flow.cpp.
Referenced by beginAsyncExecution(), executeCallAction(), getUserProperty(), setUserProperty(), and setUserPropertyAsync().
g_executeComponentFunctions
ExecuteComponentFunctionType eez::flow::g_executeComponentFunctions[] static
Definition at line 3071 of file eez-flow.cpp.
{
    executeStartComponent,
    executeEndComponent,
    executeInputComponent,
    executeOutputComponent,
    executeWatchVariableComponent,
    executeEvalExprComponent,
    executeSetVariableComponent,
    executeSwitchComponent,
    executeCompareComponent,
    executeIsTrueComponent,
    executeConstantComponent,
    executeLogComponent,
    executeCallActionComponent,
    executeDelayComponent,
    executeErrorComponent,
    executeCatchErrorComponent,
    executeCounterComponent,
    executeLoopComponent,
    executeShowPageComponent,
    nullptr,
#if EEZ_OPTION_GUI
    executeShowMessageBoxComponent,
    executeShowKeyboardComponent,
    executeShowKeypadComponent,
#else
    nullptr,
    nullptr,
    nullptr,
#endif
    executeNoopComponent,
    nullptr,
    executeSelectLanguageComponent,
#if EEZ_OPTION_GUI
    executeSetPageDirectionComponent,
#else
    nullptr,
#endif
    executeAnimateComponent,
    executeOnEventComponent,
    executeLVGLComponent,
#if EEZ_OPTION_GUI
    executeOverrideStyleComponent,
#else
    nullptr,
#endif
    executeSortArrayComponent,
    executeLVGLUserWidgetComponent,
    executeTestAndSetComponent,
    executeMQTTInitComponent,
    executeMQTTConnectComponent,
    executeMQTTDisconnectComponent,
    executeMQTTEventComponent,
    executeMQTTSubscribeComponent,
    executeMQTTUnsubscribeComponent,
    executeMQTTPublishComponent,
    executeLabelInComponent,
    executeLabelOutComponent,
    executeLVGLApiComponent,
    executeSetColorThemeComponent,
};
Referenced by executeComponent(), and registerComponent().
g_firstFlowState
FlowState* eez::flow::g_firstFlowState
Definition at line 7023 of file eez-flow.cpp.
Referenced by deletePageFlowState(), doStop(), endAsyncExecution(), freeFlowState(), getPageFlowState(), initFlowState(), processDebuggerInput(), and tick().
g_firstMQTTConnection
MQTTConnection* eez::flow::g_firstMQTTConnection = nullptr
Definition at line 4947 of file eez-flow.cpp.
Referenced by addConnection(), deleteConnection(), findConnection(), and removeEventHandler().
g_globalVariables
GlobalVariables* eez::flow::g_globalVariables = nullptr
Definition at line 10385 of file eez-flow.cpp.
Referenced by evalExpression(), getGlobalVariable(), initGlobalVariables(), onStarted(), and setGlobalVariable().
g_inputFromDebugger
char eez::flow::g_inputFromDebugger[64] static
Definition at line 6081 of file eez-flow.cpp.
Referenced by processDebuggerInput().
g_inputFromDebuggerPosition
unsigned eez::flow::g_inputFromDebuggerPosition static
Definition at line 6082 of file eez-flow.cpp.
Referenced by onDebuggerClientConnected(), and processDebuggerInput().
g_isStopped
bool eez::flow::g_isStopped = true static
Definition at line 7026 of file eez-flow.cpp.
Referenced by doStop(), isFlowStopped(), and start().
g_isStopping
bool eez::flow::g_isStopping = false static
Definition at line 7025 of file eez-flow.cpp.
Referenced by start(), stop(), and tick().
g_lastFlowState
FlowState* eez::flow::g_lastFlowState
Definition at line 7024 of file eez-flow.cpp.
Referenced by doStop(), freeFlowState(), and initFlowState().
g_lastMQTTConnection
MQTTConnection* eez::flow::g_lastMQTTConnection = nullptr
Definition at line 4948 of file eez-flow.cpp.
Referenced by addConnection(), and deleteConnection().
g_messageSubsciptionFilter
uint32_t eez::flow::g_messageSubsciptionFilter = 0xFFFFFFFF static
Definition at line 6078 of file eez-flow.cpp.
Referenced by isSubscribedTo(), and setDebuggerMessageSubsciptionFilter().
g_numNonContinuousTaskInQueue
unsigned eez::flow::g_numNonContinuousTaskInQueue
Definition at line 11069 of file eez-flow.cpp.
Referenced by addToQueue(), queueReset(), and removeNextTaskFromQueue().
[struct]
struct { ... } eez::flow::g_queue[QUEUE_SIZE]
Referenced by addToQueue(), isInQueue(), peekNextTaskFromQueue(), removeNextTaskFromQueue(), and removeTasksFromQueueForFlowState().
g_queueHead
unsigned eez::flow::g_queueHead static
Definition at line 11065 of file eez-flow.cpp.
Referenced by addToQueue(), getQueueSize(), isInQueue(), peekNextTaskFromQueue(), queueReset(), removeNextTaskFromQueue(), and removeTasksFromQueueForFlowState().
g_queueIsFull
bool eez::flow::g_queueIsFull = false static
Definition at line 11068 of file eez-flow.cpp.
Referenced by addToQueue(), getQueueSize(), isInQueue(), peekNextTaskFromQueue(), queueReset(), removeNextTaskFromQueue(), and removeTasksFromQueueForFlowState().
g_queueMax
unsigned eez::flow::g_queueMax static
Definition at line 11067 of file eez-flow.cpp.
Referenced by addToQueue(), getMaxQueueSize(), and queueReset().
g_queueTail
unsigned eez::flow::g_queueTail static
Definition at line 11066 of file eez-flow.cpp.
Referenced by addToQueue(), getQueueSize(), isInQueue(), peekNextTaskFromQueue(), queueReset(), and removeTasksFromQueueForFlowState().
g_selectedLanguage
int eez::flow::g_selectedLanguage = 0
Definition at line 7022 of file eez-flow.cpp.
Referenced by do_OPERATION_TYPE_FLOW_TRANSLATE(), and executeSelectLanguageComponent().
g_skipNextBreakpoint
bool eez::flow::g_skipNextBreakpoint static
Definition at line 6080 of file eez-flow.cpp.
Referenced by canExecuteStep(), and onDebuggerClientConnected().
g_sortArrayActionComponent
SortArrayActionComponent* eez::flow::g_sortArrayActionComponent
Definition at line 5615 of file eez-flow.cpp.
Referenced by elementCompare(), and sortArray().
g_stack
EvalStack eez::flow::g_stack
Definition at line 6728 of file eez-flow.cpp.
Referenced by evalAssignableExpression(), evalExpression(), and evalExpression().
g_tick_max_duration_count
unsigned eez::flow::g_tick_max_duration_count = 0 static
Definition at line 7021 of file eez-flow.cpp.
Referenced by getTickMaxDurationCounter(), and tick().
g_watchList
WatchList eez::flow::g_watchList static
Definition at line 11183 of file eez-flow.cpp.
Referenced by getWatchListSize(), removeWatchesForFlowState(), visitWatchList(), watchListAdd(), watchListRemove(), and watchListReset().
getDateNowHook
double(* eez::flow::getDateNowHook) () () = getDateNowDefaultImplementation
Definition at line 7588 of file eez-flow.cpp.
Referenced by eez::flow::date::now().
getLvglGroupByNameHook
int32_t(* eez::flow::getLvglGroupByNameHook) (const char *name) (const char * name) = getLvglGroupByName
Definition at line 7575 of file eez-flow.cpp.
Referenced by eez_flow_init().
getLvglGroupFromIndexHook
lv_group_t *(* eez::flow::getLvglGroupFromIndexHook) (int32_t index) (int32_t index) = getLvglGroupFromIndex
Definition at line 7572 of file eez-flow.cpp.
Referenced by eez_flow_init(), and executeLVGLComponent().
getLvglImageByNameHook
const void *(* eez::flow::getLvglImageByNameHook) (const char *name) (const char * name) = getLvglImageByName
Definition at line 7577 of file eez-flow.cpp.
Referenced by eez_flow_init(), and executeLVGLComponent().
getLvglObjectByNameHook
int32_t(* eez::flow::getLvglObjectByNameHook) (const char *name) (const char * name) = getLvglObjectByName
Definition at line 7574 of file eez-flow.cpp.
Referenced by eez_flow_init().
getLvglObjectFromIndexHook
lv_obj_t *(* eez::flow::getLvglObjectFromIndexHook) (int32_t index) (int32_t index) = getLvglObjectFromIndex
Definition at line 7571 of file eez-flow.cpp.
Referenced by eez_flow_delete_screen_on_unload(), eez_flow_init(), executeLVGLComponent(), isScreenCreated(), and replacePageHook().
getLvglScreenByNameHook
int32_t(* eez::flow::getLvglScreenByNameHook) (const char *name) (const char * name) = getLvglScreenByName
Definition at line 7573 of file eez-flow.cpp.
Referenced by eez_flow_init().
getLvglStyleByNameHook
int32_t(* eez::flow::getLvglStyleByNameHook) (const char *name) (const char * name) = getLvglStyleByName
Definition at line 7576 of file eez-flow.cpp.
Referenced by eez_flow_init().
lvglObjAddStyleHook
void(* eez::flow::lvglObjAddStyleHook) (lv_obj_t *object, int32_t styleIndex) (lv_obj_t * object, int32_t styleIndex) = lvglObjAddStyle
Definition at line 7579 of file eez-flow.cpp.
Referenced by eez_flow_init_styles(), and executeLVGLComponent().
lvglObjRemoveStyleHook
void(* eez::flow::lvglObjRemoveStyleHook) (lv_obj_t *object, int32_t styleIndex) (lv_obj_t * object, int32_t styleIndex) = lvglObjRemoveStyle
Definition at line 7580 of file eez-flow.cpp.
Referenced by eez_flow_init_styles(), and executeLVGLComponent().
lvglSetColorThemeHook
void(* eez::flow::lvglSetColorThemeHook) (const char *themeName) (const char * themeName) = lvglSetColorTheme
Definition at line 7581 of file eez-flow.cpp.
Referenced by eez_flow_init(), and executeSetColorThemeComponent().
NO_COMPONENT_INDEX
const unsigned eez::flow::NO_COMPONENT_INDEX = 0xFFFFFFFF static
Definition at line 10386 of file eez-flow.cpp.
Referenced by initFlowState(), and resetSequenceInputs().
onDebuggerInputAvailableHook
void(* eez::flow::onDebuggerInputAvailableHook) () () = onDebuggerInputAvailable
Definition at line 7527 of file eez-flow.cpp.
onFlowErrorHook
void(* eez::flow::onFlowErrorHook) (FlowState *flowState, int componentIndex, const char *errorMessage) (FlowState * flowState, int componentIndex, const char * errorMessage) = nullptr
Definition at line 7589 of file eez-flow.cpp.
Referenced by onFlowError().
outputBuffer
char eez::flow::outputBuffer[64]
Definition at line 6196 of file eez-flow.cpp.
outputBufferPosition
int eez::flow::outputBufferPosition = 0
Definition at line 6198 of file eez-flow.cpp.
QUEUE_SIZE
const unsigned eez::flow::QUEUE_SIZE = 1000 static
Definition at line 11059 of file eez-flow.cpp.
Referenced by addToQueue(), getQueueSize(), isInQueue(), removeNextTaskFromQueue(), and removeTasksFromQueueForFlowState().
replacePageHook
void(* eez::flow::replacePageHook) (int16_t pageId, uint32_t animType, uint32_t speed, uint32_t delay) (int16_t pageId, uint32_t animType, uint32_t speed, uint32_t delay) = replacePage
Definition at line 7519 of file eez-flow.cpp.
Referenced by eez_flow_init(), eez_flow_pop_screen(), eez_flow_push_screen(), eez_flow_set_screen(), and executeShowPageComponent().
scpiComponentInitHook
void(* eez::flow::scpiComponentInitHook) () () = scpiComponentInit
Definition at line 7523 of file eez-flow.cpp.
Referenced by start().
showKeyboardHook
void(* eez::flow::showKeyboardHook) (Value label, Value initialText, Value minChars, Value maxChars, bool isPassword, void(*onOk)(char *), void(*onCancel)()) (Value label, Value initialText, Value minChars, Value maxChars, bool isPassword, void(* onOk)(char *), void(* onCancel)()) = showKeyboard
Definition at line 7520 of file eez-flow.cpp.
showKeypadHook
void(* eez::flow::showKeypadHook) (Value label, Value initialValue, Value min, Value max, Unit unit, void(*onOk)(float), void(*onCancel)()) (Value label, Value initialValue, Value min, Value max, Unit unit, void(* onOk)(float), void(* onCancel)()) = showKeypad
Definition at line 7521 of file eez-flow.cpp.
startToDebuggerMessageHook
void(* eez::flow::startToDebuggerMessageHook) () () = startToDebuggerMessage
Definition at line 7524 of file eez-flow.cpp.
Referenced by isSubscribedTo().
stopScriptHook
void(* eez::flow::stopScriptHook) () () = stopScript
Definition at line 7522 of file eez-flow.cpp.
Referenced by executeEndComponent(), and throwError().
writeDebuggerBufferHook
void(* eez::flow::writeDebuggerBufferHook) (const char *buffer, uint32_t length) (const char * buffer, uint32_t length) = writeDebuggerBuffer
Definition at line 7525 of file eez-flow.cpp.
Referenced by logInfo(), logScpiCommand(), logScpiQuery(), logScpiQueryResult(), onAddToQueue(), onComponentAsyncStateChanged(), onComponentExecutionStateChanged(), onFlowError(), onFlowStateCreated(), onFlowStateDestroyed(), onFlowStateTimelineChanged(), onPageChanged(), onRemoveFromQueue(), onStarted(), onValueChanged(), setDebuggerState(), and writeValue().