EARS-PIO-WSS3-LVGL-001: eez Namespace Reference
eez Namespace Reference
Namespaces
namespace flow
Functions
void executeActionFunction (int actionId)
void initAllocHeap (uint8_t *heap, size_t heapSize)
void * alloc (size_t size, uint32_t id)
void free (void *ptr)
template<typename T>
void freeObject (T *ptr)
void getAllocInfo (uint32_t &free, uint32_t &alloc)
void fixOffsets (Assets *assets)
bool decompressAssetsData (const uint8_t *assetsData, uint32_t assetsDataSize, Assets *decompressedAssets, uint32_t maxDecompressedAssetsSize, int *err)
static void allocMemoryForDecompressedAssets (const uint8_t *assetsData, uint32_t assetsDataSize, uint8_t *&decompressedAssetsMemoryBuffer, uint32_t &decompressedAssetsMemoryBufferSize)
void loadMainAssets (const uint8_t *assets, uint32_t assetsSize)
void unloadExternalAssets ()
int getThemesCount ()
static Theme * getTheme (int i)
const char * getThemeName (int i)
uint32_t getThemeColorsCount (int themeIndex)
const uint16_t * getThemeColors (int themeIndex)
const uint16_t * getColors ()
int getExternalAssetsMainPageId ()
void initMemory ()
void initAssetsMemory ()
void initOtherMemory ()
uint8_t * allocBuffer (uint32_t size)
uint32_t millis ()
Unit getUnitFromName (const char *unitName)
Unit getBaseUnit (Unit unit)
float getUnitFactor (Unit unit)
static Unit getDerivedUnit (Unit unit, float factor)
Unit findDerivedUnit (float value, Unit unit)
static float getSmallerFactor (float factor)
Unit getSmallerUnit (Unit unit, float min, float precision)
Unit getBiggestUnit (Unit unit, float max)
Unit getSmallestUnit (Unit unit, float min, float precision)
float remap (float x, float x1, float y1, float x2, float y2)
float remapQuad (float x, float x1, float y1, float x2, float y2)
float remapOutQuad (float x, float x1, float y1, float x2, float y2)
float remapInOutQuad (float x, float x1, float y1, float x2, float y2)
float remapCubic (float x, float x1, float y1, float x2, float y2)
float remapOutCubic (float x, float x1, float y1, float x2, float y2)
float remapExp (float x, float x1, float y1, float x2, float y2)
float remapOutExp (float x, float x1, float y1, float x2, float y2)
float clamp (float x, float min, float max)
void stringCopy (char *dst, size_t maxStrLength, const char *src)
void stringCopyLength (char *dst, size_t maxStrLength, const char *src, size_t length)
void stringAppendString (char *str, size_t maxStrLength, const char *value)
void stringAppendStringLength (char *str, size_t maxStrLength, const char *value, size_t length)
void stringAppendInt (char *str, size_t maxStrLength, int value)
void stringAppendUInt32 (char *str, size_t maxStrLength, uint32_t value)
void stringAppendInt64 (char *str, size_t maxStrLength, int64_t value)
void stringAppendUInt64 (char *str, size_t maxStrLength, uint64_t value)
void stringAppendFloat (char *str, size_t maxStrLength, float value)
void stringAppendFloat (char *str, size_t maxStrLength, float value, int numDecimalPlaces)
void stringAppendDouble (char *str, size_t maxStrLength, double value)
void stringAppendDouble (char *str, size_t maxStrLength, double value, int numDecimalPlaces)
void stringAppendVoltage (char *str, size_t maxStrLength, float value)
void stringAppendCurrent (char *str, size_t maxStrLength, float value)
void stringAppendPower (char *str, size_t maxStrLength, float value)
void stringAppendDuration (char *str, size_t maxStrLength, float value)
void stringAppendLoad (char *str, size_t maxStrLength, float value)
uint32_t crc32 (const uint8_t *mem_block, size_t block_size)
uint8_t toBCD (uint8_t bin)
uint8_t fromBCD (uint8_t bcd)
float roundPrec (float a, float prec)
float floorPrec (float a, float prec)
float ceilPrec (float a, float prec)
bool isNaN (float x)
bool isNaN (double x)
bool isDigit (char ch)
bool isHexDigit (char ch)
bool isUperCaseLetter (char ch)
char toHexDigit (int num)
int fromHexDigit (char ch)
bool pointInsideRect (int xPoint, int yPoint, int xRect, int yRect, int wRect, int hRect)
void getParentDir (const char *path, char *parentDirPath)
bool parseMacAddress (const char *macAddressStr, size_t macAddressStrLength, uint8_t *macAddress)
bool parseIpAddress (const char *ipAddressStr, size_t ipAddressStrLength, uint32_t &ipAddress)
int getIpAddressPartA (uint32_t ipAddress)
void setIpAddressPartA (uint32_t *ipAddress, uint8_t value)
int getIpAddressPartB (uint32_t ipAddress)
void setIpAddressPartB (uint32_t *ipAddress, uint8_t value)
int getIpAddressPartC (uint32_t ipAddress)
void setIpAddressPartC (uint32_t *ipAddress, uint8_t value)
int getIpAddressPartD (uint32_t ipAddress)
void setIpAddressPartD (uint32_t *ipAddress, uint8_t value)
void ipAddressToArray (uint32_t ipAddress, uint8_t *ipAddressArray)
uint32_t arrayToIpAddress (uint8_t *ipAddressArray)
uint32_t getIpAddress (uint8_t a, uint8_t b, uint8_t c, uint8_t d)
void ipAddressToString (uint32_t ipAddress, char *ipAddressStr, size_t maxIpAddressStrLength)
void macAddressToString (const uint8_t *macAddress, char *macAddressStr)
void formatTimeZone (int16_t timeZone, char *text, int count)
bool parseTimeZone (const char *timeZoneStr, size_t timeZoneLength, int16_t &timeZone)
void replaceCharacter (char *str, char ch, char repl)
int strcicmp (char const *a, char const *b)
int strncicmp (char const *a, char const *b, int n)
bool isStringEmpty (char const *s)
bool startsWith (const char *str, const char *prefix)
bool startsWithNoCase (const char *str, const char *prefix)
bool endsWith (const char *str, const char *suffix)
bool endsWithNoCase (const char *str, const char *suffix)
void formatBytes (uint64_t bytes, char *text, int count)
void getFileName (const char *path, char *fileName, unsigned fileNameSize)
void getBaseFileName (const char *path, char *baseName, unsigned baseNameSize)
static bool compare_UNDEFINED_value (const Value &a, const Value &b)
static void UNDEFINED_value_to_text (const Value &value, char *text, int count)
static const char * UNDEFINED_value_type_name (const Value &value)
static bool compare_NULL_value (const Value &a, const Value &b)
static void NULL_value_to_text (const Value &value, char *text, int count)
static const char * NULL_value_type_name (const Value &value)
static bool compare_BOOLEAN_value (const Value &a, const Value &b)
static void BOOLEAN_value_to_text (const Value &value, char *text, int count)
static const char * BOOLEAN_value_type_name (const Value &value)
static bool compare_INT8_value (const Value &a, const Value &b)
static void INT8_value_to_text (const Value &value, char *text, int count)
static const char * INT8_value_type_name (const Value &value)
static bool compare_UINT8_value (const Value &a, const Value &b)
static void UINT8_value_to_text (const Value &value, char *text, int count)
static const char * UINT8_value_type_name (const Value &value)
static bool compare_INT16_value (const Value &a, const Value &b)
static void INT16_value_to_text (const Value &value, char *text, int count)
static const char * INT16_value_type_name (const Value &value)
static bool compare_UINT16_value (const Value &a, const Value &b)
static void UINT16_value_to_text (const Value &value, char *text, int count)
static const char * UINT16_value_type_name (const Value &value)
static bool compare_INT32_value (const Value &a, const Value &b)
static void INT32_value_to_text (const Value &value, char *text, int count)
static const char * INT32_value_type_name (const Value &value)
static bool compare_UINT32_value (const Value &a, const Value &b)
static void UINT32_value_to_text (const Value &value, char *text, int count)
static const char * UINT32_value_type_name (const Value &value)
static bool compare_INT64_value (const Value &a, const Value &b)
static void INT64_value_to_text (const Value &value, char *text, int count)
static const char * INT64_value_type_name (const Value &value)
static bool compare_UINT64_value (const Value &a, const Value &b)
static void UINT64_value_to_text (const Value &value, char *text, int count)
static const char * UINT64_value_type_name (const Value &value)
static bool compare_FLOAT_value (const Value &a, const Value &b)
static void FLOAT_value_to_text (const Value &value, char *text, int count)
static const char * FLOAT_value_type_name (const Value &value)
static bool compare_DOUBLE_value (const Value &a, const Value &b)
static void DOUBLE_value_to_text (const Value &value, char *text, int count)
static const char * DOUBLE_value_type_name (const Value &value)
static bool compare_STRING_value (const Value &a, const Value &b)
static void STRING_value_to_text (const Value &value, char *text, int count)
static const char * STRING_value_type_name (const Value &value)
static bool compare_STRING_ASSET_value (const Value &a, const Value &b)
static void STRING_ASSET_value_to_text (const Value &value, char *text, int count)
static const char * STRING_ASSET_value_type_name (const Value &value)
static bool compare_ARRAY_value (const Value &a, const Value &b)
static void ARRAY_value_to_text (const Value &value, char *text, int count)
static const char * ARRAY_value_type_name (const Value &value)
static bool compare_ARRAY_ASSET_value (const Value &a, const Value &b)
static void ARRAY_ASSET_value_to_text (const Value &value, char *text, int count)
static const char * ARRAY_ASSET_value_type_name (const Value &value)
static bool compare_ARRAY_REF_value (const Value &a, const Value &b)
static void ARRAY_REF_value_to_text (const Value &value, char *text, int count)
static const char * ARRAY_REF_value_type_name (const Value &value)
static bool compare_STRING_REF_value (const Value &a, const Value &b)
static void STRING_REF_value_to_text (const Value &value, char *text, int count)
static const char * STRING_REF_value_type_name (const Value &value)
static bool compare_BLOB_REF_value (const Value &a, const Value &b)
static void BLOB_REF_value_to_text (const Value &value, char *text, int count)
static const char * BLOB_REF_value_type_name (const Value &value)
static bool compare_STREAM_value (const Value &a, const Value &b)
static void STREAM_value_to_text (const Value &value, char *text, int count)
static const char * STREAM_value_type_name (const Value &value)
static bool compare_WIDGET_value (const Value &a, const Value &b)
static void WIDGET_value_to_text (const Value &value, char *text, int count)
static const char * WIDGET_value_type_name (const Value &value)
static bool compare_JSON_value (const Value &a, const Value &b)
static void JSON_value_to_text (const Value &value, char *text, int count)
static const char * JSON_value_type_name (const Value &value)
static bool compare_JSON_MEMBER_VALUE_value (const Value &a, const Value &b)
static void JSON_MEMBER_VALUE_value_to_text (const Value &value, char *text, int count)
static const char * JSON_MEMBER_VALUE_value_type_name (const Value &value)
static bool compare_EVENT_value (const Value &a, const Value &b)
static void EVENT_value_to_text (const Value &value, char *text, int count)
static const char * EVENT_value_type_name (const Value &value)
static const char * PROPERTY_REF_value_type_name (const Value &value)
static bool compare_PROPERTY_REF_value (const Value &a, const Value &b)
static void PROPERTY_REF_value_to_text (const Value &value, char *text, int count)
static bool compare_DATE_value (const Value &a, const Value &b)
static void DATE_value_to_text (const Value &value, char *text, int count)
static const char * DATE_value_type_name (const Value &value)
static bool compare_VERSIONED_STRING_value (const Value &a, const Value &b)
static void VERSIONED_STRING_value_to_text (const Value &value, char *text, int count)
static const char * VERSIONED_STRING_value_type_name (const Value &value)
static bool compare_VALUE_PTR_value (const Value &a, const Value &b)
static void VALUE_PTR_value_to_text (const Value &value, char *text, int count)
static const char * VALUE_PTR_value_type_name (const Value &value)
static bool compare_ARRAY_ELEMENT_VALUE_value (const Value &a, const Value &b)
static void ARRAY_ELEMENT_VALUE_value_to_text (const Value &value, char *text, int count)
static const char * ARRAY_ELEMENT_VALUE_value_type_name (const Value &value)
static bool compare_FLOW_OUTPUT_value (const Value &a, const Value &b)
static void FLOW_OUTPUT_value_to_text (const Value &value, char *text, int count)
static const char * FLOW_OUTPUT_value_type_name (const Value &value)
static bool compare_NATIVE_VARIABLE_value (const Value &a, const Value &b)
static void NATIVE_VARIABLE_value_to_text (const Value &value, char *text, int count)
static const char * NATIVE_VARIABLE_value_type_name (const Value &value)
static bool compare_ERROR_value (const Value &a, const Value &b)
static void ERROR_value_to_text (const Value &value, char *text, int count)
static const char * ERROR_value_type_name (const Value &value)
static bool compare_RANGE_value (const Value &a, const Value &b)
static void RANGE_value_to_text (const Value &value, char *text, int count)
static const char * RANGE_value_type_name (const Value &value)
static bool compare_POINTER_value (const Value &a, const Value &b)
static void POINTER_value_to_text (const Value &value, char *text, int count)
static const char * POINTER_value_type_name (const Value &value)
static bool compare_ENUM_value (const Value &a, const Value &b)
static void ENUM_value_to_text (const Value &value, char *text, int count)
static const char * ENUM_value_type_name (const Value &value)
static bool compare_YT_DATA_GET_VALUE_FUNCTION_POINTER_value (const Value &a, const Value &b)
static bool compare_IP_ADDRESS_value (const Value &a, const Value &b)
static void IP_ADDRESS_value_to_text (const Value &value, char *text, int count)
static const char * IP_ADDRESS_value_type_name (const Value &value)
static bool compare_TIME_ZONE_value (const Value &a, const Value &b)
static void TIME_ZONE_value_to_text (const Value &value, char *text, int count)
static const char * TIME_ZONE_value_type_name (const Value &value)
static void YT_DATA_GET_VALUE_FUNCTION_POINTER_value_to_text (const Value &value, char *text, int count)
static const char * YT_DATA_GET_VALUE_FUNCTION_POINTER_value_type_name (const Value &value)
bool assignValue (Value &dstValue, const Value &srcValue, uint32_t dstValueType)
uint16_t getPageIndexFromValue (const Value &value)
uint16_t getNumPagesFromValue (const Value &value)
Value MakeRangeValue (uint16_t from, uint16_t to)
Value MakeEnumDefinitionValue (uint8_t enumValue, uint8_t enumDefinition)
Value getVar (int16_t id)
void setVar (int16_t id, const Value &value)
Variables
bool g_isMainAssetsLoaded
Assets * g_mainAssets
bool g_mainAssetsUncompressed
Assets * g_externalAssets
uint8_t * DECOMPRESSED_ASSETS_START_ADDRESS
uint8_t * FLOW_TO_DEBUGGER_MESSAGE_BUFFER
uint8_t * ALLOC_BUFFER = 0
uint32_t ALLOC_BUFFER_SIZE = 0
const char * g_unitNames []
const Unit g_baseUnit []
const float g_unitFactor []
static const float FACTORS [] = { 1E-12F, 1E-9F, 1E-6F, 1E-3F, 1E0F, 1E3F, 1E6F, 1E9F, 1E12F }
EasingFuncType g_easingFuncs []
CompareValueFunction g_valueTypeCompareFunctions []
ValueToTextFunction g_valueTypeToTextFunctions []
ValueTypeNameFunction g_valueTypeNames []
ActionExecFunc g_actionExecFunctions [] = { 0 }
Function Documentation
alloc()
void * eez::alloc (size_t size, uint32_t id)
Definition at line 54 of file eez-flow.cpp.
{
    EEZ_UNUSED(id);
#if LVGL_VERSION_MAJOR >= 9
    return lv_malloc(size);
#else
    return lv_mem_alloc(size);
#endif
}
References EEZ_UNUSED.
Referenced by allocMemoryForDecompressedAssets(), eez::flow::beginAsyncExecution(), eez::flow::do_OPERATION_TYPE_STRING_FORMAT(), eez::flow::do_OPERATION_TYPE_STRING_SPLIT(), getAllocInfo(), eez::flow::initFlowState(), eez::flow::initGlobalVariables(), eez::flow::onAddToQueue(), and eez::flow::watchListAdd().
allocBuffer()
uint8_t * eez::allocBuffer (uint32_t size)
Definition at line 584 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
#if LVGL_VERSION_MAJOR >= 9
    return (uint8_t *)lv_malloc(size);
#else
    return (uint8_t *)lv_mem_alloc(size);
#endif
#elif defined(EEZ_DASHBOARD_API)
    return (uint8_t *)::malloc(size);
#else
    size = ((size + 1023) / 1024) * 1024;
    auto buffer = ALLOC_BUFFER;
    assert(ALLOC_BUFFER_SIZE > size);
    ALLOC_BUFFER += size;
    ALLOC_BUFFER_SIZE -= size;
    return buffer;
#endif
}
References ALLOC_BUFFER, and ALLOC_BUFFER_SIZE.
Referenced by initAssetsMemory(), and initOtherMemory().
allocMemoryForDecompressedAssets()
void eez::allocMemoryForDecompressedAssets (const uint8_t * assetsData, uint32_t assetsDataSize, uint8_t *& decompressedAssetsMemoryBuffer, uint32_t & decompressedAssetsMemoryBufferSize) static
Definition at line 315 of file eez-flow.cpp.
{
    EEZ_UNUSED(assetsDataSize);
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
    auto decompressedDataOffset = offsetof(Assets, settings);
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif
    auto header = (Header *)assetsData;
    assert (header->tag == HEADER_TAG_COMPRESSED);
    uint32_t decompressedSize = header->decompressedSize;
    decompressedAssetsMemoryBufferSize = decompressedDataOffset + decompressedSize;
    decompressedAssetsMemoryBuffer = (uint8_t *)eez::alloc(decompressedAssetsMemoryBufferSize, 0x587da194);
}
References alloc(), and EEZ_UNUSED.
Referenced by loadMainAssets().
ARRAY_ASSET_value_to_text()
void eez::ARRAY_ASSET_value_to_text (const Value & value, char * text, int count) static
Definition at line 2005 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    text[0] = 0;
}
References EEZ_UNUSED.
ARRAY_ASSET_value_type_name()
const char * eez::ARRAY_ASSET_value_type_name (const Value & value) static
Definition at line 2010 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "array";
}
References EEZ_UNUSED.
ARRAY_ELEMENT_VALUE_value_to_text()
void eez::ARRAY_ELEMENT_VALUE_value_to_text (const Value & value, char * text, int count) static
Definition at line 2160 of file eez-flow.cpp.
{
    value.getValue().toText(text, count);
}
ARRAY_ELEMENT_VALUE_value_type_name()
const char * eez::ARRAY_ELEMENT_VALUE_value_type_name (const Value & value) static
Definition at line 2163 of file eez-flow.cpp.
{
    auto value2 = value.getValue();
    return g_valueTypeNames[value2.type](value2);
}
References g_valueTypeNames.
ARRAY_REF_value_to_text()
void eez::ARRAY_REF_value_to_text (const Value & value, char * text, int count) static
Definition at line 2017 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    text[0] = 0;
}
References EEZ_UNUSED.
ARRAY_REF_value_type_name()
const char * eez::ARRAY_REF_value_type_name (const Value & value) static
Definition at line 2022 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "array";
}
References EEZ_UNUSED.
ARRAY_value_to_text()
void eez::ARRAY_value_to_text (const Value & value, char * text, int count) static
Definition at line 1993 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    text[0] = 0;
}
References EEZ_UNUSED.
ARRAY_value_type_name()
const char * eez::ARRAY_value_type_name (const Value & value) static
Definition at line 1998 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "array";
}
References EEZ_UNUSED.
arrayToIpAddress()
uint32_t eez::arrayToIpAddress (uint8_t * ipAddressArray)
Definition at line 1245 of file eez-flow.cpp.
{
    return getIpAddress(ipAddressArray[0], ipAddressArray[1], ipAddressArray[2], ipAddressArray[3]);
}
References getIpAddress().
Referenced by parseIpAddress().
assignValue()
bool eez::assignValue (Value & dstValue, const Value & srcValue, uint32_t dstValueType)
Definition at line 2348 of file eez-flow.cpp.
{
    if (dstValueType == VALUE_TYPE_BOOLEAN) {
        dstValue = Value(srcValue.toBool(), VALUE_TYPE_BOOLEAN);
    } else if (Value::isInt32OrLess(dstValueType)) {
        dstValue = Value((int)srcValue.toInt32(), (ValueType)dstValueType);
    } else if (dstValueType == VALUE_TYPE_FLOAT) {
        dstValue = Value(srcValue.toFloat(), VALUE_TYPE_FLOAT);
    } else if (dstValueType == VALUE_TYPE_DOUBLE) {
        dstValue = Value(srcValue.toDouble(), VALUE_TYPE_DOUBLE);
    } else if (dstValueType == VALUE_TYPE_STRING) {
        dstValue = srcValue.toString(0x30a91156);
#if defined(EEZ_DASHBOARD_API)
    } else if (dstValueType == VALUE_TYPE_JSON) {
        if (srcValue.isJson()) {
            dstValue = srcValue;
        } else {
            dstValue = flow::convertToJson(&srcValue);
        }
    } else if (srcValue.isJson()) {
        if (dstValueType == VALUE_TYPE_JSON) {
            dstValue = srcValue;
        }  else {
            dstValue = flow::convertFromJson(srcValue.getInt(), dstValueType);
        }
#endif
    } else if (dstValue.isBoolean()) {
        dstValue.int32Value = srcValue.toBool();
    } else if (dstValue.isInt32OrLess()) {
        dstValue.int32Value = srcValue.toInt32();
    } else if (dstValue.isFloat()) {
        dstValue.floatValue = srcValue.toFloat();
    } else if (dstValue.isDouble()) {
        dstValue.doubleValue = srcValue.toDouble();
    } else if (dstValue.isString()) {
        dstValue = srcValue.toString(0x30a91156);
    } else {
        dstValue = srcValue;
    }
    return true;
}
BLOB_REF_value_to_text()
void eez::BLOB_REF_value_to_text (const Value & value, char * text, int count) static
Definition at line 2039 of file eez-flow.cpp.
{
    snprintf(text, count, "blob (size=%d)", value.getInt());
}
BLOB_REF_value_type_name()
const char * eez::BLOB_REF_value_type_name (const Value & value) static
Definition at line 2042 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "blob";
}
References EEZ_UNUSED.
BOOLEAN_value_to_text()
void eez::BOOLEAN_value_to_text (const Value & value, char * text, int count) static
Definition at line 1705 of file eez-flow.cpp.
{
    if (value.getInt()) {
        stringCopy(text, count, "true");
    } else {
        stringCopy(text, count, "false");
    }
}
References stringCopy().
BOOLEAN_value_type_name()
const char * eez::BOOLEAN_value_type_name (const Value & value) static
Definition at line 1712 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "boolean";
}
References EEZ_UNUSED.
ceilPrec()
float eez::ceilPrec (float a, float prec)
Definition at line 1095 of file eez-flow.cpp.
{
    float r = 1 / prec;
    return ceilf(a * r) / r;
}
clamp()
float eez::clamp (float x, float min, float max)
Definition at line 971 of file eez-flow.cpp.
{
    if (x < min) {
        return min;
    }
    if (x > max) {
        return max;
    }
    return x;
}
compare_ARRAY_ASSET_value()
bool eez::compare_ARRAY_ASSET_value (const Value & a, const Value & b) static
Definition at line 2002 of file eez-flow.cpp.
{
    return a.type == b.type && a.int32Value == b.int32Value;
}
compare_ARRAY_ELEMENT_VALUE_value()
bool eez::compare_ARRAY_ELEMENT_VALUE_value (const Value & a, const Value & b) static
Definition at line 2157 of file eez-flow.cpp.
{
    return a.getValue() == b.getValue();
}
compare_ARRAY_REF_value()
bool eez::compare_ARRAY_REF_value (const Value & a, const Value & b) static
Definition at line 2014 of file eez-flow.cpp.
{
    return a.type == b.type && a.refValue == b.refValue;
}
compare_ARRAY_value()
bool eez::compare_ARRAY_value (const Value & a, const Value & b) static
Definition at line 1990 of file eez-flow.cpp.
{
    return a.type == b.type && a.arrayValue == b.arrayValue;
}
compare_BLOB_REF_value()
bool eez::compare_BLOB_REF_value (const Value & a, const Value & b) static
Definition at line 2036 of file eez-flow.cpp.
{
    return a.type == b.type && a.refValue == b.refValue;
}
compare_BOOLEAN_value()
bool eez::compare_BOOLEAN_value (const Value & a, const Value & b) static
Definition at line 1702 of file eez-flow.cpp.
{
    return a.type == b.type && a.getInt() == b.getInt();
}
compare_DATE_value()
bool eez::compare_DATE_value (const Value & a, const Value & b) static
Definition at line 2115 of file eez-flow.cpp.
{
    return a.type == b.type && a.doubleValue == b.doubleValue;
}
compare_DOUBLE_value()
bool eez::compare_DOUBLE_value (const Value & a, const Value & b) static
Definition at line 1875 of file eez-flow.cpp.
{
    return a.type == b.type && a.getUnit() == b.getUnit() && a.getDouble() == b.getDouble() && a.getOptions() == b.getOptions();
}
compare_ENUM_value()
bool eez::compare_ENUM_value (const Value & a, const Value & b) static
Definition at line 2271 of file eez-flow.cpp.
{
    EEZ_UNUSED(a);
    EEZ_UNUSED(b);
    return false;
}
References EEZ_UNUSED.
compare_ERROR_value()
bool eez::compare_ERROR_value (const Value & a, const Value & b) static
Definition at line 2210 of file eez-flow.cpp.
{
    EEZ_UNUSED(a);
    EEZ_UNUSED(b);
    return false;
}
References EEZ_UNUSED.
compare_EVENT_value()
bool eez::compare_EVENT_value (const Value & a, const Value & b) static
Definition at line 2094 of file eez-flow.cpp.
{
    return a.type == b.type && a.getVoidPointer() == b.getVoidPointer();
}
compare_FLOAT_value()
bool eez::compare_FLOAT_value (const Value & a, const Value & b) static
Definition at line 1796 of file eez-flow.cpp.
{
    return a.type == b.type && a.getUnit() == b.getUnit() && a.getFloat() == b.getFloat() && a.getOptions() == b.getOptions();
}
compare_FLOW_OUTPUT_value()
bool eez::compare_FLOW_OUTPUT_value (const Value & a, const Value & b) static
Definition at line 2167 of file eez-flow.cpp.
{
    return a.type == b.type && a.getUInt16() == b.getUInt16();
}
compare_INT16_value()
bool eez::compare_INT16_value (const Value & a, const Value & b) static
Definition at line 1736 of file eez-flow.cpp.
{
    return a.type == b.type && a.getInt16() == b.getInt16();
}
compare_INT32_value()
bool eez::compare_INT32_value (const Value & a, const Value & b) static
Definition at line 1756 of file eez-flow.cpp.
{
    return a.type == b.type && a.getInt32() == b.getInt32();
}
compare_INT64_value()
bool eez::compare_INT64_value (const Value & a, const Value & b) static
Definition at line 1776 of file eez-flow.cpp.
{
    return a.type == b.type && a.getInt64() == b.getInt64();
}
compare_INT8_value()
bool eez::compare_INT8_value (const Value & a, const Value & b) static
Definition at line 1716 of file eez-flow.cpp.
{
    return a.type == b.type && a.getInt8() == b.getInt8();
}
compare_IP_ADDRESS_value()
bool eez::compare_IP_ADDRESS_value (const Value & a, const Value & b) static
Definition at line 2289 of file eez-flow.cpp.
{
    return a.type == b.type && a.getUInt32() == b.getUInt32();
}
compare_JSON_MEMBER_VALUE_value()
bool eez::compare_JSON_MEMBER_VALUE_value (const Value & a, const Value & b) static
Definition at line 2084 of file eez-flow.cpp.
{
    return a.getValue() == b.getValue();
}
compare_JSON_value()
bool eez::compare_JSON_value (const Value & a, const Value & b) static
Definition at line 2074 of file eez-flow.cpp.
{
    return a.type == b.type && a.int32Value == b.int32Value;
}
compare_NATIVE_VARIABLE_value()
bool eez::compare_NATIVE_VARIABLE_value (const Value & a, const Value & b) static
Definition at line 2195 of file eez-flow.cpp.
{
    EEZ_UNUSED(a);
    EEZ_UNUSED(b);
    return false;
}
References EEZ_UNUSED.
compare_NULL_value()
bool eez::compare_NULL_value (const Value & a, const Value & b) static
Definition at line 1689 of file eez-flow.cpp.
{
    EEZ_UNUSED(a);
    return b.type == VALUE_TYPE_NULL;
}
References EEZ_UNUSED.
compare_POINTER_value()
bool eez::compare_POINTER_value (const Value & a, const Value & b) static
Definition at line 2236 of file eez-flow.cpp.
{
    return a.type == b.type && a.getVoidPointer() == b.getVoidPointer();
}
compare_PROPERTY_REF_value()
bool eez::compare_PROPERTY_REF_value (const Value & a, const Value & b) static
Definition at line 2108 of file eez-flow.cpp.
{
    return a.type == b.type && a.refValue == b.refValue;
}
compare_RANGE_value()
bool eez::compare_RANGE_value (const Value & a, const Value & b) static
Definition at line 2224 of file eez-flow.cpp.
{
    return a.type == b.type && a.getUInt32() == b.getUInt32();
}
compare_STREAM_value()
bool eez::compare_STREAM_value (const Value & a, const Value & b) static
Definition at line 2046 of file eez-flow.cpp.
{
    return a.type == b.type && a.int32Value == b.int32Value;
}
compare_STRING_ASSET_value()
bool eez::compare_STRING_ASSET_value (const Value & a, const Value & b) static
Definition at line 1980 of file eez-flow.cpp.
{
    return compare_STRING_value(a, b);
}
References compare_STRING_value().
compare_STRING_REF_value()
bool eez::compare_STRING_REF_value (const Value & a, const Value & b) static
Definition at line 2026 of file eez-flow.cpp.
{
    return compare_STRING_value(a, b);
}
References compare_STRING_value().
compare_STRING_value()
bool eez::compare_STRING_value (const Value & a, const Value & b) static
Definition at line 1954 of file eez-flow.cpp.
{
    if (!b.isString()) {
        return false;
    }
    const char *astr = a.getString();
    const char *bstr = b.getString();
    if (!astr && !bstr) {
        return true;
    }
    if ((!astr && bstr) || (astr && !bstr)) {
        return false;
    }
    return strcmp(astr, bstr) == 0;
}
Referenced by compare_STRING_ASSET_value(), and compare_STRING_REF_value().
compare_TIME_ZONE_value()
bool eez::compare_TIME_ZONE_value (const Value & a, const Value & b) static
Definition at line 2299 of file eez-flow.cpp.
{
    return a.type == b.type && a.getInt16() == b.getInt16();
}
compare_UINT16_value()
bool eez::compare_UINT16_value (const Value & a, const Value & b) static
Definition at line 1746 of file eez-flow.cpp.
{
    return a.type == b.type && a.getUInt16() == b.getUInt16();
}
compare_UINT32_value()
bool eez::compare_UINT32_value (const Value & a, const Value & b) static
Definition at line 1766 of file eez-flow.cpp.
{
    return a.type == b.type && a.getUInt32() == b.getUInt32();
}
compare_UINT64_value()
bool eez::compare_UINT64_value (const Value & a, const Value & b) static
Definition at line 1786 of file eez-flow.cpp.
{
    return a.type == b.type && a.getUInt64() == b.getUInt64();
}
compare_UINT8_value()
bool eez::compare_UINT8_value (const Value & a, const Value & b) static
Definition at line 1726 of file eez-flow.cpp.
{
    return a.type == b.type && a.getUInt8() == b.getUInt8();
}
compare_UNDEFINED_value()
bool eez::compare_UNDEFINED_value (const Value & a, const Value & b) static
Definition at line 1677 of file eez-flow.cpp.
{
    return b.type == VALUE_TYPE_UNDEFINED && a.int32Value == b.int32Value;
}
compare_VALUE_PTR_value()
bool eez::compare_VALUE_PTR_value (const Value & a, const Value & b) static
Definition at line 2140 of file eez-flow.cpp.
{
    return a.type == b.type && (a.pValueValue == b.pValueValue || (a.pValueValue && b.pValueValue && *a.pValueValue == *b.pValueValue));
}
compare_VERSIONED_STRING_value()
bool eez::compare_VERSIONED_STRING_value (const Value & a, const Value & b) static
Definition at line 2125 of file eez-flow.cpp.
{
    return a.type == b.type && a.unit == b.unit;
}
compare_WIDGET_value()
bool eez::compare_WIDGET_value (const Value & a, const Value & b) static
Definition at line 2056 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
    return a.type == b.type && a.getVoidPointer() == b.getVoidPointer();
#else
    return a.type == b.type && a.int32Value == b.int32Value;
#endif
}
compare_YT_DATA_GET_VALUE_FUNCTION_POINTER_value()
bool eez::compare_YT_DATA_GET_VALUE_FUNCTION_POINTER_value (const Value & a, const Value & b) static
Definition at line 2286 of file eez-flow.cpp.
{
    return a.type == b.type && a.getUInt32() == b.getUInt32();
}
crc32()
uint32_t eez::crc32 (const uint8_t * mem_block, size_t block_size)
Definition at line 1068 of file eez-flow.cpp.
{
    uint32_t crc = 0xFFFFFFFF;
    for (size_t i = 0; i < block_size; ++i) {
        uint32_t byte = mem_block[i];
        crc = crc ^ byte;
        for (int j = 0; j < 8; ++j) {
            uint32_t mask = -((int32_t)crc & 1);
            crc = (crc >> 1) ^ (0xEDB88320 & mask);
        }
    }
    return ~crc;
}
DATE_value_to_text()
void eez::DATE_value_to_text (const Value & value, char * text, int count) static
Definition at line 2118 of file eez-flow.cpp.
{
    flow::date::toLocaleString((flow::date::Date)value.getDouble(), text, count);
}
References eez::flow::date::toLocaleString().
DATE_value_type_name()
const char * eez::DATE_value_type_name (const Value & value) static
Definition at line 2121 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "date";
}
References EEZ_UNUSED.
decompressAssetsData()
bool eez::decompressAssetsData (const uint8_t * assetsData, uint32_t assetsDataSize, Assets * decompressedAssets, uint32_t maxDecompressedAssetsSize, int * err)
Definition at line 260 of file eez-flow.cpp.
{
#if EEZ_FOR_LVGL_LZ4_OPTION
    uint32_t compressedDataOffset;
    uint32_t decompressedSize;
    auto header = (Header *)assetsData;
    if (header->tag == HEADER_TAG_COMPRESSED) {
        decompressedAssets->projectMajorVersion = header->projectMajorVersion;
        decompressedAssets->projectMinorVersion = header->projectMinorVersion;
        decompressedAssets->assetsType = header->assetsType;
        compressedDataOffset = sizeof(Header);
        decompressedSize = header->decompressedSize;
    } else {
        decompressedAssets->projectMajorVersion = PROJECT_VERSION_V2;
        decompressedAssets->projectMinorVersion = 0;
        decompressedAssets->assetsType = ASSETS_TYPE_RESOURCE;
        compressedDataOffset = 4;
        decompressedSize = header->tag;
    }
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
    auto decompressedDataOffset = offsetof(Assets, settings);
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif
    if (decompressedDataOffset + decompressedSize > maxDecompressedAssetsSize) {
        if (err) {
            *err = SCPI_ERROR_OUT_OF_DEVICE_MEMORY;
        }
        return false;
    }
    int compressedSize = assetsDataSize - compressedDataOffset;
    int decompressResult = LZ4_decompress_safe(
        (const char *)(assetsData + compressedDataOffset),
        (char *)decompressedAssets + decompressedDataOffset,
        compressedSize,
        decompressedSize
    );
    if (decompressResult != (int)decompressedSize) {
        if (err) {
            *err = SCPI_ERROR_INVALID_BLOCK_DATA;
        }
        return false;
    }
    return true;
#else
    EEZ_UNUSED(assetsData);
    EEZ_UNUSED(assetsDataSize);
    EEZ_UNUSED(decompressedAssets);
    EEZ_UNUSED(maxDecompressedAssetsSize);
    *err = -1;
    return false;
#endif
}
References EEZ_UNUSED, SCPI_ERROR_INVALID_BLOCK_DATA, and SCPI_ERROR_OUT_OF_DEVICE_MEMORY.
Referenced by loadMainAssets().
DOUBLE_value_to_text()
void eez::DOUBLE_value_to_text (const Value & value, char * text, int count) static
Definition at line 1878 of file eez-flow.cpp.
{
    text[0] = 0;
    double doubleValue = value.getDouble();
#if defined(INFINITY_SYMBOL)
    if (isinf(doubleValue)) {
        snprintf(text, count, INFINITY_SYMBOL);
        return;
    }
#endif
    Unit unit = value.getUnit();
    bool appendDotZero = unit == UNIT_VOLT || unit == UNIT_VOLT_PP || unit == UNIT_AMPER || unit == UNIT_AMPER_PP || unit == UNIT_WATT;
    uint16_t options = value.getOptions();
    bool fixedDecimals = (options & FLOAT_OPTIONS_FIXED_DECIMALS) != 0;
    if (doubleValue != 0) {
        if (!fixedDecimals) {
            unit = findDerivedUnit(fabs(doubleValue), unit);
            doubleValue /= getUnitFactor(unit);
        }
    } else {
        doubleValue = 0;
    }
    if (!isNaN(doubleValue)) {
        if ((value.getOptions() & FLOAT_OPTIONS_LESS_THEN) != 0) {
            stringAppendString(text, count, "< ");
            appendDotZero = false;
        }
        if (fixedDecimals) {
            stringAppendFloat(text, count, doubleValue, FLOAT_OPTIONS_GET_NUM_FIXED_DECIMALS(options));
        } else {
            if (unit == UNIT_WATT || unit == UNIT_MILLI_WATT) {
                stringAppendDouble(text, count, doubleValue, 2);
            } else {
                stringAppendDouble(text, count, doubleValue);
            }
            int n = strlen(text);
            int decimalPointIndex;
            for (decimalPointIndex = 0; decimalPointIndex < n; ++decimalPointIndex) {
                if (text[decimalPointIndex] == '.') {
                    break;
                }
            }
            if (decimalPointIndex == n) {
                if (appendDotZero) {
                    stringAppendString(text, count, ".0");
                }
            } else if (decimalPointIndex == n - 1) {
                if (appendDotZero) {
                    stringAppendString(text, count, "0");
                } else {
                    text[decimalPointIndex] = 0;
                }
            } else {
                if (appendDotZero) {
                    for (int j = n - 1; j > decimalPointIndex + 1 && text[j] == '0'; j--) {
                        text[j] = 0;
                    }
                } else {
                    for (int j = n - 1; j >= decimalPointIndex && (text[j] == '0' || text[j] == '.'); j--) {
                        text[j] = 0;
                    }
                }
            }
        }
        const char *unitName = getUnitName(unit);
        if (unitName && *unitName) {
            stringAppendString(text, count, " ");
            stringAppendString(text, count, unitName);
        }
    } else {
        text[0] = 0;
    }
}
References findDerivedUnit(), getUnitFactor(), isNaN(), stringAppendDouble(), stringAppendFloat(), and stringAppendString().
DOUBLE_value_type_name()
const char * eez::DOUBLE_value_type_name (const Value & value) static
Definition at line 1950 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "double";
}
References EEZ_UNUSED.
endsWith()
bool eez::endsWith (const char * str, const char * suffix)
Definition at line 1405 of file eez-flow.cpp.
{
    if (!str || !suffix)
        return false;
    size_t strLen = strlen(str);
    size_t suffixLen = strlen(suffix);
    if (suffixLen > strLen)
        return false;
    return strncmp(str + strLen - suffixLen, suffix, suffixLen) == 0;
}
endsWithNoCase()
bool eez::endsWithNoCase (const char * str, const char * suffix)
Definition at line 1414 of file eez-flow.cpp.
{
    if (!str || !suffix)
        return false;
    size_t strLen = strlen(str);
    size_t suffixLen = strlen(suffix);
    if (suffixLen > strLen)
        return false;
    return strncicmp(str + strLen - suffixLen, suffix, suffixLen) == 0;
}
References strncicmp().
ENUM_value_to_text()
void eez::ENUM_value_to_text (const Value & value, char * text, int count) static
Definition at line 2276 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    *text = 0;
}
References EEZ_UNUSED.
ENUM_value_type_name()
const char * eez::ENUM_value_type_name (const Value & value) static
Definition at line 2281 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "internal";
}
References EEZ_UNUSED.
ERROR_value_to_text()
void eez::ERROR_value_to_text (const Value & value, char * text, int count) static
Definition at line 2215 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    *text = 0;
}
References EEZ_UNUSED.
ERROR_value_type_name()
const char * eez::ERROR_value_type_name (const Value & value) static
Definition at line 2220 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "error";
}
References EEZ_UNUSED.
EVENT_value_to_text()
void eez::EVENT_value_to_text (const Value & value, char * text, int count) static
Definition at line 2097 of file eez-flow.cpp.
{
    snprintf(text, count, "event (%p)", value.getVoidPointer());
}
EVENT_value_type_name()
const char * eez::EVENT_value_type_name (const Value & value) static
Definition at line 2100 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "event";
}
References EEZ_UNUSED.
executeActionFunction()
void eez::executeActionFunction (int actionId)
Definition at line 30 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
    eez::flow::executeLvglActionHook(actionId - 1);
#else
    g_actionExecFunctions[actionId]();
#endif
}
References executeActionFunction(), eez::flow::executeLvglActionHook, and g_actionExecFunctions.
Referenced by executeActionFunction(), and eez::flow::executeCallAction().
findDerivedUnit()
Unit eez::findDerivedUnit (float value, Unit unit)
Definition at line 844 of file eez-flow.cpp.
{
    Unit result;
    for (int factorIndex = 1; ; factorIndex++) {
        float factor = FACTORS[factorIndex];
        if (factor > 1.0F) {
            break;
        }
        if (value < factor) {
            result = getDerivedUnit(unit, FACTORS[factorIndex - 1]);
            if (result != UNIT_UNKNOWN) {
                return result;
            }
        }
    }
    for (int factorIndex = sizeof(FACTORS) / sizeof(float) - 1; factorIndex >= 0; factorIndex--) {
        float factor = FACTORS[factorIndex];
        if (factor == 1.0F) {
            break;
        }
        if (value >= factor) {
            result = getDerivedUnit(unit, factor);
            if (result != UNIT_UNKNOWN) {
                return result;
            }
        }
    }
    return unit;
}
References FACTORS, and getDerivedUnit().
Referenced by DOUBLE_value_to_text(), and FLOAT_value_to_text().
fixOffsets()
void eez::fixOffsets (Assets * assets)
References assets.
FLOAT_value_to_text()
void eez::FLOAT_value_to_text (const Value & value, char * text, int count) static
Definition at line 1799 of file eez-flow.cpp.
{
    text[0] = 0;
    float floatValue = value.getFloat();
#if defined(INFINITY_SYMBOL)
    if (isinf(floatValue)) {
        snprintf(text, count, INFINITY_SYMBOL);
        return;
    }
#endif
    Unit unit = value.getUnit();
    bool appendDotZero = unit == UNIT_VOLT || unit == UNIT_VOLT_PP || unit == UNIT_AMPER || unit == UNIT_AMPER_PP || unit == UNIT_WATT;
    uint16_t options = value.getOptions();
    bool fixedDecimals = (options & FLOAT_OPTIONS_FIXED_DECIMALS) != 0;
    if (floatValue != 0) {
        if (!fixedDecimals) {
            unit = findDerivedUnit(floatValue, unit);
            floatValue /= getUnitFactor(unit);
        }
    } else {
        floatValue = 0;
    }
    if (!isNaN(floatValue)) {
        if ((value.getOptions() & FLOAT_OPTIONS_LESS_THEN) != 0) {
            stringAppendString(text, count, "< ");
            appendDotZero = false;
        }
        if (fixedDecimals) {
            stringAppendFloat(text, count, floatValue, FLOAT_OPTIONS_GET_NUM_FIXED_DECIMALS(options));
        } else {
            if (unit == UNIT_WATT || unit == UNIT_MILLI_WATT) {
                stringAppendFloat(text, count, floatValue, 2);
            } else {
                stringAppendFloat(text, count, floatValue);
            }
            int n = strlen(text);
            int decimalPointIndex;
            for (decimalPointIndex = 0; decimalPointIndex < n; ++decimalPointIndex) {
                if (text[decimalPointIndex] == '.') {
                    break;
                }
            }
            if (decimalPointIndex == n) {
                if (appendDotZero) {
                    stringAppendString(text, count, ".0");
                }
            } else if (decimalPointIndex == n - 1) {
                if (appendDotZero) {
                    stringAppendString(text, count, "0");
                } else {
                    text[decimalPointIndex] = 0;
                }
            } else {
                if (appendDotZero) {
                    for (int j = n - 1; j > decimalPointIndex + 1 && text[j] == '0'; j--) {
                        text[j] = 0;
                    }
                } else {
                    for (int j = n - 1; j >= decimalPointIndex && (text[j] == '0' || text[j] == '.'); j--) {
                        text[j] = 0;
                    }
                }
            }
        }
        const char *unitName = getUnitName(unit);
        if (unitName && *unitName) {
            stringAppendString(text, count, " ");
            stringAppendString(text, count, unitName);
        }
    } else {
        text[0] = 0;
    }
}
References findDerivedUnit(), getUnitFactor(), isNaN(), stringAppendFloat(), and stringAppendString().
FLOAT_value_type_name()
const char * eez::FLOAT_value_type_name (const Value & value) static
Definition at line 1871 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "float";
}
References EEZ_UNUSED.
floorPrec()
float eez::floorPrec (float a, float prec)
Definition at line 1091 of file eez-flow.cpp.
{
    float r = 1 / prec;
    return floorf(a * r) / r;
}
FLOW_OUTPUT_value_to_text()
void eez::FLOW_OUTPUT_value_to_text (const Value & value, char * text, int count) static
Definition at line 2170 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    text[0] = 0;
}
References EEZ_UNUSED.
FLOW_OUTPUT_value_type_name()
const char * eez::FLOW_OUTPUT_value_type_name (const Value & value) static
Definition at line 2175 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "internal";
}
References EEZ_UNUSED.
formatBytes()
void eez::formatBytes (uint64_t bytes, char * text, int count)
Definition at line 1423 of file eez-flow.cpp.
{
    if (bytes == 0) {
        stringCopy(text, count, "0 Bytes");
    } else {
        double c = 1024.0;
        const char *e[] = { "Bytes", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB" };
        uint64_t f = (uint64_t)floor(log((double)bytes) / log(c));
        double g = round((bytes / pow(c, (double)f)) * 100) / 100;
        snprintf(text, count, "%g %s", g, e[f]);
    }
}
References stringCopy().
formatTimeZone()
void eez::formatTimeZone (int16_t timeZone, char * text, int count)
Definition at line 1268 of file eez-flow.cpp.
{
    if (timeZone == 0) {
        stringCopy(text, count, "GMT");
    } else {
        char sign;
        int16_t value;
        if (timeZone > 0) {
            sign = '+';
            value = timeZone;
        } else {
            sign = '-';
            value = -timeZone;
        }
        snprintf(text, count, "%c%02d:%02d GMT", sign, value / 100, value % 100);
    }
}
References stringCopy().
Referenced by TIME_ZONE_value_to_text().
free()
void eez::free (void * ptr)
Definition at line 62 of file eez-flow.cpp.
                     {
#if LVGL_VERSION_MAJOR >= 9
    lv_free(ptr);
#else
    lv_mem_free(ptr);
#endif
}
Referenced by eez::flow::do_OPERATION_TYPE_STRING_FORMAT(), eez::flow::do_OPERATION_TYPE_STRING_SPLIT(), eez::flow::endAsyncExecution(), eez::flow::freeFlowState(), getAllocInfo(), eez::flow::onAddToQueue(), unloadExternalAssets(), and eez::flow::watchListRemove().
freeObject()
template<typename T> void eez::freeObject (T * ptr)
Definition at line 69 of file eez-flow.cpp.
{
    ptr->~T();
#if LVGL_VERSION_MAJOR >= 9
    lv_free(ptr);
#else
    lv_mem_free(ptr);
#endif
}
fromBCD()
uint8_t eez::fromBCD (uint8_t bcd)
Definition at line 1084 of file eez-flow.cpp.
{
    return ((bcd >> 4) & 0xF) * 10 + (bcd & 0xF);
}
fromHexDigit()
int eez::fromHexDigit (char ch)
Definition at line 1121 of file eez-flow.cpp.
{
    if (ch >= '0' && ch <= '9') {
        return ch - '0';
    }
    if (ch >= 'a' && ch <= 'f') {
        return 10 + (ch - 'a');
    }
    return 10 + (ch - 'A');
}
Referenced by parseMacAddress().
getAllocInfo()
void eez::getAllocInfo (uint32_t & free, uint32_t & alloc)
Definition at line 77 of file eez-flow.cpp.
{
    lv_mem_monitor_t mon;
    lv_mem_monitor(&mon);
    free = mon.free_size;
    alloc = mon.total_size - mon.free_size;
}
References alloc(), and free().
Referenced by eez::flow::onAddToQueue().
getBaseFileName()
void eez::getBaseFileName (const char * path, char * baseName, unsigned baseNameSize)
Definition at line 1449 of file eez-flow.cpp.
{
    const char *a = strrchr(path, '/');
    if (a) {
         a++;
    } else {
        a = path;
    }
    const char *b = strrchr(path, '.');
    if (!b || !(b >= a)) {
        b = path + strlen(path);
    }
    unsigned n = b - a;
    n = MIN(baseNameSize - 1, n);
    if (n > 0) {
        memcpy(baseName, a, n);
    }
    baseName[n] = 0;
}
getBaseUnit()
Unit eez::getBaseUnit (Unit unit)
Definition at line 820 of file eez-flow.cpp.
{
    if (unit == UNIT_UNKNOWN) {
        return UNIT_UNKNOWN;
    }
    return g_baseUnit[unit];
}
References g_baseUnit.
getBiggestUnit()
Unit eez::getBiggestUnit (Unit unit, float max)
Definition at line 888 of file eez-flow.cpp.
{
    for (int factorIndex = sizeof(FACTORS) / sizeof(float) - 1; factorIndex >= 0; factorIndex--) {
        float factor = FACTORS[factorIndex];
        if (max >= factor) {
            auto result = getDerivedUnit(unit, factor);
            if (result != UNIT_UNKNOWN) {
                return result;
            }
        }
    }
    return UNIT_UNKNOWN;
}
References FACTORS, and getDerivedUnit().
getColors()
const uint16_t * eez::getColors ()
Definition at line 456 of file eez-flow.cpp.
{
    return static_cast<uint16_t *>(g_mainAssets->colorsDefinition->colors.items);
}
References g_mainAssets.
getDerivedUnit()
Unit eez::getDerivedUnit (Unit unit, float factor) static
Definition at line 832 of file eez-flow.cpp.
{
    if (unit == UNIT_UNKNOWN) {
        return UNIT_UNKNOWN;
    }
    for (size_t i = 0; i < sizeof(g_baseUnit) / sizeof(Unit); i++) {
        if (g_baseUnit[i] == g_baseUnit[unit] && g_unitFactor[i] == factor) {
            return (Unit)i;
        }
    }
    return UNIT_UNKNOWN;
}
References g_baseUnit, and g_unitFactor.
Referenced by findDerivedUnit(), getBiggestUnit(), getSmallerUnit(), and getSmallestUnit().
getExternalAssetsMainPageId()
int eez::getExternalAssetsMainPageId ()
Definition at line 459 of file eez-flow.cpp.
{
    return -1;
}
getFileName()
void eez::getFileName (const char * path, char * fileName, unsigned fileNameSize)
Definition at line 1434 of file eez-flow.cpp.
{
    const char *a = strrchr(path, '/');
    if (a) {
         a++;
    } else {
        a = path;
    }
    const char *b = path + strlen(path);
    unsigned n = b - a;
    n = MIN(fileNameSize - 1, n);
    if (n > 0) {
        memcpy(fileName, a, n);
    }
    fileName[n] = 0;
}
getIpAddress()
uint32_t eez::getIpAddress (uint8_t a, uint8_t b, uint8_t c, uint8_t d)
Definition at line 1248 of file eez-flow.cpp.
{
    uint32_t ipAddress;
    setIpAddressPartA(&ipAddress, a);
    setIpAddressPartB(&ipAddress, b);
    setIpAddressPartC(&ipAddress, c);
    setIpAddressPartD(&ipAddress, d);
    return ipAddress;
}
References setIpAddressPartA(), setIpAddressPartB(), setIpAddressPartC(), and setIpAddressPartD().
Referenced by arrayToIpAddress().
getIpAddressPartA()
int eez::getIpAddressPartA (uint32_t ipAddress)
Definition at line 1215 of file eez-flow.cpp.
{
    return ((uint8_t *)&ipAddress)[0];
}
Referenced by ipAddressToArray(), and ipAddressToString().
getIpAddressPartB()
int eez::getIpAddressPartB (uint32_t ipAddress)
Definition at line 1221 of file eez-flow.cpp.
{
    return ((uint8_t *)&ipAddress)[1];
}
Referenced by ipAddressToArray(), and ipAddressToString().
getIpAddressPartC()
int eez::getIpAddressPartC (uint32_t ipAddress)
Definition at line 1227 of file eez-flow.cpp.
{
    return ((uint8_t *)&ipAddress)[2];
}
Referenced by ipAddressToArray(), and ipAddressToString().
getIpAddressPartD()
int eez::getIpAddressPartD (uint32_t ipAddress)
Definition at line 1233 of file eez-flow.cpp.
{
    return ((uint8_t *)&ipAddress)[3];
}
Referenced by ipAddressToArray(), and ipAddressToString().
getNumPagesFromValue()
uint16_t eez::getNumPagesFromValue (const Value & value)
Definition at line 2391 of file eez-flow.cpp.
{
    return value.getSecondUInt16();
}
getPageIndexFromValue()
uint16_t eez::getPageIndexFromValue (const Value & value)
Definition at line 2388 of file eez-flow.cpp.
{
    return value.getFirstUInt16();
}
getParentDir()
void eez::getParentDir (const char * path, char * parentDirPath)
Definition at line 1133 of file eez-flow.cpp.
{
    int lastPathSeparatorIndex;
    for (lastPathSeparatorIndex = strlen(path) - 1;
         lastPathSeparatorIndex >= 0 && path[lastPathSeparatorIndex] != PATH_SEPARATOR[0];
         --lastPathSeparatorIndex)
        ;
    int i;
    for (i = 0; i < lastPathSeparatorIndex; ++i) {
        parentDirPath[i] = path[i];
    }
    parentDirPath[i] = 0;
}
getSmallerFactor()
float eez::getSmallerFactor (float factor) static
Definition at line 872 of file eez-flow.cpp.
{
    for (int factorIndex = sizeof(FACTORS) / sizeof(float) - 1; factorIndex > 0; factorIndex--) {
        float itFactor = FACTORS[factorIndex];
        if (itFactor < factor) {
            return itFactor;
        }
    }
    return FACTORS[0];
}
References FACTORS.
Referenced by getSmallerUnit().
getSmallerUnit()
Unit eez::getSmallerUnit (Unit unit, float min, float precision)
Definition at line 881 of file eez-flow.cpp.
{
    float factor = getUnitFactor(unit);
    if (precision <= factor || min <= factor) {
        return getDerivedUnit(unit, getSmallerFactor(factor));
    }
    return UNIT_UNKNOWN;
}
References getDerivedUnit(), getSmallerFactor(), and getUnitFactor().
getSmallestUnit()
Unit eez::getSmallestUnit (Unit unit, float min, float precision)
Definition at line 900 of file eez-flow.cpp.
{
    for (int factorIndex = 0; factorIndex < int(sizeof(FACTORS) / sizeof(float)); factorIndex++) {
        float factor = FACTORS[factorIndex];
        if (precision <= factor || min <= factor) {
            auto result = getDerivedUnit(unit, factor);
            if (result != UNIT_UNKNOWN) {
                return result;
            }
        }
    }
    return UNIT_UNKNOWN;
}
References FACTORS, and getDerivedUnit().
getTheme()
Theme * eez::getTheme (int i) static
Definition at line 428 of file eez-flow.cpp.
{
    if (i < 0 || i >= (int)g_mainAssets->colorsDefinition->themes.count) {
        return nullptr;
    }
    return g_mainAssets->colorsDefinition->themes[i];
}
References g_mainAssets.
Referenced by getThemeColors(), getThemeColorsCount(), and getThemeName().
getThemeColors()
const uint16_t * eez::getThemeColors (int themeIndex)
Definition at line 448 of file eez-flow.cpp.
{
    auto theme = getTheme(themeIndex);
    if (!theme) {
        static uint16_t *g_themeColors = { 0 };
        return g_themeColors;
    }
    return static_cast<uint16_t *>(theme->colors.items);
}
References getTheme().
getThemeColorsCount()
uint32_t eez::getThemeColorsCount (int themeIndex)
Definition at line 441 of file eez-flow.cpp.
{
    auto theme = getTheme(themeIndex);
    if (!theme) {
        return 0;
    }
    return theme->colors.count;
}
References getTheme().
getThemeName()
const char * eez::getThemeName (int i)
Definition at line 434 of file eez-flow.cpp.
{
    auto theme = getTheme(i);
    if (!theme) {
        return "";
    }
    return static_cast<const char *>(theme->name);
}
References getTheme().
getThemesCount()
int eez::getThemesCount ()
Definition at line 425 of file eez-flow.cpp.
                     {
    return (int)g_mainAssets->colorsDefinition->themes.count;
}
References g_mainAssets.
getUnitFactor()
float eez::getUnitFactor (Unit unit)
Definition at line 826 of file eez-flow.cpp.
{
    if (unit == UNIT_UNKNOWN) {
        return 1.0f;
    }
    return g_unitFactor[unit];
}
References g_unitFactor.
Referenced by DOUBLE_value_to_text(), FLOAT_value_to_text(), and getSmallerUnit().
getUnitFromName()
Unit eez::getUnitFromName (const char * unitName)
Definition at line 802 of file eez-flow.cpp.
{
    if (unitName) {
        for (unsigned i = 0; i < sizeof(g_unitNames) / sizeof(const char *); i++) {
            if (strcmp(g_unitNames[i], unitName) == 0) {
                return (Unit)i;
            }
        }
    }
    return UNIT_NONE;
}
References g_unitNames.
getVar()
Value eez::getVar (int16_t id)
Definition at line 2961 of file eez-flow.cpp.
{
    auto native_var = native_vars[id];
    if (native_var.type == NATIVE_VAR_TYPE_INTEGER) {
        auto get = (int32_t (*)())native_var.get;
        return Value((int)get(), VALUE_TYPE_INT32);
    }
    if (native_var.type == NATIVE_VAR_TYPE_BOOLEAN) {
        auto get = (bool (*)())native_var.get;
        return Value(get(), VALUE_TYPE_BOOLEAN);
    }
    if (native_var.type == NATIVE_VAR_TYPE_FLOAT) {
        auto get = (float (*)())native_var.get;
        return Value(get(), VALUE_TYPE_FLOAT);
    }
    if (native_var.type == NATIVE_VAR_TYPE_DOUBLE) {
        auto get = (double (*)())native_var.get;
        return Value(get(), VALUE_TYPE_DOUBLE);
    }
    if (native_var.type == NATIVE_VAR_TYPE_STRING) {
        auto get = (const char *(*)())native_var.get;
        return Value(get(), VALUE_TYPE_STRING);
    }
    return Value();
}
References NATIVE_VAR_TYPE_BOOLEAN, NATIVE_VAR_TYPE_DOUBLE, NATIVE_VAR_TYPE_FLOAT, NATIVE_VAR_TYPE_INTEGER, NATIVE_VAR_TYPE_STRING, and native_vars.
initAllocHeap()
void eez::initAllocHeap (uint8_t * heap, size_t heapSize)
Definition at line 50 of file eez-flow.cpp.
{
    EEZ_UNUSED(heap);
    EEZ_UNUSED(heapSize);
}
References EEZ_UNUSED.
Referenced by eez_flow_init().
initAssetsMemory()
void eez::initAssetsMemory ()
Definition at line 550 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
#if defined(LV_MEM_SIZE)
    ALLOC_BUFFER_SIZE = LV_MEM_SIZE;
#endif
#elif defined(EEZ_DASHBOARD_API)
    ALLOC_BUFFER_SIZE = emscripten_get_heap_max();
#else
    ALLOC_BUFFER = MEMORY_BEGIN;
    ALLOC_BUFFER_SIZE = MEMORY_SIZE;
    DECOMPRESSED_ASSETS_START_ADDRESS = allocBuffer(MAX_DECOMPRESSED_ASSETS_SIZE);
#endif
}
References ALLOC_BUFFER, ALLOC_BUFFER_SIZE, allocBuffer(), DECOMPRESSED_ASSETS_START_ADDRESS, and LV_MEM_SIZE.
Referenced by eez_flow_init(), and initMemory().
initMemory()
void eez::initMemory ()
Definition at line 543 of file eez-flow.cpp.
                  {
    initAssetsMemory();
    initOtherMemory();
}
References initAssetsMemory(), and initOtherMemory().
initOtherMemory()
void eez::initOtherMemory ()
Definition at line 563 of file eez-flow.cpp.
                       {
#if !defined(EEZ_FOR_LVGL) && !defined(EEZ_DASHBOARD_API)
    FLOW_TO_DEBUGGER_MESSAGE_BUFFER = allocBuffer(FLOW_TO_DEBUGGER_MESSAGE_BUFFER_SIZE);
#endif
#if EEZ_OPTION_GUI
    uint32_t VRAM_BUFFER_SIZE = DISPLAY_WIDTH * DISPLAY_HEIGHT * DISPLAY_BPP / 8;
    VRAM_BUFFER1_START_ADDRESS = allocBuffer(VRAM_BUFFER_SIZE);
    VRAM_BUFFER2_START_ADDRESS = allocBuffer(VRAM_BUFFER_SIZE);
    for (size_t i = 0; i < NUM_AUX_BUFFERS; i++) {
        VRAM_AUX_BUFFER_START_ADDRESSES[i] = allocBuffer(VRAM_BUFFER_SIZE);
    }
#if EEZ_OPTION_GUI_ANIMATIONS
    VRAM_ANIMATION_BUFFER1_START_ADDRESS = allocBuffer(VRAM_BUFFER_SIZE);
    VRAM_ANIMATION_BUFFER2_START_ADDRESS = allocBuffer(VRAM_BUFFER_SIZE);
    SCREENSHOOT_BUFFER_START_ADDRESS = VRAM_ANIMATION_BUFFER1_START_ADDRESS;
#else
    SCREENSHOOT_BUFFER_START_ADDRESS = allocBuffer(VRAM_BUFFER_SIZE * 2);
#endif
    GUI_STATE_BUFFER = allocBuffer(GUI_STATE_BUFFER_SIZE);
#endif
}
References allocBuffer(), and FLOW_TO_DEBUGGER_MESSAGE_BUFFER.
Referenced by eez_flow_init(), and initMemory().
INT16_value_to_text()
void eez::INT16_value_to_text (const Value & value, char * text, int count) static
Definition at line 1739 of file eez-flow.cpp.
{
    stringAppendInt(text, count, value.getInt16());
}
References stringAppendInt().
INT16_value_type_name()
const char * eez::INT16_value_type_name (const Value & value) static
Definition at line 1742 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "int16";
}
References EEZ_UNUSED.
INT32_value_to_text()
void eez::INT32_value_to_text (const Value & value, char * text, int count) static
Definition at line 1759 of file eez-flow.cpp.
{
    stringAppendInt(text, count, value.getInt32());
}
References stringAppendInt().
INT32_value_type_name()
const char * eez::INT32_value_type_name (const Value & value) static
Definition at line 1762 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "int32";
}
References EEZ_UNUSED.
INT64_value_to_text()
void eez::INT64_value_to_text (const Value & value, char * text, int count) static
Definition at line 1779 of file eez-flow.cpp.
{
    stringAppendInt64(text, count, value.getInt64());
}
References stringAppendInt64().
INT64_value_type_name()
const char * eez::INT64_value_type_name (const Value & value) static
Definition at line 1782 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "int64";
}
References EEZ_UNUSED.
INT8_value_to_text()
void eez::INT8_value_to_text (const Value & value, char * text, int count) static
Definition at line 1719 of file eez-flow.cpp.
{
    stringAppendInt(text, count, value.getInt8());
}
References stringAppendInt().
INT8_value_type_name()
const char * eez::INT8_value_type_name (const Value & value) static
Definition at line 1722 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "int8";
}
References EEZ_UNUSED.
IP_ADDRESS_value_to_text()
void eez::IP_ADDRESS_value_to_text (const Value & value, char * text, int count) static
Definition at line 2292 of file eez-flow.cpp.
{
    ipAddressToString(value.getUInt32(), text, count);
}
References ipAddressToString().
IP_ADDRESS_value_type_name()
const char * eez::IP_ADDRESS_value_type_name (const Value & value) static
Definition at line 2295 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "internal";
}
References EEZ_UNUSED.
ipAddressToArray()
void eez::ipAddressToArray (uint32_t ipAddress, uint8_t * ipAddressArray)
Definition at line 1239 of file eez-flow.cpp.
{
    ipAddressArray[0] = getIpAddressPartA(ipAddress);
    ipAddressArray[1] = getIpAddressPartB(ipAddress);
    ipAddressArray[2] = getIpAddressPartC(ipAddress);
    ipAddressArray[3] = getIpAddressPartD(ipAddress);
}
References getIpAddressPartA(), getIpAddressPartB(), getIpAddressPartC(), and getIpAddressPartD().
ipAddressToString()
void eez::ipAddressToString (uint32_t ipAddress, char * ipAddressStr, size_t maxIpAddressStrLength)
Definition at line 1256 of file eez-flow.cpp.
{
    snprintf(ipAddressStr, maxIpAddressStrLength, "%d.%d.%d.%d",
        getIpAddressPartA(ipAddress), getIpAddressPartB(ipAddress),
        getIpAddressPartC(ipAddress), getIpAddressPartD(ipAddress));
}
References getIpAddressPartA(), getIpAddressPartB(), getIpAddressPartC(), and getIpAddressPartD().
Referenced by IP_ADDRESS_value_to_text().
isDigit()
bool eez::isDigit (char ch)
Definition at line 1105 of file eez-flow.cpp.
                      {
    return ch >= '0' && ch <= '9';
}
Referenced by parseIpAddress(), and parseTimeZone().
isHexDigit()
bool eez::isHexDigit (char ch)
Definition at line 1108 of file eez-flow.cpp.
{
    return (ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') || (ch >= 'A' && ch <= 'F');
}
Referenced by parseMacAddress().
isNaN() [1/2]
bool eez::isNaN (double x)
Definition at line 1102 of file eez-flow.cpp.
                     {
    return x != x;
}
isNaN() [2/2]
bool eez::isNaN (float x)
Definition at line 1099 of file eez-flow.cpp.
                    {
    return x != x;
}
Referenced by DOUBLE_value_to_text(), eez::flow::executeDelayComponent(), and FLOAT_value_to_text().
isStringEmpty()
bool eez::isStringEmpty (char const * s)
Definition at line 1379 of file eez-flow.cpp.
{
    for (; *s; s++) {
        if (!isspace(*s)) {
            return false;
        }
    }
    return true;
}
isUperCaseLetter()
bool eez::isUperCaseLetter (char ch)
Definition at line 1111 of file eez-flow.cpp.
{
    return ch >= 'A' && ch <= 'Z';
}
JSON_MEMBER_VALUE_value_to_text()
void eez::JSON_MEMBER_VALUE_value_to_text (const Value & value, char * text, int count) static
Definition at line 2087 of file eez-flow.cpp.
{
    value.getValue().toText(text, count);
}
JSON_MEMBER_VALUE_value_type_name()
const char * eez::JSON_MEMBER_VALUE_value_type_name (const Value & value) static
Definition at line 2090 of file eez-flow.cpp.
{
    auto value2 = value.getValue();
    return g_valueTypeNames[value2.type](value2);
}
References g_valueTypeNames.
JSON_value_to_text()
void eez::JSON_value_to_text (const Value & value, char * text, int count) static
Definition at line 2077 of file eez-flow.cpp.
{
    snprintf(text, count, "json (id=%d)", value.getInt());
}
JSON_value_type_name()
const char * eez::JSON_value_type_name (const Value & value) static
Definition at line 2080 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "json";
}
References EEZ_UNUSED.
loadMainAssets()
void eez::loadMainAssets (const uint8_t * assets, uint32_t assetsSize)
Definition at line 331 of file eez-flow.cpp.
{
    auto header = (Header *)assets;
    if (header->tag == HEADER_TAG) {
        g_mainAssets = (Assets *)(assets + sizeof(uint32_t));
        g_mainAssetsUncompressed = true;
    } else {
#if defined(EEZ_FOR_LVGL) || defined(EEZ_DASHBOARD_API)
        uint8_t *DECOMPRESSED_ASSETS_START_ADDRESS = 0;
        uint32_t MAX_DECOMPRESSED_ASSETS_SIZE = 0;
        allocMemoryForDecompressedAssets(assets, assetsSize, DECOMPRESSED_ASSETS_START_ADDRESS, MAX_DECOMPRESSED_ASSETS_SIZE);
#endif
        g_mainAssets = (Assets *)DECOMPRESSED_ASSETS_START_ADDRESS;
        g_mainAssetsUncompressed = false;
        g_mainAssets->external = false;
        auto decompressedSize = decompressAssetsData(assets, assetsSize, g_mainAssets, MAX_DECOMPRESSED_ASSETS_SIZE, nullptr);
        assert(decompressedSize);
    }
    g_isMainAssetsLoaded = true;
}
References allocMemoryForDecompressedAssets(), assets, decompressAssetsData(), DECOMPRESSED_ASSETS_START_ADDRESS, g_isMainAssetsLoaded, g_mainAssets, and g_mainAssetsUncompressed.
Referenced by eez_flow_init().
macAddressToString()
void eez::macAddressToString (const uint8_t * macAddress, char * macAddressStr)
Definition at line 1261 of file eez-flow.cpp.
{
    for (int i = 0; i < 6; ++i) {
        macAddressStr[3 * i] = toHexDigit((macAddress[i] & 0xF0) >> 4);
        macAddressStr[3 * i + 1] = toHexDigit(macAddress[i] & 0xF);
        macAddressStr[3 * i + 2] = i < 5 ? '-' : 0;
    }
}
References toHexDigit().
MakeEnumDefinitionValue()
Value eez::MakeEnumDefinitionValue (uint8_t enumValue, uint8_t enumDefinition)
Definition at line 2401 of file eez-flow.cpp.
{
    Value value;
    value.type = VALUE_TYPE_ENUM;
    value.enumValue.enumValue = enumValue;
    value.enumValue.enumDefinition = enumDefinition;
    return value;
}
MakeRangeValue()
Value eez::MakeRangeValue (uint16_t from, uint16_t to)
Definition at line 2394 of file eez-flow.cpp.
{
    Value value;
    value.type = VALUE_TYPE_RANGE;
    value.pairOfUint16Value.first = from;
    value.pairOfUint16Value.second = to;
    return value;
}
millis()
uint32_t eez::millis ()
Definition at line 622 of file eez-flow.cpp.
                  {
#if defined(EEZ_PLATFORM_STM32)
    return HAL_GetTick();
#elif defined(__EMSCRIPTEN__)
    return (uint32_t)emscripten_get_now();
#elif defined(EEZ_PLATFORM_SIMULATOR)
    return osKernelGetTickCount();
#elif defined(EEZ_PLATFORM_ESP32)
    return (unsigned long) (esp_timer_get_time() / 1000ULL);
#elif defined(EEZ_PLATFORM_PICO)
    auto abs_time = get_absolute_time();
    return to_ms_since_boot(abs_time);
#elif defined(EEZ_PLATFORM_RASPBERRY)
    unsigned nStartTicks = CTimer::Get()->GetClockTicks();
    return nStartTicks / 1000;
#elif defined(EEZ_FOR_LVGL)
    return lv_tick_get();
#else
    #error "Missing millis implementation";
#endif
}
Referenced by eez::flow::do_OPERATION_TYPE_SYSTEM_GET_TICK(), eez::flow::executeAnimateComponent(), eez::flow::executeDelayComponent(), and eez::flow::tick().
NATIVE_VARIABLE_value_to_text()
void eez::NATIVE_VARIABLE_value_to_text (const Value & value, char * text, int count) static
Definition at line 2200 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    *text = 0;
}
References EEZ_UNUSED.
NATIVE_VARIABLE_value_type_name()
const char * eez::NATIVE_VARIABLE_value_type_name (const Value & value) static
Definition at line 2205 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "";
}
References EEZ_UNUSED.
NULL_value_to_text()
void eez::NULL_value_to_text (const Value & value, char * text, int count) static
Definition at line 1693 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    *text = 0;
}
References EEZ_UNUSED.
NULL_value_type_name()
const char * eez::NULL_value_type_name (const Value & value) static
Definition at line 1698 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "null";
}
References EEZ_UNUSED.
parseIpAddress()
bool eez::parseIpAddress (const char * ipAddressStr, size_t ipAddressStrLength, uint32_t & ipAddress)
Definition at line 1180 of file eez-flow.cpp.
{
    const char *p = ipAddressStr;
    const char *q = ipAddressStr + ipAddressStrLength;
    uint8_t ipAddressArray[4];
    for (int i = 0; i < 4; ++i) {
        if (p == q) {
            return false;
        }
        uint32_t part = 0;
        for (int j = 0; j < 3; ++j) {
            if (p == q) {
                if (j > 0 && i == 3) {
                    break;
                } else {
                    return false;
                }
            } else if (isDigit(*p)) {
                part = part * 10 + (*p++ - '0');
            } else if (j > 0 && *p == '.') {
                break;
            } else {
                return false;
            }
        }
        if (part > 255) {
            return false;
        }
        if ((i < 3 && *p++ != '.') || (i == 3 && p != q)) {
            return false;
        }
        ipAddressArray[i] = part;
    }
    ipAddress = arrayToIpAddress(ipAddressArray);
    return true;
}
References arrayToIpAddress(), and isDigit().
parseMacAddress()
bool eez::parseMacAddress (const char * macAddressStr, size_t macAddressStrLength, uint8_t * macAddress)
Definition at line 1145 of file eez-flow.cpp.
{
    int state = 0;
    int a = 0;
    int i = 0;
    uint8_t resultMacAddress[6];
    const char *end = macAddressStr + macAddressStrLength;
    for (const char *p = macAddressStr; p < end; ++p) {
        if (state == 0) {
            if (*p == '-' || *p == ' ') {
                continue;
            } else if (isHexDigit(*p)) {
                a = fromHexDigit(*p);
                state = 1;
            } else {
                return false;
            }
        } else if (state == 1) {
            if (isHexDigit(*p)) {
                if (i < 6) {
                    resultMacAddress[i++] = (a << 4) | fromHexDigit(*p);
                    state = 0;
                } else {
                    return false;
                }
            } else {
                return false;
            }
        }
    }
    if (state != 0 || i != 6) {
        return false;
    }
    memcpy(macAddress, resultMacAddress, 6);
    return true;
}
References fromHexDigit(), and isHexDigit().
parseTimeZone()
bool eez::parseTimeZone (const char * timeZoneStr, size_t timeZoneLength, int16_t & timeZone)
Definition at line 1284 of file eez-flow.cpp.
{
    int state = 0;
    int sign = 1;
    int integerPart = 0;
    int fractionPart = 0;
    const char *end = timeZoneStr + timeZoneLength;
    for (const char *p = timeZoneStr; p < end; ++p) {
        if (*p == ' ') {
            continue;
        }
        if (state == 0) {
            if (*p == '+') {
                state = 1;
            } else if (*p == '-') {
                sign = -1;
                state = 1;
            } else if (isDigit(*p)) {
                integerPart = *p - '0';
                state = 2;
            } else {
                return false;
            }
        } else if (state == 1) {
            if (isDigit(*p)) {
                integerPart = (*p - '0');
                state = 2;
            } else {
                return false;
            }
        } else if (state == 2) {
            if (*p == ':') {
                state = 4;
            } else if (isDigit(*p)) {
                integerPart = integerPart * 10 + (*p - '0');
                state = 3;
            } else {
                return false;
            }
        } else if (state == 3) {
            if (*p == ':') {
                state = 4;
            } else {
                return false;
            }
        } else if (state == 4) {
            if (isDigit(*p)) {
                fractionPart = (*p - '0');
                state = 5;
            } else {
                return false;
            }
        } else if (state == 5) {
            if (isDigit(*p)) {
                fractionPart = fractionPart * 10 + (*p - '0');
                state = 6;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
    if (state != 2 && state != 3 && state != 6) {
        return false;
    }
    int value = sign * (integerPart * 100 + fractionPart);
    if (value < -1200 || value > 1400) {
        return false;
    }
    timeZone = (int16_t)value;
    return true;
}
References isDigit().
POINTER_value_to_text()
void eez::POINTER_value_to_text (const Value & value, char * text, int count) static
Definition at line 2239 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    text[0] = 0;
}
References EEZ_UNUSED.
POINTER_value_type_name()
const char * eez::POINTER_value_type_name (const Value & value) static
Definition at line 2244 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "internal";
}
References EEZ_UNUSED.
pointInsideRect()
bool eez::pointInsideRect (int xPoint, int yPoint, int xRect, int yRect, int wRect, int hRect)
Definition at line 1130 of file eez-flow.cpp.
{
    return xPoint >= xRect && xPoint < xRect + wRect && yPoint >= yRect && yPoint < yRect + hRect;
}
PROPERTY_REF_value_to_text()
void eez::PROPERTY_REF_value_to_text (const Value & value, char * text, int count) static
Definition at line 2111 of file eez-flow.cpp.
{
    snprintf(text, count, "property-ref (flowState=%p, component=%d, property=%d)",
        (void *)value.getPropertyRef()->flowState, value.getPropertyRef()->componentIndex, value.getPropertyRef()->propertyIndex);
}
PROPERTY_REF_value_type_name()
const char * eez::PROPERTY_REF_value_type_name (const Value & value) static
Definition at line 2104 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "property-ref";
}
References EEZ_UNUSED.
RANGE_value_to_text()
void eez::RANGE_value_to_text (const Value & value, char * text, int count) static
Definition at line 2227 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    text[0] = 0;
}
References EEZ_UNUSED.
RANGE_value_type_name()
const char * eez::RANGE_value_type_name (const Value & value) static
Definition at line 2232 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "internal";
}
References EEZ_UNUSED.
remap()
float eez::remap (float x, float x1, float y1, float x2, float y2)
Definition at line 925 of file eez-flow.cpp.
{
    return y1 + (x - x1) * (y2 - y1) / (x2 - x1);
}
Referenced by remapCubic(), remapExp(), remapInOutQuad(), remapOutCubic(), remapOutExp(), remapOutQuad(), and remapQuad().
remapCubic()
float eez::remapCubic (float x, float x1, float y1, float x2, float y2)
Definition at line 946 of file eez-flow.cpp.
{
    float t = remap(x, x1, 0, x2, 1);
    t = t * t * t;
    x = remap(t, 0, x1, 1, x2);
    return remap(x, x1, y1, x2, y2);
}
References remap().
remapExp()
float eez::remapExp (float x, float x1, float y1, float x2, float y2)
Definition at line 959 of file eez-flow.cpp.
{
    float t = remap(x, x1, 0, x2, 1);
    t = t == 0 ? 0 : float(pow(2, 10 * (t - 1)));
    x = remap(t, 0, x1, 1, x2);
    return remap(x, x1, y1, x2, y2);
}
References remap().
remapInOutQuad()
float eez::remapInOutQuad (float x, float x1, float y1, float x2, float y2)
Definition at line 940 of file eez-flow.cpp.
{
    float t = remap(x, x1, 0, x2, 1);
    t = t < .5 ? 2 * t*t : -1 + (4 - 2 * t)*t;
    x = remap(t, 0, x1, 1, x2);
    return remap(x, x1, y1, x2, y2);
}
References remap().
remapOutCubic()
float eez::remapOutCubic (float x, float x1, float y1, float x2, float y2)
Definition at line 952 of file eez-flow.cpp.
{
    float t = remap(x, x1, 0, x2, 1);
    t = t - 1;
    t = 1 + t * t * t;
    x = remap(t, 0, x1, 1, x2);
    return remap(x, x1, y1, x2, y2);
}
References remap().
remapOutExp()
float eez::remapOutExp (float x, float x1, float y1, float x2, float y2)
Definition at line 965 of file eez-flow.cpp.
{
    float t = remap(x, x1, 0, x2, 1);
    t = t == 1 ? 1 : float(1 - pow(2, -10 * t));
    x = remap(t, 0, x1, 1, x2);
    return remap(x, x1, y1, x2, y2);
}
References remap().
remapOutQuad()
float eez::remapOutQuad (float x, float x1, float y1, float x2, float y2)
Definition at line 934 of file eez-flow.cpp.
{
    float t = remap(x, x1, 0, x2, 1);
    t = t * (2 - t);
    x = remap(t, 0, x1, 1, x2);
    return remap(x, x1, y1, x2, y2);
}
References remap().
remapQuad()
float eez::remapQuad (float x, float x1, float y1, float x2, float y2)
Definition at line 928 of file eez-flow.cpp.
{
    float t = remap(x, x1, 0, x2, 1);
    t = t * t;
    x = remap(t, 0, x1, 1, x2);
    return remap(x, x1, y1, x2, y2);
}
References remap().
replaceCharacter()
void eez::replaceCharacter (char * str, char ch, char repl)
Definition at line 1356 of file eez-flow.cpp.
{
    while (*str) {
        if (*str == ch) {
            *str = repl;
        }
        ++str;
    }
}
roundPrec()
float eez::roundPrec (float a, float prec)
Definition at line 1087 of file eez-flow.cpp.
{
    float r = 1 / prec;
    return roundf(a * r) / r;
}
setIpAddressPartA()
void eez::setIpAddressPartA (uint32_t * ipAddress, uint8_t value)
Definition at line 1218 of file eez-flow.cpp.
{
    ((uint8_t *)ipAddress)[0] = value;
}
Referenced by getIpAddress().
setIpAddressPartB()
void eez::setIpAddressPartB (uint32_t * ipAddress, uint8_t value)
Definition at line 1224 of file eez-flow.cpp.
{
    ((uint8_t *)ipAddress)[1] = value;
}
Referenced by getIpAddress().
setIpAddressPartC()
void eez::setIpAddressPartC (uint32_t * ipAddress, uint8_t value)
Definition at line 1230 of file eez-flow.cpp.
{
    ((uint8_t *)ipAddress)[2] = value;
}
Referenced by getIpAddress().
setIpAddressPartD()
void eez::setIpAddressPartD (uint32_t * ipAddress, uint8_t value)
Definition at line 1236 of file eez-flow.cpp.
{
    ((uint8_t *)ipAddress)[3] = value;
}
Referenced by getIpAddress().
setVar()
void eez::setVar (int16_t id, const Value & value)
Definition at line 2985 of file eez-flow.cpp.
{
    auto native_var = native_vars[id];
    if (native_var.type == NATIVE_VAR_TYPE_INTEGER) {
        auto set = (void (*)(int32_t))native_var.set;
        set(value.toInt32(nullptr));
    }
    if (native_var.type == NATIVE_VAR_TYPE_BOOLEAN) {
        auto set = (void (*)(bool))native_var.set;
        set(value.toBool(nullptr));
    }
    if (native_var.type == NATIVE_VAR_TYPE_FLOAT) {
        auto set = (void (*)(float))native_var.set;
        set(value.toFloat(nullptr));
    }
    if (native_var.type == NATIVE_VAR_TYPE_DOUBLE) {
        auto set = (void (*)(double))native_var.set;
        set(value.toDouble(nullptr));
    }
    if (native_var.type == NATIVE_VAR_TYPE_STRING) {
        auto set = (void (*)(const char *))native_var.set;
        set(value.getString());
    }
}
References NATIVE_VAR_TYPE_BOOLEAN, NATIVE_VAR_TYPE_DOUBLE, NATIVE_VAR_TYPE_FLOAT, NATIVE_VAR_TYPE_INTEGER, NATIVE_VAR_TYPE_STRING, and native_vars.
Referenced by eez::flow::assignValue().
startsWith()
bool eez::startsWith (const char * str, const char * prefix)
Definition at line 1387 of file eez-flow.cpp.
{
    if (!str || !prefix)
        return false;
    size_t strLen = strlen(str);
    size_t prefixLen = strlen(prefix);
    if (prefixLen > strLen)
        return false;
    return strncmp(str, prefix, prefixLen) == 0;
}
startsWithNoCase()
bool eez::startsWithNoCase (const char * str, const char * prefix)
Definition at line 1396 of file eez-flow.cpp.
{
    if (!str || !prefix)
        return false;
    size_t strLen = strlen(str);
    size_t prefixLen = strlen(prefix);
    if (prefixLen > strLen)
        return false;
    return strncicmp(str, prefix, prefixLen) == 0;
}
References strncicmp().
strcicmp()
int eez::strcicmp (char const * a, char const * b)
Definition at line 1364 of file eez-flow.cpp.
{
    for (;; a++, b++) {
        int d = tolower((unsigned char)*a) - tolower((unsigned char)*b);
        if (d != 0 || !*a)
            return d;
    }
}
STREAM_value_to_text()
void eez::STREAM_value_to_text (const Value & value, char * text, int count) static
Definition at line 2049 of file eez-flow.cpp.
{
    snprintf(text, count, "stream (id=%d)", value.getInt());
}
STREAM_value_type_name()
const char * eez::STREAM_value_type_name (const Value & value) static
Definition at line 2052 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "stream";
}
References EEZ_UNUSED.
STRING_ASSET_value_to_text()
void eez::STRING_ASSET_value_to_text (const Value & value, char * text, int count) static
Definition at line 1983 of file eez-flow.cpp.
{
    STRING_value_to_text(value, text, count);
}
References STRING_value_to_text().
STRING_ASSET_value_type_name()
const char * eez::STRING_ASSET_value_type_name (const Value & value) static
Definition at line 1986 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "string";
}
References EEZ_UNUSED.
STRING_REF_value_to_text()
void eez::STRING_REF_value_to_text (const Value & value, char * text, int count) static
Definition at line 2029 of file eez-flow.cpp.
{
    STRING_value_to_text(value, text, count);
}
References STRING_value_to_text().
STRING_REF_value_type_name()
const char * eez::STRING_REF_value_type_name (const Value & value) static
Definition at line 2032 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "string";
}
References EEZ_UNUSED.
STRING_value_to_text()
void eez::STRING_value_to_text (const Value & value, char * text, int count) static
Definition at line 1968 of file eez-flow.cpp.
{
    const char *str = value.getString();
    if (str) {
        stringCopy(text, count, str);
    } else {
        text[0] = 0;
    }
}
References stringCopy().
Referenced by STRING_ASSET_value_to_text(), and STRING_REF_value_to_text().
STRING_value_type_name()
const char * eez::STRING_value_type_name (const Value & value) static
Definition at line 1976 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "string";
}
References EEZ_UNUSED.
stringAppendCurrent()
void eez::stringAppendCurrent (char * str, size_t maxStrLength, float value)
Definition at line 1037 of file eez-flow.cpp.
{
    auto n = strlen(str);
    snprintf(str + n, maxStrLength - n, "%g A", value);
}
stringAppendDouble() [1/2]
void eez::stringAppendDouble (char * str, size_t maxStrLength, double value)
Definition at line 1025 of file eez-flow.cpp.
{
    auto n = strlen(str);
    snprintf(str + n, maxStrLength - n, "%g", value);
}
Referenced by DOUBLE_value_to_text().
stringAppendDouble() [2/2]
void eez::stringAppendDouble (char * str, size_t maxStrLength, double value, int numDecimalPlaces)
Definition at line 1029 of file eez-flow.cpp.
{
    auto n = strlen(str);
    snprintf(str + n, maxStrLength - n, "%.*f", numDecimalPlaces, value);
}
stringAppendDuration()
void eez::stringAppendDuration (char * str, size_t maxStrLength, float value)
Definition at line 1045 of file eez-flow.cpp.
{
    auto n = strlen(str);
    if (value > 0.1) {
        snprintf(str + n, maxStrLength - n, "%g s", value);
    } else {
        snprintf(str + n, maxStrLength - n, "%g ms", value * 1000);
    }
}
stringAppendFloat() [1/2]
void eez::stringAppendFloat (char * str, size_t maxStrLength, float value)
Definition at line 1017 of file eez-flow.cpp.
{
    auto n = strlen(str);
    snprintf(str + n, maxStrLength - n, "%g", value);
}
Referenced by DOUBLE_value_to_text(), and FLOAT_value_to_text().
stringAppendFloat() [2/2]
void eez::stringAppendFloat (char * str, size_t maxStrLength, float value, int numDecimalPlaces)
Definition at line 1021 of file eez-flow.cpp.
{
    auto n = strlen(str);
    snprintf(str + n, maxStrLength - n, "%.*f", numDecimalPlaces, value);
}
stringAppendInt()
void eez::stringAppendInt (char * str, size_t maxStrLength, int value)
Definition at line 1001 of file eez-flow.cpp.
{
    auto n = strlen(str);
    snprintf(str + n, maxStrLength - n, "%d", value);
}
Referenced by INT16_value_to_text(), INT32_value_to_text(), and INT8_value_to_text().
stringAppendInt64()
void eez::stringAppendInt64 (char * str, size_t maxStrLength, int64_t value)
Definition at line 1009 of file eez-flow.cpp.
{
    auto n = strlen(str);
    snprintf(str + n, maxStrLength - n, "%jd", value);
}
Referenced by INT64_value_to_text().
stringAppendLoad()
void eez::stringAppendLoad (char * str, size_t maxStrLength, float value)
Definition at line 1053 of file eez-flow.cpp.
{
    auto n = strlen(str);
    if (value < 1000) {
        snprintf(str + n, maxStrLength - n, "%g ohm", value);
    } else if (value < 1000000) {
        snprintf(str + n, maxStrLength - n, "%g Kohm", value / 1000);
    } else {
        snprintf(str + n, maxStrLength - n, "%g Mohm", value / 1000000);
    }
}
stringAppendPower()
void eez::stringAppendPower (char * str, size_t maxStrLength, float value)
Definition at line 1041 of file eez-flow.cpp.
{
    auto n = strlen(str);
    snprintf(str + n, maxStrLength - n, "%g W", value);
}
stringAppendString()
void eez::stringAppendString (char * str, size_t maxStrLength, const char * value)
Definition at line 989 of file eez-flow.cpp.
{
    int n = maxStrLength - strlen(str) - 1;
    if (n >= 0) {
        strncat(str, value, n);
    }
}
Referenced by _evalStringArrayPropertyAndJoin(), DOUBLE_value_to_text(), FLOAT_value_to_text(), and eez::flow::writeValue().
stringAppendStringLength()
void eez::stringAppendStringLength (char * str, size_t maxStrLength, const char * value, size_t length)
Definition at line 995 of file eez-flow.cpp.
{
    int n = MIN(maxStrLength - strlen(str) - 1, length);
    if (n >= 0) {
        strncat(str, value, n);
    }
}
stringAppendUInt32()
void eez::stringAppendUInt32 (char * str, size_t maxStrLength, uint32_t value)
Definition at line 1005 of file eez-flow.cpp.
{
    auto n = strlen(str);
    snprintf(str + n, maxStrLength - n, "%lu", (unsigned long)value);
}
Referenced by UINT16_value_to_text(), UINT32_value_to_text(), and UINT8_value_to_text().
stringAppendUInt64()
void eez::stringAppendUInt64 (char * str, size_t maxStrLength, uint64_t value)
Definition at line 1013 of file eez-flow.cpp.
{
    auto n = strlen(str);
    snprintf(str + n, maxStrLength - n, "%ju", value);
}
Referenced by UINT64_value_to_text().
stringAppendVoltage()
void eez::stringAppendVoltage (char * str, size_t maxStrLength, float value)
Definition at line 1033 of file eez-flow.cpp.
{
    auto n = strlen(str);
    snprintf(str + n, maxStrLength - n, "%g V", value);
}
stringCopy()
void eez::stringCopy (char * dst, size_t maxStrLength, const char * src)
Definition at line 980 of file eez-flow.cpp.
{
    strncpy(dst, src, maxStrLength);
    dst[maxStrLength - 1] = 0;
}
Referenced by BOOLEAN_value_to_text(), eez::flow::do_OPERATION_TYPE_STRING_PAD_START(), eez::flow::do_OPERATION_TYPE_STRING_SPLIT(), formatBytes(), formatTimeZone(), STRING_value_to_text(), VERSIONED_STRING_value_to_text(), and eez::flow::writeValue().
stringCopyLength()
void eez::stringCopyLength (char * dst, size_t maxStrLength, const char * src, size_t length)
Definition at line 984 of file eez-flow.cpp.
{
    size_t n = MIN(length, maxStrLength);
    strncpy(dst, src, n);
    dst[n] = 0;
}
strncicmp()
int eez::strncicmp (char const * a, char const * b, int n)
Definition at line 1371 of file eez-flow.cpp.
{
    for (; n--; a++, b++) {
        int d = tolower((unsigned char)*a) - tolower((unsigned char)*b);
        if (d != 0 || !*a)
            return d;
    }
    return 0;
}
Referenced by endsWithNoCase(), and startsWithNoCase().
TIME_ZONE_value_to_text()
void eez::TIME_ZONE_value_to_text (const Value & value, char * text, int count) static
Definition at line 2302 of file eez-flow.cpp.
{
    formatTimeZone(value.getInt16(), text, count);
}
References formatTimeZone().
TIME_ZONE_value_type_name()
const char * eez::TIME_ZONE_value_type_name (const Value & value) static
Definition at line 2305 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "internal";
}
References EEZ_UNUSED.
toBCD()
uint8_t eez::toBCD (uint8_t bin)
Definition at line 1081 of file eez-flow.cpp.
{
    return ((bin / 10) << 4) | (bin % 10);
}
toHexDigit()
char eez::toHexDigit (int num)
Definition at line 1114 of file eez-flow.cpp.
{
    if (num >= 0 && num <= 9) {
        return '0' + num;
    } else {
        return 'A' + (num - 10);
    }
}
Referenced by macAddressToString(), and eez::flow::writeHex().
UINT16_value_to_text()
void eez::UINT16_value_to_text (const Value & value, char * text, int count) static
Definition at line 1749 of file eez-flow.cpp.
{
    stringAppendUInt32(text, count, value.getUInt16());
}
References stringAppendUInt32().
UINT16_value_type_name()
const char * eez::UINT16_value_type_name (const Value & value) static
Definition at line 1752 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "uint16";
}
References EEZ_UNUSED.
UINT32_value_to_text()
void eez::UINT32_value_to_text (const Value & value, char * text, int count) static
Definition at line 1769 of file eez-flow.cpp.
{
    stringAppendUInt32(text, count, value.getUInt32());
}
References stringAppendUInt32().
UINT32_value_type_name()
const char * eez::UINT32_value_type_name (const Value & value) static
Definition at line 1772 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "uint32";
}
References EEZ_UNUSED.
UINT64_value_to_text()
void eez::UINT64_value_to_text (const Value & value, char * text, int count) static
Definition at line 1789 of file eez-flow.cpp.
{
    stringAppendUInt64(text, count, value.getUInt64());
}
References stringAppendUInt64().
UINT64_value_type_name()
const char * eez::UINT64_value_type_name (const Value & value) static
Definition at line 1792 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "uint64";
}
References EEZ_UNUSED.
UINT8_value_to_text()
void eez::UINT8_value_to_text (const Value & value, char * text, int count) static
Definition at line 1729 of file eez-flow.cpp.
{
    stringAppendUInt32(text, count, value.getUInt8());
}
References stringAppendUInt32().
UINT8_value_type_name()
const char * eez::UINT8_value_type_name (const Value & value) static
Definition at line 1732 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "uint8";
}
References EEZ_UNUSED.
UNDEFINED_value_to_text()
void eez::UNDEFINED_value_to_text (const Value & value, char * text, int count) static
Definition at line 1680 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    *text = 0;
}
References EEZ_UNUSED.
UNDEFINED_value_type_name()
const char * eez::UNDEFINED_value_type_name (const Value & value) static
Definition at line 1685 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "undefined";
}
References EEZ_UNUSED.
unloadExternalAssets()
void eez::unloadExternalAssets ()
Definition at line 350 of file eez-flow.cpp.
{
    if (g_externalAssets) {
#if EEZ_OPTION_GUI
        removeExternalPagesFromTheStack();
#endif
        free(g_externalAssets);
        g_externalAssets = nullptr;
    }
}
References free(), and g_externalAssets.
VALUE_PTR_value_to_text()
void eez::VALUE_PTR_value_to_text (const Value & value, char * text, int count) static
Definition at line 2143 of file eez-flow.cpp.
{
    if (value.pValueValue) {
        value.pValueValue->toText(text, count);
    } else {
        text[0] = 0;
    }
}
VALUE_PTR_value_type_name()
const char * eez::VALUE_PTR_value_type_name (const Value & value) static
Definition at line 2150 of file eez-flow.cpp.
{
    if (value.pValueValue) {
        return g_valueTypeNames[value.pValueValue->type](value.pValueValue);
    } else {
        return "null";
    }
}
References g_valueTypeNames.
VERSIONED_STRING_value_to_text()
void eez::VERSIONED_STRING_value_to_text (const Value & value, char * text, int count) static
Definition at line 2128 of file eez-flow.cpp.
{
    const char *str = value.getString();
    if (str) {
        stringCopy(text, count, str);
    } else {
        text[0] = 0;
    }
}
References stringCopy().
VERSIONED_STRING_value_type_name()
const char * eez::VERSIONED_STRING_value_type_name (const Value & value) static
Definition at line 2136 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "versioned-string";
}
References EEZ_UNUSED.
WIDGET_value_to_text()
void eez::WIDGET_value_to_text (const Value & value, char * text, int count) static
Definition at line 2063 of file eez-flow.cpp.
{
#if defined(EEZ_FOR_LVGL)
    snprintf(text, count, "widget (%p)", value.getVoidPointer());
#else
    snprintf(text, count, "widget (id=%d)", value.getInt());
#endif
}
WIDGET_value_type_name()
const char * eez::WIDGET_value_type_name (const Value & value) static
Definition at line 2070 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "widget";
}
References EEZ_UNUSED.
YT_DATA_GET_VALUE_FUNCTION_POINTER_value_to_text()
void eez::YT_DATA_GET_VALUE_FUNCTION_POINTER_value_to_text (const Value & value, char * text, int count) static
Definition at line 2309 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    EEZ_UNUSED(count);
    text[0] = 0;
}
References EEZ_UNUSED.
YT_DATA_GET_VALUE_FUNCTION_POINTER_value_type_name()
const char * eez::YT_DATA_GET_VALUE_FUNCTION_POINTER_value_type_name (const Value & value) static
Definition at line 2314 of file eez-flow.cpp.
{
    EEZ_UNUSED(value);
    return "internal";
}
References EEZ_UNUSED.
Variable Documentation
ALLOC_BUFFER
uint8_t* eez::ALLOC_BUFFER = 0
Definition at line 541 of file eez-flow.cpp.
Referenced by allocBuffer(), eez_flow_init(), initAssetsMemory(), and eez::flow::initFlowState().
ALLOC_BUFFER_SIZE
uint32_t eez::ALLOC_BUFFER_SIZE = 0
Definition at line 542 of file eez-flow.cpp.
Referenced by allocBuffer(), eez_flow_init(), initAssetsMemory(), and eez::flow::onAddToQueue().
DECOMPRESSED_ASSETS_START_ADDRESS
uint8_t* eez::DECOMPRESSED_ASSETS_START_ADDRESS
Definition at line 528 of file eez-flow.cpp.
Referenced by initAssetsMemory(), and loadMainAssets().
FACTORS
const float eez::FACTORS[] = { 1E-12F, 1E-9F, 1E-6F, 1E-3F, 1E0F, 1E3F, 1E6F, 1E9F, 1E12F } static
Definition at line 843 of file eez-flow.cpp.
{ 1E-12F, 1E-9F, 1E-6F, 1E-3F, 1E0F, 1E3F, 1E6F, 1E9F, 1E12F };
Referenced by findDerivedUnit(), getBiggestUnit(), getSmallerFactor(), and getSmallestUnit().
FLOW_TO_DEBUGGER_MESSAGE_BUFFER
uint8_t* eez::FLOW_TO_DEBUGGER_MESSAGE_BUFFER
Definition at line 529 of file eez-flow.cpp.
Referenced by initOtherMemory().
g_actionExecFunctions
ActionExecFunc eez::g_actionExecFunctions[] = { 0 }
Definition at line 7825 of file eez-flow.cpp.
{ 0 };
Referenced by executeActionFunction().
g_baseUnit
const Unit eez::g_baseUnit[]
Definition at line 689 of file eez-flow.cpp.
{
    UNIT_NONE,
    UNIT_VOLT,
    UNIT_VOLT,
    UNIT_AMPER,
    UNIT_AMPER,
    UNIT_AMPER,
    UNIT_WATT,
    UNIT_WATT,
    UNIT_SECOND,
    UNIT_SECOND,
    UNIT_CELSIUS,
    UNIT_RPM,
    UNIT_OHM,
    UNIT_OHM,
    UNIT_OHM,
    UNIT_PERCENT,
    UNIT_HERTZ,
    UNIT_HERTZ,
    UNIT_HERTZ,
    UNIT_HERTZ,
    UNIT_JOULE,
    UNIT_FARAD,
    UNIT_FARAD,
    UNIT_FARAD,
    UNIT_FARAD,
    UNIT_FARAD,
    UNIT_SECOND,
    UNIT_VOLT_AMPERE,
    UNIT_VOLT_AMPERE,
    UNIT_DEGREE,
    UNIT_VOLT_PP,
    UNIT_VOLT_PP,
    UNIT_AMPER_PP,
    UNIT_AMPER_PP,
    UNIT_AMPER_PP,
};
Referenced by getBaseUnit(), and getDerivedUnit().
g_easingFuncs
EasingFuncType eez::g_easingFuncs[]
Definition at line 1612 of file eez-flow.cpp.
{
    eez_linear,
    eez_easeInQuad,
    eez_easeOutQuad,
    eez_easeInOutQuad,
    eez_easeInCubic,
    eez_easeOutCubic,
    eez_easeInOutCubic,
    eez_easeInQuart,
    eez_easeOutQuart,
    eez_easeInOutQuart,
    eez_easeInQuint,
    eez_easeOutQuint,
    eez_easeInOutQuint,
    eez_easeInSine,
    eez_easeOutSine,
    eez_easeInOutSine,
    eez_easeInExpo,
    eez_easeOutExpo,
    eez_easeInOutExpo,
    eez_easeInCirc,
    eez_easeOutCirc,
    eez_easeInOutCirc,
    eez_easeInBack,
    eez_easeOutBack,
    eez_easeInOutBack,
    eez_easeInElastic,
    eez_easeOutElastic,
    eez_easeInOutElastic,
    eez_easeInBounce,
    eez_easeOutBounce,
    eez_easeInOutBounce,
};
g_externalAssets
Assets* eez::g_externalAssets
Definition at line 258 of file eez-flow.cpp.
Referenced by eez::flow::do_OPERATION_TYPE_FLOW_IS_PAGE_ACTIVE(), and unloadExternalAssets().
g_isMainAssetsLoaded
bool eez::g_isMainAssetsLoaded
Definition at line 255 of file eez-flow.cpp.
Referenced by loadMainAssets().
g_mainAssets
Assets* eez::g_mainAssets
Definition at line 256 of file eez-flow.cpp.
Referenced by deletePageFlowState(), eez_flow_init(), eez::flow::executeSetColorThemeComponent(), flowOnPageLoaded(), getColors(), getFlowState(), eez::flow::getGlobalVariable(), getTheme(), getThemesCount(), loadMainAssets(), eez::flow::onPageChanged(), and eez::flow::setGlobalVariable().
g_mainAssetsUncompressed
bool eez::g_mainAssetsUncompressed
Definition at line 257 of file eez-flow.cpp.
Referenced by eez::flow::initGlobalVariables(), and loadMainAssets().
g_unitFactor
const float eez::g_unitFactor[]
Definition at line 726 of file eez-flow.cpp.
{
    1.0f,
    1.0f,
    1E-3f,
    1.0f,
    1E-3f,
    1E-6f,
    1.0f,
    1E-3f,
    1.0f,
    1E-3f,
    1.0f,
    1.0f,
    1.0f,
    1E3f,
    1E6f,
    1.0f,
    1.0f,
    1E-3f,
    1E3f,
    1E6f,
    1.0f,
    1.0f,
    1E-3f,
    1E-6f,
    1E-9f,
    1E-12f,
    60.0f,
    1.0f,
    1.0f,
    1.0f,
    1.0f,
    1E-3f,
    1.0f,
    1E-3f,
    1E-6f,
};
Referenced by getDerivedUnit(), and getUnitFactor().
g_unitNames
const char* eez::g_unitNames[]
Definition at line 652 of file eez-flow.cpp.
{
    "",
    "V",
    "mV",
    "A",
    "mA",
    "uA",
    "W",
    "mW",
    "s",
    "ms",
    DEGREE_SYMBOL"C",
    "rpm",
    "\xb4",
    "K\xb4",
    "M\xb4",
    "%",
    "Hz",
    "mHz",
    "KHz",
    "MHz",
    "J",
    "F",
    "mF",
    "uF",
    "nF",
    "pF",
    "minutes",
    "VA",
    "VAR",
    DEGREE_SYMBOL,
    "Vpp",
    "mVpp",
    "App",
    "mApp",
    "uApp",
};
Referenced by getUnitFromName().
g_valueTypeCompareFunctions
CompareValueFunction eez::g_valueTypeCompareFunctions[]
Initial value:
= {
    VALUE_TYPES
}
Definition at line 2322 of file eez-flow.cpp.
{
    VALUE_TYPES
};
g_valueTypeNames
ValueTypeNameFunction eez::g_valueTypeNames[]
Initial value:
= {
    VALUE_TYPES
}
Definition at line 2338 of file eez-flow.cpp.
{
    VALUE_TYPES
};
Referenced by ARRAY_ELEMENT_VALUE_value_type_name(), eez::flow::assignValue(), JSON_MEMBER_VALUE_value_type_name(), and VALUE_PTR_value_type_name().
g_valueTypeToTextFunctions
ValueToTextFunction eez::g_valueTypeToTextFunctions[]
Initial value:
= {
    VALUE_TYPES
}
Definition at line 2330 of file eez-flow.cpp.
{
    VALUE_TYPES
};