EARS-PIO-WSS3-LVGL-001: src/ui/screens.h File Reference
screens.h File Reference
#include <lvgl.h>
Data Structures
struct _objects_t
Typedefs
typedef struct _objects_t objects_t
Enumerations
enum ScreensEnum { SCREEN_ID_INITIAL_SCREEN = 1 }
Functions
void create_screen_initial_screen ()
void tick_screen_initial_screen ()
void tick_screen_by_id (enum ScreensEnum screenId)
void tick_screen (int screen_index)
void create_screens ()
Variables
objects_t objects
Typedef Documentation
objects_t
typedef struct _objects_t objects_t
Enumeration Type Documentation
ScreensEnum
enum ScreensEnum
Enumerator
SCREEN_ID_INITIAL_SCREEN
Definition at line 16 of file screens.h.
                 {
    SCREEN_ID_INITIAL_SCREEN = 1,
};
Function Documentation
create_screen_initial_screen()
void create_screen_initial_screen ()
Definition at line 16 of file screens.c.
{
    void *flowState = getFlowState(0, 0);
    (void)flowState;
    lv_obj_t *obj = lv_obj_create(0);
    objects.initial_screen = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 480, 320);
    {
        lv_obj_t *parent_obj = obj;
        {
            lv_obj_t *obj = lv_label_create(parent_obj);
            lv_obj_set_pos(obj, 356, 232);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_label_set_text(obj, "Hello, world!");
        }
    }
    tick_screen_initial_screen();
}
References getFlowState(), objects, and tick_screen_initial_screen().
Referenced by create_screens().
create_screens()
void create_screens ()
Definition at line 57 of file screens.c.
                      {
    eez_flow_init_screen_names(screen_names, sizeof(screen_names) / sizeof(const char *));
    eez_flow_init_object_names(object_names, sizeof(object_names) / sizeof(const char *));
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    create_screen_initial_screen();
}
tick_screen()
void tick_screen (int screen_index)
Definition at line 50 of file screens.c.
{
    tick_screen_funcs[screen_index]();
}
tick_screen_by_id()
void tick_screen_by_id (enum ScreensEnum screenId)
Definition at line 53 of file screens.c.
{
    tick_screen_funcs[screenId - 1]();
}
References tick_screen_funcs.
tick_screen_initial_screen()
void tick_screen_initial_screen ()
Definition at line 36 of file screens.c.
{
    void *flowState = getFlowState(0, 0);
    (void)flowState;
}
References getFlowState().
Referenced by create_screen_initial_screen().
Variable Documentation
objects
objects_t objects extern
Definition at line 13 of file screens.c.
Referenced by create_screen_initial_screen(), eez_flow_init(), and ui_init().